### ISSUE TITLE
Three different hosts, three different issues

### ISSUE THREAD

**Issue by raisro** [TRON-US/go-btfs#1000]
1. HOSTS REPAIR MODE ON
  
 Have they started working in REPAIR MODE ON?, I still have no contracts.

  
C:\BTFS>btfs daemon
Initializing daemon...
go-btfs version: 1.5.1-208e586
Repo version: 10
System version: amd64/windows
Golang version: go1.15.8
Repo location: Z:\BTFSon
Peer identity: 16Uiu2HAmBiSzSAvnMQtF3uueFsYy8ynUwqh8t1vdtBW4C9EfftVw
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/192.168.0.24/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/192.168.0.24/tcp/4001
Swarm announcing /ip4/82.159.129.175/tcp/1027
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
WebUI: http://127.0.0.1:5001/webui
HostUI: http://127.0.0.1:5001/hostui
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Remote API server listening on /ip4/127.0.0.1/tcp/5101
Daemon is ready
Storage host info will be synced at [SCORE] mode
Current host stats will be synced
Current host settings will be synced
BTFS is up-to-date.
BTFS is up-to-date.

![image](https://user-images.githubusercontent.com/75047166/115091048-bb92f780-9f16-11eb-913b-354c32d32f8c.png)

2. BTFS STORAGE RENTAL
 
 This node had a good score but in an update (I think) the score began to drop.
 What I can do?

C:\BTFS>btfs daemon
Initializing daemon...
go-btfs version: 1.5.1-208e586
Repo version: 10
System version: amd64/windows
Golang version: go1.15.8
Repo location: Z:\BTFSR
Peer identity: 16Uiu2HAmRZPicVTGjETds2UctTThZDq9Dh4RVJm9G3TCnZzJnKxu
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/192.168.0.15/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/192.168.0.15/tcp/4001
Swarm announcing /ip4/82.159.129.175/tcp/1027
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
WebUI: http://127.0.0.1:5001/webui
HostUI: http://127.0.0.1:5001/hostui
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Remote API server listening on /ip4/127.0.0.1/tcp/5101
Daemon is ready
Storage host info will be synced at [SCORE] mode
Current host stats will be synced
Current host settings will be synced
BTFS is up-to-date.
BTFS is up-to-date.

![image](https://user-images.githubusercontent.com/75047166/115091146-04e34700-9f17-11eb-9481-d582a5305e12.png)

3. HOSTING
 Next payment date Apr 02,2021 (and we are at Apr 16)
  
 The same thing has happened to this node as to STORAGE RENTAL, it had a good score but it has fallen; and it is rising slowly.

Z:\btfs>btfs daemon
Initializing daemon...
go-btfs version: 1.5.1-208e586
Repo version: 10
System version: amd64/windows
Golang version: go1.15.8
Repo location: Z:\BTFSFILE
Peer identity: 16Uiu2HAmNEW7i1Y6AbaMcF2xDNcVrzPtjhCzSJNnfFcZP7i25ggM
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/192.168.0.22/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/192.168.0.22/tcp/4001
Swarm announcing /ip4/82.159.129.175/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
WebUI: http://127.0.0.1:5001/webui
HostUI: http://127.0.0.1:5001/hostui
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Remote API server listening on /ip4/127.0.0.1/tcp/5101
Daemon is ready
Storage host info will be synced at [SCORE] mode
Current host stats will be synced
Current host settings will be synced
BTFS is up-to-date.
BTFS is up-to-date.

![image](https://user-images.githubusercontent.com/75047166/115091251-54297780-9f17-11eb-830d-62468572b03a.png)

![image](https://user-images.githubusercontent.com/75047166/115091327-820ebc00-9f17-11eb-89d0-d58d02d13434.png)

How can I make sure I have them configured correctly?

Thanks for your support,
Raúl

**Comment by laipogo** [comment]
1. You could close repair mode because it's still WIP.
2. Looks like there were some network issue when the nodes sent the heartbeats.
3. The payment date issue is a known issue, we'll look into it asap.

**Comment by raisro** [comment]
1. What does WIP mean?. Excuse my ignorance. :(
2. The funny thing is that it only happens with that node, I have the three nodes in the same network and with the others that problem does not happen.
3. Ok, thank you very much for the information.

**Comment by raisro** [comment]
The problems have been solved, it was a matter of having patience, only the payment issue remains.

**Comment by WhiteHeadbanger** [comment]
Hello, my payment date is blank and it has been this way for many months. I have been paid in the last year, but after that the payment date went from a XXX date to show nothing
![image](https://user-images.githubusercontent.com/12226415/117336518-aacd0600-ae72-11eb-99a6-7818e1c1e5a8.png)

**Comment by WhiteHeadbanger** [comment]
> Hello, my payment date is blank and it has been this way for many months. I have been paid in the last year, but after that the payment date went from a XXX date to show nothing
> ![image](https://user-images.githubusercontent.com/12226415/117336518-aacd0600-ae72-11eb-99a6-7818e1c1e5a8.png)

Also, the "earnings to-date" is wrong. I have made more than 2977 BTT.

**Comment by WhiteHeadbanger** [comment]
> can yu tell me how much time required to get 10 score and get contract. is we hve to do something for getting contract or get after 10 score automatically

I don't know how much time. A few days or weeks at most, but the exact time I don't know.
To acquire a new contract the only thing that you should do is to keep the daemon running on the background. The system "assigns" contracts by itself. The score helps, but I don't know how much it helps

**Comment by Sophia-yu-kk** [comment]
> can yu tell me how much time required to get 10 score and get contract. is we hve to do something for getting contract or get after 10 score automatically

The BTFS node score ranges from 0-10, which is the main measure of the quality of BTFS nodes. The weight of each score factor is different, and the weights are 0.6, 0.2, 0.05, 0.05 and 0.1 respectively, i.e. total score = uptimeScore * 0.6 + ageScore * 0.2 + uploadSpeedScore * 0.05 + downloadSpeedScore * 0.05 + versionScore * 0.1.

The above is the calculation method, can be for your reference.

**Comment by Sophia-yu-kk** [comment]
If you have any questions, you can also join the discord group chat to contact us
https://discord.gg/2CwVmm5X
