### ISSUE TITLE
Swarm addresses inaccessible

### ISSUE THREAD

**Issue by fta85** [TRON-US/go-btfs#1001]
I have an issue that my webui is not working. I have this message in web interface:
`btfs resolve -r /btns/QmWJWGxKKaqZUW4xga2BCzT5FBtYDL8Cc5Q5jywd6xPt1g/: could not resolve name`

this is a one of default swarm addreses from config.
I have check another addresses from config and no one is not accesible:

btfs swarm connect /ip4/34.213.5.20/tcp/4001/p2p/QmQVQBsM7uoJy8hATjTm51uSAkx2y3iGLhSwA6LWLa7iQJ
Error: connect QmQVQBsM7uoJy8hATjTm51uSAkx2y3iGLhSwA6LWLa7iQJ failure: failed to dial QmQVQBsM7uoJy8hATjTm51uSAkx2y3iGLhSwA6LWLa7iQJ: all dials failed
  * [/ip4/34.213.5.20/tcp/4001] dial tcp4 0.0.0.0:4001->34.213.5.20:4001: i/o timeout

My node is up about 10 days and everything was ok before.
Hostui work properly.
Now i havent peers on my node, but host is working and up.

btfs swarm peers is empty too

My bootstrap list (no one is accessible):

/ip4/13.229.45.41/tcp/4001/p2p/QmX7RZXh27AX8iv2BKLGMgPBiuUpEy8p4LFXgtXAfaZDn9
/ip4/18.194.71.27/tcp/4001/p2p/QmYHkY5CrWcvgaDo4PfvzTQgaZtfaqRGDjwW1MrHUj8cLK
/ip4/18.237.202.91/tcp/4001/p2p/QmbVFdiNkvxtc7Nni7yBWAgtHg8MuyhaZ5mDaYR2ZrhhvN
/ip4/18.237.54.123/tcp/4001/p2p/QmWJWGxKKaqZUW4xga2BCzT5FBtYDL8Cc5Q5jywd6xPt1g
/ip4/3.126.224.22/tcp/4001/p2p/QmWTTmvchTodUaVvuKZMo67xk7ZgkxJf4nBo7SZry3vGU5
/ip4/34.213.5.20/tcp/4001/p2p/QmQVQBsM7uoJy8hATjTm51uSAkx2y3iGLhSwA6LWLa7iQJ
/ip4/52.77.240.134/tcp/4001/p2p/QmURPwdLYesWUDB66EGXvDvwcyV44rVRqV2iGNqKN24eVu
/ip4/54.213.128.120/tcp/4001/p2p/QmWm3vBCRuZcJMUT9jDZysoYBb66aokmSReX26UaMk8qq5
/ip4/54.254.227.188/tcp/4001/p2p/QmYqCq3PasrzLr3PxtLo5D6spEAJ836W9Re9Eo4zUou45U
/ip4/54.93.47.134/tcp/4001/p2p/QmeHaHe7WvjeY37z5MYC3qYQcQcuvDwUhwTXtP3KhKLXXK

in logs i have attempts to sync swarm peers from bootstrap list in config:

`{"TraceID":7396733587058076116,"SpanID":3119986715031798224,"ParentSpanID":0,"Operation":"swarmDialDo","Start":"2021-04-17T09:47:33.405499333Z","Duration":5001669489,"Tags":{"system":"swarm2"},"Logs":[{"Timestamp":"2021-04-17T09:47:33.405506218Z","Fields":[{"Key":"localPeer","Value":"16Uiu2HAmSxQJGuvcLYY4ruJGroTX3ZYwj8jkJ6Urc7ezYgYQPKbY"}]},{"Timestamp":"2021-04-17T09:47:33.405506857Z","Fields":[{"Key":"remotePeer","Value":"QmWm3vBCRuZcJMUT9jDZysoYBb66aokmSReX26UaMk8qq5"}]},{"Timestamp":"2021-04-17T09:47:33.405507403Z","Fields":[{"Key":"subsystem","Value":"swarm"}]}]}
{"TraceID":4166665120563255941,"SpanID":1422217269528503742,"ParentSpanID":0,"Operation":"swarmDialAttemptStart","Start":"2021-04-17T09:47:33.405488538Z","Duration":5001763920,"Tags":{"system":"swarm2"},"Logs":[{"Timestamp":"2021-04-17T09:47:33.405496049Z","Fields":[{"Key":"localPeer","Value":"16Uiu2HAmSxQJGuvcLYY4ruJGroTX3ZYwj8jkJ6Urc7ezYgYQPKbY"}]},{"Timestamp":"2021-04-17T09:47:33.405496669Z","Fields":[{"Key":"remotePeer","Value":"QmWm3vBCRuZcJMUT9jDZysoYBb66aokmSReX26UaMk8qq5"}]},{"Timestamp":"2021-04-17T09:47:33.405497338Z","Fields":[{"Key":"subsystem","Value":"swarm"}]}]}
{"TraceID":453706943364997561,"SpanID":6357978488840330577,"ParentSpanID":0,"Operation":"swarmDialAttemptSync","Start":"2021-04-17T09:47:33.40547043Z","Duration":5001958061,"Tags":{"system":"swarm2"},"Logs":[{"Timestamp":"2021-04-17T09:47:33.405476459Z","Fields":[{"Key":"peerID","Value":"QmWm3vBCRuZcJMUT9jDZysoYBb66aokmSReX26UaMk8qq5"}]}]}

My peer id is

16Uiu2HAmSxQJGuvcLYY4ruJGroTX3ZYwj8jkJ6Urc7ezYgYQPKbY

**Comment by aladyn93** [comment]
same problem. any updates?

**Comment by Lukpc** [comment]
I0m also having the same problem

**Comment by laipogo** [comment]
could u try `btfs bootstrap add /ip4/106.14.42.95/tcp/4001/p2p/16Uiu2HAmSACrUuNd7rJeHD6xctaEqn8cdouRio4NsL2yup68YcVP`

**Comment by aladyn93** [comment]
> could u try `btfs bootstrap add /ip4/106.14.42.95/tcp/4001/p2p/16Uiu2HAmSACrUuNd7rJeHD6xctaEqn8cdouRio4NsL2yup68YcVP`

it worked : "added /ip4/106.14.42.95/tcp/4001/p2p/16Uiu2HAmSACrUuNd7rJeHD6xctaEqn8cdouRio4NsL2yup68YcVP"

**Comment by Lukpc** [comment]
It also worked for me thank you so much

**Comment by fta85** [comment]
> could u try `btfs bootstrap add /ip4/106.14.42.95/tcp/4001/p2p/16Uiu2HAmSACrUuNd7rJeHD6xctaEqn8cdouRio4NsL2yup68YcVP`

yes, this trap it added, but webui is still not work, same error in webiu: 
btfs resolve -r /btns/QmWJWGxKKaqZUW4xga2BCzT5FBtYDL8Cc5Q5jywd6xPt1g/: could not resolve name

**Comment by gh0stwolf** [comment]
Strange.. I was having issues similar to OP. I performed the command below. Still received the same error.
btfs bootstrap add /ip4/106.14.42.95/tcp/4001/p2p/16Uiu2HAmSACrUuNd7rJeHD6xctaEqn8cdouRio4NsL2yup68YcVP
I then performed
btfs bootstrap rm /ip4/106.14.42.95/tcp/4001/p2p/16Uiu2HAmSACrUuNd7rJeHD6xctaEqn8cdouRio4NsL2yup68YcVP
Then all of a sudden it worked! This was done using a fresh install of btfs, where hostui worked but not webui. Hope this helps someone!

**Comment by fta85** [comment]
> Strange.. I was having issues similar to OP. I performed the command below. Still received the same error.
> btfs bootstrap add /ip4/106.14.42.95/tcp/4001/p2p/16Uiu2HAmSACrUuNd7rJeHD6xctaEqn8cdouRio4NsL2yup68YcVP
> I then performed
> btfs bootstrap rm /ip4/106.14.42.95/tcp/4001/p2p/16Uiu2HAmSACrUuNd7rJeHD6xctaEqn8cdouRio4NsL2yup68YcVP
> Then all of a sudden it worked! This was done using a fresh install of btfs, where hostui worked but not webui. Hope this helps someone!

not help for me... same error

**Comment by shadehv** [comment]
> Strange.. I was having issues similar to OP. I performed the command below. Still received the same error.
> btfs bootstrap add /ip4/106.14.42.95/tcp/4001/p2p/16Uiu2HAmSACrUuNd7rJeHD6xctaEqn8cdouRio4NsL2yup68YcVP
> I then performed
> btfs bootstrap rm /ip4/106.14.42.95/tcp/4001/p2p/16Uiu2HAmSACrUuNd7rJeHD6xctaEqn8cdouRio4NsL2yup68YcVP
> Then all of a sudden it worked! This was done using a fresh install of btfs, where hostui worked but not webui. Hope this helps someone!

This worked for me. Thanks!

**Comment by fta85** [comment]
i'm found same problem in IPFS github:
https://github.com/ipfs/go-ipfs/issues/6721

**Comment by MilNoslen** [comment]
Bump, just got this issue after restarting quick. Opened up fine and webui was accessible. Then after hitting refresh a few minutes later received the message 
btfs resolve -r /btns/QmWJWGxKKaqZUW4xga2BCzT5FBtYDL8Cc5Q5jywd6xPt1g/: could not resolve name

**Comment by Sophia-yu-kk** [comment]
The system will automatically close the longer issues, if your problem is still not solved, you can join the discord group chat: https://discord.gg/2CwVmm5X
