### ISSUE TITLE
reprovider.simple       failed to reprovide: failed to find any peer in table

### ISSUE THREAD

**Issue by themantas1994** [TRON-US/go-btfs#1003]
![image](https://user-images.githubusercontent.com/82760904/115145121-f34d8c80-a047-11eb-87ff-61dcbdd746db.png)
 Im getting no bandwith usage and the web ui shows this:
![image](https://user-images.githubusercontent.com/82760904/115145164-1c6e1d00-a048-11eb-8d39-9de99e6f97f2.png)
no issues until yesterday

**Comment by Lukpc** [comment]
Have the same problem and all was working fine

**Comment by thatalbertaguy** [comment]
Same here , on my computer btfs was totally closed out at 5am (CST) for some reason I restarted and couldn’t load webpage and got the same error

**Comment by laipogo** [comment]
looks like u can't connect to the bootstrap nodes.

**Comment by laipogo** [comment]
could u try `btfs bootstrap add /ip4/106.14.42.95/tcp/4001/p2p/16Uiu2HAmSACrUuNd7rJeHD6xctaEqn8cdouRio4NsL2yup68YcVP`

**Comment by themantas1994** [comment]
> btfs bootstrap add /ip4/106.14.42.95/tcp/4001/p2p/16Uiu2HAmSACrUuNd7rJeHD6xctaEqn8cdouRio4NsL2yup68YcVP

that fixed the issue thank you very much

**Comment by akgamersa3** [comment]
facing same,i did same but not resolved, can yu help me out
