### ISSUE TITLE
dial tcp: lookup api.trongrid.io: no such host

### ISSUE THREAD

**Issue by aladyn93** [TRON-US/go-btfs#1004]
![image](https://user-images.githubusercontent.com/82755381/115242357-73e4b980-a12a-11eb-9735-6043e04d09a2.png)

How to fix this?

**Comment by aladyn93** [comment]
also, when i get this errod, my entire internet connection drops for a momment

**Comment by laipogo** [comment]
known issue. thanks.

**Comment by laipogo** [comment]
the error could be ignored
