### ISSUE TITLE
ERROR	spin	Failed to sync host stats: Failed to query stats from Hub service: HubQueryClient: Cannot query to get stats, please wait for host validation

### ISSUE THREAD

**Issue by phongtnit** [TRON-US/go-btfs#1007]
Hello,

I ran btfs on CentOS 8 about 20 hours ago, however, my log saw many errors like that `ERROR	spin	Failed to sync host stats: Failed to query stats from Hub service: HubQueryClient: Cannot query to get stats, please wait for host validation!`

My Peer identity: 16Uiu2HAmS8pvT6xrjQH9jZyJS4NdTUARRGCiDMhvACmFgmRvEoWG

I changed my btfs config from `"API": "/ip4/127.0.0.1/tcp/5001"` to `"API": "/ip4/0.0.0.0/tcp/5001"`, so I can access btfs dashboard via public IP.

My env:
```
go-btfs version: 1.5.1-208e586
Repo version: 10
System version: amd64/linux
Golang version: go1.15.8
```

Please help me to solve the issue, many thanks

**Comment by Kalmon** [comment]
I have the same problem.
My system and Linux arm64, is on the SCORE ASSESSMENT screen about 4 hours ago.
And that error started to appear.

**Comment by gcirvini** [comment]
same problem here
2021-04-25T01:01:28.373+0200    [31mERROR[0m  spin    Failed to sync host stats: Failed to query stats from Hub service: HubQueryClient: Cannot query to get stats, please wait for host validation!

**Comment by Kalmon** [comment]
> same problem here
> 2021-04-25T01:01:28.373+0200 �[31mERROR�[0m spin Failed to sync host stats: Failed to query stats from Hub service: HubQueryClient: Cannot query to get stats, please wait for host validation!

After activating "REPAIR MODE" in the settings, this error stopped appearing.
Another thing, in my case the error appeared after opening remote access to the APIs (GET, POST).

**Comment by tty666** [comment]
It takes almost a full night even maybe a bit more to get validated guys but indeed the message about 4h is wrong ... it was probably the case in the past but with the actual size of transactions it looks like more something 8h - 12h than 4h :-)
But you will see surprises aren't finished yet other errors will pop up and contracts are like the bigfoot : everybody talk about it, nobody saw one !

**Comment by aofdev** [comment]
I have the same problem. 
My system OS windows

**Comment by Kalmon** [comment]
> It takes almost a full night even maybe a bit more to get validated guys but indeed the message about 4h is wrong ... it was probably the case in the past but with the actual size of transactions it looks like more something 8h - 12h than 4h :-)
> But you will see surprises aren't finished yet other errors will pop up and contracts are like the bigfoot : everybody talk about it, nobody saw one !

My opinion, the BTFS score must be between 8 and 10.
 At least 6/10 age of the host.
Taking a look at payment errors, the server averages were 9.0 to 9.5.
In BTFS (https://scan.btfs.io/) 36% are between 8 and 10 the final grade.
By: Google Translator

**Comment by tty666** [comment]
> > It takes almost a full night even maybe a bit more to get validated guys but indeed the message about 4h is wrong ... it was probably the case in the past but with the actual size of transactions it looks like more something 8h - 12h than 4h :-)
> > But you will see surprises aren't finished yet other errors will pop up and contracts are like the bigfoot : everybody talk about it, nobody saw one !
> 
> My opinion, the BTFS score must be between 8 and 10.
> At least 6/10 age of the host.
> Taking a look at payment errors, the server averages were 9.0 to 9.5.
> In BTFS (https://scan.btfs.io/) 36% are between 8 and 10 the final grade.
> By: Google Translator

My host has score of 10, runs for one month now and had 0 contracts at all only errors ...

**Comment by Kalmon** [comment]
> > > It takes almost a full night even maybe a bit more to get validated guys but indeed the message about 4h is wrong ... it was probably the case in the past but with the actual size of transactions it looks like more something 8h - 12h than 4h :-)
> > > But you will see surprises aren't finished yet other errors will pop up and contracts are like the bigfoot : everybody talk about it, nobody saw one !
> > 
> > 
> > My opinion, the BTFS score must be between 8 and 10.
> > At least 6/10 age of the host.
> > Taking a look at payment errors, the server averages were 9.0 to 9.5.
> > In BTFS (https://scan.btfs.io/) 36% are between 8 and 10 the final grade.
> > By: Google Translator
> 
> My host has score of 10, runs for one month now and had 0 contracts at all only errors ...

Strange, what system and architecture is using the BTFS server?

**Comment by tty666** [comment]
> > > > It takes almost a full night even maybe a bit more to get validated guys but indeed the message about 4h is wrong ... it was probably the case in the past but with the actual size of transactions it looks like more something 8h - 12h than 4h :-)
> > > > But you will see surprises aren't finished yet other errors will pop up and contracts are like the bigfoot : everybody talk about it, nobody saw one !
> > > 
> > > 
> > > My opinion, the BTFS score must be between 8 and 10.
> > > At least 6/10 age of the host.
> > > Taking a look at payment errors, the server averages were 9.0 to 9.5.
> > > In BTFS (https://scan.btfs.io/) 36% are between 8 and 10 the final grade.
> > > By: Google Translator
> > 
> > 
> > My host has score of 10, runs for one month now and had 0 contracts at all only errors ...
> 
> Strange, what system and architecture is using the BTFS server?

I am running it on my NAS which is ARM based.
A dedicated ed 2TB disk attached to it for BTFS but I think I will move to Siacoin if devs continues to not answer question and explain what could be wrong which all those errors popping and nothing to host or earn at the end ...
I am professional linux engineer so I don't think to be wrong in the config but they anyway don't answer to the issues posted there and don't help at all ...

**Comment by Sophia-yu-kk** [comment]
This issue has been resolved and you are welcome to join the Discord group chat!
https://discord.gg/2CwVmm5X
