### ISSUE TITLE
ERROR	reprovider.simple	failed to reprovide: failed to find any peer in table

### ISSUE THREAD

**Issue by djuab** [TRON-US/go-btfs#1008]
BTFS is running on Ubuntu 20.04. 
Can you guys help me please?

Got this error message on terminal :
2021-04-21T19:50:00.126+0530	ERROR	reprovider.simple	failed to reprovide: failed to find any peer in table

**Comment by susLimbaugh** [comment]
having the same issue. Node shows as online, yet no contracts and receiving this error among others, such as i/o timeout. I think it is BTFS end, not us.

**Comment by djuab** [comment]
@susLimbaugh Thanks for the update. Getting this error whenever btfs daemon is restarting.

**Comment by akgamersa3** [comment]
same issue
16Uiu2HAmUCsrx7S9aEoN6fKZteGZnaLGmZkb2hsxXp3b2x7mhrCJ

**Comment by Sophia-yu-kk** [comment]
This issue has been fixed, if you have new problems you can reintroduce issues

**Comment by AmigoAndrel** [comment]
←[31mERROR←[0m  reprovider.simple       simple/r eprovide.go:108 failed to reprovide: failed to find any peer in table
