### ISSUE TITLE
Please Fix

### ISSUE THREAD

**Issue by susLimbaugh** [TRON-US/go-btfs#1009]
No contracts, not potential future earnings, no payment date. Update when?

**Comment by susLimbaugh** [comment]
If this project is going to be discontinued please just share that so I can repurpose my resources.

**Comment by lukasvdberk** [comment]
I think that there are way to many hosts in compassion to the amount of people using it to store files.

**Comment by Sophia-yu-kk** [comment]
> No contracts, not potential future earnings, no payment date. Update when?

The current rule is that contracts are assigned randomly over 8 points. There is a competitive relationship between nodes and nodes.
