### ISSUE TITLE
I suspect someone is cheating!!!!

### ISSUE THREAD

**Issue by blue-cai** [TRON-US/go-btfs#1010]
![{09817167-ABD9-4E89-8BB9-5032874C4D5B}-149c3cf17f1671324ab896f8c13e73bd](https://user-images.githubusercontent.com/58155644/115684834-439b5600-a38a-11eb-81b0-1009e3524770.jpg)

Yesterday, the top two mining machines were the same machine. Why did he have so many contracts while I didn't have any contracts for other machines in the same area. Is he cheating? Or is he a member of your team? Please tell me why!!!!!Many of the top 30 are this IP!!!!!

**Comment by blue-cai** [comment]
This picture is the IP and port number I got from the node ID in the code during debugging.

**Comment by laipogo** [comment]
will look into it.
