### ISSUE TITLE
Sent here to ask about issue w/ BTT not dispensing to wallet correctly from Bittorrent Speed

### ISSUE THREAD

**Issue by mostly4yt** [TRON-US/go-btfs#1011]
99% sure this is the wrong place but was pointed here when asking for help. I use bittorrent + speed to mine BTT.  Noticed BTT wallet showing incorrect amounts - I'm not using BTFS (haven't set it up), have made no transfers or withdrawals, and received no reply from the support email on the wallet page.  It's been too much time for this to be a network delay.
The enclosed image shows BTT earned, minus deductions - but the wallet balance is itself off by nearly 50%.  Can't think of any resolutions I can offer on the user side. 

In the 48 hours since I first asked around the discrepency is now 1650BTT, which seems like no big deal except for the obvious fact that I'm mining and holding for a reason. 

![image](https://user-images.githubusercontent.com/83013263/115709809-df977400-a32e-11eb-8885-3eb5d2864e0b.png)

**Comment by Merkbud** [comment]
Same thing with me missing ~2000 BTT

as can be seen here -> https://www.reddit.com/r/BittorrentToken/comments/mza4ry/where_does_all_my_btt_go_from_bittorrent_speed/

**Comment by akgamersa3** [comment]
my earning ratio is showing 0btt/gb in earning ratio, but i seeded about 99 gb. help me out.

**Comment by Sophia-yu-kk** [comment]
pavel@tron.network
This is the person in charge of BT speed project, you can contact him to solve the problems related to BT speed.
