### ISSUE TITLE
BTFS payment not received 

### ISSUE THREAD

**Issue by Merkbud** [TRON-US/go-btfs#1012]
![image](https://user-images.githubusercontent.com/37555605/116160369-e7a13c00-a6bf-11eb-96aa-1e339be06c4b.png)

as shown here I was supposed to be paid ~17 BTT on March 26th it has now been a full month and I have yet to receive the payment I have 5 contracts and I dont see a point in hosting their files if they will not pay me what I am owed for my storage. Does anyone else have this issue?

**Comment by murthydevarakonda** [comment]
Hello, I see the same issue. 
![image](https://user-images.githubusercontent.com/12900125/116171945-9d6b8b00-a6be-11eb-856e-96ee795765ea.png)

**Comment by murthydevarakonda** [comment]
Can someone resolve this issue? Even though my node uptime is above 9.4, I did not get a single contract in last month. Do you know why?

**Comment by thatalbertaguy** [comment]
I am not a dev nor an expert but I do know the new contract rate is 3840 btt/tb so I would adjust my rate to that instead of 7680.  As for the missing payment I’m in the same boat 800 btt missing from March 12

**Comment by Sophia-yu-kk** [comment]
> ![image](https://user-images.githubusercontent.com/37555605/116160369-e7a13c00-a6bf-11eb-96aa-1e339be06c4b.png)
> 
> as shown here I was supposed to be paid ~17 BTT on March 26th it has now been a full month and I have yet to receive the payment I have 5 contracts and I dont see a point in hosting their files if they will not pay me what I am owed for my storage. Does anyone else have this issue?

Have you received this payment?

**Comment by Sophia-yu-kk** [comment]
> Can someone resolve this issue? Even though my node uptime is above 9.4, I did not get a single contract in last month. Do you know why?

It is recommended that the price is adjusted and changing the default price will help to get the contract.
