### ISSUE TITLE
error getting peer record from Identify message: failed to validate envelope: invalid signature or incorrect domain

### ISSUE THREAD

**Issue by themantas1994** [TRON-US/go-btfs#1015]
![image](https://user-images.githubusercontent.com/82760904/116772247-7d80f200-aa45-11eb-9cc9-e29b9dc128eb.png)
im getting this error on console for about 2 days and payment is due.
![image](https://user-images.githubusercontent.com/82760904/116772284-c9339b80-aa45-11eb-8120-a8f1e4614abc.png)

**Comment by AlexBion** [comment]
hi, have you solved that problem? i have same problem :

error getting peer record from Identify message: failed to validate envelope: invalid signature or incorrect domain

**Comment by themantas1994** [comment]
no still getting it

**Comment by Sophia-yu-kk** [comment]
Hello, it has been confirmed. This is a libp2p error, just ignore it
