### ISSUE TITLE
Error: Failed to sync btt-tx

### ISSUE THREAD

**Issue by ZeroCool1974** [TRON-US/go-btfs#1018]
I got this error today:

2021-05-03T16:43:25.205-0300    ←[31mERROR←[0m  spin    Failed to sync btt-tx: Get "https://api.trongrid.io/v1/accounts/TNMR1iHefCS9vLGV4TXb8dvaZYPFovMJC2/transactions?limit=200&only_to=true&order_by=block_timestamp,asc&min_block_timestamp=0": dial tcp 52.37.188.174:443: i/o timeout

I have 1 contract to receive BTT from...

C:\btfs>btfs.exe daemon
Initializing daemon...
go-btfs version: 1.5.1-208e586
Repo version: 10
System version: amd64/windows
Golang version: go1.15.8
Repo location: G:\
Peer identity: 16Uiu2HAmQUxZexD9ShqirzMEM2CjRx9LpyqPzqfXmAvkmCbW4duL
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/192.168.100.5/tcp/4001
Swarm listening on /ip6/2804:f24:c10d:6b00:11ec:e7b:721a:99a1/tcp/4001
Swarm listening on /ip6/2804:f24:c10d:6b00:3188:81cb:c70e:9840/tcp/4001
Swarm listening on /ip6/2804:f24:c10d:6b00:357a:5367:26a:9c91/tcp/4001
Swarm listening on /ip6/2804:f24:c10d:6b00:d2f:ddbc:97a2:a9cb/tcp/4001
Swarm listening on /ip6/2804:f24:c10d:6b00:d5de:391e:4213:a394/tcp/4001
Swarm listening on /ip6/2804:f24:c10d:6b00:e834:60db:3525:c07e/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/179.109.45.164/tcp/24307
Swarm announcing /ip4/192.168.100.5/tcp/4001
Swarm announcing /ip6/2804:f24:c10d:6b00:357a:5367:26a:9c91/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
WebUI: http://127.0.0.1:5001/webui
HostUI: http://127.0.0.1:5001/hostui
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Remote API server listening on /ip4/127.0.0.1/tcp/5101
Daemon is ready
Storage host info will be synced at [SCORE] mode
Current host stats will be synced
Current host settings will be synced
BTFS is up-to-date.
2021-05-07T03:46:10.895-0300    ←[31mERROR←[0m  spin    Failed to sync btt-tx: Get "https://api.trongrid.io/v1/accounts/TNMR1iHefCS9vLGV4TXb8dvaZYPFovMJC2/transactions?limit=200&only_to=true&order_by=block_timestamp,asc&min_block_timestamp=0": dial tcp: lookup api.trongrid.io: no such host
BTFS is up-to-date.

Edit:

Today is 22/05/2021 and I'm still receiving the same errors:

E:\btfs_daemon>btfs.exe daemon
Initializing daemon...
go-btfs version: 1.5.1-208e586
Repo version: 10
System version: amd64/windows
Golang version: go1.15.8
Repo location: G:\
Peer identity: 16Uiu2HAmQUxZexD9ShqirzMEM2CjRx9LpyqPzqfXmAvkmCbW4duL
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/192.168.100.5/tcp/4001
Swarm listening on /ip6/2804:f24:c10d:6b00:357a:5367:26a:9c91/tcp/4001
Swarm listening on /ip6/2804:f24:c10d:6b00:5c76:778c:a93a:7761/tcp/4001
Swarm listening on /ip6/2804:f24:c10d:6b00:8da1:84bb:cfca:4b57/tcp/4001
Swarm listening on /ip6/2804:f24:c10d:6b00:e122:3138:d55:c83/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/179.109.39.149/tcp/2556
Swarm announcing /ip4/192.168.100.5/tcp/4001
Swarm announcing /ip6/2804:f24:c10d:6b00:5c76:778c:a93a:7761/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
WebUI: http://127.0.0.1:5001/webui
HostUI: http://127.0.0.1:5001/hostui
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Remote API server listening on /ip4/127.0.0.1/tcp/5101
Daemon is ready
Storage host info will be synced at [SCORE] mode
Current host stats will be synced
Current host settings will be synced
BTFS is up-to-date.
2021-05-21T22:11:15.886-0300    ←[31mERROR←[0m  spin    Failed to sync btt-tx: Get "https://api.trongrid.io/v1/accounts/TNMR1iHefCS9vLGV4TXb8dvaZYPFovMJC2/transactions?limit=200&only_to=true&order_by=block_timestamp,asc&min_block_timestamp=0": net/http: TLS handshake timeout
2021-05-21T22:14:08.825-0300    ←[31mERROR←[0m  spin    Failed to sync btt-tx: Get "https://api.trongrid.io/v1/accounts/TNMR1iHefCS9vLGV4TXb8dvaZYPFovMJC2/transactions?limit=200&only_to=true&order_by=block_timestamp,asc&min_block_timestamp=0": net/http: TLS handshake timeout

**Comment by fxjerzy** [comment]
Me to...

**Comment by fxjerzy** [comment]
```
Initializing daemon...
go-btfs version: 1.5.1-208e586
Repo version: 10
System version: amd64/windows
Golang version: go1.15.8
Repo location: E:\Torrent_BTFS
Peer identity: 16Uiu2HAmNqeECCfdgrRo2YHyhTutz5XJMvHmvqBvrdpNvnNCph8R
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/192.168.2.105/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/192.168.2.105/tcp/4001
Swarm announcing /ip4/82.160.124.144/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
WebUI: http://127.0.0.1:5001/webui
HostUI: http://127.0.0.1:5001/hostui
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Remote API server listening on /ip4/127.0.0.1/tcp/5101
Daemon is ready
Experimental.Analytics is overridden by Experimental.StorageHostEnabled
Storage host info will be synced at [SCORE] mode
Current host stats will be synced
Current host settings will be synced
2021-05-08T00:00:40.290+0200    ←[31mERROR←[0m  spin    Failed to sync host stats: Failed to query stats from Hub service: HubQueryClient: Cannot query to get stats, please wait for host validation!
BTFS is up-to-date.
```

**Comment by Sophia-yu-kk** [comment]
Thank you for your feedback, this problem has been solved. Wish you a happy life!

**Comment by akgamersa3** [comment]
16Uiu2HAmUCsrx7S9aEoN6fKZteGZnaLGmZkb2hsxXp3b2x7mhrCJ
getting same problem help me out
