### ISSUE TITLE
I can not choose a second disc

### ISSUE THREAD

**Issue by velyar** [TRON-US/go-btfs#1019]
![image](https://user-images.githubusercontent.com/22917604/116996347-f1d8c100-ace3-11eb-9312-d523bf495019.png)
![image](https://user-images.githubusercontent.com/22917604/116996483-29476d80-ace4-11eb-9915-a68f16c34068.png)
![image](https://user-images.githubusercontent.com/22917604/116996555-4714d280-ace4-11eb-861a-051ec251680d.png)
![image](https://user-images.githubusercontent.com/22917604/116996615-5bf16600-ace4-11eb-8015-f7d83e0b7685.png)
![image](https://user-images.githubusercontent.com/22917604/116996691-7e837f00-ace4-11eb-95fb-a3dd5e88ee44.png)
Disk "D" was previously used for BTFS.
After reinstalling the operating system, BTFS does not see this drive.

**Comment by Rchua72** [comment]
@velyar Did you try creating a BTFS folder in D: drive?  I think I had the same problem before and when I created a new BTFS folder in the other drive, it worked

**Comment by loganxart** [comment]
Unsubscribe
