### ISSUE TITLE
BTFS stuck on validation - almost 6 hours - 8TB HDD

### ISSUE THREAD

**Issue by shenzhenadam** [TRON-US/go-btfs#1020]
Hello,
BTFS stuck on validation - almost 6 hours - 8TB HDD - Please advise if there is an error or if i need to be more patient! 
![2021-05-05_173344](https://user-images.githubusercontent.com/54853892/117122129-20c86300-adc8-11eb-8815-2a5453d52450.png)

**Comment by ZeroCool1974** [comment]
You need to be more patient, mine took almost one day to finish. Good luck!

**Comment by shenzhenadam** [comment]
Thanks for that ... I will wait - does it make any difference if the HDD is an external USB type? and how about adding additional HDD later?
Thanks!

**Comment by velyar** [comment]
The firewall might be blocking the ports.
You can turn it off temporarily.

**Comment by shenzhenadam** [comment]
> 
> 
> The firewall might be blocking the ports.
> You can turn it off temporarily.

Upon installation - already allow through firewall - I have checked again and all boxes ticked to allow through firewall ...

I'll see how it looks after 24/36 hours

**Comment by shenzhenadam** [comment]
Another issue - I had to change the drive letter as I did not do that at the beginning and now the BTFS icon is missing in Bittorrent client - is this something to be concerned about? - it's still validating although I had to directed the web client to new drive letter which it eventually accepted - it seems to have continued on from old drive letter and I checked the capacity it seems it is 5TB full now which shows something is happening ...
![2021-05-05_191908](https://user-images.githubusercontent.com/54853892/117133519-ee723200-add6-11eb-88ef-351cf0324e49.png)

**Comment by shenzhenadam** [comment]
OK I had to start from scratch again .. validation was still reading from old drive letter as well as new drive letter

**Comment by shenzhenadam** [comment]
48 Hours later still stuck on validation .. Shall I still be more patient?

Can someone check on my ID Node to see if there is a problem: 16Uiu2HAm9K4EY188ZnDxz9r8rEkQAQqnFE8vGwVPkrFgMisYmmGJ

Thanks!

**Comment by Sophia-yu-kk** [comment]
The problem of verification timeout has been effectively solved, thank you for your feedback

**Comment by remoicuya** [comment]
Having the same issue. What's the fix for this?

**Comment by shenzhenadam** [comment]
How to solve:
You have to start again - reformat the HDD again and create new folder - it must be labelled: .btfs - it should then work  - it did at least for me ...

Don't bank on earning anything soon - 2 months later no earnings at all for a 8TB HDD - maybe wait for a year or so?

**Comment by remoicuya** [comment]
@shenzhenadam I see. 2 months for a 8tb HDD huh.. I wonder if there's any difference if you'll be using a faster drive. I mean HDDs are limited to 5400 and 7200. Have anyone tried using SSDs?

**Comment by shenzhenadam** [comment]
This sort of crypto mining is only utilizing proof of space so as I far as it is not dependent on HD speed so 5,400/7200 should be fine
