### ISSUE TITLE
hello, problem validating takes too long how to fix that please??

### ISSUE THREAD

**Issue by erfan9292** [TRON-US/go-btfs#1021]
hello, problem validating takes too long how to fix that please??!!

https://prnt.sc/12lm4xy

**Comment by erfan9292** [comment]
my node id

16Uiu2HAmJPMoK33RVwMAD5crvYZHmn7X32ng64E8noWz89VVXRnC

**Comment by shenzhenadam** [comment]
I'm also still wait 40 hours now

**Comment by stevensiliconarts** [comment]
I have the same problem and have waited almost 5 hours and the "btfs" folder is growing extremely slow.

**Comment by shenzhenadam** [comment]
It's still validating for me  (3 days + 40 hours ).. My BTFS folder has not grown at all ... Is there something they are not telling us about?? Is it time to give up?? I did not create a BTFT folder in HDD - could that be the problem not having a dedicated folder called "BTFS" ?

**Comment by Sophia-yu-kk** [comment]
The problem of verification timeout has been effectively solved, thank you for your feedback
