### ISSUE TITLE
uptime going down but node is up 24/7

### ISSUE THREAD

**Issue by aladyn93** [TRON-US/go-btfs#1022]
For a few days the uptime percentage is goind down constantly, about 1%a day but the node is up 24/7. any ideas?

node id : 16Uiu2HAmAhkcLjecpp6gNVJ6NqdABVGvqsRecd1HDWjy2SHp9ZYD

**Comment by Sophia-yu-kk** [comment]
![image](https://user-images.githubusercontent.com/56811501/119616265-fd2a9280-be32-11eb-9ba5-84aac315925e.png)

**Comment by Sophia-yu-kk** [comment]
Uptime will have a regular detection of whether online, a few times no heartbeat is detected is normal. Node 8 points or more will have a chance to get a contract. Thank you for your feedback and have a nice life.
