### ISSUE TITLE
48 Hours later still stuck on validation .. Shall I still be more patient?

### ISSUE THREAD

**Issue by shenzhenadam** [TRON-US/go-btfs#1023]
48 Hours later still stuck on validation .. Shall I still be more patient?

Can someone check on my ID Node to see if there is a problem: 16Uiu2HAm9K4EY188ZnDxz9r8rEkQAQqnFE8vGwVPkrFgMisYmmGJ

Thanks!

_Originally posted by @shenzhenadam in https://github.com/TRON-US/go-btfs/issues/1020#issuecomment-834526444_

**Comment by Sophia-yu-kk** [comment]
48 hours, that's too long. It should be that there were a lot of new nodes added during that time, and the verification queue was long causing the time to be even slower. It should be back up now. Sorry for the inconvenience.

**Comment by alj3dabi** [comment]
> 48 hours, that's too long. It should be that there were a lot of new nodes added during that time, and the verification queue was long causing the time to be even slower. It should be back up now. Sorry for the inconvenience.

Can you provide me the solution? cause I can't find it here. I'm having the same issue.

**Comment by carlin54** [comment]
Yeah, me too

**Comment by shenzhenadam** [comment]
This was commented on earlier in another message: 
https://github.com/TRON-US/go-btfs/issues/1020#issuecomment-877742231

**Comment by carlin54** [comment]
Mine started working haha, thanks.
