### ISSUE TITLE
3k BTT vanished from my BTT in app wallet over night BT Speed and BTFS (shared wallet) 

### ISSUE THREAD

**Issue by Merkbud** [TRON-US/go-btfs#1024]
I woke up this morning to find 3k BTT missing from my BT Speed wallet. Has this happened to anyone else? How do I get it back

![image](https://user-images.githubusercontent.com/37555605/117989081-04698080-b30a-11eb-8c7a-5bf2fe1fc9b7.png)
this was my wallet 15 days ago you can see my post here :

https://www.reddit.com/r/BittorrentToken/comments/mza4ry/where_does_all_my_btt_go_from_bittorrent_speed/

![image](https://user-images.githubusercontent.com/37555605/117989176-1814e700-b30a-11eb-834b-8e74bc536101.png)
Woke up this morning to my balance looking like this.

![image](https://user-images.githubusercontent.com/37555605/117989222-2236e580-b30a-11eb-8075-a15c446c0d1a.png)
I have not moved BTT since February

![image](https://user-images.githubusercontent.com/37555605/117989259-2b27b700-b30a-11eb-82e8-b60eaa56c265.png)
This is my spending, even though I have spending turned off I have only spend ~100BTT

Where has my BTT gone and how can I get it back I was planning on moving my balance to my external wallet app long ago but when I tried to I noticed they disabled sending your BTT to external wallets. Has this happened to anyone else?

**Comment by zxin123662** [comment]
hi,man  can you share me how to earn btt with bittorrent web?

**Comment by EmersonOrion** [comment]
@Merkbud check my issue. it is now 3 month dev promise to return funds. i am missing 15k BTT. over $100USD when BTT was high price. https://github.com/TRON-US/go-btfs/issues/958

**Comment by cyberwalker82** [comment]
This is a BitTorrent Speed wallet question, not directly related to BTFS project, so closing it.

**Comment by xerZV** [comment]
same here, but with less amount only 1k....
