### ISSUE TITLE
How do I expand my BTFS storage? is there a way to add more than 64GB

### ISSUE THREAD

**Issue by westiewill** [TRON-US/go-btfs#1025]
Let me know if its possible to expand my BTFS node's storage, I have 100TB available to provide to BTFS network!
--edit   I figured how to expand from 64 > 7999GB (from 8TB drive) 

also how do i add more drives to the host storage? Seems like you can only have one drive letter

**Comment by Tafaz** [comment]
You can only use one drive letter at once, but you can create a logical volume with multiple disk and use that

**Comment by westiewill** [comment]
Thanks for the tip!   much appreciated
