### ISSUE TITLE
Docker Installation Shows v1.6.0dev but Host Score Version shows 5/10

### ISSUE THREAD

**Issue by dustinshackley** [TRON-US/go-btfs#1028]
Following the docker instructions on this repo, the host ui shows that the version is out of date.

Re-cloning and rebuilding the image doesn't make any difference.
![Capture](https://user-images.githubusercontent.com/40769728/118414930-68c37180-b675-11eb-9ef7-beae72b54038.PNG)
![Capture2](https://user-images.githubusercontent.com/40769728/118414928-68c37180-b675-11eb-8707-0055939ab518.PNG)

**Comment by istarion** [comment]
@dustinshackley , you should use stable version (v1.5.1 ATM)

**Comment by dustinshackley** [comment]
@istarion How do you specify the version when building the docker image?

**Comment by istarion** [comment]
```git checkout btfs-v1.5.1```

**Comment by akgamersa3** [comment]
> Following the docker instructions on this repo, the host ui shows that the version is out of date.
> 
> Re-cloning and rebuilding the image doesn't make any difference.
> ![Capture](https://user-images.githubusercontent.com/40769728/118414930-68c37180-b675-11eb-9ef7-beae72b54038.PNG)
> ![Capture2](https://user-images.githubusercontent.com/40769728/118414928-68c37180-b675-11eb-8707-0055939ab518.PNG)

how much time will it take to get 5 score. plz reply

**Comment by akgamersa3** [comment]
How much time will it take to get 5 score and how much score is required to get contract and earn btt. plz reply

**Comment by dustinshackley** [comment]
@akgamersa3  host scores takes about 2 weeks to increase to 5/10 and I'm guessing for 10/10 a month or more.
You won't be making any btt anytime soon. There's something like 500 petabytes of available storage on btfs right now with very little being used. Odds of you getting the contract are extremely low. This isn't a get rich quick thing.
