### ISSUE TITLE
need help to recover my wallet

### ISSUE THREAD

**Issue by waitformee** [TRON-US/go-btfs#1029]
my harddisk crashed.

when i start btfs again, my wallet is missing. i tried to recover it. but the btt inside is zero.

what should I do now? please help. thanks thanks

**Comment by waitformee** [comment]
hi, anyone got any advise what i can do next.

thanks a lot in advance.

**Comment by cyberwalker82** [comment]
Hi,

If you lost the BTFS config file (a file named config located in where you choose to store files when you run/configure BTFS) which in turn contains the built-in wallet's private key, then there is no chance for you to recover the wallet.

Now the only option is to run a completely new BTFS, this time you can back up the config file or even the whole BTFS repo (the folder you choose to store files).

**Comment by waitformee** [comment]
thanks for the update..... omg.... ahhhh
