### ISSUE TITLE
[go-btfs node] Used space not correct ???

### ISSUE THREAD

**Issue by dipol0** [TRON-US/go-btfs#1030]
I run BTFS-node on Ubuntu linux. On **http://127.0.0.1:5001/hostui/#/host** i see used 41Gb/543.

![Выделение_103](https://user-images.githubusercontent.com/32021806/119012587-d5ed4480-b99e-11eb-94cc-7e9560d9784f.jpg)

But on files webui page i dont see nothing in list, but see info about 13Gb files and 34.8Gb peno (????):

![Выделение_104](https://user-images.githubusercontent.com/32021806/119014262-7728ca80-b9a0-11eb-9359-a5becc6b3f71.jpg)
WTF ? Sorry :))) How i can check and set/fix to correct storage size ???

PS and feature request - set periodic payment who run BTFS-NODE on linux (not use win torrent client) or develope/integrate torrent-client to go-btfs node (like qbittorrent-nox for example).

Tnx.

**Comment by Sophia-yu-kk** [comment]
Hi, when there is an inconsistency between what is displayed on the host UI and the webUI. The one shown on the host UI will prevail.

Sorry for your confusion and have a nice day
