### ISSUE TITLE
BTFS- How to work with dynamic IP address?

### ISSUE THREAD

**Issue by panveli** [TRON-US/go-btfs#1032]
Hello BTFS team and members,

There are many people who are facing issues using a dynamic IP address

When another peer tries to connect by btfs dht findpeer <node id> then ''routing not found'' is the message received.

How can one overcome this issue?

Is there any way to use a hostname or domain name in BTFS in swarm config? Again this is an option for dynamic IP users.

Someone please address this issue as many people will be thankful if they get a solution for this.

Best Regards,
BTT Supporter

**Comment by dipol0** [comment]
You need direct portforward 4001 port on router. Or configure UPNP/NAT-PMP on you router.

**Comment by panveli** [comment]
Portforward 4001 and upnp both are done. With some dynamic IP addresses even these do not work.

**Comment by dipol0** [comment]
> Portforward 4001 and upnp both are done. With some dynamic IP addresses even these do not work.

Open https://portchecker.co/ - you can see you current dynamic IP. Enter in POT FIELD - 8444 and press chek - if CLOSED - i think you need contact with you ISP (may be ISP block port). But YES - optimal use STATIC (WHITE) IP addres for this.
