### ISSUE TITLE
Host UI not working

### ISSUE THREAD

**Issue by andreasbx** [TRON-US/go-btfs#1033]
I did everything as described in the install & Run BTFS page.
The Web UI is also working and the btfs.exe daemon is running.

My current problem is, that the host UI is showing:

 Host profile not enabled

    1. In order to enable your host profile, use command:
    btfs config profile apply storage-host

2. Restart your daemon
3. Refresh this page

Where should I enter this command? I cant type anything in my btfs daemon window and cmd is also not working.
I already Add the btfs folder to the environment variable but Im not sure if it was correct.
Ißm absolutely no programming guy but I really want to get it running.
The Daemon client is saying BTFS is up-to-date and storage host info will be synced at [SCORE] mode.
THe Web UI is showing, that BTFS is working.

Installation via Bittorent client is not working, as the program contijnues to install a crap Webhelper.exe and the btfs 64bit version, or it is not even showing a BTFS button, thats why I´m trying to install it manually.

Any suggestion what I can try else? My brain is cooking right now, as I´ve spent pretty much time on it.

I got the requirements, using win7 32bit with at least 500GB free HDD, 4 GB Ram

Many thanks in advance for any help!

**Comment by dipol0** [comment]
Locate folder with you btfs.exe file? cd in and run in command line (Power Shell) like this:

_**btfs.exe config profile apply storage-host**_

**Comment by cyberwalker82** [comment]
Let us know if there is still problems.
