### ISSUE TITLE
host age is not increasing 

### ISSUE THREAD

**Issue by akgamersa3** [TRON-US/go-btfs#1034]
I leave my system running straight for 2 days but mt host score is still 2. My hostage and uptime score is not increasing.
Host ID
16Uiu2HAmUCsrx7S9aEoN6fKZteGZnaLGmZkb2hsxXp3b2x7mhrCJ

**Comment by akgamersa3** [comment]
now its being 5 days my host age is still 0

**Comment by muntherz7** [comment]
I also left my system running now for 5 days did you receive any result ???

**Comment by akgamersa3** [comment]
Leave it bro, not going to get contract easily, go for other minnig. Mine too getting no response and results.

**Comment by pgmsoul** [comment]
I run it for 3 day，but it is still 0/10
