### ISSUE TITLE
Нow get more BTT for node owner ?

### ISSUE THREAD

**Issue by dipol0** [TRON-US/go-btfs#1035]
I own BTT node on linux ubuntu a few weeks. Have a rank 9. Set low cost per Tb, but not have contracts. Same time win bittorrent client users get more btt with torrent-client and many not run 27/7. May be need think more about peoples who nodes owner? Integrate web-bittorrent client (like qbittorrent-nox for example) or set regular payment per day/week/month + reward for used space.

**Comment by Sophia-yu-kk** [comment]
The current rule is that nodes with a score of 8 or more will randomly acquire contracts . We will think carefully about your suggestions, thank you for your feedback.
