### ISSUE TITLE
BTFS on kubernetes?

### ISSUE THREAD

**Issue by DrissiReda** [TRON-US/go-btfs#1036]
Hello, is there any plan in the near future to add a helm chart to deploy this in kubernetes? And if so, any plans to integrate it with open-id connect sso for more security (something like keycloak) ?

**Comment by cyberwalker82** [comment]
Hi,

Thanks for bringing up this question, but we don't have plan to create/maintain an official Helm Chart. However there are official Docker images hosted in this GitHub repo's Packages' section.
