### ISSUE TITLE
My host age is still 0 after 5 days

### ISSUE THREAD

**Issue by akgamersa3** [TRON-US/go-btfs#1038]
my host age is still 0, my system is running from 5 days, but host age is not increasing.
score is 5.4 due to uptime of 80 percent. But no sign of host age

**Comment by Sophia-yu-kk** [comment]
> my host age is still 0, my system is running from 5 days, but host age is not increasing.
> score is 5.4 due to uptime of 80 percent. But no sign of host age

Could you provide a screenshot of your ID and your score details?

**Comment by akgamersa3** [comment]
Now my uptime score is stuck, my uprime is 87 percent still my score is 6.6 
 my host age is 5 now

**Comment by devagarwal77** [comment]
How your uptime increased did you do anything.

**Comment by akgamersa3** [comment]
i followed every instruction, my system is running from 7 days , giving above 800gb storage,power,internet what else should i do

**Comment by akgamersa3** [comment]
see sir, as per you tron you even not specifying on what score did i able to get contract, plus i hade 87 percent uptime still, score is not updating, you didn't specify rules or time required for getting contract in you own website or in youtube video. kindly clarify....

**Comment by devagarwal77** [comment]
Same here bro.. Better we mine different coin..

**Comment by devagarwal77** [comment]
![IMG_20210529_112826](https://user-images.githubusercontent.com/28737478/120059757-0ef97900-c071-11eb-880d-d9c98635dba0.jpg)

See this bro. Host age still 0 only. Not sure when it will increase.

**Comment by akgamersa3** [comment]
dont know yesterday mine host age was 0, today is 5 and uptime percentage is 88 but still total score is 6.6 
dont know what they are doing

**Comment by akgamersa3** [comment]
![fff](https://user-images.githubusercontent.com/84560762/120059900-2bfa6180-c009-11eb-9fe8-89b7bd98d351.png)

**Comment by Sophia-yu-kk** [comment]
This score is normal.Uptime to be enhanced, to stay constantly online，host age, will automatically grow. These seem to be normal.
