### ISSUE TITLE
0 earning ratio btt speed, what the bug is this

### ISSUE THREAD

**Issue by akgamersa3** [TRON-US/go-btfs#1039]
I seeded more than 150 gb, still my earning ratio is showing 0btt/gb. no wallet update plus no earning of btt. help me out of this
![sfsdf](https://user-images.githubusercontent.com/84560762/119648786-7cbe5e80-be3f-11eb-9009-0d1d3569f6a1.png)

**Comment by Sophia-yu-kk** [comment]
> I seeded more than 150 gb, still my earning ratio is showing 0btt/gb. no wallet update plus no earning of btt. help me out of this

Hello, thank you for your feedback. This is a BTFS project and your question has been sent back to the person in charge of BT speed

**Comment by akgamersa3** [comment]
where should i post

**Comment by akgamersa3** [comment]
plz send this no seeding earning speed kindly check, 
![image](https://user-images.githubusercontent.com/84560762/120167056-eb723200-c21a-11eb-971b-ac6dcc7a28ed.png)
