### ISSUE TITLE
failed to sync btt-tx

### ISSUE THREAD

**Issue by akgamersa3** [TRON-US/go-btfs#1040]
every night it comes i have to restart the daemon. its disgusting to do that. devs do something
16Uiu2HAmUCsrx7S9aEoN6fKZteGZnaLGmZkb2hsxXp3b2x7mhrCJ
![gg](https://user-images.githubusercontent.com/84560762/119751042-4dafe900-be4f-11eb-97dc-6f33c2755c67.png)

**Comment by Sophia-yu-kk** [comment]
Hello, thank you for your feedback. After confirming that this error report should not BTFS related function use, you can ignore it. In the future, we will make an optimization to hide this error report to avoid misunderstanding.

**Comment by akgamersa3** [comment]
ok, please tell me that my host score is not incresing, my system is working from 6 days but host score is still 0.
16Uiu2HAmUCsrx7S9aEoN6fKZteGZnaLGmZkb2hsxXp3b2x7mhrCJ
please tell me when, will i gained acess for contract
