### ISSUE TITLE
Sign in to your BitTorrent Wallet

### ISSUE THREAD

**Issue by MilNoslen** [TRON-US/go-btfs#1044]
I imported my BTT Speed wallet with the passphrase and set the password. However, when trying to login, it gives me "Incorrect password". This password is correct.

I am currently validating my node, do I have to wait to access my wallet?

**Comment by MilNoslen** [comment]
Node has been validated. 
I imported my wallet again and changed the password. I remember reading a closed issue that # doesn't work well in the password. 

Might need to add % to that list too.

**Comment by Sophia-yu-kk** [comment]
> Node has been validated.
> I imported my wallet again and changed the password. I remember reading a closed issue that # doesn't work well in the password.
> 
> Might need to add % to that list too.

Thank you for your feedback. If the problem has been resolved, I will go ahead and close this issue. If you have any further project-related questions, feel free to contact us.
