### ISSUE TITLE
Host age is 0 Please tell me the solution

### ISSUE THREAD

**Issue by devagarwal77** [TRON-US/go-btfs#1045]
![IMG_20210529_112826](https://user-images.githubusercontent.com/28737478/120059757-0ef97900-c071-11eb-880d-d9c98635dba0.jpg 
Host age still 0 only. Not sure when it will increase.

_Originally posted by @devagarwal77 in https://github.com/TRON-US/go-btfs/issues/1038#issuecomment-850776980_

**Comment by lukasmd1989** [comment]
It takes at least 10 days. Just be patient...

**Comment by Sophia-yu-kk** [comment]
I saw your screenshot and this score improvement is probably going to take about 10 days.
