### ISSUE TITLE
uptime score is stuck 

### ISSUE THREAD

**Issue by akgamersa3** [TRON-US/go-btfs#1047]
my uptime percentage is 89 but my uptime score is 6 
peer id -16Uiu2HAmUCsrx7S9aEoN6fKZteGZnaLGmZkb2hsxXp3b2x7mhrCJ
![tgff](https://user-images.githubusercontent.com/84560762/120166311-4cfdb680-c1b1-11eb-8c2e-94783af86c8b.png)

**Comment by Sophia-yu-kk** [comment]
> my uptime percentage is 89 but my uptime score is 6
> peer id -16Uiu2HAmUCsrx7S9aEoN6fKZteGZnaLGmZkb2hsxXp3b2x7mhrCJ

Hello, glad to see your feedback!
uptime is 89%, which means 89% of the time online.
The score of uptime is 6, because uptime is 6 in 80%-90%.
This is a normal situation, please continue to stay online.
Have a great day!
