### ISSUE TITLE
Stuck at Validating Screen for 6 hours & counting

### ISSUE THREAD

**Issue by kunal88del** [TRON-US/go-btfs#1048]
Node ID:
16Uiu2HAmNNf4BdA9HjSk5BAqYUAHB1j5jvAi6W3zcT6axRf66rAm

I know this is a persistent issue faced by several other users, many of whom have mentioned it here on Github & I am afraid even I am facing this problem fo being stuck at Validating screen for far the last 6+ hours (at the time of writing this post).

Can you please look into this issue & provide a suitable update in order to resolve this problem? 
Another query that I have is regarding the Pricing TB/month. For my profile, it was automatically set at custom pricing of 3,840 BTT which was lower than the default pricing. So, I changed it back to the default pricing of 7,680 BTT. Now, it says over there that changes to advanced settings can impact your host earnings. Please make sure you understand the effects before making any changes. So, what I would like to know is which setting provides better earnings, the default at 7,680 BTT or the custom setting which was pre-filled for my profile at 3,840 BTT?
Thanks in advance

**Comment by Sophia-yu-kk** [comment]
> Node ID:
> 16Uiu2HAmNNf4BdA9HjSk5BAqYUAHB1j5jvAi6W3zcT6axRf66rAm
> 
> I know this is a persistent issue faced by several other users, many of whom have mentioned it here on Github & I am afraid even I am facing this problem fo being stuck at Validating screen for far the last 6+ hours (at the time of writing this post).
> 
> Can you please look into this issue & provide a suitable update in order to resolve this problem?
> Another query that I have is regarding the Pricing TB/month. For my profile, it was automatically set at custom pricing of 3,840 BTT which was lower than the default pricing. So, I changed it back to the default pricing of 7,680 BTT. Now, it says over there that changes to advanced settings can impact your host earnings. Please make sure you understand the effects before making any changes. So, what I would like to know is which setting provides better earnings, the default at 7,680 BTT or the custom setting which was pre-filled for my profile at 3,840 BTT?
> Thanks in advance

This issue of validating is checked by the team, and sometimes too many synchronized nodes can cause slowdowns, but we will check this issue anyway.

I suggest you to be 3840, this is the real suggested price and more beneficial to get the contract. 7680 is the previous suggested price, which has been changed to 3840.

Thank you for your feedback and have a great day.
