### ISSUE TITLE
Even hard drive being used no earnings is being received and score is slow changing when syncing.

### ISSUE THREAD

**Issue by rgouzal** [TRON-US/go-btfs#1049]
I have an issue seeing earnings until now, I have a 12 TB hard drive mounted on a raspberry pi 4b running Ubuntu OS. I left the raspberry pi online for about  a week and I can't see score increasing until now the score is still 6.2. Can you please tell me why score is so low at start and why it is slow syncing?

My  specs:
 
CPU: ARM Cortex-A72 CPU 1.5 GHz
RAM: 4GB
OS: Ubuntu Desktop 21.04

**Comment by Sophia-yu-kk** [comment]
The slow sync speed is due to many new nodes recently and this part of the team is in the process of optimization.
Thank you for your feedback.
About the slow growth of the score, you can send me the specific parameters of the score.

**Comment by rgouzal** [comment]
@Sophia-yu-kk what parameters? and where can I find them?

**Comment by Sophia-yu-kk** [comment]
You can use this command to query" btfs storage stats info"
