### ISSUE TITLE
How can I add storage from multiple hard drives on my Windows system?

### ISSUE THREAD

**Issue by kunal88del** [TRON-US/go-btfs#1051]
Node ID:
16Uiu2HAmNNf4BdA9HjSk5BAqYUAHB1j5jvAi6W3zcT6axRf66rAm

I have recently set-up the BTFS node on one of my internal hard drives & I would like to ask how can I add more space to BTFS by combining multiple internal hard drive space that I have with me? Right now, I can only select a single folder thru the WebUI.

**Comment by Yrp** [comment]
Hi, @kunal88del, this is a good question, but BTFS does not support multipath storage. If you want to use multiple drives to add storage space to BTFS, consider using raid.

**Comment by Yrp** [comment]
I will close this issue, please reopen it if you have questions about it.
