### ISSUE TITLE
Failed to syn btt-tx-,   lookup api.trongrid.io: no such host

### ISSUE THREAD

**Issue by akgamersa3** [TRON-US/go-btfs#1052]
peer id - 16Uiu2HAmUCsrx7S9aEoN6fKZteGZnaLGmZkb2hsxXp3b2x7mhrCJ

plus i think my uptime percentage is stuck its being 3 days it is same 91 percent no change ...

![fffa](https://user-images.githubusercontent.com/84560762/120734669-ebb64a00-c506-11eb-9277-886fa3212094.png)
![tgff](https://user-images.githubusercontent.com/84560762/120734926-54052b80-c507-11eb-9b11-b996feceda12.png)

**Comment by Sophia-yu-kk** [comment]
This is a known issue and is already being optimized for this issue

**Comment by Sophia-yu-kk** [comment]
This issue has been fixed, thank you for your feedback.
