### ISSUE TITLE
Wallet get balance failed ERR: Failed to get ledger balance,

### ISSUE THREAD

**Issue by nastaransamui** [TRON-US/go-btfs#1053]
Wallet get balance failed ERR: Failed to get ledger balance, reason: EscrowClient: rpc error: code = Unknown desc = ledger error:context dealine exceeded
I get this error on Ubuntu 20 server and doesn't show any balance

**Comment by Sophia-yu-kk** [comment]
The wallet service is under maintenance, sorry for any inconvenience caused to you.
