### ISSUE TITLE
failed to find any peer in table

### ISSUE THREAD

**Issue by akgamersa3** [TRON-US/go-btfs#1054]
peer id - 16Uiu2HAmUCsrx7S9aEoN6fKZteGZnaLGmZkb2hsxXp3b2x7mhrCJ
![Untitled](https://user-images.githubusercontent.com/84560762/120745158-270e4400-c51a-11eb-9498-942aae07ff3a.png)

**Comment by Sophia-yu-kk** [comment]
When uploading files, this error is reported if a peer node is not found within 15 minutes. This bug has been fixed.

Thank you for your feedback.
