### ISSUE TITLE
stuck with 91 percent uptime from 5 days

### ISSUE THREAD

**Issue by akgamersa3** [TRON-US/go-btfs#1055]
peer id - 16Uiu2HAmUCsrx7S9aEoN6fKZteGZnaLGmZkb2hsxXp3b2x7mhrCJ
![tgff](https://user-images.githubusercontent.com/84560762/120925683-49a98400-c6f7-11eb-998f-72675fb2c964.png)

**Comment by Sophia-yu-kk** [comment]
May I ask, does this machine stay online all the time?

**Comment by akgamersa3** [comment]
yes, all the time. 
but also i restarted deamon many times, as i am facing issues that i posted

**Comment by Sophia-yu-kk** [comment]
uptime, the online time, reflects the online status of the node.
Please take care to stay online and do not turn off or disconnect the power.In the meantime, we also check if there are any problems with the uptime display.

Thank you for your feedback.

**Comment by emm-dee** [comment]
Same here. Host is online 24/7 and the uptime hasn't budged in several days. BTFS shows online and my node is visible in the explorer, still the uptime doesn't move.

**Comment by akgamersa3** [comment]
> uptime, the online time, reflects the online status of the node.
> Please take care to stay online and do not turn off or disconnect the power.In the meantime, we also check if there are any problems with the uptime display.
> 
> Thank you for your feedback.

still on same uptime percentage... and same score..

**Comment by MasterZeh** [comment]
Sorry for the dumb question, why do you leave the host in Repair On? Is there any benefit?

**Comment by Sophia-yu-kk** [comment]
Thank you for your feedback, we attach great importance to this issue. This issue has now been fixed. It is now back to normal.

**Comment by Sophia-yu-kk** [comment]
> Sorry for the dumb question, why do you leave the host in Repair On? Is there any benefit?

Hi, currently there is no revenue, you can choose to turn off this mode. Thank you for your question.
