### ISSUE TITLE
Cannot transfer BTFS wallet balance back to BTT crypto wallet

### ISSUE THREAD

**Issue by jefftrex** [TRON-US/go-btfs#1056]
I transferred 1000 BTT from my tronlink wallet to my BTFS wallet on 5/30. Today, I tried to send this 1000 BTT back to my BTT wallet, but it has failed twice in my trying. The interface doesn't give me any information about why or what failed, and I see no transaction on tronscan at all for my wallet on either attempt.

Any idea how to fix or how to get my tokens back to tronscan?

Peer ID 16Uiu2HAm2gT68oSMFUTrCoyssWQGHRKhtnBD2mm4eDsGZFGh43Qj

Edit to add: I have plenty of energy and bandwidth stored in my tronlink wallet if that matters, but like I said before, no transactions appear in tronscan.

![Screenshot 2021-06-06 101841](https://user-images.githubusercontent.com/24946456/120927978-d4b35b80-c6b0-11eb-8015-4079e09fef4a.png)

**Comment by Sophia-yu-kk** [comment]
Hi, this is a known issue and the wallet related features are undergoing maintenance. We apologize for any inconvenience caused to you.
