### ISSUE TITLE
Failed to sync btt-tx An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by akgamersa3** [TRON-US/go-btfs#1057]
id - 16Uiu2HAmUCsrx7S9aEoN6fKZteGZnaLGmZkb2hsxXp3b2x7mhrCJ
![image](https://user-images.githubusercontent.com/84560762/120953009-cd03bd80-c769-11eb-8619-edbb789a2cfc.png)
![image](https://user-images.githubusercontent.com/84560762/120953033-d7be5280-c769-11eb-8137-b0443fe9a158.png)

**Comment by Sophia-yu-kk** [comment]
After confirming, this is caused by trongrid current limit, which can be ignored and has no effect on using BTFS.
