### ISSUE TITLE
btfs host still showing as validating status after 24 hours

### ISSUE THREAD

**Issue by mdeora** [TRON-US/go-btfs#1058]
Host id - 16Uiu2HAkx4ni2xUhBgmdcm613MrfnUpcHnno2WapRvDCnKXJ7Eg5

Not much data transfer too.
![Screenshot 2021-06-07 at 10 56 21 AM](https://user-images.githubusercontent.com/156933/120963362-114d8880-c77f-11eb-98e2-75c415ba280c.png)

**Comment by Sophia-yu-kk** [comment]
> Host id - 16Uiu2HAkx4ni2xUhBgmdcm613MrfnUpcHnno2WapRvDCnKXJ7Eg5
> 
> Not much data transfer too.
> ![Screenshot 2021-06-07 at 10 56 21 AM](https://user-images.githubusercontent.com/156933/120963362-114d8880-c77f-11eb-98e2-75c415ba280c.png)

There are currently more new nodes, resulting in slow validation times. Team side is in optimization. Thank you for your feedback.

**Comment by mdeora** [comment]
Hey, thanks for the response. Is there any open analytics status page to have some stats around it?
"There are currently more new nodes,"
