### ISSUE TITLE
stuck uptime and host age

### ISSUE THREAD

**Issue by TrackerCoder** [TRON-US/go-btfs#1060]
12 day I do not turn off the system, uptime is 99 percent, host age is 0. 
What's wrong?

**Comment by emm-dee** [comment]
Same issue, host uptime has not updated in 4+ days

**Comment by Yrp** [comment]
@TrackerCoder @emm-dee Please provide your node id.

**Comment by TrackerCoder** [comment]
@Yrp 16Uiu2HAmCmL72tQEQJLjPs3x8eVHc6XK57TuTqVRf3vNhJ2kMzvz

**Comment by TrackerCoder** [comment]
Any update?

**Comment by TrackerCoder** [comment]
Two weeks, uptime 99%, hostage 0. Didn't turn off my computer

**Comment by Sophia-yu-kk** [comment]
This is a known issue and is already being optimized for this issue

**Comment by TrackerCoder** [comment]
Updated today, uptime 100%, hostage 5/10. Closed the issue.

**Comment by Yrp** [comment]
Congratulations!
