### ISSUE TITLE
Failed to sync host stats ! More 3 days...

### ISSUE THREAD

**Issue by antoinerude** [TRON-US/go-btfs#1061]
For 3 days without shutting down my computer, my node is still not validated! With the following error message:

2021-06-07T14:38:05.960+0200    ←[31mERROR←[0m  spin    Failed to sync host stats: Failed to query stats from Hub service: HubQueryClient: Cannot query to get stats, please wait for host validation!

Node ID : 16Uiu2HAmJo5W5mA7DxuPhDSThJnBxmqQFoiuYwAzjbe6jwroCAaE

**Comment by maksimla** [comment]
the same 
![image](https://user-images.githubusercontent.com/3274545/121223414-2d8d1a80-c890-11eb-927e-589b97633a54.png)
Peer identity: 16Uiu2HAkzzSLP6tmMZuYeeJcT6QXysKFxhnqEoZE4WRXQVTyhHUB

**Comment by AlexBion** [comment]
solved?

**Comment by antoinerude** [comment]
No solution :( ???

**Comment by Sophia-yu-kk** [comment]
This is a known issue, caused by too many nodes recently, and is already being optimized for this issue.
Sorry for the inconvenience

**Comment by antoinerude** [comment]
> This is a known issue, caused by too many nodes recently, and is already being optimized for this issue.
> Sorry for the inconvenience

Do you have any idea when my node will be active? Already more than 4 days that I wait...
> Node ID : 16Uiu2HAmJo5W5mA7DxuPhDSThJnBxmqQFoiuYwAzjbe6jwroCAaE

**Comment by antoinerude** [comment]
???
