### ISSUE TITLE
stuck on validation 

### ISSUE THREAD

**Issue by naplord95** [TRON-US/go-btfs#1062]
It's been over a week but I'm still stuck on this screen

How i can fix it?

**Comment by emilortacu22** [comment]
Hello, I'm waiting for more than 6 hours for this turn (earlier I've waiting 3 days and nothing). I get the same message a lot of times:
2021-06-10T00:07:23.293+0300 ←[31mERROR←[0m spin Failed to sync host stats: Failed to query stats from Hub service: HubQueryClient: Cannot query to get stats, please wait for host validation!

Also my host id is: 16Uiu2HAmRWFD98ZqUStCrPksTZiX1NbdM7pFYV9mDoHpKbHgs77G

Can you please help me? I want to contribute with 60 TiB, but I think I'll quit if no one will help me.

**Comment by Mascotch** [comment]
Same here.
Cannot query to get stats, please wait for host validation!

**Comment by Sophia-yu-kk** [comment]
This is a known issue and is already being optimized for this issue

**Comment by Mascotch** [comment]
No host validation here. Where can I check logs to figure out what is going on?

**Comment by Mascotch** [comment]
Been running non stop for 6 hours today. Nothing happens. This is really frustrating.

**Comment by Sophia-yu-kk** [comment]
This issue has been fixed, thank you for your feedback. It works fine now.
