### ISSUE TITLE
Stuck on validation

### ISSUE THREAD

**Issue by emilortacu22** [TRON-US/go-btfs#1063]
Hello, I'm waiting for more than 6 hours for this turn (earlier I've waiting 3 days and nothing). I get the same message a lot of times:
2021-06-10T00:07:23.293+0300 ←[31mERROR←[0m spin Failed to sync host stats: Failed to query stats from Hub service: HubQueryClient: Cannot query to get stats, please wait for host validation!

Also my host id is: 16Uiu2HAmRWFD98ZqUStCrPksTZiX1NbdM7pFYV9mDoHpKbHgs77G

Can you please help me? I want to contribute with 60 TiB, but I think I'll quit if no one will help me.

**Comment by realabbas** [comment]
@emilortacu22 Yeah I'm facing a similar issue. Do you want to contribute 60PiB?

**Comment by emilortacu22** [comment]
@realabbas , Hey, I want to contribute with 60 TiB. The value which you provided it's the size of a big datacenter 👯‍♀️

**Comment by Sophia-yu-kk** [comment]
This is a known issue and is already being optimized for this issue

**Comment by emilortacu22** [comment]
@Sophia-yu-kk What's the solution for our problem? You mean the issue is currently under investigation?

**Comment by realabbas** [comment]
> @realabbas , Hey, I want to contribute with 60 TiB. The value which you provided it's the size of a big datacenter 👯‍♀️

how did you manage 60PiB?

**Comment by GustavoPAlmeida** [comment]
Seems like it's working now

**Comment by Sophia-yu-kk** [comment]
This issue has been fixed, thank you for your feedback. It works fine now.
