### ISSUE TITLE
Uptime and Score not updating

### ISSUE THREAD

**Issue by coolpintud** [TRON-US/go-btfs#1064]
Hi,

I have issues with score update i stated btfs on 31/05/2021 within two days my score increase to 6.2 on 02/06/2021 but after 8 day my score still same 6.2 no any update so please check and confirm is there is issues with my host so i have to reinstall ?

My host id: 
16Uiu2HAmFKweSGrnncNdUg4b6ZEnXphy69wR1ESRF3nhFyw7Tvmb

**Comment by Sophia-yu-kk** [comment]
This issue has been fixed, thank you for your feedback. It works fine now.
