### ISSUE TITLE
The host's uptime decreases.

### ISSUE THREAD

**Issue by zarethernet** [TRON-US/go-btfs#1065]
Hello, the uptime of the host is decreasing every day, is it possible to somehow restore or reset?

Node ID: 16Uiu2HAmMSEYe4JmvJJ6Gjbikh87crqjXymmBeBBpyV9yoUVyBpV

**Comment by Sophia-yu-kk** [comment]
> Hello, the uptime of the host is decreasing every day, is it possible to somehow restore or reset?
> 
> Node ID: 16Uiu2HAmMSEYe4JmvJJ6Gjbikh87crqjXymmBeBBpyV9yoUVyBpV

Thank you for your feedback, we attach great importance to this issue. This issue has now been fixed. It is now back to normal.

**Comment by zarethernet** [comment]
> > Hello, the uptime of the host is decreasing every day, is it possible to somehow restore or reset?
> > Node ID: 16Uiu2HAmMSEYe4JmvJJ6Gjbikh87crqjXymmBeBBpyV9yoUVyBpV
> 
> Thank you for your feedback, we attach great importance to this issue. This issue has now been fixed. It is now back to normal.

Thank you :-)
