### ISSUE TITLE
Gateway link to  download file from btfs not responding again

### ISSUE THREAD

**Issue by nikorobos** [TRON-US/go-btfs#1066]
Hello i uploaded a file to btfs web ui and i cannot access it after. I tried to downlaod it froma phone and a computer and nothing happens. Here is the link to try https://gateway.btfs.io/btfs/QmPoBqTHLPgg4wVnB6NjHuX2shdR5YxTNShUFdpVyWqENy?filename=2.jpg

**Comment by Sophia-yu-kk** [comment]
QmPoBqTHLPgg4wVnB6NjHuX2shdR5YxTNShUFdpVyWqENy?filename=2.jpg
This doesn't look like a file hash.

Please check if the file hash is correct

**Comment by nikorobos** [comment]
This is the default hash that is generated when i upload file to btfs from the web ui

**Comment by nikorobos** [comment]
I tried also to remove ?filename=2.jpg from the link and still nothing is happening, stuck in infinite loading

**Comment by Sophia-yu-kk** [comment]
This kind of similar problem could be not only a Gateway error, but also a problem with the connection from the node where he uploaded the file to the BTFS network,Other nodes in the BTFS network cannot download the files added to it.
