### ISSUE TITLE
Host uptime decrease

### ISSUE THREAD

**Issue by MasterZeh** [TRON-US/go-btfs#1067]
Hi

I noticed both of my hosts are decreasing its uptime index. My older host dropped uptime in two days from 100% to 91% and my host score went from 10 to 8.2, while the new one (3 days old) never reached its 100% initial uptime.

I do not see any errors in the daemon log page.

I'm unsure if that makes any difference, but it I noticed the old host drop at the same day I did:

- dist upgrade from Ubuntu 20.10 to 21.04
- the new host came up online (and both hosts share the same internet/IP address)

Any help is super appreciated. The old host has a few contracts in it.

Affected hosts:
16Uiu2HAmKAZrNQ9Jjay1dkfwws2dnxvPWxidhu4RaiwTsAAyoEhp
![image](https://user-images.githubusercontent.com/85850180/121823893-72c7a700-cceb-11eb-9032-46ea92daf96a.png)

16Uiu2HAm5qZe8KpqEV1JFTSdn8zwT3fD8CCJKaTR5MtnRzvUCGsA
![image](https://user-images.githubusercontent.com/85850180/121823944-de117900-cceb-11eb-9f51-f44e84c88bd2.png)

Thank you very much
Zeh

**Comment by MasterZeh** [comment]
Hi guys
Please hold any check on this issue, I think I found out what was wrong.
I'll give an update in the next days, but it was definitely something here :(

Regards,
Zeh

**Comment by Sophia-yu-kk** [comment]
> Hi guys
> Please hold any check on this issue, I think I found out what was wrong.
> I'll give an update in the next days, but it was definitely something here :(
> 
> Regards,
> Zeh

There was a problem with the data module a while ago, which has been resolved. If you have questions, you can keep in touch. Thank you for your feedback.

**Comment by MasterZeh** [comment]
Hi @Sophia-yu-kk  I think I made a mistake while upgrading my Ubuntu, I forgot to reapply the sleep setting on logind.conf, which made the host go to sleep everytime I closed the lid... dumb me.
It's all good now, thanks heaps!
