### ISSUE TITLE
failed to validate envelope

### ISSUE THREAD

**Issue by AlexBion** [TRON-US/go-btfs#1068]
Please help me!
after 1 week with the "sync error", now I'm with an host-score=3, an uptime 0/10 (i have the pc online from about 3 days) and the daemon give me this errors and shutdown:

![image](https://user-images.githubusercontent.com/49072180/121886819-3198bc80-cd16-11eb-9327-f8068bec2f25.png)

**Comment by AlexBion** [comment]
![image](https://user-images.githubusercontent.com/49072180/121918523-69176100-cd36-11eb-8619-21b53ebbc2fa.png)

this is my actual problem. What can I do to resolve it?

**Comment by AlexBion** [comment]
no one can help me? please :(

**Comment by Sophia-yu-kk** [comment]
The sync timeout issue has been fixed and is now normal.You can try again, thanks for your feedback.

**Comment by AlexBion** [comment]
> The sync timeout issue has been fixed and is now normal.You can try again, thanks for your feedback.

very thanks :)
