### ISSUE TITLE
Can't acess internet when btfs is on

### ISSUE THREAD

**Issue by poke-anis** [TRON-US/go-btfs#1069]
When i start btfs all my network hosts can't get access to internet ,i checked my network with wireshark and i don't get response from dns server
i can access to pages with their ip what confirm the dns theory.
can someone help me ?
i tried to to create a local DNS server ,it doesn't work .
go-btfs version : 1.5.1-208e586

**Comment by Sophia-yu-kk** [comment]
> When i start btfs all my network hosts can't get access to internet ,i checked my network with wireshark and i don't get response from dns server
> i can access to pages with their ip what confirm the dns theory.
> can someone help me ?
> i tried to to create a local DNS server ,it doesn't work .
> go-btfs version : 1.5.1-208e586

This problem seems to have nothing to do with go-btfs, except that his network dns configuration may be wrong. Thank you for your feedback!

**Comment by poke-anis** [comment]
it does have i reduced swarm high water and now its better i suppose it exceeded bandwidth limit
