### ISSUE TITLE
Error getting peer record

### ISSUE THREAD

**Issue by emilortacu22** [TRON-US/go-btfs#1070]
Does anyone know what this error means?

 ←[31mERROR←[0m  net/identify    error getting peer record from Identify message: failed to validate envelope: invalid signature or incorrect domain

**Comment by Sophia-yu-kk** [comment]
“error getting peer record from Identify message: failed to validate envelope: invalid signature or incorrect domain”
This error is reported when adding a trusted address to the p2p network of btfs and verifying that the domain or envelop signature of the other party is illegal

**Comment by emilortacu22** [comment]
Thanks for the info. Also can you check my host? The host marks are getting up very very slow like 1-2% percent a day. This is my host id: 16Uiu2HAmGNLRyKwnMKb2cXBTY8b5Hkxn88YW2o9aj7eGuTVghDjF
