### ISSUE TITLE
Connection timeout from gateway download link of file

### ISSUE THREAD

**Issue by nikorobos** [TRON-US/go-btfs#1071]
After i upload the file in the BTFS Web Ui it generating a link which is https://gateway.btfs.io/btfs/QmYAfkqAHwWkXqvwxdwDfCznj6DNdBvc7od6rntpX4yYh8 and i am not able to download the file. It keeps loading and showing this image. I have asked a question before but i was not able to have a solution about the problem. Thank you.

![Web capture_17-6-2021_2289_gateway btfs io](https://user-images.githubusercontent.com/30929830/122459453-9f184780-cfb9-11eb-858e-b86a4066f15c.jpeg)

**Comment by Sophia-yu-kk** [comment]
After confirming, it's not a Gateway problem. It is because there is a problem with the connection from the node you uploaded the file to the BTFS network, and other nodes on the BTFS network cannot download the file it added.

**Comment by nikorobos** [comment]
So what can i do to fix this problem? I am uploading the file through the web ui and it is uploaded with success.

**Comment by Sophia-yu-kk** [comment]
Uploading via the web is uploading to the local node, if you want to store to the BTFS network, you need to do something else, see https://docs.btfs.io/docs/storage-rental
