### ISSUE TITLE
Slow host mark increasing

### ISSUE THREAD

**Issue by emilortacu22** [TRON-US/go-btfs#1072]
Can you check my host? The host marks are getting up very very slow like 1-2% percent a day. This is my host id: 16Uiu2HAmGNLRyKwnMKb2cXBTY8b5Hkxn88YW2o9aj7eGuTVghDjF

**Comment by coolpintud** [comment]
same here not updating host age 
my host id: 16Uiu2HAmFKweSGrnncNdUg4b6ZEnXphy69wR1ESRF3nhFyw7Tvmb
![image](https://user-images.githubusercontent.com/16254213/122589955-86259a00-d07e-11eb-9bf2-5110b1f138df.png)

**Comment by dipol0** [comment]
Wait a month +- few days. Pls close )))

![Выделение_148](https://user-images.githubusercontent.com/32021806/122616584-503ee080-d093-11eb-9524-8776d0e7df78.jpg)

**Comment by EduardDobre** [comment]
@dipol0 , did you get any contracts/BTT yet?
