### ISSUE TITLE
problem with starting the daemon

### ISSUE THREAD

**Issue by Piraveen09** [TRON-US/go-btfs#1073]
serveHTTPGateway: manet.Listen(/ip4/127.0.0.1/tcp/8080) failed: listen tcp4 127.0.0.1:8080: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

**Comment by MasterZeh** [comment]
Which OS are you running?
When/Where do you see that message?
Do you have this port 8080 in use? 
Any firewall/AV/SELinux running?

**Comment by Sophia-yu-kk** [comment]
It is recommended that you check your firewall settings.

**Comment by Piraveen09** [comment]
Hi, thank you for the suggestions. 
I found the issue and rectified.
Now it is working good .

Actually the port 8080 was used by another so after I terminated it . BTFS started to working well.

Thank you 👍🏽👍🏽

**Comment by Sophia-yu-kk** [comment]
You are welcome, and if you have new questions, you can contact us. You are also welcome to join our idscord group chat. https://discord.gg/vYD6Kyeb
