### ISSUE TITLE
Score 10, 14TB storage, over a month of running,    ZERO CONTRACTS

### ISSUE THREAD

**Issue by mqm165** [TRON-US/go-btfs#1076]
I've been running btfs for over a month now

I have:
- Score 10
- 14TB of storage

and till now I'm having ZERO CONTRACTS

**Comment by Sophia-yu-kk** [comment]
Theoretically, a node score of 8 or more has a chance to get the contract, and the number of nodes in the whole network has exceeded 1 million, so the competition is relatively fierce.

Node-related data can be accessed at this address: https://scan.btfs.io

**Comment by wbkys** [comment]
me too
