### ISSUE TITLE
Failed to sync

### ISSUE THREAD

**Issue by AlexBion** [TRON-US/go-btfs#1077]
Hello,
how long does it take to sync?
My desktop has been online for several hours, with this error: ← [31mERROR ← [0m spin Failed to synchronize host statistics: Failed to query statistics from Hub service: HubQueryClient: Failed to query to get statistics, please wait validation of the host!

my id is : 16Uiu2HAmBuWmZGeg1CQbMfUNHTbG3uBjqT6XaMPnXbHutLVG4Er6

Thanks in advance for your help.

**Comment by TheBestBadGamer** [comment]
Have the same problem.

My ID is:
16Uiu2HAm3ykxHkzUYhF53PTsERkVftnVNQw8Ph1sU6BUvQ3ugqDC

**Comment by Sophia-yu-kk** [comment]
Hello, it takes about 10 hours for a single node to validating , what is the current status of your node? Is it still in sync?

**Comment by Sophia-yu-kk** [comment]
> Hello,
> how long does it take to sync?
> My desktop has been online for several hours, with this error: ← [31mERROR ← [0m spin Failed to synchronize host statistics: Failed to query statistics from Hub service: HubQueryClient: Failed to query to get statistics, please wait validation of the host!
> 
> my id is : 16Uiu2HAmBuWmZGeg1CQbMfUNHTbG3uBjqT6XaMPnXbHutLVG4Er6
> 
> Thanks in advance for your help.

I read the error message you provided. The error message means that you need to keep waiting, not that the sync failed

**Comment by AlexBion** [comment]
Hi sophia,
this morning I found it synchronized automatically. thank you

**Comment by Sophia-yu-kk** [comment]
happy to
