### ISSUE TITLE
Missing payment 

### ISSUE THREAD

**Issue by thatalbertaguy** [TRON-US/go-btfs#1079]
Hi , 

I have been running a node since February and have not received a payment as stated on my page for March 12 for 902 btt

here is my node is

16Uiu2HAmGQg7xKM6GhRqEACGJuWFfC46FsyijBc6kigUc8Y1hM9j

![8C265B2D-AC59-425C-9A30-E6B0C8CAC585](https://user-images.githubusercontent.com/81401292/123479855-bad5ac00-d5be-11eb-87ec-c1d905634c16.png)
![81ADA6CA-AAE3-4BFD-8EBE-7824DE315F7E](https://user-images.githubusercontent.com/81401292/123479858-bc9f6f80-d5be-11eb-9f72-3d3746ceba63.png)

**Comment by thatalbertaguy** [comment]
Hi 

Is anyone looking into this ? 

Thanks

**Comment by thatalbertaguy** [comment]
Do you need any addition info ? Payment still hasn’t been received just as an update .

**Comment by riwell** [comment]
Hi...
I have same problem were you able to solve the problem

**Comment by thatalbertaguy** [comment]
Nope , no one has answered

**Comment by Sophia-yu-kk** [comment]
The issue will be closed automatically when the timeout is not solved, you can join the group chat for discussion, discord address https://discord.gg/9M8cAVAp

**Comment by thatalbertaguy** [comment]
Join the chat? So my question can be forgotten/buried there . 

I don’t understand why the node address cant be looked up, ensure I haven’t received payment , then send payment and refresh the next payment due date . 

There are obviously other people with this same issue
