### ISSUE TITLE
Cannot Get node valided 

### ISSUE THREAD

**Issue by guozhen-dev** [TRON-US/go-btfs#1080]
Node id    16Uiu2HAkwe18SaXUTVRtGHLGRDgKFRqVAQGLttLgRoFJntgkwgnN. Wait for a long time but cannot be validated. I have public IP address. However, it takes forever to be validated as a node.

**Comment by Sophia-yu-kk** [comment]
How many hours do you keep in sync? It will be a little bit slower when the number of new nodes syncing across the network is high. But in general it will complete the verification operation within 10 hours.

You can check the current status of your node to see if the verification has been completed. Thank you for your feedback.

**Comment by Sophia-yu-kk** [comment]
I checked through btfsscan browser and your node has been verified and currently has a score of 2.
