### ISSUE TITLE
Uptime score goes down

### ISSUE THREAD

**Issue by TheBestBadGamer** [TRON-US/go-btfs#1081]
Uptime score drops from 76% to 75% even though I have it in operation 24/7

My ID is: 
16Uiu2HAmTpMtorC3Gs1zGomJCN7P1gj6kM6YB8jPVeTU1GDqx4jL

![Screenshot_2021-06-27-18-04-52-405_com.realvnc.viewer.android.jpg](https://user-images.githubusercontent.com/85425079/123551485-3e83ca00-d772-11eb-828c-0b79880af3ee.jpg)

**Comment by Sophia-yu-kk** [comment]
Hello, slight variations in uptimetime are normal. Individual failure of a particular heartbeat detection can happen, even when staying online.
