### ISSUE TITLE
No payout and cannot transfer out to public wallet

### ISSUE THREAD

**Issue by kenken64** [TRON-US/go-btfs#1088]
PEER ID	16Uiu2HAkyJQYaWWP3PsntbvPZRMo2UswVGTqWfEHNTYq88ZsM9na
AGENT	go-btfs v1.5.1
UI	v2.11.4

**Comment by Sophia-yu-kk** [comment]
Both of these are known issues and the engineer is currently looking at them. Thank you for your feedback

**Comment by kenken64** [comment]
I see payout now but cannot transfer to internal wallet

**Comment by Sophia-yu-kk** [comment]
What is the error message, can you show me a screenshot?

**Comment by Stevevk88** [comment]
A box pop up that says:  "Transfer confirmation       You are about to send 1111 BTT"   with a Continue button to click.  You click it, it says "Transfer Processing" for 2 to 8 seconds and then it says "transfer failed."

**Comment by Sophia-yu-kk** [comment]
The issue will be closed automatically when the timeout is not solved, you can join the group chat for discussion, discord address https://discord.gg/9M8cAVAp
