### ISSUE TITLE
Stuck on Validation!

### ISSUE THREAD

**Issue by Babayahga** [TRON-US/go-btfs#1089]
I got this same issue stuck on Validation, peer ID: 16Uiu2HAmF1skSDMvx23Z6hRf1vsFFhLQentFD3K9o1rdmDUxEosH

![Capture](https://user-images.githubusercontent.com/86980065/124537901-9acc9680-ddcf-11eb-9fdf-00bb34f93dcf.PNG)

**Comment by Sophia-yu-kk** [comment]
When there are more new nodes, the synchronization speed will be slower. Is your node currently synchronized?

**Comment by Babayahga** [comment]
The WEBUI confirms the connection with BTFS, but the HOSTUI still struck on validation for two days.
![Capture1](https://user-images.githubusercontent.com/86980065/124627028-0f392100-de34-11eb-9812-bd0bd3ef2a01.PNG)

**Comment by Sophia-yu-kk** [comment]
You can try refreshing the page.

**Comment by Babayahga** [comment]
It worked 👍
