### ISSUE TITLE
No contracts!

### ISSUE THREAD

**Issue by Babayahga** [TRON-US/go-btfs#1090]
What is the parameters and time period for a new node to get it's first contract?

**Comment by rgouzal** [comment]
Same here, this is becoming a joke!

**Comment by Vikvek** [comment]
Waiting for validation now about 10hours and nothing

**Comment by rgouzal** [comment]
@Vikvek I think that people is driving through chia that's why no support on bittorrent they need at least to get support of community

**Comment by Sophia-yu-kk** [comment]
Theoretically, nodes with 8 points or more have a chance to get the contract. Currently, there are many super miners and the pressure of competition is relatively high across the network. Specific network information can be found on the browser at https://scan.btfs.io/#/
