### ISSUE TITLE
Cannot create wallet

### ISSUE THREAD

**Issue by DutchCloud4Work** [TRON-US/go-btfs#1093]
Node is validated, when I try to create the wallet nothing happens..
When I input an strong password, the continue button does not work..

Any help or should I just reset and start over?

**Comment by DutchCloud4Work** [comment]
This is the error the webbrowser gives me;

POSThttp://192.168.178.143:5001/api/v1/wallet/keys?
[HTTP/1.1 404 Not Found 1ms]

Uncaught (in promise) SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 5 of the JSON data
    walletKeys wallet.js:115
    promise callback*walletKeys wallet.js:114
    L vuex.esm.js:847
    dispatch vuex.esm.js:512
    dispatch vuex.esm.js:402
    getKeys App.vue:483
    handlePasswordSet WalletSetup.vue:86

**Comment by Sophia-yu-kk** [comment]
> Node is validated, when I try to create the wallet nothing happens..
> When I input an strong password, the continue button does not work..
> 
> Any help or should I just reset and start over?

After the node synchronization, the host UI page accesses the local server, there are users with similar problems before, we suggest you change the browser to operate

**Comment by DutchCloud4Work** [comment]
Tried several browsers.. chrome/firefox/edge/iexplore..
none seem to work

**Comment by Sophia-yu-kk** [comment]
In this case, it is recommended that you reinstall once, it may be a problem with the installed client version, to install the latest version

**Comment by DutchCloud4Work** [comment]
Got it to work;; what I needed to do;
Change binding API to 0.0.0.0
and..;
https://docs.btfs.io/docs/access-wallet-remotely
