### ISSUE TITLE
Missing Payment 

### ISSUE THREAD

**Issue by thatalbertaguy** [TRON-US/go-btfs#1097]
Hi ,

I have been running a node since February and have not received a payment as stated on my page for March 12 for 902 btt

here is my node is

16Uiu2HAmGQg7xKM6GhRqEACGJuWFfC46FsyijBc6kigUc8Y1hM9j

Reference issue #1079

https://github.com/TRON-US/go-btfs/issues/1079

My previous post was closed due to timeout with no resolve but I don’t think that’s a good enough reason . We have provided a service hosting our hard drive space for payment we should be paid .

**Comment by Sophia-yu-kk** [comment]
> Hi ,
> 
> I have been running a node since February and have not received a payment as stated on my page for March 12 for 902 btt
> 
> here is my node is
> 
> 16Uiu2HAmGQg7xKM6GhRqEACGJuWFfC46FsyijBc6kigUc8Y1hM9j
> 
> Reference issue #1079
> 
> #1079
> 
> My previous post was closed due to timeout with no resolve but I don’t think that’s a good enough reason . We have provided a service hosting our hard drive space for payment we should be paid .

We have sent feedback to the relevant responsible colleagues and expect to receive a reply tomorrow. We will inform you as soon as we have news. Sorry for the inconvenience.

This is a problem that needs to be solved by our cooperation team, so there will be some problems with the speed, sorry for the bad experience you brought. We will optimize the product and improve efficiency later.

**Comment by themantas1994** [comment]
![image](https://user-images.githubusercontent.com/82760904/129457173-1b691a20-b75b-43e7-aebf-6636045fa3a7.png)
im also missing payment since april 
this is my node
16Uiu2HAmJVwpEUWGbnvGPtC6Z9wTHmnHjhZZQtkmsMds4SWpEd47

**Comment by wbkys** [comment]
me too 
16Uiu2HAmUVD8vr3hfW5zeHRkfvvR8maY82YnrR7K4RT9n4P8Po6o

**Comment by AlexGGWP** [comment]
me as well!

16Uiu2HAm5T216MDXK7KuTyHYhLYtqAuyyrcrpfbt3Z1v1x2qTvkh

**Comment by torontopwc** [comment]
unfortunately I'm also suffering no payment what so ever. I'm also not receiving new contract despite my up-time and score of 10. Please looking my node! Thank you for your time.

16Uiu2HAkvkNJTmi3s8zBfcGq8AMSjh5MKgdMbxHHSmXLdsikfv8R

**Comment by akinto2006** [comment]
I too am experiencing no payment since the occurrence of "Failed to sync host stats" error in the CLI. Recently I have been getting only a fraction of what I am supposed to be receiving every week.

My node ID is 16Uiu2HAkvZ9T8SYSnradx8SbH3s15K5cWCgZLA7kMZBvG99NPFzf

**Comment by akinto2006** [comment]
I just received a payment today but for a node that has 102 contracts and 150GB space, I used to receive 3000 to 5000 BTT per week. What happened?

Node ID: 16Uiu2HAkvZ9T8SYSnradx8SbH3s15K5cWCgZLA7kMZBvG99NPFzf

**Comment by DrissiReda** [comment]
Same, no payment since july:

Node ID: 16Uiu2HAm3tZaiReoVSnuV2BYKAyLof1ketLBCzTuPy65udgvL8H4

**Comment by akinto2006** [comment]
Any update on this?

Node ID: 16Uiu2HAkvZ9T8SYSnradx8SbH3s15K5cWCgZLA7kMZBvG99NPFzf

**Comment by DrissiReda** [comment]
This has not been solved for me, still exact same issue.

**Comment by wbkys** [comment]
> This has not been solved for me, still exact same issue.

+1 me too

**Comment by torontopwc** [comment]
I still have not received any payment!!

Richard Corbyn
(416)8987237
________________________________

**Comment by stachi** [comment]
> 
> 
> > This has not been solved for me, still exact same issue.
> 
> +1 me too

+1 Still no Payment with 43 contracts since april 8 2021

**Comment by ZeroCool1974-BR** [comment]
We are doing charity for BTFS right now! 45 contracts and no payment so far...

16Uiu2HAmQUxZexD9ShqirzMEM2CjRx9LpyqPzqfXmAvkmCbW4duL

**Comment by wbkys** [comment]
It's been started for 2 months and I haven't got anything

**Comment by akinto2006** [comment]
1.5.1 was the best version but I can't use it anymore. Add to that 1.5.2 autoupdates to 1.5.3 which is the worst update. I am now not receiving any payment. Ca nwe just rollback to 1.5.1?

**Comment by chris110110** [comment]
Same here, no payment.
Date was 16.nov
Can you please check?
Id: 
16Uiu2HAmSdmJd3T8dm7JyW1bG22xbsJgHSJLJ3f4DJiMxZ6tH3dV

Thank you.

**Comment by Sophia-yu-kk** [comment]
Hello everyone, the BTFS team is currently doing its best to solve this problem, and is currently expected to finish solving the problem in early December, we apologize for the inconvenience caused to everyone.

We will also inform you again when the problem is solved and give you an expected time for now. Thank you all for your support of BTFS.

**Comment by Sophia-yu-kk** [comment]
@all

**Comment by Turtus** [comment]
@olenheim

**Comment by Sophia-yu-kk** [comment]
The proceeds of the node storage file, before September are paid out, you can check to see if the account

**Comment by akinto2006** [comment]
How about November until now?

**Comment by Sophia-yu-kk** [comment]
> How about November until now?

The remainder is continuously being distributed, as the large number of transactions requires more time.

**Comment by akinto2006** [comment]
Thanks for the update. Also, does this include times where I never got the same payment that I was to get per week? If so, mine started since October.

**Comment by Dgyosh** [comment]
hey guys I can help you ....

**Comment by ZeroCool1974-BR** [comment]
Hi, I have some BTT received In-App wallet and some directly into crypto wallet, why is that?

**Comment by DrissiReda** [comment]
> Same, no payment since july:
> 
> Node ID: 16Uiu2HAm3tZaiReoVSnuV2BYKAyLof1ketLBCzTuPy65udgvL8H4

Only got a single month payment. Is that normal?

**Comment by Sophia-yu-kk** [comment]
> Hi, I have some BTT received In-App wallet and some directly into crypto wallet, why is that?

BTFS's revenue model is partly an airdrop bonus and partly a bonus for saving the file itself.
https://docs.btfs.io/docs/summary-of-btfs-faq#1-what-is-the-revenue-model-of-btfs

**Comment by Sophia-yu-kk** [comment]
> 

May I ask, how do you see only one month's earnings?

**Comment by DrissiReda** [comment]
The amount I gained is what has been mentioned as “future potential earnings” since july. And I only got it once. 


On Tuesday, December 7, 2021, 07:18, 我是丑八怪积极又可爱 ***@***.***> wrote:






May I ask, how do you see only one month's earnings?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by akinto2006** [comment]
BTFS v2.0 is out. How about an update on our payment.

**Comment by Sophia-yu-kk** [comment]
> BTFS v2.0 is out. How about an update on our payment.

BTFS2.0 is still a test network, in the test node, not officially released.
After September on the revenue is being released.

**Comment by akinto2006** [comment]
Will there be a new client to download and setup? How about our existing contracts?

I still haven't received my November payment.

**Comment by Zymare** [comment]
I also have not received any payments.
I found it odd I had a solid 10/10 score for a good 3-4 months a year ago, only got 1 contract.
since then nothing. I even put my storage price way down for months.
i have 500GB of Space dedicated to this project and I was hoping it would make economical sense to plug my old server in and run that for TBs of storage for BTFS but no payments and 1 tiny contract Was not very convincing.
Is there a issue with the software? I would like to continue with the project I truly believe in BTT

my node is
16Uiu2HAmM4JKeiSmnFxRLchoQzCH1fzFh2dNNbLdW4ZVGCGH3AAM

**Comment by zhimipe** [comment]
The same problem. Missing Payment. 
16Uiu2HAm9Y8KhjmxnJ4mYfmmEJxQaUVtsmeaJC1kws8kVbsLWzmo
https://prnt.sc/23omn51
https://prnt.sc/23q95yi

**Comment by Sophia-yu-kk** [comment]
Hello everyone, for the three months of September-November, the miner's payment has been issued.

If the withdrawal fails, it is due to the wallet single day withdrawal limit, we suggest submitting a work order to the following address，https://forum.bittorrent.com/topic/56988-important-information-on-btt-withdrawal/

**Comment by Sophia-yu-kk** [comment]
In addition, the payment for December-January will be issued in early February.

**Comment by akinto2006** [comment]
Is the airdrop still going? I haven't received any airdrop since 1.5.2.

**Comment by ZeroCool1974-BR** [comment]
> Hello everyone, for the three months of September-November, the miner's payment has been issued.
> 
> If the withdrawal fails, it is due to the wallet single day withdrawal limit, we suggest submitting a work order to the following address，https://forum.bittorrent.com/topic/56988-important-information-on-btt-withdrawal/

I'm trying to withdraw BTT from BitTorrent Speed wallet in-app balance but it's impossible! I try many times during the day with no success,  I don't know why we just can't withdraw diretcly to another chain wallet... we earn these tokens but can't use them! That's a shame! My BTFS in-app wallet has less than 1000 BTT so I can't withdraw yet...

**Comment by xoka** [comment]
> In addition, the payment for December-January will be issued in early February.

#1218

**Comment by Zymare** [comment]
I deleted BTFS and it's contracted files.
I've moved on from BTT to a different file sharing platform.

**Comment by maksisru** [comment]
> 

Зимаре   на какую? (что за проект)

**Comment by AlexeiKaDev** [comment]
Hi. missing payment for a month.
![image](https://user-images.githubusercontent.com/45790487/156869194-d689e624-3695-4ab0-965a-eb0fce367390.png)


id 16Uiu2HAmHWX8aZC1tSNE7wGfNQFD5VVPaJE798mew1fBH4Gv47wn
walett TPeqQcK9FRQ9QwDWo9tPsCew3qu8YAMpV5

**Comment by Pedanov** [comment]
Same issue. Next payment date is still 22 March 2022.
ID: 16Uiu2HAmKRpUNRTvUKDH4ryTanTJcytmjTWvSVM5e2Qu2V7rn6bg

**Comment by Sophia-yu-kk** [comment]
> Hello everyone, for the three months of September-November, the miner's payment has been issued.
> 
> If the withdrawal fails, it is due to the wallet single day withdrawal limit, we suggest submitting a work order to the following address，https://forum.bittorrent.com/topic/56988-important-information-on-btt-withdrawal/

The rewards for BTFS 1.0 have all been distributed and can be withdrawn by everyone.
If the withdrawal fails, it is due to the wallet single day withdrawal limit, we suggest submitting a work order to the following address，https://forum.bittorrent.com/topic/56988-important-information-on-btt-withdrawal/
