### ISSUE TITLE
Response Required: failed to reprovide: failed to find any peer in table

### ISSUE THREAD

**Issue by AdineVikash** [TRON-US/go-btfs#1101]
**2021-08-13T12:03:46.468+0530	ERROR	reprovider.simple	failed to reprovide: failed to find any peer in table**

Peer identity: **16Uiu2HAkvLTniW9SyrsMbbT6UgFi2yXa1EHodsL23uYsHK1hH1sz**

Daemon startup information:
![image](https://user-images.githubusercontent.com/68943180/129327717-169961d2-c807-4d8a-b439-2d34c604b085.png)

I'm waited for more then 1 and half day still nothing had changed and also tried opening all ports but still didn't work.
![image](https://user-images.githubusercontent.com/68943180/129327877-3d0ddacf-100f-4fc1-9fe5-2bfd6acceeb0.png)

Please let me know to fix this issue.

**Comment by felixishim** [comment]
same problem here. moreover, my WebUI page is no longer accessible. instead it displays btfs resolve -r /btns/QmWJWGxKKaqZUW4xga2BCzT5FBtYDL8Cc5Q5jywd6xPt1g/: could not resolve name

**Comment by AdineVikash** [comment]
> same problem here. moreover, my WebUI page is no longer accessible. instead it displays btfs resolve -r /btns/QmWJWGxKKaqZUW4xga2BCzT5FBtYDL8Cc5Q5jywd6xPt1g/: could not resolve name

Try opening `http://127.0.0.1:5001/hostui/#/host`

**Comment by AdineVikash** [comment]
![image](https://user-images.githubusercontent.com/68943180/129484722-b7eb0dc4-9eeb-4506-adaa-f06741d42a16.png)
Host age is 0.

![image](https://user-images.githubusercontent.com/68943180/129484744-babd542c-09d8-444b-80e4-c0488683339f.png)
I'm not sure, why it's not reachable but all ports are open in my network and ufw is not even on at all in my Raspberry Pi4.

**Comment by Sophia-yu-kk** [comment]
To confirm, you can check the command `btfs swarm peers` if the return is empty, you need to update the bootstrap node, update method reference, https://github.com/TRON-US/go-btfs/issues/1099

Thank you for your feedback.
