### ISSUE TITLE
I stay in this state in more than 8 hours 

### ISSUE THREAD

**Issue by zhtut** [TRON-US/go-btfs#1102]
C:\Users\shutut>btfs daemon
Initializing daemon...
go-btfs version: 1.5.1-208e586
Repo version: 10
System version: amd64/windows
Golang version: go1.15.8
Repo location: D:\btfs_data
Peer identity: 16Uiu2HAm4hpQNkw8oAngF6JSVkN4pPprPEMsUuJrSVJwEqCjypNR
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/169.254.14.150/tcp/4001
Swarm listening on /ip4/172.20.10.14/tcp/4001
Swarm listening on /ip6/2408:8456:3001:7007:68ef:c20d:9995:9d73/tcp/4001
Swarm listening on /ip6/2408:8456:3001:7007:6cd8:43e4:d662:4d35/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/172.20.10.14/tcp/4001
Swarm announcing /ip6/2408:8456:3001:7007:6cd8:43e4:d662:4d35/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
WebUI: http://127.0.0.1:5001/webui
HostUI: http://127.0.0.1:5001/hostui
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Remote API server listening on /ip4/127.0.0.1/tcp/5101
Daemon is ready
Experimental.Analytics is overridden by Experimental.StorageHostEnabled
Storage host info will be synced at [SCORE] mode
Current host stats will be synced
Current host settings will be synced
2021-08-13T20:06:04.919+0800    [31mERROR[0m  spin    Failed to sync host stats: Failed to query stats from Hub service: HubQueryClient: Cannot query to get stats, please wait for host validation!
BTFS is up-to-date.

![image](https://user-images.githubusercontent.com/7497402/129355690-9abe5aae-7658-47d3-a03f-03cb6f2d3233.png)

**Comment by Sophia-yu-kk** [comment]
Typically, new nodes are synchronized and verified for more than 30 hours. Thank you for your feedback.
