### ISSUE TITLE
i am not getting btfs option in bittorent for setting up the node

### ISSUE THREAD

**Issue by 2674saketh** [TRON-US/go-btfs#1103]
please suggest to get btfs option
![Capture](https://user-images.githubusercontent.com/88958576/129467900-d10d326d-e75c-4fb8-96ed-8f091ba24bf7.PNG)

**Comment by Sophia-yu-kk** [comment]
Click Options>Settings>BTFS>Check Enable BTFS>OK in order. This time the BTFS node will start automatically.Thank you for your feedback

**Comment by 2674saketh** [comment]
But iam not getting the btfs option in bittorent after enabling btfs in
preferences.
I am unable to open the host webpage in the browser. It is saying that the
server cant be reached

**Comment by Sophia-yu-kk** [comment]
This happens individually, this is a problem in the integration process, it
is recommended to uninstall and try again. Google Chrome is the recommended
browser.
