### ISSUE TITLE
btfs resolve -r /btns/QmWJWGxKKaqZUW4xga2BCzT5FBtYDL8Cc5Q5jywd6xPt1g/: could not resolve name

### ISSUE THREAD

**Issue by disund** [TRON-US/go-btfs#1105]
btfs resolve -r /btns/QmWJWGxKKaqZUW4xga2BCzT5FBtYDL8Cc5Q5jywd6xPt1g/: could not resolve name

[disund@ArchatWork ~]$ btfs daemon
Initializing daemon...
go-btfs version: 1.5.1-208e586
Repo version: 10
System version: amd64/linux
Golang version: go1.15.8
Repo location: /home/disund/.btfs
Peer identity: 16Uiu2HAmQb61tHsmWvUHnh8MUuHD871i1s8ADnsRNUShReRhwbg7
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/192.168.1.10/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/192.168.1.10/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
WebUI: http://127.0.0.1:5001/webui
HostUI: http://127.0.0.1:5001/hostui
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Remote API server listening on /ip4/127.0.0.1/tcp/5101
Daemon is ready
Storage host info will be synced at [SCORE] mode
Current host stats will be synced
Current host settings will be synced
BTFS is up-to-date.

**Comment by iceman7613** [comment]
or I am in the same situation as you ... I have tried everything but nothing without support I know that I give up

**Comment by UeberDaniel** [comment]
me too :(

**Comment by Sophia-yu-kk** [comment]
> or I am in the same situation as you ... I have tried everything but nothing without support I know that I give up

https://github.com/TRON-US/go-btfs/issues/1099

**Comment by Sophia-yu-kk** [comment]
> me too :(

https://github.com/TRON-US/go-btfs/issues/1099

**Comment by Sophia-yu-kk** [comment]
This is because there is no connection to the seed node. To connect to the seed node, see #1099
