### ISSUE TITLE
help i can't solve

### ISSUE THREAD

**Issue by iceman7613** [TRON-US/go-btfs#1109]
C:\btfs>btfs daemon
Initializing daemon...
go-btfs version: 1.5.1-208e586
Repo version: 10
System version: 386/windows
Golang version: go1.15.8
Repo location: F:\
Peer identity: 16Uiu2HAkz6NCMX2nWZGWghDw1SrBfKWHWAXoN6BLT6paadN4qZRB
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
WebUI: http://127.0.0.1:5001/webui
HostUI: http://127.0.0.1:5001/hostui
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Remote API server listening on /ip4/127.0.0.1/tcp/5101
Daemon is ready
Storage host info will be synced at [SCORE] mode
Current host stats will be synced
Current host settings will be synced
2021-08-18T13:48:45.234+0200    ←[31mERROR←[0m  spin    Failed to sync host stats: Failed to query stats from Hub service: HubQueryClient: Cannot query to get stats, please wait for host validation!
BTFS is up-to-date.

**Comment by Sophia-yu-kk** [comment]
The new node is currently taking over 30 hours to sync and is still in sync

**Comment by AlexBion** [comment]
I'm waiting host validation too, but I'm online from 1 month with Host Score: 10
id: 16Uiu2HAkyNqfvcZPDeCfs52fDnhX5NL7nam1su7c9Nr8aSMpMxxm
thanks in advance
