### ISSUE TITLE
Disable autoupdate

### ISSUE THREAD

**Issue by kvasselkvasier** [TRON-US/go-btfs#1114]
Hi
It would be cool if we could disable the auto update. As for me I use systemd on Linux to make sure the daemon restarts after a failure. I use this for all my services. The problem is because of the auto update feature my nodes are in an update circle because after downloading the update it exit the daemon and systemd restarts it faster with no update. So it would be cool if you can add the disable auto feature like ipfs had it

**Comment by daniel-tron** [comment]
Per doc https://docs.btfs.io/docs/autoupdate, you can set autoupdateFlg to false.

**Comment by Yrp** [comment]
Hi, @kvasselkvasier 
Yes, you can already do that. Disabling auto update has been implemented. You can find option **DisableAutoUpdate** in the configuration file (usually in ***~/.btfs/config***), just set it to **true**.
Enjoy it.

```
"Experimental": {
    ...
    "DisableAutoUpdate": false,
    ...
  },
```

**Comment by karawitan** [comment]
When running from within a Docker, auto-update is an issue as well ...

**Comment by daniel-tron** [comment]
> When running from within a Docker, auto-update is an issue as well ...
yes, maybe need map a customized config to overwrite.
