### ISSUE TITLE
Host rating dropped due to old version

### ISSUE THREAD

**Issue by LordMerlin** [TRON-US/go-btfs#1116]
The host's rating dropped due to the old version, but after updating to the latest, the rating remains 9. And the rating parameter from the version still shows 0/10.
![image](https://user-images.githubusercontent.com/2853937/130921520-b75a7e8f-f068-428d-96bc-a004ad5b4604.png)

**Comment by Sophia-yu-kk** [comment]
Please provide us with the corresponding node ID，thanks

**Comment by LordMerlin** [comment]
All my nodes have the same ID 16Uiu2HAmDi4fxzSmfpGpiHgZKo8DYi6rGdxUHb2hQvtKvtckL8C5
Most likely due to the fact that one wallet address is tied to them.
Can there be a version error if one of my nodes has not been updated? 
Is that why everyone else got a bad rating?

**Comment by Sophia-yu-kk** [comment]
You should have three different ip's running the node, two running 1.5.1 and the other running 1.5.2

**Comment by LordMerlin** [comment]
Tell me why auto-update might not work for them? All nodes under Windows 10.

**Comment by Sophia-yu-kk** [comment]
If you encounter a long time no automatic upgrade or automatic upgrade failure, users can refer to https://docs.btfs.io/docs/btfs-demo to install, or go to the github release page https://github.com/TRON-US/go-btfs/releases to download the executable for the corresponding platform file to replace it manually.

**Comment by LordMerlin** [comment]
Thanks. Yes, I know, and on most nodes I did it by hand. It would be great to be able to make a request and see which nodes, on which addresses, which versions they have.

**Comment by Sophia-yu-kk** [comment]
No such tool is currently available, but your request will be seriously considered.

**Comment by LordMerlin** [comment]
Thank you very much! Let's wait and hope.

**Comment by Sophia-yu-kk** [comment]
Okay, thank you for your feedback, if you have any questions subsequently you can submit an issue to feedback.have a nice day~
