### ISSUE TITLE
BTFS host stuck on validation

### ISSUE THREAD

**Issue by VS-Instinct** [TRON-US/go-btfs#1117]
Hi, I think the issue from (https://github.com/TRON-US/go-btfs/issues/908)has started again because I'm having the same issue since almost 36 hours!
My host ID: 16Uiu2HAmHmJN92sPEm9Dv53yESbUeQ4dVJXHjMrkWfgxibfJo6Yj
This is what it has been looking like during that time

![image](https://user-images.githubusercontent.com/89718562/131238988-f1353c64-7f3e-4d6a-81df-87feec3ab859.png)

Please find a fix!
Thanks in advance!

**Comment by Sophia-yu-kk** [comment]
When there are more new nodes, the synchronization speed is slowed down.

If you you synchronize for more than 30 hours, we suggest you refresh your browser, thanks for the feedback, we will also upgrade our service to shorten the synchronization time.

**Comment by Nickitos30** [comment]
hello, please tell me how long to wait for upgrading your equipment and speeding up the validation process when connecting a new node.

**Comment by Nickitos30** [comment]
> 
> 
> When there are more new nodes, the synchronization speed is slowed down.
> 
> If you you synchronize for more than 30 hours, we suggest you refresh your browser, thanks for the feedback, we will also upgrade our service to shorten the synchronization time.

**Comment by Nickitos30** [comment]
> 
> 
> When there are more new nodes, the synchronization speed is slowed down.
> 
> If you you synchronize for more than 30 hours, we suggest you refresh your browser, thanks for the feedback, we will also upgrade our service to shorten the synchronization time.

hello, please tell me how long to wait for upgrading your equipment and speeding up the validation process when connecting a new node.

**Comment by AxolotlPrime** [comment]
is this still an issue? This is the message i get... let's see how long this will take^^

![Screenshot 2021-12-07 at 17-16-58 BTFS UI](https://user-images.githubusercontent.com/83839768/145066038-074f92c5-efbc-4caf-bef6-95fe937afa3d.png)
