### ISSUE TITLE
Failed to sync host stats

### ISSUE THREAD

**Issue by ami102k** [TRON-US/go-btfs#1118]
HI, I am getting the same error and even after more than 4 hours getting that same 30 minutes wait screen.
My node id is:

16Uiu2HAmTU8NussgCmaagGJg89WLPKhDPYAdYSngJGip7n7TxBUA

**Comment by Sophia-yu-kk** [comment]
Individual times due to network problems will appear, usually will automatically disappear. If a similar problem occurs you can continue to submit. This issue takes too long to open, my side first closed, looking forward to your follow-up questions feedback.
