### ISSUE TITLE
Transfer wallet transaction failed and missing amount

### ISSUE THREAD

**Issue by shadehv** [TRON-US/go-btfs#1120]
I tried to transfer from BTFS IN-APP WALLET BALANCE to BTT CRYPTO WALLET BALANCE. However it is recorded as failed.
Now the balance in BTFS IN-APP is 0 and BTT CRYPTO WALLET also empty.

![btfs transaction](https://user-images.githubusercontent.com/35190612/132168850-f2dc6f45-4162-4ea4-b87c-70e905aa6944.PNG)

![btfs balance](https://user-images.githubusercontent.com/35190612/132168874-c1cb2108-8dd6-4600-8030-06e6eccc35ed.PNG)

What can I do to get back the balance?

Thanks.

**Comment by Sophia-yu-kk** [comment]
Please provide your host ID and chain address, we'll help you see what's going on，thanks

**Comment by shadehv** [comment]
Host ID is Peer ID? If not, where can I find it?
How do I check my chain address?

**Comment by undeman** [comment]
Faced the same error
Host Node id:
16Uiu2HAkz7Bbp8Fn8sCzbNFim5QZMgayv8cGQYkCCyQ7XREDAMCx
TRON Address:
TMTkLoVYZGuxYiUyEhZG1pyFmpTBD7szhQ

**Comment by Sophia-yu-kk** [comment]
https://forum.bittorrent.com/topic/56988-important-information-on-btt-withdrawal/
Regarding the failure of everyone's extraction, a solution channel has been established. People can submit work orders by clicking this address, which is the quickest solution.
