### ISSUE TITLE
Transfer BTT to BTFS still pending

### ISSUE THREAD

**Issue by viewee-ohm** [TRON-US/go-btfs#1121]
I am operating multiple accounts

id : 16Uiu2HAm8vNatmg2zCW2xixRiRAoeHg2bgZ9nxTXL8a9peeEu2vR
tron address : TUNGqyn5MokLdPSQTbR1ZqTD8sGcjcRr9E

id : 16Uiu2HAm2ynK96mMFZBV3FPjB9KDhvSmBmEM1RCfSSw9RxABfRxo
tron address  : TMn9exNrFsYx2zB1cWdBKpnZB23WCjppJC

can you figure it out?

**Comment by Sophia-yu-kk** [comment]
https://forum.bittorrent.com/topic/56988-important-information-on-btt-withdrawal/
Regarding the failure of everyone's extraction, a solution channel has been established. People can submit work orders by clicking this address, which is the quickest solution.

**Comment by Sophia-yu-kk** [comment]
https://github.com/TRON-US/go-btfs/issues/1121

A dedicated link was created, so as not to duplicate this link of yours close it first. Thank you for your feedback
