### ISSUE TITLE
Failed to sync host stats

### ISSUE THREAD

**Issue by kizzshot** [TRON-US/go-btfs#1123]
Please help me 
i run btfs then run cmd and  ### btfs config profile apply storage-host 
After run command 

<a href="https://www.img.in.th/image/PJIYzw"><img src="https://www.img.in.th/images/310809d2c8f164561d798be6fa93ab4d.md.jpg" alt="310809d2c8f164561d798be6fa93ab4d.jpg" border="0" /></a>

how to next step

**Comment by Sophia-yu-kk** [comment]
The current new node validation is at least 30 hours, and the error report will disappear after the validation is over.
