### ISSUE TITLE
 Cannot query to get stats, please wait for host validation!

### ISSUE THREAD

**Issue by AlexGGWP** [TRON-US/go-btfs#1125]
Hi

I have been running a node for almost an year now. Skipping the well known issue of missing payments and node not being discoverable at all (not getting new contracts at all), I recently encountered a brand new error: 

2021-09-09T10:06:10.076+0300    ←[31mERROR←[0m  spin    Failed to sync host stats: Failed to query stats from Hub service: HubQueryClient: Cannot query to get stats, please wait for host validation!

Here is a screenshot:

![Screenshot 2021-09-09 151045](https://user-images.githubusercontent.com/19946697/132683607-75897b56-d789-4105-8a3c-907a40980af4.png)

But like I said my node has been running for almost an year, which means the host **MUST** be validated.  Here is the HostUI:

![Screenshot 2021-09-09 151129](https://user-images.githubusercontent.com/19946697/132683656-00f0bf0c-75a6-4867-bc63-f1c6a77e4610.png)

As you can see from the image above the host is validated. However I keep getting the error that the host is **NOT** validated. 

My node ID is: 16Uiu2HAm5T216MDXK7KuTyHYhLYtqAuyyrcrpfbt3Z1v1x2qTvkh

**Comment by Sophia-yu-kk** [comment]
Hi, seeing the validating error reported on the old node is currently a known issue and does not affect getting contracts. The developers are currently working on a fix for this issue. Thank you for your feedback.
