### ISSUE TITLE
 Failed to sync host stats: Failed to query stats from Hub service: HubQueryClient: Cannot query to get stats

### ISSUE THREAD

**Issue by CrypToots** [TRON-US/go-btfs#1126]
Failed to sync host stats: Failed to query stats from Hub service: HubQueryClient: Cannot query to get stats, please wait for host validation!
BTFS is up-to-date.

Peer identity: 16Uiu2HAmJ8bBm3o9mUz9rzVJXDn533pn6yqGuPPhUQfEzVa2LgxH

**Comment by Sophia-yu-kk** [comment]
This error does not affect the acquisition of contracts, and in the meantime the team is optimizing this issue.

**Comment by alienfunk** [comment]
> This error does not affect the acquisition of contracts, and in the meantime the team is optimizing this issue.

My UI Host remains "validating..." for ever and i get this error. What can I do?

**Comment by Sophia-yu-kk** [comment]
> > This error does not affect the acquisition of contracts, and in the meantime the team is optimizing this issue.
> 
> My UI Host remains "validating..." for ever and i get this error. What can I do?

You don't need to do anything, it's a known problem
