### ISSUE TITLE
Failed to sync hosts

### ISSUE THREAD

**Issue by sunsetdiscountsfl** [TRON-US/go-btfs#1128]
I have this error with a score of 10
2021-09-15T22:43:15.600-0500    ←[31mERROR←[0m  spin    Failed to sync hosts: Failed to query hosts from Hub service: HubQueryClient: Cannot query to get hosts!
Peer identity: 16Uiu2HAmGLYKojSjLaAHtWrDCFMFyJFpy2mQenRqe9wyFix5HSrF
Please advise
Thank You

**Comment by Sophia-yu-kk** [comment]
After checking that the node is located in the US, this error report does not affect the normal contract acquisition, meanwhile we are optimizing this error report and the issues related to the error report. Thank you for your feedback.

**Comment by akinto2006** [comment]
Same error.

Node ID: 16Uiu2HAkvZ9T8SYSnradx8SbH3s15K5cWCgZLA7kMZBvG99NPFzf

**Comment by Sophia-yu-kk** [comment]
Will optimize this issue, has put this issue into the optimization list, thanks for the feedback

**Comment by Sophia-yu-kk** [comment]
After confirming, this is some hosts recommended by hub when renter uploads files. if there is no need to upload files, you can ignore this error
