### ISSUE TITLE
ERROR spin Failed to sync host stats: Failed to query stats from Hub service: HubQueryClient: Cannot query to get stats, please wait for host validation!

### ISSUE THREAD

**Issue by alienfunk** [TRON-US/go-btfs#1133]
BTFS Node Host it is still validating after +12 hours .  Daemon output from terminal: 

`Failed to query stats from Hub service: HubQueryClient: Cannot query to get stats, please wait for host validation!`

My Node ID: 16Uiu2HAmUSNFjDZEtYofpPE9eufwo6UDTcR7xsYRqdXqZM5vzCam

**Comment by lk2684753** [comment]
I came across the same problem
My Node ID: 16Uiu2HAm6ir6GnG5fj1UMhguqGUxcL2jLzguhz6QyXTehzv7pMDh

**Comment by Sophia-yu-kk** [comment]
Currently, BTFS has more new nodes, which will be slower to synchronize. Normally, the synchronization time is about 30 hours. the description on the UI page we will optimize. Thank you for your feedback.

https://docs.btfs.io/docs/13-how-long-does-it-take-to-synchronize-the-new-node
