### ISSUE TITLE
BTFS has been validating my node for 6 hours, when it says it will only take 180 minutes

### ISSUE THREAD

**Issue by samyjones1** [TRON-US/go-btfs#1135]

**Comment by Sophia-yu-kk** [comment]
https://docs.btfs.io/docs/13-how-long-does-it-take-to-synchronize-the-new-node

Currently, BTFS has more new nodes, which will be slower to synchronize. Normally, the synchronization time is about 30 hours. the description on the UI page we will optimize. Thank you for your feedback.
