### ISSUE TITLE
Unable to obtain contract

### ISSUE THREAD

**Issue by lk2684753** [TRON-US/go-btfs#1137]
My node: 16Uiu2HAm6ir6GnG5fj1UMhguqGUxcL2jLzguhz6QyXTehzv7pMDh
has been running for many days without interruption, but now there is no contract.
The BTFS node has been unable to get the host status log
![image](https://user-images.githubusercontent.com/42611777/134303695-4146417e-4877-4d26-8621-b5f50c7e335e.png)

![image](https://user-images.githubusercontent.com/42611777/134303745-1df2cb3b-c75f-4e4e-aa1f-914f41861474.png)

**Comment by aladyn93** [comment]
same problem here....any updates?

**Comment by Sophia-yu-kk** [comment]
https://docs.btfs.io/docs/summary-of-btfs-faq#7-my-btfs-node-has-been-online-and-has-a-score-of-10-but-no-contract-my-btfs-node-had-a-contract-before-and-now-it-doesnt-have-one

You can refer to the FAQ, the old node error please wait for validation is a known problem, does not affect the contract acquisition, the team optimization.
