### ISSUE TITLE
Could not import wallet and reset the password

### ISSUE THREAD

**Issue by jaffsys** [TRON-US/go-btfs#1140]
Even after resetting password using recovery phrase. System says incorrect password. Tried restarting btfs/Bittorrent. 
HostID 16Uiu2HAkyJnCka1jq4GFQQoM8NtHyqfn9RiqFvbzqCjiS9fQju5d

**Comment by Sophia-yu-kk** [comment]
BTFS is a decentralized network that does not store user passwords. We have no way to help you retrieve your password at this time
