### ISSUE TITLE
thanks for the fix. its now working correct. you are the best

### ISSUE THREAD

**Issue by jertoy** [TRON-US/go-btfs#1146]
thanks for the fix. its now working correct. you are the best

_Originally posted by @kvasselkvasier in https://github.com/TRON-US/go-btfs/issues/536#issuecomment-641718499_

**Comment by jertoy** [comment]
I have the same issue, Im running my node for almost a month now but still get the same error ,

Failed to sync hosts: Failed to query hosts from Hub service: HubQueryClient: Cannot query to get hosts!

my host id : 16Uiu2HAmTSB23b69yVsynpd7c6gSwqXSrcm6kr94XxqdWxV7JDTF

please help!

**Comment by bitspent** [comment]
Hi there, I am still having the same issue since 3 days of trials
