### ISSUE TITLE
BTFS WebUI returns : could not resolve name

### ISSUE THREAD

**Issue by benjaminbih** [TRON-US/go-btfs#1157]
Hi, 

my btfs node is installed on Windows. Since two days the WebUI returns the error:
`btfs resolve -r /btns/QmWJWGxKKaqZUW4xga2BCzT5FBtYDL8Cc5Q5jywd6xPt1g/: could not resolve name`

 I have allready updated the Bootstrap part in the config file as described here #1099 , but the error is still there.

**Comment by lucasgb98** [comment]
hello Yrp and benjaminbih I don't understand what I should do, refresh the page? give F5 in the browser? I don't think so, could you give me the step by step?
