### ISSUE TITLE
No sync / version score 0/10 after update to 1.5.3

### ISSUE THREAD

**Issue by ZeroCool1974-BR** [TRON-US/go-btfs#1165]
C:\Games\btfs>btfs.exe daemon
Initializing daemon...
go-btfs version: 1.5.3-17053fc
Repo version: 10
System version: amd64/windows
Golang version: go1.15.15
Repo location: D:\btfs
Peer identity: 16Uiu2HAmQUxZexD9ShqirzMEM2CjRx9LpyqPzqfXmAvkmCbW4duL
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/192.168.100.39/tcp/4001
Swarm listening on /ip6/2804:f24:c10d:6b00:4902:edb8:7192:801d/tcp/4001
Swarm listening on /ip6/2804:f24:c10d:6b00:e4fb:97a4:f96d:bf40/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/192.168.100.39/tcp/4001
Swarm announcing /ip6/2804:f24:c10d:6b00:4902:edb8:7192:801d/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
WebUI: http://127.0.0.1:5001/webui
HostUI: http://127.0.0.1:5001/hostui
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Remote API server listening on /ip4/127.0.0.1/tcp/5101
Daemon is ready
Current host stats will be synced
Current host settings will be synced

Stay like this forever.

**Comment by thatalbertaguy** [comment]
Same here node 

16Uiu2HAmGQg7xKM6GhRqEACGJuWFfC46FsyijBc6kigUc8Y1hM9j

**Comment by thatalbertaguy** [comment]
My node has updated to have a score of 10 now

**Comment by Yrp** [comment]
It's normal, don't worry.
