### ISSUE TITLE
The number of contracts will not increase

### ISSUE THREAD

**Issue by holychen1234** [TRON-US/go-btfs#1184]
I have many  nodes,But I found that when the number of contracts per node reaches 20, no new contracts will be obtained.Is this normal？

**Comment by holychen1234** [comment]
Is the contract related to storage space？

**Comment by Sophia-yu-kk** [comment]
> Is the contract related to storage space？

is not relevant, as long as it meets the minimum criteria for BTFS nodes.

**Comment by Sophia-yu-kk** [comment]
https://docs.btfs.io/docs/summary-of-btfs-faq#7-my-btfs-node-has-been-online-and-has-a-score-of-10-but-no-contract-my-btfs-node-had-a-contract-before-and-now-it-doesnt-have-one

Regarding contract acquisition this is a common question and can be answered by referring to this answer. At the same time we are constantly optimizing the reward incentives of BTFS with the aim of being more decentralized and fair.
