### ISSUE TITLE
"transport is closing error" while the daemon is running

### ISSUE THREAD

**Issue by DILLUCHERY** [TRON-US/go-btfs#1186]
I am getting an error from time to time while the daemon is running. My Node got validated in a day and has been running since for some days now, but the error shown below pops up from time to time:

**2021-11-16T00:26:01.095+0530    ←[31mERROR←[0m  spin    failed to send data to status server: StatusClient: rpc error: code = Unavailable desc = transport is closing**

**btfs version 1.5.3** is the version of btfs I am using and my Host node ID is:
**16Uiu2HAmKbxpQunTv8pghXCdnJgCyZt4D1ieJyFieBqTdQPzyqhs**

**Comment by Sophia-yu-kk** [comment]
After confirmation, this error report stays just fine. This error report will not affect the acquisition of the contract, and the user does not need to perform additional operations, just ignore this error report.
