### ISSUE TITLE
What's the problem?

### ISSUE THREAD

**Issue by holychen1234** [TRON-US/go-btfs#1195]
Nov 22 10:00:41 localhost btfs: 2021-11-22T10:00:41.595+0800#011#033[31mERROR#033[0m#011spin#011failed to send data to status server: StatusClient: rpc error: code = Unavailable desc = the connection is draining
Nov 22 13:13:15 localhost btfs: 2021-11-22T13:13:15.193+0800#011#033[31mERROR#033[0m#011spin#011failed to send data to status server: StatusClient: rpc error: code = Unavailable desc = the connection is draining
Nov 22 18:15:42 localhost btfs: 2021-11-22T18:15:42.772+0800#011#033[31mERROR#033[0m#011spin#011failed to send data to status server: StatusClient: rpc error: code = Unavailable desc = the connection is draining
Nov 22 19:45:37 localhost btfs: 2021-11-22T19:45:37.533+0800#011#033[31mERROR#033[0m#011spin#011failed to send data to status server: StatusClient: rpc error: code = Unavailable desc = the connection is draining
Nov 22 19:45:42 localhost btfs: 2021-11-22T19:45:42.656+0800#011#033[31mERROR#033[0m#011spin#011failed to send data to status server: StatusClient: rpc error: code = Unavailable desc = the connection is draining
Nov 22 19:45:43 localhost btfs: 2021-11-22T19:45:43.727+0800#011#033[31mERROR#033[0m#011spin#011failed to send data to status server: StatusClient: rpc error: code = Unavailable desc = the connection is draining
Nov 22 20:45:39 localhost btfs: 2021-11-22T20:45:39.697+0800#011#033[31mERROR#033[0m#011spin#011failed to send data to status server: StatusClient: rpc error: code = Unavailable desc = the connection is draining
Nov 22 20:45:42 localhost btfs: 2021-11-22T20:45:42.591+0800#011#033[31mERROR#033[0m#011spin#011failed to send data to status server: StatusClient: rpc error: code = Unavailable desc = the connection is draining
Nov 22 20:45:43 localhost btfs: 2021-11-22T20:45:43.066+0800#011#033[31mERROR#033[0m#011spin#011failed to send data to status server: StatusClient: rpc error: code = Unavailable desc = the connection is draining
Nov 22 20:45:45 localhost btfs: 2021-11-22T20:45:45.255+0800#011#033[31mERROR#033[0m#011spin#011failed to send data to status server: StatusClient: rpc error: code = Unavailable desc = the connection is draining
Nov 22 20:45:48 localhost btfs: 2021-11-22T20:45:48.333+0800#011#033[31mERROR#033[0m#011spin#011failed to send data to status server: StatusClient: rpc error: code = Unavailable desc = the connection is draining
Nov 22 20:51:44 localhost btfs: 2021-11-22T20:51:44.176+0800#011#033[31mERROR#033[0m#011spin#011failed to send data to status server: StatusClient: rpc error: code = Unavailable desc = the connection is draining
Nov 22 21:30:40 localhost btfs: 2021-11-22T21:30:40.584+0800#011#033[31mERROR#033[0m#011spin#011failed to send data to status server: StatusClient: rpc error: code = Unavailable desc = the connection is draining
Nov 22 21:30:42 localhost btfs: 2021-11-22T21:30:42.818+0800#011#033[31mERROR#033[0m#011spin#011failed to send data to status server: StatusClient: rpc error: code = Unavailable desc = the connection is draining
Nov 22 21:30:43 localhost btfs: 2021-11-22T21:30:43.537+0800#011#033[31mERROR#033[0m#011spin#011failed to send data to status server: StatusClient: rpc error: code = Unavailable desc = the connection is draining
Nov 22 21:30:44 localhost btfs: 2021-11-22T21:30:44.863+0800#011#033[31mERROR#033[0m#011spin#011failed to send data to status server: StatusClient: rpc error: code = Unavailable desc = the connection is draining
Nov 22 21:30:47 localhost btfs: 2021-11-22T21:30:47.509+0800#011#033[31mERROR#033[0m#011spin#011failed to send data to status server: StatusClient: rpc error: code = Unavailable desc = the connection is draining
Nov 22 21:45:37 localhost btfs: 2021-11-22T21:45:37.398+0800#011#033[31mERROR#033[0m#011spin#011failed to send data to status server: StatusClient: rpc error: code = Unavailable desc = the connection is draining
Nov 22 21:45:46 localhost btfs: 2021-11-22T21:45:46.173+0800#011#033[31mERROR#033[0m#011spin#011failed to send data to status server: StatusClient: rpc error: code = Unavailable desc = the connection is draining

**Comment by Sophia-yu-kk** [comment]
> Nov 22 10:00:41 localhost btfs: 2021-11-22T10:00:41.595+0800#11#033[31mERROR#33[0m#011spin#011failed to send data to status server: StatusClient: rpc error: code = Unavailable desc = the connection is draining

After confirming, this error report does not affect contract acquisition, just ignore it. In subsequent releases, we will optimize this error message.Thank you for your feedback, have a nice day~
