### ISSUE TITLE
Update correctly

### ISSUE THREAD

**Issue by chris110110** [TRON-US/go-btfs#1201]
Can anyone tell me how to update correctly on a raspberry?
Thank you very much.

**Comment by Mejahmad** [comment]
anyone finding a problem to update?

**Comment by ZeroCool1974-BR** [comment]
> anyone finding a problem to update?

No problem, stop daemon, update, start daemon, simple as that!

**Comment by goodnamehadbeeneatbydog** [comment]
how to update for linux? stop the daemon? what  next?

**Comment by chris110110** [comment]
> > anyone finding a problem to update?
> 
> No problem, stop daemon, update, start daemon, simple as that!

Stop daemon is clear.
Start deamon is also clear.
Update is not clear, thats why i ask the question how to update on raspberry.

**Comment by Sophia-yu-kk** [comment]
Manual update method: You can download the appropriate executable from the GitHub release page and replace it manually or use the download and update script to update it manually.

**Comment by chris110110** [comment]
Where can I find the update script?
Thanks
