### ISSUE TITLE
Cannot recover BTT in Tron wallet using Mnemonic - 0 Balance.  

### ISSUE THREAD

**Issue by elurevad76** [TRON-US/go-btfs#1202]
Hi, I'd love some help.
I bought some BTT years ago and transferred it to a mobile wallet and since lost the phone. I tried restoring the wallet using my mnemonic using tronlink extension but it shows no BTT balance.
Tronscan shows the BTT on the chain here: TNxLBiWtCc4bABFL5sJgW1SrREaZCxqPSG
Any ideas how I might access my funds?

Thanks,
Dave

**Comment by Sophia-yu-kk** [comment]
Hello, thank you for your feedback!

As this is dedicated to issues related to BTFS decentralized network, your question can be asked in the tronlink group.

The link to tronlink on the discord is: https://discord.gg/YTbGTGs8
