### ISSUE TITLE
Unable to auto update

### ISSUE THREAD

**Issue by AlexGGWP** [TRON-US/go-btfs#1203]
After update 1.5.3 my btfs client is unable to auto update. I tried restarting and nothing works. Also I noticed that the message: **BTFS is up to date** is missing. How can I fix this?

![Screenshot 2021-11-29 170432](https://user-images.githubusercontent.com/19946697/143892169-64c6c23f-4b4d-4c4b-8839-5b7a0e8ad102.png)

**Comment by chris110110** [comment]
Where can I find the update script for Linux?

**Comment by Sophia-yu-kk** [comment]
Hello, 

from v1.6.0 version all upgrades need to be updated manually and automatic updates have been cancelled.

Please refer to the link for upgrade details:[]( https://docs.btfs.io/docs/v160)

You can download the appropriate executable from the GitHub release page and replace it manually.

have a nice day~
