### ISSUE TITLE
Monitoring of the host status via CLI

### ISSUE THREAD

**Issue by zvictorp** [TRON-US/go-btfs#1207]
Dear community

Please, give me a hint on how to monitor the process of syncing via Linux CLI.

Thank you in advance.

**Comment by Sophia-yu-kk** [comment]
Hello, there is no official monitoring program like this available at this time. The new node will currently be synchronized in about 30 hours. This is the current situation for your reference.Thank you for your question, we will continue to optimize the program.

**Comment by zvictorp** [comment]
How may I check if the host is being validated via CLI?
Unfortunately, I cannot connect to its web UI.

Thank you.
