### ISSUE TITLE
Same peer ID for different nodes.

### ISSUE THREAD

**Issue by zvictorp** [TRON-US/go-btfs#1210]
Dear community is this a normal situation when I imported the same wallet to three nodes all of them started showing the same peer ID?

Thank you.

**Comment by Sophia-yu-kk** [comment]
Hello, this is a normal situation. The same wallet address corresponds to the same node ID.

But we don't recommend you to do so. https://docs.btfs.io/docs/summary-of-btfs-faq#5-if-running-multiple-btfs-nodes-then-each-node-needs-to-generate-a-new- wallet

**Comment by Sophia-yu-kk** [comment]
https://docs.btfs.io/docs/summary-of-btfs-faq#5-if-running-multiple-btfs-nodes-then-each-node-needs-to-generate-a-new-wallet
