### ISSUE TITLE
btfs-v2.0 install problem

### ISSUE THREAD

**Issue by holychen1234** [TRON-US/go-btfs#1211]
i try to install btfs-v2.0，but it seems to stuck in the step of "make install".What's the problem?

**Comment by holychen1234** [comment]
[root@iZj6c0u0zcojlroll9t444Z go-btfs]# make install
go: launchpad.net/gocheck@v0.0.0-20140225173054-000000000087: bzr branch --use-existing-dir -- https://launchpad.net/~niemeyer/gocheck/trunk . in /root/go/pkg/mod/cache/vcs/f46ce2ae80d31f9b0a29099baa203e3b6d269dace4e5357a2cf74bd109e13339: exec: "bzr": executable file not found in $PATH
go: launchpad.net/gocheck@v0.0.0-20140225173054-000000000087: bzr branch --use-existing-dir -- https://launchpad.net/~niemeyer/gocheck/trunk . in /root/go/pkg/mod/cache/vcs/f46ce2ae80d31f9b0a29099baa203e3b6d269dace4e5357a2cf74bd109e13339: exec: "bzr": executable file not found in $PATH
go version go1.15.14 linux/amd64
bin/check_go_version 1.15
plugin/loader/preload.sh > plugin/loader/preload.go
go fmt plugin/loader/preload.go >/dev/null
go: launchpad.net/gocheck@v0.0.0-20140225173054-000000000087: bzr branch --use-existing-dir -- https://launchpad.net/~niemeyer/gocheck/trunk . in /root/go/pkg/mod/cache/vcs/f46ce2ae80d31f9b0a29099baa203e3b6d269dace4e5357a2cf74bd109e13339: exec: "bzr": executable file not found in $PATH
make: *** [plugin/loader/preload.go] Error 1
[root@iZj6c0u0zcojlroll9t444Z go-btfs]#

**Comment by Sophia-yu-kk** [comment]
https://github.com/bittorrent/go-btfs/issues

Hello, BTFS2.0 issues in this address feedback , the relevant personnel will help you.I closed this issue first.
