### ISSUE TITLE
Then configure cross-origin(CORS) is not persistent | Bug?

### ISSUE THREAD

**Issue by JeanCarloEM** [TRON-US/go-btfs#1213]
Then configure cross-origin(CORS) is not persistent in docker, making the mandatory step "restart", revert to the original settings. What am I not seeing? Is this a mistake?

Using the docker image, built exactly as instructed in the article, it is apparently impossible to access the UI.

System: Truenas Scale RC 2

**Comment by Sophia-yu-kk** [comment]
` .btfs`directory mapping to the host's directory
