### ISSUE TITLE
Stuck on validating

### ISSUE THREAD

**Issue by hpcavalcante** [TRON-US/go-btfs#1215]
I saw that I already had the same fixed errors here but none helped me, I'm having the following error when I start the daemon: 

> Error: serveHTTPApi: manet.Listen(/ip4/127.0.0.1/tcp/5001) failed: listen tcp4 127.0. 0.1:5001: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

And then it gets stuck in the host validation screen, I've waited for hours and hours, I've tried to redo everything step by step, but the error remains
![WindowsTerminal_A60cF70RI7](https://user-images.githubusercontent.com/97175725/148423166-1bfe374b-b8b2-44bb-9557-2a6be1b489ef.png)
![msedge_0IMWvgMne7](https://user-images.githubusercontent.com/97175725/148423175-f4e69713-9adb-40da-b218-9823dfcd7c3f.png)

**Comment by Sophia-yu-kk** [comment]
It looks like you started two processes and the ports are conflicting. You can check that.

Also the synchronization verification time is at least 30 hours, which is one of the current verification times.
