### ISSUE TITLE
BTFS Syncing too long

### ISSUE THREAD

**Issue by dor4ymond** [TRON-US/go-btfs#1219]
Hi, can you please help me out here.

I've beeng running the btfs for more than a day and it looks like it'b been going around with no update. 

Web UI - status says it's online
Host UI - validating...

Peer ID: 16Uiu2HAmL9uCnGwEkiFDCkbGWA8rAQdS5NTGTuz8FQLTkFYuydp9

**Comment by Sophia-yu-kk** [comment]
https://docs.btfs.io/docs/summary-of-btfs-faq#13-how-long-does-it-take-to-synchronize-the-new-node

Current synchronization time for new nodes is at least 30 hours.thanks for your support.

**Comment by dor4ymond** [comment]
Got it. Thank you. I'll monitor it again.

**Comment by dor4ymond** [comment]
@Sophia-yu-kk I'm still getting the same syncing page. Can you please revisit the Peer ID?
