### ISSUE TITLE
Unauthorized transaction

### ISSUE THREAD

**Issue by zvictorp** [TRON-US/go-btfs#1224]
Dear support 

My TRON wallet address is TUoqh9dPze1fiG9BHWoX6tCeU3PbeSpdiu
I noticed that all my BTTOLD tokens 2022-01-26 18:07:24 GMT+4 were transferred to some address without my permission.

Is that something related to the transition to the new BTT? Or I was hacked and robbed?

Thank you.

**Comment by Sophia-yu-kk** [comment]
Hi, the transfer of funds on TRON can only be done via private key.
