### ISSUE TITLE
Failed to sync host stats

### ISSUE THREAD

**Issue by Festim98** [TRON-US/go-btfs#1225]
Hi, can someone help me with this issue?
![Capturre](https://user-images.githubusercontent.com/98594995/151551945-3f981298-9d6a-4291-bc96-245693b411a0.PNG)
?

**Comment by Sophia-yu-kk** [comment]
In this case the port is already occupied, and my guess is that you already have a btfs running

**Comment by Festim98** [comment]
Yeah, I checked the ports via cmd and I saw that the port was already occupied. What I have done is that I used taskkill to cmd to stop the occupied port. Thanks a lot :D
