### ISSUE TITLE
What Is This ?

### ISSUE THREAD

**Issue by drunkrytnow** [TRON-US/go-btfs#1226]
Microsoft Windows [Version 10.0.19044.1466]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Kakashi>btfs.exe daemon
Initializing daemon...
go-btfs version: 1.5.3-17053fc
Repo version: 10
System version: amd64/windows
Golang version: go1.15.15
Repo location: E:\.btfs
Peer identity: 16Uiu2HAmNupVURsQqhur2w29KF7SrfndqbunuMA9jfpepCJUaDut
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/169.254.178.226/tcp/4001
Swarm listening on /ip4/169.254.190.74/tcp/4001
Swarm listening on /ip4/192.168.29.228/tcp/4001
Swarm listening on /ip6/2405:201:7000:5007:5c67:f269:c8b1:76ba/tcp/4001
Swarm listening on /ip6/2405:201:7000:5007:a466:9751:75be:f014/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/192.168.29.228/tcp/4001
Swarm announcing /ip4/49.36.187.36/tcp/4001
Swarm announcing /ip6/2405:201:7000:5007:a466:9751:75be:f014/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
WebUI: http://127.0.0.1:5001/webui
HostUI: http://127.0.0.1:5001/hostui
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Remote API server listening on /ip4/127.0.0.1/tcp/5101
Daemon is ready
Current host stats will be synced
Current host settings will be synced
**2022-01-29T12:19:47.220+0530    ←[31mERROR←[0m  spin    Failed to sync host stats: Failed to query stats from Hub service: HubQueryClient: rpc error: code = DeadlineExceeded desc = context deadline exceeded**

**Comment by Sophia-yu-kk** [comment]
Hi, this error does not affect the contract acquisition and usually disappears automatically after a few hours. You can ignore this error.
