### ISSUE TITLE
rasp4 4GB error on init

### ISSUE THREAD

**Issue by AlterX76** [TRON-US/go-btfs#1227]
./btfs init
panic: qtls.ClientHelloInfo doesn't match

goroutine 1 [running]:
github.com/marten-seemann/qtls-go1-15.init.0()
	/home/pi/go/pkg/mod/github.com/marten-seemann/qtls-go1-15@v0.1.1/unsafe.go:20 +0x168

go-1.7.x (but it does not really matter)

How to fix it?

**Comment by AlterX76** [comment]
go version go1.15 linux/amd64
bin/check_go_version 1.15
plugin/loader/preload.sh > plugin/loader/preload.go
go fmt plugin/loader/preload.go >/dev/null
go install "-asmflags=all='-trimpath='" "-gcflags=all='-trimpath='" -ldflags="-X "github.com/bittorrent/go-btfs".CurrentCommit=2970ddfd8" ./cmd/btfs
# internal/abi
/usr/local/go/src/internal/abi/abi_generic.go:5:3: //go:build is not allowed in the standard library
# math
/usr/local/go/src/math/dim_asm.go:5:3: //go:build is not allowed in the standard library
/usr/local/go/src/math/exp2_noasm.go:5:3: //go:build is not allowed in the standard library
/usr/local/go/src/math/exp_amd64.go:5:3: //go:build is not allowed in the standard library
/usr/local/go/src/math/exp_asm.go:11:5: useFMA redeclared in this block
	previous declaration at /usr/local/go/src/math/exp_amd64.go:12:5
/usr/local/go/src/math/floor_asm.go:5:3: //go:build is not allowed in the standard library
/usr/local/go/src/math/hypot_asm.go:5:3: //go:build is not allowed in the standard library
/usr/local/go/src/math/log_asm.go:5:3: //go:build is not allowed in the standard library
/usr/local/go/src/math/modf_noasm.go:5:3: //go:build is not allowed in the standard library
/usr/local/go/src/math/sqrt_asm.go:5:3: //go:build is not allowed in the standard library
/usr/local/go/src/math/stubs.go:5:3: //go:build is not allowed in the standard library
/usr/local/go/src/math/stubs.go:5:3: too many errors

**Comment by sunbenxin** [comment]
You can try like this:
1. try use go1.15.x
2. git clone https://github.com/bittorrent/go-btfs in some dir
3. make build
