### ISSUE TITLE
Future Earnings 0

### ISSUE THREAD

**Issue by benjaminbih** [TRON-US/go-btfs#1228]
Hi,

i have a BTFS Host running on Windows, i get 16 contracts until January 2022 and in February i get 2 new contracts. 
So there are 18 contracts.
But HOSTUI says, Future potential earnings 0 BTT
Next payment date Nov 02, 2021
Score is 10
Current version 1.6.0 
Peer-ID    16Uiu2HAmTP3Rbyekb15Rtg2DzqHe7qqNg3fXAvDGJRoR8ncRZbMf

What is wrong ?

Thank you

Benjaminbih

**Comment by Sophia-yu-kk** [comment]
After 2.0 official network release the storage revenue will be released to miners in one go, the display on hostui can be ignored.
Thank you for your support.
