### ISSUE TITLE
Btfs 2.1.0 100 Btt Gas Problem 

### ISSUE THREAD

**Issue by TheBestBadGamer** [TRON-US/go-btfs#1229]
even though i have enough btt, the node still demands money from me.  What could be the reason?

Please help me

ID: 16Uiu2HAmTpMtorC3Gs1zGomJCN7P1gj6kM6YB8jPVeTU1GDqx4jL

**Comment by TheBestBadGamer** [comment]
ID: 16Uiu2HAmTpMtorC3Gs1zGomJCN7P1gj6kM6YB8jPVeTU1GDqx4jL

**Comment by rgouzal** [comment]
@TheBestBadGamer will you able to get it working? I have the same issue.

**Comment by TheBestBadGamer** [comment]
yes fixed it. Write your BTTC address and I will transfer you 100BTTC

**Comment by TheBestBadGamer** [comment]
> @TheBestBadGamer will you able to get it working? I have the same issue.

Yes fixed it. Write your BTTC address and I will transfer you 100BTTC

**Comment by TheBestBadGamer** [comment]
> @TheBestBadGamer will you able to get it working? I have the same issue.

@rgouzal Yes fixed it.  You must have an external wallet and transfer through it.  If you want, write your BTTC address and I'll transfer you 100BTTC.

**Comment by rgouzal** [comment]
> > @TheBestBadGamer will you able to get it working? I have the same issue.
> 
> @rgouzal Yes fixed it.  You must have an external wallet and transfer through it.  If you want, write your BTTC address and I'll transfer you 100BTTC.

@TheBestBadGamer Did you transfer through bridge?

That's what I did I had external wallet and transferred through bridge the only thing annoying is gas fees it required me 12 trx for transferring From Tron network to BTTC network!

**Comment by TheBestBadGamer** [comment]
> > > @TheBestBadGamer will you able to get it working? I have the same issue.
> > 
> > @rgouzal Yes fixed it.  You must have an external wallet and transfer through it.  If you want, write your BTTC address and I'll transfer you 100BTTC.
> 
> @TheBestBadGamer Did you transfer through bridge?


@rgouzal I use MetaMask and Tronlink Pro App together to bridge from Tron network to BTTC network. And only then did I transfer the 100BTTC via MetaMask.

**Comment by TheBestBadGamer** [comment]
@rgouzal if you want i can transfer them i have enough of them. just enter your bttc address from the node

**Comment by rgouzal** [comment]
> @rgouzal if you want i can transfer them i have enough of them. just enter your bttc address from the node

@TheBestBadGamer sure thank you appreciate it. My bttc address:

0xAD4E8bd23536BD07F366E5986c705db5295F9ea0

**Comment by TheBestBadGamer** [comment]
@rgouzal finished

let me know if it worked

**Comment by rgouzal** [comment]
> @rgouzal finished

@TheBestBadGamer really thank you for helping but it's still stuck not triggered yet I think this is a bug cause in my case I already had a vault contract created but it needs redeployment after upgrading.

![20220628_154129.jpg](https://user-images.githubusercontent.com/13728193/176208602-9bfd11cf-653c-4250-a3f2-a70414bdccda.jpg)

I will link your issue to my issue I already created an issue explaining the problem.

**Comment by TheBestBadGamer** [comment]
@rgouzal Yes, I had this problem too, I solved it with this tutorial

https://docs.btfs.io/docs/tutorials-for-upgrading-to-v212

**Comment by rgouzal** [comment]
> @rgouzal Yes, I had this problem too, I solved it with this tutorial
> 
> https://docs.btfs.io/docs/tutorials-for-upgrading-to-v212

@TheBestBadGamer I did followed exactly what the tutorial says. What step you did that you had it solved?

I am thinking to create a new btfs configuration by `btfs init` to avoid all the headache.

**Comment by TheBestBadGamer** [comment]
@rgouzal Enter this command.  I recall that this command worked

btfs config storage-host-enable true

https://github.com/bittorrent/go-btfs/releases/tag/btfs-v2.1.2

**Comment by TheBestBadGamer** [comment]
> > @rgouzal Yes, I had this problem too, I solved it with this tutorial
> > 
> > https://docs.btfs.io/docs/tutorials-for-upgrading-to-v212
> 
> @TheBestBadGamer I did followed exactly what the tutorial says. What step you did that you had it solved?
> 
> I am thinking to create a new btfs configuration by `btfs init` to avoid all the headache.

I had solved it with the tutorial, it worked but not 100%. i lost half of my contracts. where i was not satisfied then i just reinstalled it again. And finally just had to start over.
