### ISSUE TITLE
BTFS not triggering to continue even if suggested BTT is sent to TRX or BTTC address!

### ISSUE THREAD

**Issue by rgouzal** [TRON-US/go-btfs#1231]
I tried to follow exactly what it is being said on the documentation page and yet still having issue, I used to get the dashboard and see it when there was the problem of a payment which was not paid for my consumed hard drive storage and now I am facing another problem which was  not at first getting the dashboard running. I followed the steps said on the documentation:

```
Start the Daemon
Start the BTFS Daemon
$ ./btfs daemon --chain-id <chainid>

Specify the chain for btfs to run by --
chainid, the chainid of the main network is 199, and the start command becomes: btfs daemon --chain-id 199 

Run the Daemon
When starting the BTFS daemon for the first time, the system will create a node account and at the same time print a string of messages: cannot continue until there is sufficient (100 Suggested) BTT (for Gas) available on. After seeing such a message, it is necessary to recharge the node account with BTT through an external account, and the system suggests a minimum of 100 BTT, which is used as gas to deploy a node vault contract by the node account.

BTT token application address: https://doc.bt.io/v1/doc/network.html#mainnet-chainid-0xc9-decimal-199

After the recharge, the BTFS node will create the vault contract

```

Then I sent 100 BTT  from Tron Link wallet and nothing! I thought it was sent to the wrong address but no when I checked  TRmZzjGr6PVwv4aauoEiXRFVVTgSWPHVD9 on tron link I can see 100 BTT there.

Initializing daemon...
go-btfs version: 2.1.0-56bba50
Repo version: 10
System version: amd64/windows
Golang version: go1.15.15
Repo location: C:\Users\Alcacer\.btfs
Peer identity: 16Uiu2HAm8WRKvX9WAv4MPXRNVBQLaqfGgCNgG94957SCBmKpWnzU
the address of Bttc format is:  0xAD4E8bd23536BD07F366E5986c705db5295F9ea0
the address of Tron format is:  TRmZzjGr6PVwv4aauoEiXRFVVTgSWPHVD9
cannot continue until there is sufficient (100 Suggested) BTT (for Gas) available on 0xad4e8bd23536bd07f366e5986c705db5295f9ea0
cannot continue until there is sufficient (100 Suggested) BTT (for Gas) available on 0xad4e8bd23536bd07f366e5986c705db5295f9ea0
cannot continue until there is sufficient (100 Suggested) BTT (for Gas) available on 0xad4e8bd23536bd07f366e5986c705db5295f9ea0
cannot continue until there is sufficient (100 Suggested) BTT (for Gas) available on 0xad4e8bd23536bd07f366e5986c705db5295f9ea0
cannot continue until there is sufficient (100 Suggested) BTT (for Gas) available on 0xad4e8bd23536bd07f366e5986c705db5295f9ea0
cannot continue until there is sufficient (100 Suggested) BTT (for Gas) available on 0xad4e8bd23536bd07f366e5986c705db5295f9ea0
cannot continue until there is sufficient (100 Suggested) BTT (for Gas) available on 0xad4e8bd23536bd07f366e5986c705db5295f9ea0
cannot continue until there is sufficient (100 Suggested) BTT (for Gas) available on 0xad4e8bd23536bd07f366e5986c705db5295f9ea0

**Comment by Sophia-yu-kk** [comment]
I noticed a detail, you are transferring from tronlink wallet, in fact, after the upgrade V2.1.0 official network is using BTT on BTTC chain for top-up, this point needs to be noted.
https://docs.btfs.io/docs/how-to-get-bttwbtt

**Comment by rgouzal** [comment]
@Sophia-yu-kk why this is not noted on the documentation then?So 100 BTT is gone not retrievable again? And for sending BTT to BTTC can I use the BTTC bridge indicated below link?
https://bttc.zendesk.com/hc/en-us/articles/4408439332761-Deposit-Assets-from-TRON-to-BTTC

Is is possible  to  activate throught BTT received from faucet then switching to mainnet or 100 BTT should be sent from real BTT from BTTC mainnet?

**Comment by rgouzal** [comment]
I have sent many times to bttc address 
And not able to get dashboard triggered to navigate to main dashboard. I even tried version 2.1.3, 2.1.2, 2.0 and still not able to get it working. The bttc address: 0xAD4E8bd23536BD07F366E5986c705db5295F9ea0
