### ISSUE TITLE
Btfs unavailable desc = transport is closing

### ISSUE THREAD

**Issue by compadreamigo** [TRON-US/go-btfs#1232]
Hey I have been running a node for over a month and always get the same errors but this time a little more errors have started showing up.
Host ui works fine. 
Daemon is ready
Current host stats will be synced 
Current host settings will be synced
31merror 0m spin failed to sync host stats: failed to query stats from hub service: context deadline exceeded
31merror 0 m spun Failed to sync host settings : hubqueryclient: rpc error: code = deadlineexceeded desc= context deadline exceeded 
31merror 0m spin failed to sync host contracts: GuardClient: rpc error: code = unavailable desc= transport is closing.. 

Over a month i used to get first two errors. Now there are two more. Please help
Peer identity 16Uiu2HAkyVEWBoGwX81tUhuG3gKFUryhvFkx641HmDeyjt6HQ5dS

**Comment by Sophia-yu-kk** [comment]
Usually the network is unstable. It is recommended to check the network situation.
