### ISSUE TITLE
simple/reprovide.go:108 failed to reprovide: no known addresses for self, cannot put provider

### ISSUE THREAD

**Issue by felixishim** [TRON-US/go-btfs#1233]
My node has this error reprovider.simple       simple/reprovide.go:108 failed to reprovide: no known addresses for self, cannot put provider
Also i upgraded from to v2.1 and was not able to withdrawn the BTT from v1

**Comment by Sophia-yu-kk** [comment]
It is confirmed that this is a network or NAT error report. We suggest you to check the network
