### ISSUE TITLE
HOst Age decreased to 5 points

### ISSUE THREAD

**Issue by juchambo** [TRON-US/go-btfs#1235]
I have 2 nodes, one from july 2020 and another from january 2021. In the past few days both of them have decreased host age to 5 points. I think this is a bug or something cause nodes can´t get younger....

![image](https://user-images.githubusercontent.com/39893857/158170230-f2e4c0b8-5db0-4cf0-afb8-f8b07bfccafc.png)

**Comment by chris110110** [comment]
Same here.
What causes this issue?

**Comment by Sophia-yu-kk** [comment]
https://github.com/bittorrent/go-btfs/issues

For questions related to BTFS v2.0, we suggest you ask at the new repository.
