### ISSUE TITLE
Looks like your node is not connected

### ISSUE THREAD

**Issue by matiasnowo** [TRON-US/go-btfs#1236]
why i am getting this?

![imagen](https://user-images.githubusercontent.com/19611956/159332243-a6c2e298-f093-43fc-933c-734b6d247def.png)

**Comment by matiasnowo** [comment]
0 errors in log 

![imagen](https://user-images.githubusercontent.com/19611956/159332292-13a8c3c5-3dba-458d-885c-b1715cc04fc9.png)

**Comment by matiasnowo** [comment]
Initializing daemon...
go-btfs version: 2.1.1-f76f7e0
Repo version: 10
System version: amd64/windows
Golang version: go1.15.15
Repo location: Z:/BTFS
Peer identity: 16Uiu2HAmSu8FH5ZoNhDBi8Yh9vd5d5QZ3nAxCPM3kofe7V9r6CCS
the address of Bttc format is:  0x4f308052CD392c15AAE0D63a40bc978729536B79
the address of Tron format is:  THBvV96nGk6TKgV5YYq72pVUTBSY7gmeC1
self vault: 0x0394f3acc1870a9face93bb11fbb44f372a4a318
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/169.254.172.124/tcp/4001
Swarm listening on /ip4/169.254.27.101/tcp/4001
Swarm listening on /ip4/192.168.1.192/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/192.168.1.192/tcp/4001
Swarm announcing /ip4/200.127.235.219/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
Dashboard: http://127.0.0.1:5001/dashboard
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Remote API server listening on /ip4/127.0.0.1/tcp/5101
Daemon is ready
Current host stats will be synced
Current host settings will be synced

**Comment by Sophia-yu-kk** [comment]
https://docs.btfs.io/docs/btfs20-dashboard#settings
Miners can set up the module, system configure the API port (default is http://localhost:5001/)
and click the Submit button.

**Comment by dipol0** [comment]
Have same issue.

Have PC with static IP in LAN. PC without X and other DM (headless). I portforward only one port on this PC - 4001.
When i run node dafault ./btfs daemon WebUI start on localhost only and i cant see it from another PCs from LAN.
If i run ./btfs daemon --api=/ip4/192.168.0.35/tcp/5001 - i see webUI but have something wrong: 
![Выделение_371](https://user-images.githubusercontent.com/32021806/230157222-5e4fa5ab-37af-48ab-96ae-541e6daa282b.png)
When i try submit new API URL get this:
![Выделение_373](https://user-images.githubusercontent.com/32021806/230157354-99be7383-18ff-4eae-aad4-ae8b519c218f.png)
I read it - https://docs.btfs.io/docs/btfs20-dashboard#settings
but...may be i dont understand or may be mistake...
On https://scan.btfs.io/#/node/NODE_ID - i see my node and correct balance.
