### ISSUE TITLE
No owner account

### ISSUE THREAD

**Issue by bravepiper** [TRON-US/go-btfs#1238]
Hello, when I called  `btfs wallet deposit 10000000` command, 'No owner account' error is returned, I'm not sure why it happened and how to address it, can anyone help point it out? thanks.

`
Error: calling interface [TransferAsset2] error, reasons: [calling interface [TransferAsset2] failed, reasons: [Contract validate error : No owner account!]]
`

**Comment by Sophia-yu-kk** [comment]
The BTFS repository was migrated and the new repository address is https://github.com/bittorrent/go-btfs/issues 
You can ask questions here
