### ISSUE TITLE
BTFS not navigating to main dashboard after 100 btt deposit BTFS requires deposit even if address has balance

### ISSUE THREAD

**Issue by rgouzal** [TRON-US/go-btfs#1241]
I had dashboard working on other device raspberry pie my raspberry pie got usb port damaged so I decided to switch to small desktop to run BTFS on. I moved backed BTFS files on raspberry pie to desktop running Windows 10 and upgraded BTFS. I deposit 100 BTT from Tron network to BTTC network through the bridge but still not able to get dashboard and setup screen showing!!

Note: I noticed that BTTC address has more than 100 btt and still requires to deposit even though there is enough balance to redeploy vault contract!

Update: I had some friend sent me 100 btt and still wasn't able to get it working!

**Comment by Sophia-yu-kk** [comment]
https://github.com/TRON-US/go-btfs/issues/1240
BTFS has migrated to a new address, and you are welcome to ask questions at the new address.
