### ISSUE TITLE
The add api has no limit?

### ISSUE THREAD

**Issue by samohyes** [TRON-US/go-btfs#342]
So it looks like that anyone can use the add api to the local daemon.
"http://localhost:5001/api/v0/add"

So if this api is exposed, then anyone can add the file to a machine and consume its storage. Is this a potential security problem?

**Comment by taiyangc** [comment]
There is no built-in permission control at the moment. You should keep the api port protected or restrict cors through `"Access-Control-Allow-Origin"` in your `~/.btfs/config`:

```
"Gateway": {
    "APICommands": [],
    "HTTPHeaders": {
      "Access-Control-Allow-Headers": [
        "X-Requested-With",
        "Range",
        "User-Agent"
      ],
      "Access-Control-Allow-Methods": [
        "GET"
      ],
      "Access-Control-Allow-Origin": [
        "*"
      ]
    },
    "NoFetch": false,
    "PathPrefixes": [],
    "RootRedirect": "",
    "Writable": false
},
```

**Comment by samohyes** [comment]
Looks like the api  can only be accessed locally?

> API server listening on /ip4/127.0.0.1/tcp/5001
WebUI: http://127.0.0.1:5001/webui
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Remote API server listening on /ip4/127.0.0.1/tcp/5101


I tried to access the 8080 port out of the vm and it failed...

**Comment by richlee33** [comment]
@samohyes thats correct, the api will only listen to locally by default.  if you do a `btfs config show` and view the Address, API settings it has the 127.0.0.1 by default.  the settings is a multiaddr format.  thanks.
