### ISSUE TITLE
webgui calls wrong api adress (v0 instead of v1?)

### ISSUE THREAD

**Issue by zero24x** [TRON-US/go-btfs#346]
hi,

congrats on releasing something exciting like btfs!

i installed version the version v1.0.0-beta1 using https://github.com/TRON-US/btfs-binary-releases
and notice the webgui is broken, it makes ajax calls to urls with api version0, but this fails.

probably you need to change to version 1?

url the webgui : http://127.0.0.1:5001/api/v0/stats/bw?stream-channels=true
should be probably: http://127.0.0.1:5001/api/v1/stats/bw?stream-channels=true

related to https://github.com/TRON-US/go-btfs/issues/338 maybe

**Comment by richlee33** [comment]
@zero24x thank you for the bug report.  we are tracking the broken webUI request URL internally https://tronnetwork.atlassian.net/browse/BTFS-1444.  we'll let you know when its fixed.  thanks.

**Comment by zero24x** [comment]
ok thank you and keep up the great work, btfs might be a new era coming up!
