### ISSUE TITLE
how to check rewards of a storage node?

### ISSUE THREAD

**Issue by zero24x** [TRON-US/go-btfs#347]
hi,

please describe in docs https://docs.btfs.io/docs/run-a-btfs-host  or add to webgui a way how to check the node host status, hosters want to see usually how many gb or files they store, how many coins they earned etc.

thanks

**Comment by taiyangc** [comment]
There is an upcoming release for such UI dashboard at the end of Q1 2020.

**Comment by zero24x** [comment]
ok thank you!
