### ISSUE TITLE
How to add domain binding?

### ISSUE THREAD

**Issue by qiushui777** [TRON-US/go-btfs#352]
At the end of the tutorial here

https://docs.btfs.io/docs/common-usage

It says we can add DNS TXT record. However, I am reading the source code of btfs and through some debugging, I was able to figure out the actual "btns" domain resolving is at here

https://github.com/TRON-US/go-btfs/blob/master/namesys/dns.go#L116

So it calls lookupTXT(name).

It looks like the actual domain resolving is here. And I can't really find this  lookupTXT func in the repo. So where is this func? And how to add a domain binding?

Thanks.

**Comment by richlee33** [comment]
@qiushui777 the domain binding mentioned in:
https://docs.btfs.io/docs/common-usage 
uses the btfs gateway server found at:
https://gateway.btfssoter.io/
it involves editing the dns entry from the website hosting service that you own/administer.
