### ISSUE TITLE
The logic of guard, hub

### ISSUE THREAD

**Issue by samohyes** [TRON-US/go-btfs#354]
So according to the help doc, the btfs network contains the guard, hub providing different service. However, currently, in the github I can only find the go-btfs related codes. There is no tutorial of setting up a guard or hub. I do find some requests to the hub or guard here

https://github.com/TRON-US/go-btfs-common/tree/master/protos

But I'd love to check the source codes of guard and hub as well as setting up these local services. Because it seems that this is the new features that you add to the ipfs. 

Thanks.

**Comment by tycm4109** [comment]
Those components act as a layer for facilitating renter/host exchange. Currently, there is no plan to open source them. Please join other developers in our discord channel at https://discord.gg/PQWfzWS. Thx.
