### ISSUE TITLE
Hostui uses hardcoded domain (localhost)

### ISSUE THREAD

**Issue by Jbekker** [TRON-US/go-btfs#452]
I have a dev server running currently on commit 36dce32606ae3ad766b231869ccf390f0a08115a to be exact. It's running on a remote server without a desktop interface to I'm just connecting through the web interface. Even though I'm connecting to the new hostui (/hostui/#/) through a DNS name, it's trying to connect to the API on localhost. Which of course will never work with this setup.
![image](https://user-images.githubusercontent.com/930668/79329708-8ffebb00-7f18-11ea-9798-fe6b630d61b6.png)

Should the API endpoint be configurable?

**Comment by rudya** [comment]
Hostui should indeed be pointing to the API by following the current hostname and not localhost. I'll go ahead and update the code and remove the hardcoded domain which should resolve your issue. In the mean time, you could set up an ssh tunnel to get it working.

**Comment by Jbekker** [comment]
The workaround works for me.

**Comment by Jbekker** [comment]
Fixed with 646080171811412b1393dc002a04b9dc58ffac77
