### ISSUE TITLE
Crashes since 1.1.1 panic: runtime error: index out of range

### ISSUE THREAD

**Issue by Jbekker** [TRON-US/go-btfs#477]
Since my BTFS host was updated to 1.1.1 I'm seeing very regular crashes. In the logfiles I see the below:
> panic: runtime error: index out of range [9] with length 9
> 
> goroutine 413010 [running]:
> github.com/TRON-US/go-btfs/core/commands/storage/upload/upload.glob..func1(0xc00300b650, 0x25ec4c0, 0xc0034b8180, 0x1e96d60, 0xc00053c                                                                                                     180, 0x0, 0x0)
>         /go-btfs/core/commands/storage/upload/upload/init.go:110 +0xcf2
> github.com/TRON-US/go-btfs-cmds.(*Command).call.func1(0xc005d80420, 0x33b7d20, 0xc00300b650, 0x25ec4c0, 0xc0034b8180, 0x1e96d60, 0xc00                                                                                                     053c180)
>         pkg/mod/github.com/!t!r!o!n-!u!s/go-btfs-cmds@v0.1.6/command.go:118 +0x66
> created by github.com/TRON-US/go-btfs-cmds.(*Command).call
>         pkg/mod/github.com/!t!r!o!n-!u!s/go-btfs-cmds@v0.1.6/command.go:117 +0x2bb
> panic: runtime error: index out of range [9] with length 9

I'm not 100% sure that this is related to the crash but it seems likely?

**Comment by taiyangc** [comment]
Sorry about the crash. This is caused by incompatibilities from an older renter node. We will try to provide a fix asap.

**Comment by Jbekker** [comment]
Thx, let me know if you need me to test it before release

**Comment by taiyangc** [comment]
@Jbekker Could you temporarily try building from master to see if it gets rid of the crashes? Thanks. Release will come in the next few days if nothing else.

**Comment by Jbekker** [comment]
@taiyangc, Ok, will do that now.. I will let you know when how it runs.

**Comment by Jbekker** [comment]
My host have been running again for 9 hours without any issues, before it would crash within 10 minutes so looks good to me.

**Comment by Jbekker** [comment]
Fixed in v1.1.2 -> 86bbcbc4e046a77505b613b47f2350aba279162d
