### ISSUE TITLE
Reverse Proxy

### ISSUE THREAD

**Issue by bondibox** [TRON-US/go-btfs#483]
I run btfs on a remote host, and I'm unable to connect to hostui / webui with my local computer. After a few hours tinkering with NGINX I realized the futility of setting up my own reverse proxy, and even if it was successful it would open a security vulnerability unless paired with a firewall restriction. I would like to submit a feature request to add a built in proxy, password protected access to hostui / webui. Perhaps the password could be displayed when launching btfs daemon.

**Comment by taiyangc** [comment]
If you have a normal btfs daemon running on `domain.com`, then you should be able to access it from `domain.com:5001/hostui`. What's the error you get when trying to connect? Can you make sure `domain.com:5001` is accessible?

**Comment by bondibox** [comment]
I do not have DNS configured for this server. On that host I am able to wget http://127.0.0.1:5001/webui but I get "connection refused" when accessing via public IP. From my local computer I also get connection refused.
I have also noticed that I must run btfs as root if I want to connect to http://127.0.0.1:5001 from a different user than the one who launched btfs.

**Comment by taiyangc** [comment]
Yeah you need to make sure your public ip and/or dns address is reachable on the 5001 port.

**Comment by bondibox** [comment]
There is nothing prohibiting outside connections on port 5001. I terminated btfs daemon and launched a "Hello World" node.js app on port 5001 and was able to connect with a broswer.

**Comment by taiyangc** [comment]
ok, will look into it.

**Comment by taiyangc** [comment]
can you try setting a cors rule allowing access on that public ip like

`btfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '["http://pubip:5001"]'`

Then restart daemon

**Comment by bondibox** [comment]
OK Now we're cooking with gas.
Your suggestion got me halfway there. After editing the config file to this
`"API": "/ip4/public.ip/tcp/5001",`
it works
oddly, it wasn't the "RemoteAPI" config parameter.
I'll be able to work with this to make it secure, but perhaps some people would need built in security - like a login password that is shown at daemon launch
