### ISSUE TITLE
BTFS Sync issue

### ISSUE THREAD

**Issue by leek21** [TRON-US/go-btfs#495]
Followed these instructions:
https://youtu.be/mVoo17ig-PU

BTFS never finishes syncing.  Tried on 3 different computers.

"Syncing...
Currently syncing with the BTFS network, please refresh this page after 30-45 minutes"

Runs for hours and never syncs.

**Comment by taiyangc** [comment]
Hello, please run `btfs config profile apply storage-host` and restart your daemon. Then after 30 mins you should see the normal Host UI.

**Comment by leek21** [comment]
I'm not very familiar with github and programming.

Can you explain how I should:

'run btfs config profile apply storage-host'

Do I need to download a file from github and run it command prompt ?
Where is the file located?

Sorry my knowledge is limited.

Thanks.

**Comment by leek21** [comment]
Never mind, I understand, just ran it in cmd prompt and will retry syncing.

Thanks.

**Comment by leek21** [comment]
It worked, thanks for your help!
