### ISSUE TITLE
ERROR spin: Failed to sync host stats: 

### ISSUE THREAD

**Issue by leek21** [TRON-US/go-btfs#498]
When I run BTFS.exe Daemon I get the following error:
ERROR spin: Failed to sync host stats: Failed to query stats rom Hub service: hits 0 hosts.go:66

Below is all the lines from Command Prompt:

F:\BTFS>btfs.exe daemon
Initializing daemon...
go-btfs version: 1.1.2-
Repo version: 7
System version: 386/windows
Golang version: go1.14.2
Swarm listening on /ip4/10.11.0.45/tcp/4001
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/130.15.144.44/tcp/4001
Swarm listening on /ip4/169.254.237.229/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/10.11.0.45/tcp/4001
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/130.15.144.44/tcp/4001
Swarm announcing /ip4/169.254.237.229/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
WebUI: http://127.0.0.1:5001/webui
HostUI: http://127.0.0.1:5001/hostui
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Remote API server listening on /ip4/127.0.0.1/tcp/5101
Daemon is ready
Storage host info will be synced at [SCORE] mode
Current host stats will be synced
Current host settings will be synced
10:50:11.010 ERROR       spin: Failed to sync host stats: Failed to query stats from Hub service: hits 0 hosts.go:66
BTFS is up-to-date.

**Comment by taiyangc** [comment]
This is normal for a new host. After 30-45 mins it should no longer show this message.

**Comment by leek21** [comment]
Thanks again.

Do you have any idea of the volume of data I should expect ?  After about
24 hours I have zero data.

**Comment by alvintronnetwork** [comment]
Since BTFS is a decentralized network, we do not have an estimation of the amount of data a Host will allocation. In the meantime, We are also bringing in partners who are taking advantage of the BTFS network to store large scale data, which will further benefit all the Hosts in the network.
