### ISSUE TITLE
Swarm listener accept error: unexpected flag swarm_listen.go:83

### ISSUE THREAD

**Issue by leek21** [TRON-US/go-btfs#502]
I have had BTFS up and running for about 4 days, but no data yet.
Just noticed this error after checking cmd prompt after 2 days:

13:26:39.330 ERROR     swarm2: swarm listener accept error: unexpected flag swarm_listen.go:83
BTFS is up-to-date.

**Comment by taiyangc** [comment]
This is a normal error that can be ignored.
