### ISSUE TITLE
Deposit BTT to BTFS

### ISSUE THREAD

**Issue by Kyliux** [TRON-US/go-btfs#528]
Hi all,

I followed exactly the tutorial : https://docs.btfs.io/docs/deposit-btt-to-btfs

Putted 10k btt on it
Output : {"BtfsWalletBalance":0,"BttWalletBalance":10000000000}
Then following command : 
`btfs wallet deposit 10000000000`
`btfs wallet balance`
Output : {"BtfsWalletBalance":0,"BttWalletBalance":0}

Here is the [transaction hash](https://tronscan.io/#/transaction/47d961eec2930208e17933d0a0d6a8c18720a510a8c7567e7c2fef4267a2c0ac)

No clue why my BTT went from [my BTFS address](https://tronscan.io/#/address/TT8j8Pn7seYSG4QRUmtZjtMQKo5xTyHwMU) to [there](https://tronscan.io/#/address/TA1EHWb1PymZ1qpBNfNj9uTaxd18ubrC7a) 

Extra infos : I was running the daemon in the same time in another tab and tried to upload a folder of 100Mo for 35 days at the standard price. The command to get the statuts  `btfs storage upload <session-id> status | jq '.Status'`  brought errors of insufficient balance

Please sent the same amount back to me and correct this issue.

Thanks in advance,

**Comment by alvintronnetwork** [comment]
@Kyliux could you retry `btfs wallet balance`? And show me the balance?

**Comment by Kyliux** [comment]
`btfs wallet balance` 
{"BtfsWalletBalance":0,"BttWalletBalance":0}

as i explained before, it was 
{"BtfsWalletBalance":0,"BttWalletBalance":10000000000}
then 
`btfs wallet deposit 10000000000` 
then 
`btfs wallet balance` 
{"BtfsWalletBalance":0,"BttWalletBalance":0}
the money went [there](https://tronscan.io/#/address/TA1EHWb1PymZ1qpBNfNj9uTaxd18ubrC7a)

**Comment by alvintronnetwork** [comment]
@Kyliux we had an API communicate issue at that exact moment, that was why the transaction did not go through. We have refunded the 10,000 BTT to your crypto wallet address.
