### ISSUE TITLE
 Failed to sync host stats

### ISSUE THREAD

**Issue by kvasselkvasier** [TRON-US/go-btfs#536]
if setup a new btfs node as host but i get the following error:

19:23:10.901 ERROR       spin: Failed to sync host stats: Failed to query stats from Hub service: Cannot query to get stats! hosts.go:66

and i didnt see anything on the hostui. 
on the webui ist everything ok and it shows me what i am hosting right now

**Comment by taiyangc** [comment]
It's a safe error to ignore on starting up a new node. The message will go away after 30-45 mins of being online. If you get persistent errors even after being online for more than 45 mins please let us know your node id, thanks.

**Comment by kvasselkvasier** [comment]
still get the error.
the id is: 16Uiu2HAmLLr13CPqvxYjGYG1bKkLgkhKZRpBpvcSkrrbUzkbZYQA

**Comment by kvasselkvasier** [comment]
Yes and the config file tells me host is enabled. It also automatcly took 150gb on max storage in the config.

**Comment by taiyangc** [comment]
I see. Could you post a screenshot of what host ui shows for you?

**Comment by leek21** [comment]
I am getting the same error.  I had BTFS running for over a week with no issues, but it crashed and when I restarted I get the same error:
08:26:55.492 ERROR       spin: Failed to sync host stats: Failed to query stats from Hub service: Cannot query to get stats! hosts.go:66

And I have had it up and running for over 20 hours again, the same error message keeps repeating.

Hostui page is also blank, except the left hand menu.

![image](https://user-images.githubusercontent.com/42178789/84147483-7915aa00-aa2b-11ea-99db-fa195265034e.png)

**Comment by taiyangc** [comment]
@kvasselkvasier @leek21 Please try again. We deployed a fix. Your host should be correctly syncing within 30 mins.

**Comment by kvasselkvasier** [comment]
thanks for the fix. its now working correct. you are the best

**Comment by Ragnaryu** [comment]
i am having the same issue, and dunno how to solve it. did several times the procedure but nothing.. what should i do? my ID :     16Uiu2HAmMyiKXxC3uRQgCzFhqq7fcaz27apjNrogvnZQrTYSxZ1B

**Comment by Stevevk88** [comment]
Same  thing:

	16Uiu2HAmDBgypPtT8wzZK8iD2C8MctuLsFUvdoKbeKsvW1MrJgNG

**Comment by maitiest** [comment]
HI, I am getting the same error and even after more than 45 minutes getting that same 30-45 minutes wait screen.
My node id is: 16Uiu2HAm7JxJsDrdHsMBsx9QqviK54Gqcgd8hZnau2M2b8ypssQd

**Comment by Stevevk88** [comment]
Yea, I just noticed this:

2020-07-12T03:04:49.244-0400    ←[31mERROR←[0m  storage/contracts       storage/contracts.go:432        get payout status batch error:rpc error: code = Internal desc = runtime error: invalid memory address or nil pointer dereference
2020-07-12T03:04:49.246-0400    ←[31mERROR←[0m  spin    spin/hosts.go:66        Failed to sync HOST contracts: rpc error: code = Internal desc = runtime error: invalid memory address or nil pointer dereference

            (  ID	      16Uiu2HAmDBgypPtT8wzZK8iD2C8MctuLsFUvdoKbeKsvW1MrJgNG  )

**Comment by maitiest** [comment]
> HI, I am getting the same error and even after more than 45 minutes getting that same 30-45 minutes wait screen.
> My node id is:
> `16Uiu2HAm7JxJsDrdHsMBsx9QqviK54Gqcgd8hZnau2M2b8ypssQd`

It started working after couple of hours.

It would be great to show some kind of progress indicator during this initial sync

**Comment by Jenos-Idanian** [comment]
@taiyangc,

Is this still an ongoing issue that needs per node fix? Or has the system been updated so this no longer should occur?

I have received it once, almost three hours ago and I am wondering if there is something actionable on my side that I should be doing.

Thanks and Much appreciation for what you guys are doing!!!

**Comment by taiyangc** [comment]
It should no longer be an issue. Normally you should see 3-4 warnings as a new host and it will go away.

**Comment by Jenos-Idanian** [comment]
Phew! Thanks man, really appreciate you getting back to me so quickly. Have a good weekend!

**Comment by Jenos-Idanian** [comment]
@taiyangc I have one more question for you?

![Screenshot_20200726-180252.png](https://user-images.githubusercontent.com/68447731/88490548-623efe80-cf6a-11ea-9683-46bde3b526db.png)

I have gotten this several days in a row.

What does this error imply?

Is there something I can do to fix it?

**Comment by yuzhongrong** [comment]
i have the same probele .


Initializing daemon...
go-btfs version: 1.3.5-20c165c
Repo version: 9
System version: amd64/darwin
Golang version: go1.14.6
Repo location: /Users/yuzhongrong/.btfs
Node ID: 16Uiu2HAm1PfdBYocF3kPUmkkBEuThbjdoaV5e8kP4zZ2Ksvk1haj
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/192.168.2.105/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/192.168.2.105/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
WebUI: http://127.0.0.1:5001/webui
HostUI: http://127.0.0.1:5001/hostui
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Remote API server listening on /ip4/127.0.0.1/tcp/5101
Daemon is ready
Storage host info will be synced at [SCORE] mode
Current host stats will be synced
Current host settings will be synced

2020-08-18T09:53:00.409+0800    ERROR   spin    spin/hosts.go:63        Failed to sync host stats: Failed to query stats

from Hub service: Cannot query to get stats!
BTFS is up-to-date.

**Comment by MrBotType** [comment]
Facing the same issue. 
" Failed to sync host stats: Failed to query stats from Hub service: HubQueryClient: Cannot query to get stats!"
My host node id is -  
16Uiu2HAkzyZXQHB3UghpYh1Yu2JFSEmZt3aHnk7HDXuEf5mPEMCd 

Please check.

**Comment by felixishim** [comment]
still facing this issue, please help my node id is 16Uiu2HAm8Cy2oEB4w5Dq6KQYdnS9qsnJ5eYozbZLX18nktYf6QLx

**Comment by jooe289** [comment]
I'm also having the same issue :

Current host settings will be synced
2020-09-17T13:35:37.232+0300    [31mERROR[0m  spin    spin/hosts.go:63        Failed to sync host stats: Failed to query stats from Hub service: HubQueryClient: Cannot query to get stats!

my id is : 16Uiu2HAmAnrywErdigQbDieYCgmouTJhpgh7mRgLiRJJSNWxj4gL

**Comment by Donnie11** [comment]
Same issue here. I've switched to host mode and run for a couple of days but I get the same shell error and UI is stuck on validating.

ID: 16Uiu2HAmDKoToVDkz89SuJ6kjcbUMTeDZHF9Jbc5nh5YVaeSuQj1

**Comment by latentlust214** [comment]
same issue please fix: 

ID: Node ID: 16Uiu2HAmRPRKtS59gqnBk5QrZemyhFF3cn1KRhofMc4Y56WHF62w

**Comment by hudyk-taras** [comment]
same issue please fix:
16Uiu2HAmJp6JkHuHku7qjWVuPMUd2S5GZvyyrspBVW5YwFvUevLu

**Comment by Khudyk** [comment]
same issue please fix:
16Uiu2HAmLFwvyjMS21hHWd1GbQmtLkYqLUnZT1agPEWE4GP9yshp

**Comment by shades443** [comment]
Hi, I am facing the same issue.
Please help fix.
Node ID: 16Uiu2HAm3zMMEifCUNo5s6yRZeY4biKyLgDwUoW9uksb49cavHBb

**Comment by cagrieren** [comment]
Hi, i am facing the same issue too. I'm waiting your help.
Node ID: 16Uiu2HAmSL4XBsXd4MLCpJaWc2tAqMRzhznLyTP6X5FGKpWNL1s3

![image](https://user-images.githubusercontent.com/50526082/103270427-f1908800-49c8-11eb-8436-1424a17304c9.png)

**Comment by helloeyesimple** [comment]
I don't understand why this issue has been closed despite so many people having the same problem
My node id: 16Uiu2HAmGt36jQmDhGYboBhhpxUpziMsx7YLhRgeNSKRFobEiv15

**Comment by Thomolew** [comment]
I'm having the exact same problem. I would love some help!

My node ID: 16Uiu2HAmHvbexTsHTVjicKtPS7KRRJjNQqXwBpmyP5A1qGKLMoZN

**Comment by gubao0129** [comment]
Hi, I am facing the same issue.
Please help fix.
Node ID: 16Uiu2HAmDJLz7MizkgSfhuYBfBpata6mwToXZw1NTs5uLyxDLDpJ

**Comment by boysie3** [comment]
same issue here, getting error
 
Failed to sync hosts: Failed to query hosts from Hub service: HubQueryClient: Cannot query to get hosts!

node id: 16Uiu2HAm1c5zhyX6V7JobgWG1drLydJAPFaDJKXbH5Qo1JXD2bqh

**Comment by rpotter6298** [comment]
Same issue, waited overnight, still posting, stuck in "validating" on dashboard. Please help.
Node ID: 16Uiu2HAmBmLGzRQqESkb1H9qwj8Lo5Sp7eQ7kvUhxgoVoLQ2Xv6x
Thanks!

**Comment by whitedesignd** [comment]
same issue here, getting error

Failed to sync hosts: Failed to query hosts from Hub service: HubQueryClient: Cannot query to get hosts!

node id: 	16Uiu2HAmJHBxnHTy9urGJUyGQnyqhpqm4GExeCAUFmmF9G9wrGTS

**Comment by sepivip** [comment]
The same issue, waited for 48h, still posting, stuck in "validating" on the dashboard. Please help.
Node ID: 16Uiu2HAmPYEy9u1jNUEyGB5ezpzUciyvoYHnxd8EDfMVy7Ewo6YD
Thanks!

**Comment by gubao0129** [comment]
same issue here, getting error

ERROR	spin	Failed to sync host stats: Failed to query stats from Hub service: HubQueryClient: Cannot query to get stats, please wait for host validation!

PEER ID: 16Uiu2HAm3YT31R9KqnYZBLVep9p3wXkUEgavjtCw2DuNBnst2cCA

Thank you!

**Comment by VictorBac** [comment]
Hi,

I have the same issue. I've been waiting all day but still got the error:
ERROR	spin	Failed to sync host stats: Failed to query stats from Hub service: HubQueryClient: Cannot query to get stats, please wait for host validation!

When I go to /webui, I see that I am connected to ~900 peers. But on /hostui I am still Waiting!

Peer identity: 16Uiu2HAmEvc11QTpD1iy97HrUUi8TZ1ZqDKSeRD2JLKGu5uCGA1e

**Comment by rooie1971** [comment]
Nodeid: 16Uiu2HAmPZaoLN3E9ohD4wzABDTx8owBTpFgZAUc8GpBpK3iTuhM

Been waiting for 24 hpours now, same error and hostui is still on validatng host
Golang version: go1.15.6
Swarm listening on /ip4/37.97.141.180/tcp/4001

**Comment by k4sP3rsky** [comment]
Hey Team,

same probleme: 16Uiu2HAm7nat5KwtMRDZDqqPhaY9MUQ8BLZUEsEPiGBA4pFQYHuo

Thank you

**Comment by algimantaszz** [comment]
PEER ID	16Uiu2HAmRFD5rGsTyXzgUBZCHUKhdLMFeCmjtTmQMvfeQpzRAi9B
Been waiting for 68 hours now, hostui is still on validatng host

**Comment by kodefutureal** [comment]
PEER ID: 16Uiu2HAkzxWP29FGyA4rphFRwhQsXYvjWhiiGrn3RkRrWWqj5vut

More than 24h and still stuck on Validating.

**Comment by AndreaDesogus** [comment]
PEER ID: 16Uiu2HAm7bemCyaqo3d3mAthMzQYFS3ww7pLy4fsAkMDUcHE3d1e

Can someone who solves the problem help us?
Thanks!

**Comment by rpblccmmndo38** [comment]
PEER ID: 16Uiu2HAmPDeK1mmTo2A3h5RHxTbbkHa6rs4MzuVpwfwzgTCCFvnz

Stuck with this error for 4 hours, please help.

**Comment by rpblccmmndo38** [comment]
I successfully validated, then started validating again. can we get some kind of fix action?

**Comment by kenken64** [comment]
Peer id : 16Uiu2HAmHFd3Sw3N1UfBGxtUto7EAK1Cy8oqUPKnafVC3KAaouQY

**Comment by growdelan** [comment]
Im stuck with this error too 5h

"PeerID": "16Uiu2HAmEjRPuTyEDSW6EsSnnb3gBGFw6E6Ki67Zc4r7FTJPrWxa"

**Comment by tty666** [comment]
Same issue here already more than 4h waiting for validation ...

Peer id : 16Uiu2HAkv5RRApaFM2M5JnfFuQUh7MoejY5zEkHGtmhwri7WNSpo

**Comment by EdwardSnowmen** [comment]
Same issue for me.

Peer ID: 16Uiu2HAkxABK3ndx1wfUKueNxtMTAYZUpJhrZKT2sLHpzq7KvuHr

**Comment by cofeein** [comment]
Same issue

Peer id :  16Uiu2HAm6QNhhC8qSXYGX3hStoZ2zgpVkd3XSS19A98cN5ajQHKW

**Comment by cofeein** [comment]
helo @taiyangc 

Same issue for me

Peer id : 16Uiu2HAm6QNhhC8qSXYGX3hStoZ2zgpVkd3XSS19A98cN5ajQHKW

**Comment by rohitfarmer** [comment]
I am facing the same issue. 

Peer identity: 16Uiu2HAmMvFVAsVubuNvzprmug1o38iCf5qLiBaxYPuBKWK7ojjj

**Comment by SijoonPark** [comment]
I am facing the same issue.

My peer identify : 16Uiu2HAmScEo8XCcTsrGgBCypo2APggJMmDZDRk3h6d7hx141H8Y

**Comment by stevenstc** [comment]
I am facing the same issue.

My peer identify : 16Uiu2HAmSham4uvxShiAbaK3qe7JhEnkD9ZcdctEns4DFJfLsqfC

**Comment by moeasaleh** [comment]
I am facing the same issue
Peer Identity: 16Uiu2HAm64ZvFe3Y13iGdGfi2VpGBwWx7dxtcw5qA8DECvtQTH1X
Appreciate the help here

**Comment by june07** [comment]
Ditto.

**Comment by phongtnit** [comment]
Hello,

I had same issues, I run btfs on CentOS 8.

My Peer identity: 16Uiu2HAmS8pvT6xrjQH9jZyJS4NdTUARRGCiDMhvACmFgmRvEoWG

I changed my btfs config:
`"API": "/ip4/127.0.0.1/tcp/5001"` to `"API": "/ip4/0.0.0.0/tcp/5001"`

Please help me,

**Comment by june07** [comment]
@NathanQiu666 @laocheng-cheng @bittorrent @laipogo Anyone watching this one?

Many people have replied with the same issue...

**Comment by anudeep251** [comment]
hi same issue, struck for more than 6hrs on linux 
Node id:16Uiu2HAm5aj3Do5RWafm4Kb8WTZMAnSGbPQj3Yu3j3N7G2xzG1Lr

**Comment by KKostas86** [comment]
Hello,

I have the same issue, can't get this to work.
2021-05-17T01:59:53.077-0700    ←[31mERROR←[0m  spin    Failed to sync host stats: Failed to query stats from Hub service: HubQueryClient: Cannot query to get stats, please wait for host validation!

Peer identity: 16Uiu2HAm7GzfBbytgPRKyLrg4y8xhvS8EbxYDpkdRguYevb6b2zW

**Comment by angelzbg** [comment]
Same issues here:

2021-05-20T02:24:21.472+0300    ←[31mERROR←[0m  spin    Failed to sync host stats: Failed to query stats from Hub service: HubQueryClient: Cannot query to get stats, please wait for host validation!

Peer identity: 16Uiu2HAmPSqNwnvtBYe7Y7iV23pnczpM8jDK2DNxpPn3vUiQ7hZx

**Comment by akgamersa3** [comment]
Same Issue Plz Fix it
16Uiu2HAmAr1x1aQuRqT5KrbmijPj5QqoBCVsq1QuDiLCc77Db7xw

**Comment by gvelasquez85** [comment]
Hi, I'm sorry to write on an old topic but I'm afraid it is happening again... It's been a day and a few hours and I haven't been validated. Is there any chance to get some help from you guys? 
My node ID: 16Uiu2HAmQkEAxwm9NQ1TkF37HuabdP2yXPMsoWX8U2TaRsBoRoyF
Thanks!!

**Comment by akgamersa3** [comment]
> Hi, I'm sorry to write on an old topic but I'm afraid it is happening again... It's been a day and a few hours and I haven't been validated. Is there any chance to get some help from you guys?
> My node ID: 16Uiu2HAmQkEAxwm9NQ1TkF37HuabdP2yXPMsoWX8U2TaRsBoRoyF
> Thanks!!

On my experience, Its being running for 24 hrs but not validated. I don't know what happened may be tron community helped here or not. On the next day I restart my system and it validated.

**Comment by lavdrimb** [comment]
Same issue here too.
Node Id: 16Uiu2HAmUxVx7gN52ScAY9g7VVhtpXMs9DrXGv7XfjaVgmq5g4my

**Comment by AlexBion** [comment]
Same problem too:
Peer identity: 16Uiu2HAm8nHNFoNBE75uMCdjJXS74g7WE5SfyeHig19UxjtTJ9E8

**Comment by antoinerude** [comment]
Same issue here too.
Node Id: 16Uiu2HAmJo5W5mA7DxuPhDSThJnBxmqQFoiuYwAzjbe6jwroCAaE

**Comment by iliot-tech** [comment]
Same here: 16Uiu2HAmAuVVCFUU3pzfV4kMMwSRQEd7R9ZeaWt3iLXBzYPCXgcE

**Comment by hudyk-taras** [comment]
16Uiu2HAm6eLf1inRxf6aNnatuzVBXuWB6deakAkrhKzMxZbehVMk

**Comment by antoinerude** [comment]
What to do ? Always the same for me for 3 days !!

Node Id: 16Uiu2HAmJo5W5mA7DxuPhDSThJnBxmqQFoiuYwAzjbe6jwroCAaE

**Comment by renatovalle** [comment]
PEER ID: 16Uiu2HAmDeLdkvGEzyHHZxBXh9eDtPU9LQp2QrAjsBYsEBB8X2vz

More than 24h and still stuck on Validating.

**Comment by realabbas** [comment]
PEER ID:  16Uiu2HAm1b9AEpf5CPUbc1rkg4zFnkCSnZRiE3mzZNWYEUKVpWXS

More than 24 hrs and still suck on validating

**Comment by AlexBion** [comment]
after 3 days, I'm still waiting for...
my Peer Id: 16Uiu2HAmJyQFbL47DJNF5ERhiXeyrWZhBUZSoUb1GUqma7SuSNdY

**Comment by maksimla** [comment]
![image](https://user-images.githubusercontent.com/3274545/121223189-f1f25080-c88f-11eb-9bf0-58551464e351.png)

**Comment by AlexBion** [comment]
but someone is solving the problem? after 3 days i'm thinking of quitting now, i can't find any help, the only reference is this post, it's absurd

**Comment by GustavoPAlmeida** [comment]
What is going on? Is it taking longer than expected?

**Comment by carlosbts16** [comment]
Hi there, I could use some help

Error: serveHTTPApi: manet.Listen(/ip4/127.0.0.1/tcp/5001) failed: listen tcp4 127.0.0.1:5001: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

16Uiu2HAm2vqaP27HDBw4kUYiwZLixobMRJhSNSJrJSdfyLY4mA88

Thanks so much in advanced

**Comment by bethox14** [comment]
Peer id: 16Uiu2HAkxKKDUKssBLDGJWNTg4pXpKXHiLr7QZcN7kTSLj8ZVuCt
2 days and nothing

**Comment by emilortacu22** [comment]
Hello, I'm waiting for more than 6 hours for this turn (earlier I've waiting 3 days and nothing). I get the same message a lot of times: 
2021-06-10T00:07:23.293+0300    ←[31mERROR←[0m  spin    Failed to sync host stats: Failed to query stats from Hub service: HubQueryClient: Cannot query to get stats, please wait for host validation!

Also my host id is: 16Uiu2HAmRWFD98ZqUStCrPksTZiX1NbdM7pFYV9mDoHpKbHgs77G

Can you please help me? I want to contribute with 60 TiB, but I think I'll quit if no one will help me.

**Comment by Hishiro** [comment]
Initializing daemon...
go-btfs version: 1.5.1-208e586
Repo version: 10
System version: amd64/windows
Golang version: go1.15.8
Repo location: C:\Users\hishi\.btfs
Peer identity: 16Uiu2HAmGGMAiHUTT4jqhtQmYFfuRRzTL7TfFdF1oWiAFxK9bcDc
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/172.21.145.52/tcp/4001
Swarm listening on /ip4/192.168.1.7/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/192.168.1.7/tcp/4001
Swarm announcing /ip4/90.188.92.137/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
WebUI: http://127.0.0.1:5001/webui
HostUI: http://127.0.0.1:5001/hostui
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Remote API server listening on /ip4/127.0.0.1/tcp/5101
Daemon is ready
Storage host info will be synced at [SCORE] mode
Current host stats will be synced
Current host settings will be synced
2021-06-11T00:59:20.628+0700    ←[31mERROR←[0m  spin    Failed to sync host stats: Failed to query stats from Hub service: HubQueryClient: Cannot query to get stats, please wait for host validation!


Help me please.

**Comment by DesertThief** [comment]
same here 16Uiu2HAmEbjXAtjbM6oj4KWjaCCDzduA7ygaVDQdaFsEEZigHC88

**Comment by Cracker8x** [comment]
same here:
16Uiu2HAmRuqDJw4xTwM6VpMPRP7RqtQSSQ9fZsr6uwBFgM6hb9iK

**Comment by alkhatibahm** [comment]
Hi All 
I'm Facing the same problem, it keep giving me waiting time 
16Uiu2HAmP6JUhhT5YgHwboBZUjGJ1zEhJscEx8nwgpAaET7bbGUy

**Comment by iceman7613** [comment]
C:\btfs>btfs daemon
Initializing daemon...
go-btfs version: 1.5.1-208e586
Repo version: 10
System version: 386/windows
Golang version: go1.15.8
Repo location: F:\
Peer identity: 16Uiu2HAkz6NCMX2nWZGWghDw1SrBfKWHWAXoN6BLT6paadN4qZRB
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
WebUI: http://127.0.0.1:5001/webui
HostUI: http://127.0.0.1:5001/hostui
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Remote API server listening on /ip4/127.0.0.1/tcp/5101
Daemon is ready
Storage host info will be synced at [SCORE] mode
Current host stats will be synced
Current host settings will be synced
2021-08-18T13:48:45.234+0200    ←[31mERROR←[0m  spin    Failed to sync host stats: Failed to query stats from Hub service: HubQueryClient: Cannot query to get stats, please wait for host validation!
BTFS is up-to-date.

**Comment by thefundcrypto** [comment]
Same issue here with 16Uiu2HAmF7JURmwx9Ye25eqNQryYk3EWJMJZXXNcSHQrFDHF3kzN

**Comment by gudofabi** [comment]
I have issue too:
![Untitled](https://user-images.githubusercontent.com/36878974/130249097-312e188e-ff98-43b7-bda7-927b68d9cf23.png)


Peer identity: 16Uiu2HAmKaYyDwLQKjbVDi2oaf71e8RS4YaQgJbnnZhfjCMgXdid

**Comment by kbk704** [comment]
![제목 없음](https://user-images.githubusercontent.com/89263411/130250050-cf18b1bb-5f8c-45b9-b8bc-646820e60204.png)

i have some issue

peer id : 16Uiu2HAkugrEacRWMKo2MjSGBYu83cwBbBXf8f8EMfQB98VMhfw3

**Comment by akinto2006** [comment]
Same issue after updating to 1.5.2.

Node ID: 16Uiu2HAkvZ9T8SYSnradx8SbH3s15K5cWCgZLA7kMZBvG99NPFzf

**Comment by GREYES1981** [comment]
Hi. Same issue. 5 days and I am waiting.... 
Node ID: 16Uiu2HAmTrWwtxYsHCF2NGa7oA43WTVSXujQErWj8uz27EKPnxh4

**Comment by klangborste** [comment]
Hi, it happens also for me
Node ID: 16Uiu2HAkuSeu5qK8FsWcoLy52oNotW6wiFmtNbkaxZ3rCYHQYLPP

**Comment by bensalleh** [comment]
same here it s been 2 days and i keep getting this error please fix it 
this is my id : 16Uiu2HAm6btbSJGP597qjFWojZkDSEqnkJPBxGFZDQ6eL2LDYsFk

**Comment by doomalay** [comment]
same here it s been i keep getting this error please fix it
this is my id :  16Uiu2HAm29N67A5Yf3XsT4TGPCnroksn4Maxxoxj9gYKE6283MPR

**Comment by SawGererra** [comment]
Hey!
I got a similar problem.
The validation process has been hanging around all day.
I attach a screen of a log with a btfs error
My id 16Uiu2HAmJhEehUz6XBANv77mGXRZD4nfgoBzkFxS9Vy2tv6jWuCm

I ask you to solve the problem.
![Проблема](https://user-images.githubusercontent.com/91480270/134928065-9992cf8f-32d8-43ef-872f-49924e4bf45a.jpg)

**Comment by jertoy** [comment]
one month of running my node still get the same trouble

**Cannot query to get stats, please wait for host validation!** 

I think this program isn't is working anymore,

Peer ID  16Uiu2HAmTSB23b69yVsynpd7c6gSwqXSrcm6kr94XxqdWxV7JDTF

**Comment by Yurii-Tor** [comment]
I have this error. Check the image.
Host node ID: 16Uiu2HAmMfB4Pqbm5LyobdnWN3tNX7PedtfGgjTSvssDfaief18c

![image](https://user-images.githubusercontent.com/1465544/139540115-528c1025-4634-4bfe-ae59-4a102d513182.png)

**Comment by NewBTfs** [comment]
Hello, I'm new to the BTFS and installed it before and still not able to connect to any host. Can u help me with this please.
Peer ID: 16Uiu2HAmBAEUAMetVZmTnMLkGUxXUt96q4WavmPNXUJtm9dVMCUB

**Comment by zvictorp** [comment]
I have faced with two main troubles:
1. I installed BTFS on three different Linux servers, but I got the same peer ID for each instance.
2. Validating procedure has been going on for more than 36 hours.

The peer ID is 16Uiu2HAkvFVyKN7Hzmw29sgVU5qCzwPjyvVmMtLk7G2wb7WubShx for all three nodes.

Please, help me to handle it.
Thank you.

**Comment by Nusstoertchen** [comment]
when I run it always stays with "Current host settings will be synced"
and then it doesn't go any further

Peer identity: 16Uiu2HAmCtMgSCBzskSVQxTruXErtoeS3di7k7wfAdNeoVuhXJGn

**Comment by Nusstoertchen** [comment]
how can I make "HostsSyncEnabled": false, to true ?

 "Analytics": true,
    "DisableAutoUpdate": false,
    "FilestoreEnabled": false,
    "GraphsyncEnabled": false,
    "HostChallengeEnabled": true,
    "HostRepairEnabled": true,
    "HostsSyncEnabled": false,
    "HostsSyncFlag": true,
    "HostsSyncMode": "SCORE",
    "Libp2pStreamMounting": true,
    "P2pHttpProxy": false,
    "RemoveOnUnpin": false,
    "ShardingEnabled": false,
    "StorageClientEnabled": true,
    "StorageHostEnabled": true,
    "StrategicProviding": false,
    "UrlstoreEnabled": false

**Comment by zvictorp** [comment]
> when I run it always stays with "Current host settings will be synced" and then it doesn't go any further
> 
> Peer identity: 16Uiu2HAmCtMgSCBzskSVQxTruXErtoeS3di7k7wfAdNeoVuhXJGn

You should wait for at least 30 hours.
Then run the command 

`btfs storage stats info 
`
The output should look like 

`{"host_stats":{"online":true,"storage_used":9439635,"storage_cap":2000000000000,"storage_disk_total":11997863215104,"storage_disk_available":5243387904000,"uptime":0.8242,"score":5.6,"uptime_score":6,"age_score":0,"version_score":10,"speed_score":20,"upload_speed_score":10,"download_speed_score":10,"uptime_weight":0.6,"age_weight":0.2,"version_weight":0.1,"speed_weight":0.05,"upload_speed_weight":0.05,"download_speed_weight":0.05,"last_updated":"2021-12-17T06:47:50.231783862Z"},"renter_stats":{"reserved":""}}`

**Comment by zvictorp** [comment]
How can I check the list of contracts via CLI?

```
btfs storage info
{"storage_price_ask":125000,"storage_time_min":2,"storage_price_default":125000,"roles":[0,1]}

 btfs storage contracts stat
Error: argument "role" is required

btfs storage contracts stat 0
Error: invalid role: 0
```

Please, help me to handle it.
Thank you.

**Comment by AmigoAndrel** [comment]
Hello friends!
Faced the same problem, does anyone know what it is
 16Uiu2HAkvKkYbw2xaZcMNF3jeHqc4YdHh7YXkSABUfYnC5XBX7uq
![2022 03 27_21h03m15s_32](https://user-images.githubusercontent.com/102483571/160295599-3e1cfe48-2e1f-421b-ab68-5655ce86daad.png)
?
