### ISSUE TITLE
Is 32GB the minimum available space for hosting?

### ISSUE THREAD

**Issue by geemaple** [TRON-US/go-btfs#540]
hostui page complains "32 GB is the minimum available space needed to continue setting up your host. Please use another computer with at least 32 GB of availabe space to continue"

![image](https://user-images.githubusercontent.com/16501576/84332111-a050b080-abbe-11ea-9b6a-88c7d5788dae.png)

**Comment by taiyangc** [comment]
Yes. We will give you the option to select a different drive on the next hostui update if you current drive is full.
