### ISSUE TITLE
Uptime going down ?  Payment Date; Dec. 31, 9999

### ISSUE THREAD

**Issue by leek21** [TRON-US/go-btfs#544]
I have had the BTFS daemon running continuously but each day my reported uptime goes down 1%, presently at 69%.  
Also my next payment date is listed as: Dec. 31, 9999.
See picture below:

![image](https://user-images.githubusercontent.com/42178789/84781117-6c0d3380-afb4-11ea-83f9-8e17934b6d1e.png)

**Comment by taiyangc** [comment]
Hello, could you email btfs-developer@bittorrent.com with `btfs id` result and the output of `btfs storage contracts list host`, and the devs will take a look, thanks.

**Comment by taiyangc** [comment]
Should have been fixed in v1.3.5.
