### ISSUE TITLE
 hard disk space is not enough 32g

### ISSUE THREAD

**Issue by alanwang123** [TRON-US/go-btfs#573]
Not enough storage space

32 GB is the minimum available space needed to continue setting up your host. Please use another computer with at least 32 GB of availabe space to continue. 

but my PC has enough space.

**Comment by geoffsnyder** [comment]
I got this during the initial setup. Once I made the adjustment, all was fine.

*note* the .btfs folder resides under the user profile, so make sure the partition and drive are the same as where the .btfs file folder resides (not the application itself).

**Comment by taiyangc** [comment]
We will give an option to pick another folder with enough storage in an upcoming v1.3.2 release.

**Comment by taiyangc** [comment]
v1.3.2 released. Please try again.

**Comment by geoffsnyder** [comment]
Just did while also enabling FuseAllowOther

So far so good!

P.S. I liked it better before the decimal point was corrected in Future
Rewards Earnings. Hundreds of millions of BTT was more appealing! 😉

Thanks for the note.
