### ISSUE TITLE
btfs/autoupdate error

### ISSUE THREAD

**Issue by geoffsnyder** [TRON-US/go-btfs#578]
Initializing daemon...
go-btfs version: 1.3.1-ed6b1d7
Repo version: 9
System version: amd64/windows
Golang version: go1.14.4
Swarm listening on /ip4/10.110.108.30/tcp/4001
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/10.110.108.30/tcp/4001
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/173.244.36.74/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
WebUI: http://127.0.0.1:5001/webui
HostUI: http://127.0.0.1:5001/hostui
Gateway (writable) server listening on /ip4/127.0.0.1/tcp/8080
Remote API server listening on /ip4/127.0.0.1/tcp/5101
Daemon is ready
Storage host info will be synced at [SCORE] mode
Current host stats will be synced
Current host settings will be synced
BTFS is up-to-date.

2020-07-14T15:15:52.511-0700    ←[31mERROR←[0m  cmd/btfs        btfs/autoupdate.
go:431  Http get error, reasons: [Get "https://dist.btfs.io/release/windows/amd6
4/config_windows_amd64.yaml": net/http: TLS handshake timeout]
2020-07-14T15:15:52.511-0700    ←[31mERROR←[0m  cmd/btfs        btfs/autoupdate.
go:144  Download latest btfs config file error, reasons: [Get "https://dist.btfs
.io/release/windows/amd64/config_windows_amd64.yaml": net/http: TLS handshake ti
meout]

**Comment by taiyangc** [comment]
Is it still not working?

**Comment by geoffsnyder** [comment]
The host seems to be working fine now. Nothing changed... It was just a new
error that popped up and just wanted to let you know.

I hope I'm not being difficult, just excited about the project and am
trying to be proactive to help you advance it and get others in board along
the way.

**Comment by taiyangc** [comment]
Yeah it was a CDN hiccup as seen in the error logs. Nothing needs to be done to fix it. Thanks for bringing it up.

**Comment by geoffsnyder** [comment]
OK, great.

Thanks for the insight and your continued efforts!
