### ISSUE TITLE
Unable to upload and/or host Files or Folders over 100MB

### ISSUE THREAD

**Issue by geoffsnyder** [TRON-US/go-btfs#589]
Version information: 1.3.2 for Windows amd64

Unable to upload and host files or folders that are larger than 100MB via webui without each attempt failing.

**Comment by taiyangc** [comment]
Do you have any error logs or a screenshot of what you are using?

**Comment by geoffsnyder** [comment]
Yes. Please see attached.

**Comment by taiyangc** [comment]
Hello @geoffsnyder the attachment is not showing up here.

**Comment by geoffsnyder** [comment]
Hello @taiyangc  - Initial respond was via e-mail... my apologies. Here you go:

![IMG_20200721_164355__01](https://user-images.githubusercontent.com/3204964/88118131-af3d6200-cb71-11ea-91bc-b78beb9c38d1.jpg)


![IMG_20200721_125602__01](https://user-images.githubusercontent.com/3204964/88118101-a482cd00-cb71-11ea-808e-997f3279b7f0.jpg)

**Comment by taiyangc** [comment]
We are actively looking into this issue. If you have further error logs feel free to post here.

**Comment by geoffsnyder** [comment]
Thank you. I have updated to verion 1.3.3 -f11869f and am seeing the same thing happen each time a file or folder larger than 100MB, If there is a log or report I can generate with more specifics, please let me know (where and/or how) and I'll post it here.

**Comment by geoffsnyder** [comment]
Confirming issue still exists within version 1.3.4-46772a3. It will not accept any files or folders larger than 100MB. 

Anything less than 100MB is not a problem.

**Comment by geoffsnyder** [comment]
Update: Client updated to 1.3.5-20c165c in the same environment as it still rejecting Files and/or Folder uploads greater than 100MB in size via WebUI.

However, when installed and ran on a different machine (same build and OS), it seems to have no problem.

There are various setting(s) differences between the two (old environment has some experimental settings enabled and the new environment is configured 'as-is'/'out of the box').

I'm simply trying to understand what may cause/impact the adding or files/folders larger than 100MB versus the environment which seems to be working but is not configured per the documentation provided.

**Comment by luksssy** [comment]
client 1.3.5 on windows is working fine for files under 5gb to upload... if you try something bigger it just crashes.  I guess itis related with free ram capacity which is needed to cache files while uploading.

**Comment by geoffsnyder** [comment]
That's what I've been thinking, however, the available RAM on the box I'm
having issues with is double the amount of RAM I have no issues with. It's
perplexing and I'm on the fence about messing with the daemon's cache
setting but don't want to sacrifice any uptime.

**Comment by taiyangc** [comment]
Yes there is a certain limitation w.r.t to your RAM, but we are also looking for ways to optimize that, so you can potentially upload larger files.
