### ISSUE TITLE
Hosting 5GB but host ui shows 0

### ISSUE THREAD

**Issue by Jenos-Idanian** [TRON-US/go-btfs#604]
1.3.4 - 46772a3
 Amd64 win 10

Status UI shows that I am hosting 5 gb of files.

Host UI shows that zero gb of storage being used while it shows contracts and a potential earnings.

Seem like this is incorrect.

Status UI
![Screenshot_20200727-223643.png](https://user-images.githubusercontent.com/68447731/88612715-d2787d80-d059-11ea-8d3c-6a5d16421c94.png)

Host UI
![Screenshot_20200727-223715.png](https://user-images.githubusercontent.com/68447731/88612807-02278580-d05a-11ea-9b9a-e9d99da75fef.png)

**Comment by Jenos-Idanian** [comment]
Just found my daemon not running with this in the terminal
![image](https://user-images.githubusercontent.com/68447731/88720603-1f5c6280-d0f3-11ea-9b8d-32f521b0cffd.png)

**Comment by taiyangc** [comment]
The storage used issue you mentioned is a valid bug. We will fix it in the next release. Thanks.

**Comment by Jenos-Idanian** [comment]
Thanks responding to the storage bug.

Do you have any info on the error that I posted in the most recent picture?

**Comment by taiyangc** [comment]
Not sure where those errors came from, looks like underlying network lib errors.

**Comment by Jenos-Idanian** [comment]
> Not sure where those errors came from, looks like underlying network lib errors.

Since that occured I have received no new contracts, not any of the previous cannot download shard errors. It seems like the host UI is not acting like it should.
