### ISSUE TITLE
1.3.4 to 1.3.5 no auto update

### ISSUE THREAD

**Issue by kvasselkvasier** [TRON-US/go-btfs#621]
#### Description: The auto update is not working on 1.3.4 for the new update to 1.3.5

Restartet the node 5 times around the day but always say btfs is up to date. 

Auto update is activated

**Comment by taiyangc** [comment]
Can you provide your operating system information? We are aware that certain users are not upgrading.

**Comment by kvasselkvasier** [comment]
Ubuntu Linux 20.04.1
Linux 5.4.0-42-generic on x86_64

Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz, 4 cores
--

**Comment by Jenos-Idanian** [comment]
This is also happening on windows amd

**Comment by taiyangc** [comment]
Is it working now if you restart daemon?

**Comment by kvasselkvasier** [comment]
Yes could update all my nodes. Thanks a lot great work.
