### ISSUE TITLE
Cannot Move BTT Between In App Wallet and Crypto Wallet on Host UI

### ISSUE THREAD

**Issue by Jenos-Idanian** [TRON-US/go-btfs#623]
1.3.5
 
Windows 10 Amd

I am not able to transfer BTT in either direction from either wallet.

This is the error in cmd prompt that is listed when I try.

2020-08-07T06:06:29.251-0400    ←[31mERROR←[0m  core/wallet     wallet/wallet.go:113    Failed to Deposit, ERR[%v]

Please let me know if you need anything else from me on this.

**Comment by taiyangc** [comment]
Can you try again now.

**Comment by Jenos-Idanian** [comment]
It seems like it worked, but when I hit refresh on the browser I am still having the validation issue.

Should I create a new issue for this?

Or just have it in this thread?
