### ISSUE TITLE
HOST UI not displaying Contracts or Future Potential Earning/Next Payment Date

### ISSUE THREAD

**Issue by geoffsnyder** [TRON-US/go-btfs#626]
#### Version information:
go-btfs version: 1.3.5-20c165c
Repo Version: 9
System version: amd64/winblows
Golang: Go1.14.6
Intel Dual E2180 2.00GHz; 8GB RAM, 500GB HDD, Windows Server 2008 Standard

#### Description:
This seems to have occurred with the last update. Multiple environments and different browsers used; same results.

**Comment by taiyangc** [comment]
v1.3.5 addressed a bunch of UI fixes including showing the wrong number of active contracts.

Note that invalid contracts (those that never finished payment or didn't finish upload flow) are not counted towards next payment. Now you are seeing accurate information.
