### ISSUE TITLE
BTFS - lost all my contracts with last update, randomly into a never-ending VALIDATION cycle and various daemon errors.

### ISSUE THREAD

**Issue by Crypto72** [TRON-US/go-btfs#630]
Host ID: 16Uiu2HAm37e4LJ5RCtcVDrESGMS1oLU1B73eTEV2qLLY23HxbtSh

Daemon output:

go-btfs version: 1.3.5-20c165c
Repo version: 9
System version: amd64/windows
Golang version: go1.14.6
Repo location: T:\btfs
Node ID: 16Uiu2HAm37e4LJ5RCtcVDrESGMS1oLU1B73eTEV2qLLY23HxbtSh
Swarm listening on /ip4/127.0.0.1/tcp/1234
Swarm listening on /ip4/169.254.107.2/tcp/1234
Swarm listening on /ip4/169.254.114.255/tcp/1234
Swarm listening on /ip4/169.254.202.243/tcp/1234
Swarm listening on /ip4/169.254.40.171/tcp/1234
Swarm listening on /ip4/169.254.70.232/tcp/1234
Swarm listening on /ip4/192.168.0.17/tcp/1234
Swarm listening on /ip6/::1/tcp/1234
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/1234
Swarm announcing /ip4/169.254.107.2/tcp/1234
Swarm announcing /ip4/169.254.114.255/tcp/1234
Swarm announcing /ip4/169.254.202.243/tcp/1234
Swarm announcing /ip4/169.254.40.171/tcp/1234
Swarm announcing /ip4/169.254.70.232/tcp/1234
Swarm announcing /ip4/192.168.0.17/tcp/1234
Swarm announcing /ip4/90.201.122.128/tcp/1234
Swarm announcing /ip6/::1/tcp/1234
API server listening on /ip4/127.0.0.1/tcp/5001
WebUI: http://127.0.0.1:5001/webui
HostUI: http://127.0.0.1:5001/hostui
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Remote API server listening on /ip4/127.0.0.1/tcp/5101
Daemon is ready
Storage host info will be synced at [SCORE] mode
Current host stats will be synced
Current host settings will be synced
BTFS is up-to-date.
2020-08-08T12:36:29.171+0100    ←[31mERROR←[0m  spin    spin/hosts.go:63        Failed to sync HOST contracts: context d
eadline exceeded
2020-08-08T13:13:26.764+0100    ←[31mERROR←[0m  upload  upload/init.go:303      failed to download shard QmfA2CYcY91Xsz7
Z3d6itjcLXK1UtdkauQ1uEjgozfZFh2 from file QmPjUFqekACQ428G8vWiNq3i21Zn1GBxqk51kuCLxDSgQg with contract id e7d16466-bd75-
45b6-a554-b74805e3d5b8,d096bf6d-5280-442b-938e-95dfc2710c53: [failed to get block for QmZWfT8JgHw1ZVUNT2TPXivPDnPwugMubD
XR8VmvLTMLhv: context deadline exceeded]
2020-08-08T13:52:06.325+0100    ←[31mERROR←[0m  upload  upload/init.go:303      failed to download shard QmQqsfZZnTs3vCW
cNmwo7FdcfynwSQ2364qEHPFG2bS4K3 from file QmeKBZxBUjRQSAo8kEh1jQyq6CchQJE54dougURB8pseU6 with contract id 7fd6f749-a20e-
4715-852b-1a0622e4ae57,206e5d2b-4885-49c6-a978-203bfc875bf4: [failed to get block for QmUZjZfozCSwfokcC4Q69XSagBTMJZKtQs
ajjmvCea7bVB: context deadline exceeded]

Until the last update, everything worked smoothly and then after it issues started to come up. As you can notice from the attached screenshot randomly I get the VALIDATION process, and it keeps spinning my hard drives for hours, and then the process crashes miserably.

Also, my disk space is still occupied by the files renters have uploaded before the last update. If the contracts are not active or they are revoked, deleted or whatever, why my disk space is still occupied by them? Is there any chance to clean or reinitialize my host? It is more than 12GB!!!
![screen1](https://user-images.githubusercontent.com/30170409/89716891-c9b46f80-d9a8-11ea-85d6-1ede4791a7e7.jpg)

Any idea?

**Comment by Jenos-Idanian** [comment]
Hey man, thanks for making sure the right people are seeing the issues you are facing running a btfs node. If you can, next time try to read through the existing open issues and please add comments to other appropriate open issues. There are three open issues that address all of the challenges your are facing with your node. We want to let the devs know what issues we are experiencing, but not unduly overwhelm them, especially with duplicate issues. Thanks for believing in btfs!!!

**Comment by Crypto72** [comment]
Hi there,

Sorry, my bad. Thanks for your reply and I am sure that all the issue will be properly addressed. Cheers.
