### ISSUE TITLE
Failed to sync HOST contracts: context deadline exceeded

### ISSUE THREAD

**Issue by endofthepain** [TRON-US/go-btfs#635]
![Screenshot_664](https://user-images.githubusercontent.com/11496089/89967632-3024e080-dc7c-11ea-8207-8305b68ea211.png)

actualy i cant run "btfs storage contracts sync host" on my node

**Comment by taiyangc** [comment]
Hello, this is a known issue we are looking into fixing.

**Comment by endofthepain** [comment]
ah okay, thank you if team has known this issue hope can get fixed soon, i give my details of my node 

this node running on Ubuntu 18.04 with 2 core CPU and 4 GB of RAM
