### ISSUE TITLE
Incorrect display of disk size and free space.

### ISSUE THREAD

**Issue by Nitrosalad** [TRON-US/go-btfs#667]
![Screenshot_1](https://user-images.githubusercontent.com/37898249/90953388-bd81e500-e473-11ea-98e5-3550c87b341e.png)

**Comment by taiyangc** [comment]
This is a placeholder text when there are errors accessing node info.

What's the output of the command `btfs storage stats info`

**Comment by Nitrosalad** [comment]
btfs storage stats info
Error: context deadline exceeded

**Comment by taiyangc** [comment]
What about `btfs storage stats info -l=true`? If this still doesn't work, please try to reboot your machine.

**Comment by Nitrosalad** [comment]
btfs storage stats info -l=true
Error: context deadline exceeded

**Comment by Nitrosalad** [comment]
Reboot doesn't change anything

**Comment by taiyangc** [comment]
Sorry, one last check, does it timeout on `btfs repo stat` ?

**Comment by Nitrosalad** [comment]
btfs repo stat
NumObjects: 7871973
RepoSize:   2043589156858
StorageMax: 2500000000000
RepoPath:   S:\BTFS
Version:    fs-repo@9

**Comment by digbicks** [comment]
Does anyone have an update on this issue? I am too experiencing the same thing! 

![изображение](https://user-images.githubusercontent.com/6688467/93499116-4711bf00-f91b-11ea-93cb-cfda261b48d1.png)

**Comment by taiyangc** [comment]
@digbicks Yours is ok. What it means is that 68GB is currently being used, out of 998GB totally available. You can adjust it in the commitment size field.
