### ISSUE TITLE
Not Able to find PEER TABLE

### ISSUE THREAD

**Issue by pavansantani** [TRON-US/go-btfs#669]
![Screenshot_20200822-225309_AnyDesk](https://user-images.githubusercontent.com/58158473/90962039-999dbe00-e4ca-11ea-8bd3-15b0bccf9213.jpg)

This is my 2nd node in SAME PC

I DID +1 IN EVERY PORT WHICH BTFS USES.
BUT GOT THIS ERROR 

Node id: 16Uiu2HAm1yj3DV4Sz9SgjwibHyUabddrycSNVHG8NUfoZDqoNzhP

And node is in CONSTANT VALIDATION MODE.

**Comment by pavansantani** [comment]
16Uiu2HAkumJBEP7WMMJyyf9GWoDJQDSn8r9oxEA4iHjeVnMZzFof

SAME ISSUE IN NEW NODE 

is it a serious problem

WEBUI is also not opening  

not able to find any peer in the table

**Comment by taiyangc** [comment]
Please check your internet connection. I could not reproduce your issue.

**Comment by Evgen-Viktorovich** [comment]
Hi, can somebody pls tell me how much score and uptime do i need to get first contract.
Also it is not clear for me how **much time should it take**.
I started system about 5 days ago, had 7.0/100% but after small pause (about 3 hours) it dropped to 6.4/98% and uptime raise too slow (more than 2 days for 1% uptime).
I still have 0 contracts. It is important for me because i want to buy few big HDD, but i`m not sure that it will work at all.
And do i need to open some ports in router or make extra setup in windows 10? Or if it`s tells that i`m "online" and uptime changes then everything fine and just need to wait?
It runs at separate wifi connected laptop with 700gb for this system.

**Comment by pavansantani** [comment]
> Please check your internet connection. I could not reproduce your issue.

webui still not working but that error of peer is not showing up now

**Comment by pavansantani** [comment]
> Hi, can somebody pls tell me how much score and uptime do i need to get first contract.
> Also it is not clear for me how **much time should it take**???
> I started system about 5 days ago, had 7.0/100% but after small pause (about 3 hours) it dropped to 6.4/98% and uptime raise slowly.
> I still have 0 contracts. It is important for me because i want to buy few big HDD, but i am not sure that it will work at all.
> And do i need to open some ports in router or make extra setup in windows 10? Or if it is tells that i`m "online" and uptime changes then everything fine and just need to wait?
> It runs at separate wifi connected laptop with 700gb for this node.

score of 8 gets u contract

rest just leave it in online mode.

**Comment by taiyangc** [comment]
@pavansantani What does "not working" mean? Can you open the 5001 port? Is it showing blank? Is it showing an error message? Please elaborate. A screenshot would help.

**Comment by pavansantani** [comment]
> @pavansantani What does "not working" mean? Can you open the 5001 port? Is it showing blank? Is it showing an error message? Please elaborate. A screenshot would help.

![error](https://user-images.githubusercontent.com/58158473/91540208-16e88900-e938-11ea-8eb8-cc8bfda0e76e.png)
ERROR for PEER TABLE



And, NOTHING APPEARS in URL
![rotating](https://user-images.githubusercontent.com/58158473/91540488-7fd00100-e938-11ea-8913-f4822ae3ebf0.png)



I HAVE CHANGED THE PORTS FOR ACCESS  BCZ of diff harddrive use diff NODE ID

DETAILS OF CONFIG FILE

{
  "API": {
    "HTTPHeaders": {}
  },
  "Addresses": {
    "API": "/ip4/127.0.0.1/tcp/5003",
    "Announce": [],
    "Gateway": "/ip4/127.0.0.1/tcp/8082",
    "NoAnnounce": [],
    "RemoteAPI": "/ip4/127.0.0.1/tcp/5103",
    "Swarm": [
      "/ip4/0.0.0.0/tcp/4003",
      "/ip6/::/tcp/4003"
    ]
  },
  "AutoNAT": {},
  "Bootstrap": [
    "/ip4/18.237.54.123/tcp/4003/p2p/QmWJWGxKKaqZUW4xga2BCzT5FBtYDL8Cc5Q5jywd6xPt1g",
    "/ip4/34.213.5.20/tcp/4003/p2p/QmQVQBsM7uoJy8hATjTm51uSAkx2y3iGLhSwA6LWLa7iQJ",
    "/ip4/18.194.71.27/tcp/4003/p2p/QmYHkY5CrWcvgaDo4PfvzTQgaZtfaqRGDjwW1MrHUj8cLK",
    "/ip4/54.93.47.134/tcp/4003/p2p/QmeHaHe7WvjeY37z5MYC3qYQcQcuvDwUhwTXtP3KhKLXXK",
    "/ip4/3.126.224.22/tcp/4003/p2p/QmWTTmvchTodUaVvuKZMo67xk7ZgkxJf4nBo7SZry3vGU5",
    "/ip4/54.213.128.120/tcp/4003/p2p/QmWm3vBCRuZcJMUT9jDZysoYBb66aokmSReX26UaMk8qq5",
    "/ip4/18.237.202.91/tcp/4003/p2p/QmbVFdiNkvxtc7Nni7yBWAgtHg8MuyhaZ5mDaYR2ZrhhvN",
    "/ip4/13.229.45.41/tcp/4003/p2p/QmX7RZXh27AX8iv2BKLGMgPBiuUpEy8p4LFXgtXAfaZDn9",
    "/ip4/54.254.227.188/tcp/4003/p2p/QmYqCq3PasrzLr3PxtLo5D6spEAJ836W9Re9Eo4zUou45U",
    "/ip4/52.77.240.134/tcp/4003/p2p/QmURPwdLYesWUDB66EGXvDvwcyV44rVRqV2iGNqKN24eVu"
  ],
  "Datastore": {
    "BloomFilterSize": 0,
    "GCPeriod": "1h",
    "HashOnRead": false,
    "Spec": {
      "mounts": [
        {
          "child": {
            "path": "blocks",
            "shardFunc": "/repo/flatfs/shard/v1/next-to-last/2",
            "sync": true,
            "type": "flatfs"
          },
          "mountpoint": "/blocks",
          "prefix": "flatfs.datastore",
          "type": "measure"
        },
        {
          "child": {
            "compression": "none",
            "path": "datastore",
            "type": "levelds"
          },
          "mountpoint": "/",
          "prefix": "leveldb.datastore",
          "type": "measure"
        }
      ],
      "type": "mount"
    },
    "StorageGCWatermark": 90,
    "StorageMax": "209 GB"
  },
  "Discovery": {
    "MDNS": {
      "Enabled": true,
      "Interval": 10
    }
  },
  "Experimental": {
    "Analytics": true,
    "DisableAutoUpdate": false,
    "FilestoreEnabled": false,
    "GraphsyncEnabled": false,
    "HostChallengeEnabled": false,
    "HostRepairEnabled": false,
    "HostsSyncEnabled": true,
    "HostsSyncMode": "SCORE",
    "Libp2pStreamMounting": true,
    "P2pHttpProxy": false,
    "QUIC": false,
    "RemoveOnUnpin": false,
    "ShardingEnabled": false,
    "StorageClientEnabled": true,
    "StorageHostEnabled": true,
    "StrategicProviding": false,
    "UrlstoreEnabled": false
  },
  "Gateway": {
    "APICommands": [],
    "HTTPHeaders": {
      "Access-Control-Allow-Headers": [
        "X-Requested-With",
        "Range",
        "User-Agent"
      ],
      "Access-Control-Allow-Methods": [
        "GET"
      ],
      "Access-Control-Allow-Origin": [
        "*"
      ]
    },
    "NoDNSLink": false,
    "NoFetch": false,
    "PathPrefixes": [],
    "PublicGateways": null,
    "RootRedirect": "",
    "Writable": false
  },
  "Identity": {
    "EncryptedMnemonic": "(removed itentionally)",
    "EncryptedPrivKey": "(removed itentionally)",
    "PeerID": "16Uiu2HAkumJBEP7WMMJyyf9GWoDJQDSn8r9oxEA4iHjeVnMZzFof",
    "PrivKey": "(removed itentionally)"
  },
  "Ipns": {
    "RecordLifetime": "",
    "RepublishPeriod": "",
    "ResolveCacheSize": 128
  },
  "Mounts": {
    "FuseAllowOther": false,
    "IPFS": "/btfs",
    "IPNS": "/btns"
  },
  "Plugins": {
    "Plugins": null
  },
  "Provider": {
    "Strategy": ""
  },
  "Pubsub": {
    "DisableSigning": false,
    "Router": "",
    "StrictSignatureVerification": false
  },
  "Reprovider": {
    "Interval": "12h",
    "Strategy": "all"
  },
  "Routing": {
    "Type": "dht"
  },
  "Services": {
    "EscrowDomain": "https://escrow.btfs.io",
    "EscrowPubKeys": [
      "(removed itentionally)"
    ],
    "ExchangeDomain": "https://exchange.bt.co",
    "FullnodeDomain": "grpc.trongrid.io:50051",
    "GuardDomain": "https://guard.btfs.io",
    "GuardPubKeys": [
      "(removed itentionally)"
    ],
    "HubDomain": "https://hub.btfs.io",
    "SolidityDomain": "grpc.trongrid.io:50052",
    "StatusServerDomain": "https://status.btfs.io"
  },
  "Swarm": {
    "AddrFilters": null,
    "ConnMgr": {
      "GracePeriod": "20s",
      "HighWater": 900,
      "LowWater": 600,
      "Type": "basic"
    },
    "DisableBandwidthMetrics": false,
    "DisableNatPortMap": false,
    "DisableRelay": false,
    "EnableAutoRelay": true,
    "EnableRelayHop": false,
    "SwarmKey": "/key/swarm/psk/1.0.0/\n/base16/\(removed itentionally)"
  },
  "UI": {
    "Host": {
      "ContractManager": {
        "HighWater": 300,
        "LowWater": 100,
        "Threshold": 10000000
      },
      "Initialized": true
    },
    "Renter": {
      "Initialized": false
    },
    "Wallet": {
      "Initialized": true
    }
  }
}

**Comment by pavansantani** [comment]
**### Constant ERROR OF PEER TABLE**

![error update](https://user-images.githubusercontent.com/58158473/91581495-21247a80-e96c-11ea-893b-f9d30abefcc3.png)

**Comment by taiyangc** [comment]
I noticed that your daemon is not swarm broadcasting on any external ip. Did you modify your config manually or through any command lately? It could also be that your port is firewalled so outside access is not allowed. Please double check.

**Comment by pavansantani** [comment]
> I noticed that your daemon is not swarm broadcasting on any external ip. Did you modify your config manually or through any command lately? It could also be that your port is firewalled so outside access is not allowed. Please double check.

HOW TO DO THAT i have pasted my config file rest i have 

8082, 5103, 4003, 5003 all allowed in firewall through inbound roles

and no command used

**Comment by pavansantani** [comment]
hi any update?  NO FIREWALL BLOCKED

& config file copy paste above

**Comment by h1lyl1ly** [comment]
hi guys, have the same thing, try to fix too.
<img width="409" alt="09" src="https://user-images.githubusercontent.com/43503620/91844384-0863df80-ec60-11ea-86cb-b2ee30142f9c.png">

**Comment by cyberwalker82** [comment]
> hi guys, have the same thing, try to fix too.
> <img alt="09" width="409" src="https://user-images.githubusercontent.com/43503620/91844384-0863df80-ec60-11ea-86cb-b2ee30142f9c.png">

This issue happens when BTFS or even your whole computer can't access Internet. Please check your Internet connection.

**Comment by pavansantani** [comment]
> > hi guys, have the same thing, try to fix too.
> > <img alt="09" width="409" src="https://user-images.githubusercontent.com/43503620/91844384-0863df80-ec60-11ea-86cb-b2ee30142f9c.png">
> 
> This issue happens when BTFS or even your whole computer can't access Internet. Please check your Internet connection.

CMON man we r not that care less 

i have total 3 nodes running on the PC   but this one only has this error

**Comment by cyberwalker82** [comment]
> > > hi guys, have the same thing, try to fix too.
> > > <img alt="09" width="409" src="https://user-images.githubusercontent.com/43503620/91844384-0863df80-ec60-11ea-86cb-b2ee30142f9c.png">
> > 
> > 
> > This issue happens when BTFS or even your whole computer can't access Internet. Please check your Internet connection.
> 
> CMON man we r not that care less
> 
> i have total 3 nodes running on the PC but this one only has this error

We will try to reproduce the issue and get back to you if we identify the issue and found a solution.

**Comment by geoffsnyder** [comment]
> > hi guys, have the same thing, try to fix too.
> > <img alt="09" width="409" src="https://user-images.githubusercontent.com/43503620/91844384-0863df80-ec60-11ea-86cb-b2ee30142f9c.png">
> 
> This issue happens when BTFS or even your whole computer can't access Internet. Please check your Internet connection.

When this error occurs, how far out from the actual event does it report? Example: Internet breaks or Firewall flakes out at 12:00AM on 01/01/2045; at what time will the daemon begin flagging the errors? Realtime or later during a validation period? Or... both?

I'm working on expanding my lab and trying to zero-in on replicating issues, for the sole purpose to benefit the network, but I'm having a difficult time establishing consistencies.

**Comment by pavansantani** [comment]
> > > hi guys, have the same thing, try to fix too.
> > > <img alt="09" width="409" src="https://user-images.githubusercontent.com/43503620/91844384-0863df80-ec60-11ea-86cb-b2ee30142f9c.png">
> > 
> > 
> > This issue happens when BTFS or even your whole computer can't access Internet. Please check your Internet connection.
> 
> When this error occurs, how far out from the actual event does it report? Example: Internet breaks or Firewall flakes out at 12:00AM on 01/01/2045; at what time will the daemon begin flagging the errors? Realtime or later during a validation period? Or... both?
> 
> I'm working on expanding my lab and trying to zero-in on replicating issues, for the sole purpose to benefit the network, but I'm having a difficult time establishing consistencies.

ok i get ur point u can check my prrv attached pics  for that data

and internet does not goes down as other 2 nodes do not produce that sort of error.

the latest data of the error time is


on 2 sep 2020  at 12:29:11.042 +05:30(ist time)

on 3 sep 2020 at 00:28:39.220+05:30 (ist time)  

some times after 12 hrs or 24 hrs..

**Comment by pavansantani** [comment]
**### UPDATE**

![issue](https://user-images.githubusercontent.com/58158473/92378520-88d48580-f123-11ea-87e9-76dd29ee1201.png)

**Comment by pavansantani** [comment]
UPDATE

![sasadsa](https://user-images.githubusercontent.com/58158473/92564432-c574be00-f296-11ea-90a0-e0821c569a6e.png)

**Comment by pavansantani** [comment]
**### UPDATE**

![issue update](https://user-images.githubusercontent.com/58158473/92694195-52d21400-f364-11ea-91ee-533e923f36b5.png)

**Comment by geoffsnyder** [comment]
Same here... appears to be serverside.
(still trying to figure out what 'GuardClient' means/does)

**Comment by pavansantani** [comment]
**### UPDATE**

![saadsada](https://user-images.githubusercontent.com/58158473/93051646-78bc2900-f682-11ea-80e2-77b7876b5190.png)

**Comment by pavansantani** [comment]
**### UPDATE**

![sadhasb](https://user-images.githubusercontent.com/58158473/93345317-4cee9e00-f850-11ea-8fef-d1316eadd065.png)

**Comment by pavansantani** [comment]
**### UPDATE
![wqwwqq](https://user-images.githubusercontent.com/58158473/93756955-8db92f00-fc23-11ea-998d-61a5dd5d8a8c.png)
**

**Comment by pavansantani** [comment]
It was port 4001 error  the port was not properly open.
