### ISSUE TITLE
Different Storage SIZE used IN  HOST UI & WEBUI

### ISSUE THREAD

**Issue by pavansantani** [TRON-US/go-btfs#670]
![Screenshot_20200822-224730_AnyDesk](https://user-images.githubusercontent.com/58158473/90962331-d8cd0e80-e4cc-11ea-816e-28a762ed05b8.jpg)

Node id : 16Uiu2HAmAzcZoULDd7Q38FHPzA46VxsiaRm1psrBvoSV1RkUygLW

![Screenshot_20200822-224743_AnyDesk](https://user-images.githubusercontent.com/58158473/90962352-f7330a00-e4cc-11ea-8f3f-14f7e34abf7e.jpg)

Webui shows 2gb used  & host ui shows 1gb used

I refreshed it and also used the PURGE COMMAND.

WEB UI IS CORRECT I HAVE 2GB SPACE UTILISED
BUT STILL SAME RESULTS...

Payment AMOUNT  REAMINED SAME AS BEFORE

**Comment by pavansantani** [comment]
AGAIN SAME ISSUE HAPPENING SINCE LAST 3 days

used the purge command too

![wat](https://user-images.githubusercontent.com/58158473/93585016-c9ee5480-f9c3-11ea-8028-15e666e2ba49.png)

**Comment by taiyangc** [comment]
Both these are using the `btfs repo stat` command to display file size. My guess is that different rounding strategies are used. Also, we do not actively maintain legacy/ipfs webui, as our main focus is on the host ui.
