### ISSUE TITLE
spin/hosts.go:63 failed to sync host stats error AND unlimited 180 min validation

### ISSUE THREAD

**Issue by Evgen-Viktorovich** [TRON-US/go-btfs#671]
#### Version information:
Latest Ubuntu with all updates and curl - 7.68.0

#### Description:
**_Main info_**: After clean install latest Ubuntu and curl, then following https://docs.btfs.io/docs/btfs-demo i have next error: 
`error spin spin/hosts.go:63 failed to sync host stats: failed to query stats from hub service: hubqueryclient: cannot query to get stats`.
**Detailed info**:
Laptop with good WIFI connection (idk maybe important). One completely empty hard drive.
 20.04 lts Ubuntu with all auto setup drivers and one more update after start. Installed curl - 7.68.0 (clean ubuntu do not have it and i can not run `bash install.sh -o linux -a amd64` command without it, line 47 error).
Full following guide from https://docs.btfs.io/docs/btfs-demo .
All ok till `btfs daemon` started. After start i have hostui that says that i need to enter `btfs config profile apply storage-host` and restart daemon, after this command and `btfs shutdown` then `btfs daemon` i got this `error spin spin/hosts.go:63...` error.
But daemon is working, the only problem that i was waiting about 5-6 hours that 180 min validation, but it did not finished, so i just turn it off. So **i have unlimited 180 min validation**.
I tried Linux Mint also, tried to install Fuse/Go/Libcurl/Libtorrent but no (maybe it is missing some libraries or something like this).
I think if you will install Ubuntu and will follow guide from https://docs.btfs.io/docs/btfs-demo then you will have same situation, coz i tried about four times, but only for linux.
Sorry for mistakes, English is not my native language.
Feel free to clarify something, thank you and best regards.

UPD:
Looks like this error can be caused if Daemon will be restarted after `btfs config profile apply storage-host` (like hostui said to do).
I just started new try and looks like i don`t have this error anymore, i just did not added wallet and did not restarted daemon, lets see how much validation will take.

**Comment by taiyangc** [comment]
It's fixed yesterday. Sorry about the interruption.
