### ISSUE TITLE
Node will not validate.

### ISSUE THREAD

**Issue by Stevevk88** [TRON-US/go-btfs#672]
Initializing daemon...
go-btfs version: 1.3.6-b1722d1
Repo version: 9
System version: amd64/windows
Golang version: go1.14.6
Repo location: C:\Users\Slim Shady\.btfs
Node ID: 16Uiu2HAmA34HanmEUduoL9AqBKdU6oXG6rsENJowgWcANsztFAK7
Swarm listening on /ip4/10.0.0.183/tcp/4001
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/169.254.120.26/tcp/4001
Swarm listening on /ip4/169.254.164.225/tcp/4001
Swarm listening on /ip4/169.254.249.110/tcp/4001
Swarm listening on /ip4/169.254.78.241/tcp/4001
Swarm listening on /ip6/2601:410:81:70a0::c2eb/tcp/4001
Swarm listening on /ip6/2601:410:81:70a0:f022:cc:11e1:8bbe/tcp/4001
Swarm listening on /ip6/2601:410:81:70a0:fcbb:ef7a:b764:4b9f/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/10.0.0.183/tcp/4001
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/169.254.120.26/tcp/4001
Swarm announcing /ip4/169.254.164.225/tcp/4001
Swarm announcing /ip4/169.254.249.110/tcp/4001
Swarm announcing /ip4/169.254.78.241/tcp/4001
Swarm announcing /ip4/68.60.91.105/tcp/26199
Swarm announcing /ip4/68.60.91.105/tcp/51085
Swarm announcing /ip6/2601:410:81:70a0::c2eb/tcp/4001
Swarm announcing /ip6/2601:410:81:70a0:f022:cc:11e1:8bbe/tcp/4001
Swarm announcing /ip6/2601:410:81:70a0:fcbb:ef7a:b764:4b9f/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
WebUI: http://127.0.0.1:5001/webui
HostUI: http://127.0.0.1:5001/hostui
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Remote API server listening on /ip4/127.0.0.1/tcp/5101
Daemon is ready
Storage host info will be synced at [SCORE] mode
Current host stats will be synced
Current host settings will be synced
2020-08-23T04:07:01.964-0400    ←[31mERROR←[0m  spin    spin/hosts.go:63        Failed to sync host stats: Failed to query stats from Hub service: HubQueryClient: Cannot query to get stats!
BTFS is up-to-date.

After 4-5 hours still will not validate.

**Comment by tobytaro** [comment]
> try to restart the node. It helped me

Do you mean shutdown and start again?
I tried but it didn't work.

**Comment by Evgen-Viktorovich** [comment]
I have same problem, if you check 63 error in already closed issues you will see that developers says that it is okay for new node.
Not perfect but ok, i`m checking this for about 7 hours and will text here if and when it finally validate.

**Comment by taiyangc** [comment]
Fixed just yesterday. Thanks for the report.
