### ISSUE TITLE
403 appear after upgrade to 1.3.6

### ISSUE THREAD

**Issue by sunguide** [TRON-US/go-btfs#675]
####OS: centos
####BTFS version: 1.3.6
####example:

[root@web1 ~]# /root/btfs/bin/btfs wallet balance
Error: 403 - Forbidden

**Comment by taiyangc** [comment]
Is `btfs daemon` running on the same machine?

**Comment by sunguide** [comment]
> Is `btfs daemon` running on the same machine?

sure

**Comment by sunguide** [comment]
what should i do ?

**Comment by taiyangc** [comment]
We are working on a fix.

**Comment by taiyangc** [comment]
Please upgrade to v1.4.0 for a fix.
