### ISSUE TITLE
score calculat wrong

### ISSUE THREAD

**Issue by boringw** [TRON-US/go-btfs#676]
my stats info:

{"host_stats":{"online":true,"uptime":0.9738,"score":6.4,"storage_used":11416153,"storage_cap":59000000000,"storage_disk_total":64454631424,"storage_disk_available":58736103424,"uptime_score":9,"age_score":0,"version_score":10,"speed_score":9.536743e-7,"uptime_weight":0.6,"age_weight":0.2,"version_weight":0.1,"speed_weight":0.1},"renter_stats":{"reserved":""}}

why 'speed_score' is a strange number，and it looks at not work
my score : 9*0.6 + 10*0.1 = 6.4 speed_score not include

if include my score reach 7.2
not one node，my all n odes ‘speed_score’ the same number
so is this some err?

**Comment by taiyangc** [comment]
Thank you for your feedback. We are investigating this issue. Will update back soon.

**Comment by pavansantani** [comment]
HI, Update same issue with me
btfs.exe storage stats info
{"host_stats":{"online":true,"uptime":0.9591,"score":6.4,"storage_used":8096390,
"storage_cap":438000000000,"storage_disk_total":438458904576,"storage_disk_avail
able":438272819200,"uptime_score":9,"age_score":0,"version_score":10,"speed_scor
e":9.536743e-7,"uptime_weight":0.6,"age_weight":0.2,"version_weight":0.1,"speed_
weight":0.1},"renter_stats":{"reserved":""}}

**Comment by taiyangc** [comment]
This is fixed.
