### ISSUE TITLE
speed_score show no data

### ISSUE THREAD

**Issue by juchambo** [TRON-US/go-btfs#677]
#### Version information:
PS D:\btfs> ./btfs daemon
Initializing daemon...
go-btfs version: 1.3.6-b1722d1
Repo version: 9
System version: amd64/windows
Golang version: go1.14.6
Repo location: D:\btfs\.btfs

#### Description:
When using `btfs storage stats info` speed_score isn´t working.

./btfs storage stats info
{"host_stats":{"online":true,"uptime":0.9959,"score":9,"storage_used":20058482371,"storage_cap":600000000000,"storage_disk_total":2000396742656,"storage_disk_available":614950313984,"uptime_score":10,"age_score":10,"version_score":10,`"speed_score":0`,"uptime_weight":0.6,"age_weight":0.2,"version_weight":0.1,"speed_weight":0.1},"renter_stats":{"reserved":""}}

**Comment by taiyangc** [comment]
Thank you for your feedback. We are investigating this issue. Will update back soon.

**Comment by RowdyMuncher** [comment]
Same issue with mine as well.

Version Information:

efraimsilver@BTFSNode2 ~ % btfs daemon                         
Initializing daemon...
go-btfs version: 1.3.6-b1722d1
Repo version: 9
System version: amd64/darwin
Golang version: go1.14.6
Repo location: /Users/efraimsilver/.btfs

When using btfs storage stats info speed_score isn't working as well.

{"host_stats":{"online":true,"uptime":0.9407,"score":7.2,"storage_used":7472808051,"storage_cap":2900000000000,"storage_disk_total":3121506295808,"storage_disk_available":2891044495360,"uptime_score":7,"age_score":10,"version_score":10,"speed_score":0,"uptime_weight":0.6,"age_weight":0.2,"version_weight":0.1,"speed_weight":0.1},"renter_stats":{"reserved":""}}

Thank you

**Comment by taiyangc** [comment]
This is fixed, please check again.
