### ISSUE TITLE
No Issues to report

### ISSUE THREAD

**Issue by geoffsnyder** [TRON-US/go-btfs#679]
Figured I'd drop in and mention that since upgrading to 1.3.6 and have been online and stabilized for for 24-48 hours... no known issues to report on 5 nodes running 386 & amd64 for Windblows. 

HostSync looks good. GUI issues don't appear to be present, airdrop payouts are coming in, and contracts are flowing. 

Devs: Keep up the good work!

**Comment by taiyangc** [comment]
Thank you for your kind support.
