### ISSUE TITLE
 commands/wallet.go:214  wallet get balance failed, ERR: Failed to get exchange tron balance, reason: context canceled

### ISSUE THREAD

**Issue by yuzhongrong** [TRON-US/go-btfs#683]
i have a problem :

commands/wallet.go:214  wallet get balance failed, ERR: Failed to get exchange tron balance, reason: context canceled

**Comment by yuzhongrong** [comment]
need to wait?

**Comment by taiyangc** [comment]
Maybe just a temporary issue, is it working again now?
