### ISSUE TITLE
i provider the space 3999G but show 401 GB available of 3999 GB

### ISSUE THREAD

**Issue by yuzhongrong** [TRON-US/go-btfs#684]
i provider the space 3999G but show 401 GB available of 3999 GB

**Comment by yuzhongrong** [comment]
<img width="562" alt="111222" src="https://user-images.githubusercontent.com/7382234/92211274-cc7c8480-eec2-11ea-8b3e-eaa766c40782.png">

**Comment by yuzhongrong** [comment]
The score always shows 3  and uptime is long time 
<img width="973" alt="score" src="https://user-images.githubusercontent.com/7382234/92220034-f4251a00-eecd-11ea-80ca-df149f60d1d2.png">

**Comment by yuzhongrong** [comment]
this is my hostinfo  :


{"host_stats":{"online":true,"uptime":0.1833,"score":3,"storage_used":14866984,"storage_cap":3600000000000,"storage_disk_total":4000441171968,"storage_disk_available":3999314788352,"uptime_score":0,"age_score":5,"version_score":10,"speed_score":20,"uptime_weight":0.6,"age_weight":0.2,"version_weight":0.1,"speed_weight":0.1},"renter_stats":{"reserved":""}}

**Comment by yuzhongrong** [comment]
<img width="1279" alt="3333" src="https://user-images.githubusercontent.com/7382234/92231786-f4c6ac00-eedf-11ea-8fc0-081880af9efb.png">

my uptime is long time  why ?

**Comment by endofthepain** [comment]
its normal ur node online from ? few days ?  hours ? week ?

**Comment by yuzhongrong** [comment]
about 2 day

**Comment by yuzhongrong** [comment]
need more time ?

**Comment by yuzhongrong** [comment]
my provider 3.5T storeage  but  show the info of 401 GB available of 3999 GB

**Comment by yuzhongrong** [comment]
why is  401 GB

**Comment by endofthepain** [comment]
yeah my uptime 13 days ago is 97%

**Comment by endofthepain** [comment]
> why is 401 GB

restart your daemon again

**Comment by yuzhongrong** [comment]
ok i know thanks

**Comment by geoffsnyder** [comment]
might be best to start over. i'm finding that with the continuous changes to the scoring requirements, a lot of new nodes that are taking 3-5 days to get validated are better off starting off from scratch. 

this network is becoming much more difficult... and it appears airpdops have been skewed quite a bit the past few weeks.

**Comment by yuzhongrong** [comment]
@geoffsnyder   What does it mean to reinstall the BTFS mining program from scratch？

**Comment by yuzhongrong** [comment]
<img width="611" alt="555" src="https://user-images.githubusercontent.com/7382234/92298326-50457800-ef7a-11ea-8b0d-7a4ceeda8776.png">

Two days have passed and my valid savings is still 401

**Comment by yuzhongrong** [comment]
I need more efficient space because I might have to expand to 100T  later

**Comment by geoffsnyder** [comment]
> @geoffsnyder What does it mean to reinstall the BTFS mining program from scratch？

@yuzhongrong Delete the btfs folder and start out with a fresh 'install' (using yaml.config and daemon). Just tend to the new nodes more efficiently than previously. *note* I have not seen that many valid contracts since the last couple version releases. Mostly because I think we're seeing a more accurate network and scoring system, but also... because there isn't enough public/user facing exposure for BTFS usage other than for airdrop/research/testing purposes.

**Comment by yuzhongrong** [comment]
@geoffsnyder  the uptime to 100% need long long time  if i delete the btfs folder

**Comment by yuzhongrong** [comment]
im not  find  command about  using yaml.config and daemon   to install

**Comment by yuzhongrong** [comment]
It is impossible for me to change the storage at once and reinstall it because I will expand the storage size later

**Comment by yuzhongrong** [comment]
the uptime is 24% now  , if i reinstall the btfs  the uptime change to 0%?

**Comment by yuzhongrong** [comment]
retry the command  'sudo btfs daemon '  but the storeage size Still 401G

**Comment by yuzhongrong** [comment]
What command do I need if I go to reinstall and it does not affect uptime

**Comment by taiyangc** [comment]
This can be a little confusing for some, what 401GB out of 3999 means is that "You have 3999GB available for use, but your btfs folder is currently only allocating 401GB as the soft max for all the files". You can increase it by changing the "Storage commitment size" on the bottom.
