### ISSUE TITLE
escrow time filter

### ISSUE THREAD

**Issue by WhiteEgg** [TRON-US/go-btfs#687]
#### Version information:
go-btfs version: 1.4.0-ac55def5c-dirty
Repo version: 9
System version: amd64/linux
Golang version: go1.14.7

#### Description:
9999-12-31T23:59:59Z filter not work
![1](https://user-images.githubusercontent.com/20720225/92324114-17d49580-f071-11ea-82de-9b0c9264354b.png)
test with https://github.com/TRON-US/go-btfs/pull/686

**Comment by taiyangc** [comment]
Did you hard refresh the page, or use incognito?

**Comment by taiyangc** [comment]
ok, fix is coming up

**Comment by taiyangc** [comment]
@WhiteEgg Try this fix again? https://github.com/TRON-US/go-btfs/commit/52e1e106a65439a0458c1a9c73c1e0f3b82672e0

**Comment by WhiteEgg** [comment]
@taiyangc always refresh with Disable cache option, no any output now
![1](https://user-images.githubusercontent.com/20720225/92877214-82a11a80-f43d-11ea-984a-0d6b964ee7ca.png)

**Comment by taiyangc** [comment]
ok, the filter is working then.
