### ISSUE TITLE
Can I use a same wallet address for each node?

### ISSUE THREAD

**Issue by neicedai** [TRON-US/go-btfs#688]
#### Description

I have four nodes, and I use a same wallet for each one.
they are running well
But I found all of these  nodes have the same node id and peer id.
Is it normal？

**Comment by laipogo** [comment]
You'd better not to use same id.
Peer id is used for routing so you should use different ids.

**Comment by neicedai** [comment]
> You'd better not to use same id.
> Peer id is used for routing so you should use different ids.

How to change the wallet?

**Comment by pavansantani** [comment]
> > You'd better not to use same id.
> > Peer id is used for routing so you should use different ids.
> 
> How to change the wallet?

open webui

then go to last section where u see

wallet 

true

change that true to false

& restart daemon   & then back to wallet area in host ui   create new

**Comment by neicedai** [comment]
> > > You'd better not to use same id.
> > > Peer id is used for routing so you should use different ids.
> > 
> > 
> > How to change the wallet?
> 
> open webui
> 
> then go to last section where u see
> 
> wallet
> 
> true
> 
> change that true to false
> 
> & restart daemon & then back to wallet area in host ui create new

When i create a new wallet it also the old wallet

**Comment by pavansantani** [comment]
> > > > You'd better not to use same id.
> > > > Peer id is used for routing so you should use different ids.
> > > 
> > > 
> > > How to change the wallet?
> > 
> > 
> > open webui
> > then go to last section where u see
> > wallet
> > true
> > change that true to false
> > & restart daemon & then back to wallet area in host ui create new
> 
> When i create a new wallet it is still the old wallet

i did not get you. 

if u do exactly wat i hav written in above msg i think u should get new wallet 


STEP 1 GOT TO 127.0.0.1:5001/WEBUI

STEP 2  LOOK FOR SETTINGS  AND IN THE SETTINGS PAGE LOOK FOR WALLET IN BOTTOM PART

STEP 3  CHANGE TRUE FOR WALLET INTO FALSE

SETP 4 RESTART BTFS DAEMON

STEP 5  GO TO 127.0.0.1:5001/hostui
STEP 6 GO TO WALLET

STEP 7  CREATE NEW WALLET WITH NEW PASSWORD

STEP 8 RESTART DAEMON AGAIN.

**Comment by neicedai** [comment]
> > > > > You'd better not to use same id.
> > > > > Peer id is used for routing so you should use different ids.
> > > > 
> > > > 
> > > > How to change the wallet?
> > > 
> > > 
> > > open webui
> > > then go to last section where u see
> > > wallet
> > > true
> > > change that true to false
> > > & restart daemon & then back to wallet area in host ui create new
> > 
> > 
> > When i create a new wallet it is still the old wallet
> 
> i did not get you.
> 
> if u do exactly wat i hav written in above msg i think u should get new wallet
> 
> STEP 1 GOT TO 127.0.0.1:5001/WEBUI
> 
> STEP 2 LOOK FOR SETTINGS AND IN THE SETTINGS PAGE LOOK FOR WALLET IN BOTTOM PART
> 
> STEP 3 CHANGE TRUE FOR WALLET INTO FALSE
> 
> SETP 4 RESTART BTFS DAEMON
> 
> STEP 5 GO TO 127.0.0.1:5001/hostui
> STEP 6 GO TO WALLET
> 
> STEP 7 CREATE NEW WALLET WITH NEW PASSWORD
> 
> STEP 8 RESTART DAEMON AGAIN.

after I finished step 8 ,it still the old wallet
not a new one
