### ISSUE TITLE
Unable to sync host stats

### ISSUE THREAD

**Issue by digbicks** [TRON-US/go-btfs#691]
Hi,

I just started hosting, everithing was going smooth until I got this error in the btfs daemon:

**2020-09-09T07:21:50.680+0300    [31mERROR[0m  spin    spin/hosts.go:63        Failed to sync host stats: Failed to query stats from Hub service: HubQueryClient: Cannot query to get stats!**

After that the daemon freezes. No information is updating. I looked at the webui and it seems that there is some traffic going in and out but no information is displayed in the CMD.

my node id is: 16Uiu2HAmG77oceHuz56MkyxKki6zy1q2yvv3ddw4bhmPdwKbhGaS

StorageHostEnabled is set to "True"

![Annotation 2020-09-09 074733](https://user-images.githubusercontent.com/6688467/92555639-c2ff6d80-f270-11ea-993f-db7ea5cb2dd8.png)

**Comment by pavansantani** [comment]
Be relaxed it's a normal error for new host 

& CMD updates every 24 hrs  

to check ur host is ok & working just go to

http://127.0.0.1/hostui

**Comment by pavansantani** [comment]
> Hi,
> 
> I just started hosting, everithing was going smooth until I got this error in the btfs daemon:
> 
> **2020-09-09T07:21:50.680+0300 �[31mERROR�[0m spin spin/hosts.go:63 Failed to sync host stats: Failed to query stats from Hub service: HubQueryClient: Cannot query to get stats!**
> 
> After that the daemon freezes. No information is updating. I looked at the webui and it seems that there is some traffic going in and out but no information is displayed in the CMD.
> 
> my node id is: 16Uiu2HAmG77oceHuz56MkyxKki6zy1q2yvv3ddw4bhmPdwKbhGaS
> 
> StorageHostEnabled is set to "True"
> 
> ![Annotation 2020-09-09 074733](https://user-images.githubusercontent.com/6688467/92555639-c2ff6d80-f270-11ea-993f-db7ea5cb2dd8.png)

THIS IS NOT AN ISSUE U SHOULD CLOSE THE ISSUE.

**Comment by digbicks** [comment]
@pavansantani so the lack of validation for the past 8 hours is also normal and I should just leave it and eventually it will work itself out? Because for the past 8 hours I have not received validation.

**Comment by pavansantani** [comment]
> @pavansantani so the lack of validation for the past 8 hours is also normal and I should just leave it and eventually it will work itself out? Because for the past 8 hours I have not received validation.

if u r saying that ur host ui is in validation mode since last 8+ hrs then i think give it time as for my new node setup after 1.3.6 update  it took more that 48+ hrs to validate.

**Comment by digbicks** [comment]
@pavansantani exactly just wanted to make sure that I did not do anything wrong. Thank you for the clarification!
