### ISSUE TITLE
DID NOT RECEIVED PAYMENT FOR HOSTING 

### ISSUE THREAD

**Issue by pavansantani** [TRON-US/go-btfs#692]
VERSION 1.3.6
-sep-
i have hosted 4 GB space since last 1 month  it showed payment date of  08-09-2020

but now it shows payment date of jan 01, 10000

and also did not got any payment for hosting

![1](https://user-images.githubusercontent.com/58158473/92564770-564b9980-f297-11ea-9ec1-1eb1171d9adb.png)

for more info on contracts i used this command

btfs storage contracts list host |jq
{
  "contracts": [
    {
      "contract_id": "9c4bdfb7-f959-4c83-8cbf-e4958f16fc98,ab2e1ae4-9098-4c12-8ef5-30626743bc1f",
      "host_id": "16Uiu2HAmRqJFB4U5JQsavLXfZrLCdbpC6nrxiGguXZALjfpkAwYA",
      "renter_id": "16Uiu2HAkz5shmDGPhWibau4vSF6bwZoLh73TRiSoRLuJQxkF2oMK",
      "status": 8,
      "start_time": "2020-08-08T02:30:48.267635Z",
      "end_time": "2021-08-08T02:30:48.267635Z",
      "next_escrow_time": "9999-12-31T23:59:59Z",
      "compensation_paid": 0,
      "compensation_outstanding": 4474458,
      "unit_price": 250000,
      "shard_size": 52651106,
      "shard_hash": "QmY2yyGHiVaxv4KDfdGJ1qtkw2gJUabKUbX99QbUtbyBza",
      "file_hash": "QmNn4XceD9n7qF5NXMNDF3tKpAciKvjYg76ErDPJrhHX2Y",
      "last_modify_time": "2020-09-09T03:35:44.492024Z"
    },
    {
      "contract_id": "1c46d140-90f2-485b-a71b-d6ee5982d325,9787cf76-1b2a-4785-ad57-7e8c2e292ffe",
      "host_id": "16Uiu2HAmRqJFB4U5JQsavLXfZrLCdbpC6nrxiGguXZALjfpkAwYA",
      "renter_id": "16Uiu2HAkz5shmDGPhWibau4vSF6bwZoLh73TRiSoRLuJQxkF2oMK",
      "status": 8,
      "start_time": "2020-08-08T03:10:55.259034Z",
      "end_time": "2021-08-08T03:10:55.259034Z",
      "next_escrow_time": "9999-12-31T23:59:59Z",
      "compensation_paid": 0,
      "compensation_outstanding": 4474458,
      "unit_price": 250000,
      "shard_size": 52651106,
      "shard_hash": "QmV6qRWF179AAxowhaLmwcd3ZB2kZby1YBFJvV661ENdwe",
      "file_hash": "QmcFEinFjnySP8u6FGFTD5ydmC33MjhKw58sZwzoge1u4e",
      "last_modify_time": "2020-09-09T05:43:20.169276Z"
    },
    {
      "contract_id": "9f54d239-6ff3-4ee1-bdc0-533730f23ebe,0e9c0781-f41e-4835-802f-147ef40011b1",
      "host_id": "16Uiu2HAmRqJFB4U5JQsavLXfZrLCdbpC6nrxiGguXZALjfpkAwYA",
      "renter_id": "16Uiu2HAkz5shmDGPhWibau4vSF6bwZoLh73TRiSoRLuJQxkF2oMK",
      "status": 8,
      "start_time": "2020-08-08T03:30:13.473754Z",
      "end_time": "2021-08-08T03:30:13.473754Z",
      "next_escrow_time": "9999-12-31T23:59:59Z",
      "compensation_paid": 0,
      "compensation_outstanding": 4474458,
      "unit_price": 250000,
      "shard_size": 52651106,
      "shard_hash": "QmdSiQwwuEXagP6pzhQo37RAraFS3ut58QEaJoiQUnV17q",
      "file_hash": "QmdeWPSQoi2mpcxiwX3RpNGMtTotkwf1K5mndQa5fdwTKp",
      "last_modify_time": "2020-09-09T05:43:20.169276Z"
    },
    {
      "contract_id": "a444ec9c-590b-454c-9344-262f8ad76d61,042f2ba0-54c1-49e2-9ec3-a6d9d4ae9c58",
      "host_id": "16Uiu2HAmRqJFB4U5JQsavLXfZrLCdbpC6nrxiGguXZALjfpkAwYA",
      "renter_id": "16Uiu2HAkz5shmDGPhWibau4vSF6bwZoLh73TRiSoRLuJQxkF2oMK",
      "status": 8,
      "start_time": "2020-08-08T03:37:09.094621Z",
      "end_time": "2021-08-08T03:37:09.094621Z",
      "next_escrow_time": "9999-12-31T23:59:59Z",
      "compensation_paid": 0,
      "compensation_outstanding": 4474458,
      "unit_price": 250000,
      "shard_size": 52651106,
      "shard_hash": "QmTdhxRnbueDB7aJK2Y48Y983jvhx4e39pb4hSb1wdLcwR",
      "file_hash": "QmS3nCbqpNPJ8K8fzYA41XptGB3eqJeGoLMZJh6qtZGT3W",
      "last_modify_time": "2020-09-09T05:43:20.169276Z"
    },
    {
      "contract_id": "7f26b4e7-6a46-4026-8177-e4bd0eebcefe,83c534d2-cc31-4d4c-96f1-3030d1bd4798",
      "host_id": "16Uiu2HAmRqJFB4U5JQsavLXfZrLCdbpC6nrxiGguXZALjfpkAwYA",
      "renter_id": "16Uiu2HAkz5shmDGPhWibau4vSF6bwZoLh73TRiSoRLuJQxkF2oMK",
      "status": 8,
      "start_time": "2020-08-08T03:58:05.366636Z",
      "end_time": "2021-08-08T03:58:05.366636Z",
      "next_escrow_time": "9999-12-31T23:59:59Z",
      "compensation_paid": 0,
      "compensation_outstanding": 1559824,
      "unit_price": 250000,
      "shard_size": 18354504,
      "shard_hash": "QmdvNkjXDQDGPkcpNt3oZveybP4xZddmzW7vpN6EK8PRPM",
      "file_hash": "QmUTnHbykVSn6KBXy9uYeTT8Ly9Emy5mcjxVWFwS4Z2uqT",
      "last_modify_time": "2020-09-09T05:43:20.169276Z"
    },
    {
      "contract_id": "0cfe6508-25b9-4574-b1fe-f411b4a6155e,dad3ad6e-e5b6-40a2-a511-f646a75c05f9",
      "host_id": "16Uiu2HAmRqJFB4U5JQsavLXfZrLCdbpC6nrxiGguXZALjfpkAwYA",
      "renter_id": "16Uiu2HAkz5shmDGPhWibau4vSF6bwZoLh73TRiSoRLuJQxkF2oMK",
      "status": 8,
      "start_time": "2020-08-08T04:53:26.003369Z",
      "end_time": "2021-08-08T04:53:26.003369Z",
      "next_escrow_time": "9999-12-31T23:59:59Z",
      "compensation_paid": 0,
      "compensation_outstanding": 3802998,
      "unit_price": 250000,
      "shard_size": 44750015,
      "shard_hash": "QmeWBnuph2WQFsD1FvJ7CbkuCsuaZsZQaqwFw9BTY7jvnM",
      "file_hash": "QmRNNh1K3WG6AA3HyaqaLmKMRmiYFvGh2dDeFfcDxes4co",
      "last_modify_time": "2020-09-09T05:43:20.169276Z"
    },
    {
      "contract_id": "bfb331b4-5f48-4d9a-8468-33b88a11e6e0,c2c55e00-2739-47df-9723-035d1119377c",
      "host_id": "16Uiu2HAmRqJFB4U5JQsavLXfZrLCdbpC6nrxiGguXZALjfpkAwYA",
      "renter_id": "16Uiu2HAkz5shmDGPhWibau4vSF6bwZoLh73TRiSoRLuJQxkF2oMK",
      "status": 8,
      "start_time": "2020-08-08T06:54:20.184889Z",
      "end_time": "2021-08-08T06:54:20.184889Z",
      "next_escrow_time": "9999-12-31T23:59:59Z",
      "compensation_paid": 0,
      "compensation_outstanding": 4465547,
      "unit_price": 250000,
      "shard_size": 52546248,
      "shard_hash": "QmZacq6GYMvXQAk9jxLmUgT5KCuVoC3Rk8zmZkFsUpL9qY",
      "file_hash": "QmX8jXjzAVWUNFnzHpKM4ci8EbVNWchmpg8sDvduHEQXEu",
      "last_modify_time": "2020-09-09T05:43:20.169276Z"
    },
    {
      "contract_id": "9a06ccca-f522-472d-8880-9680feef2f09,a1306df7-603e-47e3-94fd-91e3f3d4d3a6",
      "host_id": "16Uiu2HAmRqJFB4U5JQsavLXfZrLCdbpC6nrxiGguXZALjfpkAwYA",
      "renter_id": "16Uiu2HAkz5shmDGPhWibau4vSF6bwZoLh73TRiSoRLuJQxkF2oMK",
      "status": 8,
      "start_time": "2020-08-08T07:26:21.494277Z",
      "end_time": "2021-08-08T07:26:21.494277Z",
      "next_escrow_time": "9999-12-31T23:59:59Z",
      "compensation_paid": 0,
      "compensation_outstanding": 823457,
      "unit_price": 250000,
      "shard_size": 9689656,
      "shard_hash": "QmPc3XZtzAVRjgE7kKo9bkYsfBpBKXPZq6V4gry8yYDhed",
      "file_hash": "Qmb7Deha9AWrsQtKhaBA5uBhs2bp1Piiptk6w226L1w81J",
      "last_modify_time": "2020-09-09T05:43:20.169276Z"
    },
    {
      "contract_id": "270bb247-c34f-4a42-bb16-52c741a3cd53,7b7117bb-12ff-4a82-b9d4-e4a0b7412aea",
      "host_id": "16Uiu2HAmRqJFB4U5JQsavLXfZrLCdbpC6nrxiGguXZALjfpkAwYA",
      "renter_id": "16Uiu2HAkz5shmDGPhWibau4vSF6bwZoLh73TRiSoRLuJQxkF2oMK",
      "status": 8,
      "start_time": "2020-08-08T07:45:39.490713Z",
      "end_time": "2021-08-08T07:45:39.490713Z",
      "next_escrow_time": "9999-12-31T23:59:59Z",
      "compensation_paid": 0,
      "compensation_outstanding": 4465547,
      "unit_price": 250000,
      "shard_size": 52546248,
      "shard_hash": "QmZCNe5ZThLEAmGFSVornitvLco5K26Q915CjEb6mdshEC",
      "file_hash": "QmP6jzCvXofQmfZ8dRMmofuRiiPJ6ayDaPUZCvfbkxhj6h",
      "last_modify_time": "2020-09-09T05:43:20.169276Z"
    },
    {
      "contract_id": "41659b94-26e4-4ef5-828c-a3e813178813,7cb97139-f4ca-47f1-9f84-aa8d9077cddf",
      "host_id": "16Uiu2HAmRqJFB4U5JQsavLXfZrLCdbpC6nrxiGguXZALjfpkAwYA",
      "renter_id": "16Uiu2HAkz5shmDGPhWibau4vSF6bwZoLh73TRiSoRLuJQxkF2oMK",
      "status": 8,
      "start_time": "2020-08-08T09:15:29.171357Z",
      "end_time": "2021-08-08T09:15:29.171357Z",
      "next_escrow_time": "9999-12-31T23:59:59Z",
      "compensation_paid": 0,
      "compensation_outstanding": 4465547,
      "unit_price": 250000,
      "shard_size": 52546248,
      "shard_hash": "QmbM8F713ZARCXnvzij9hcfbFd3GsK6pobrBbiw3E7Xe2D",
      "file_hash": "QmSqv9uDQj8rspo2dcJBC7C6Dr5Y2SspTU993p5KJV48D9",
      "last_modify_time": "2020-09-09T05:43:20.169276Z"
    },
    {
      "contract_id": "b45dda7d-207b-4a61-a894-bedac49cf6e1,7009f1e5-4f3f-4aa3-a498-f192fcbf9cf4",
      "host_id": "16Uiu2HAmRqJFB4U5JQsavLXfZrLCdbpC6nrxiGguXZALjfpkAwYA",
      "renter_id": "16Uiu2HAkz5shmDGPhWibau4vSF6bwZoLh73TRiSoRLuJQxkF2oMK",
      "status": 8,
      "start_time": "2020-08-08T09:32:21.325516Z",
      "end_time": "2021-08-08T09:32:21.325516Z",
      "next_escrow_time": "9999-12-31T23:59:59Z",
      "compensation_paid": 0,
      "compensation_outstanding": 196095,
      "unit_price": 250000,
      "shard_size": 2307459,
      "shard_hash": "QmSUmiGYBG4hW2CoXki2dzA4Qpp9i4Vx8537x1M7uhATQK",
      "file_hash": "QmfZqoZrQajxw6Knq5Vx4yaagtouh2X9EAfVEHXtc5SEpp",
      "last_modify_time": "2020-09-09T05:43:20.169276Z"
    },
    {
      "contract_id": "97563ece-69ae-4856-a6da-5b0543d6553b,7202f2ff-996f-459e-a25b-30a32457cba1",
      "host_id": "16Uiu2HAmRqJFB4U5JQsavLXfZrLCdbpC6nrxiGguXZALjfpkAwYA",
      "renter_id": "16Uiu2HAkz5shmDGPhWibau4vSF6bwZoLh73TRiSoRLuJQxkF2oMK",
      "status": 8,
      "start_time": "2020-08-08T10:11:16.039369Z",
      "end_time": "2021-08-08T10:11:16.039369Z",
      "next_escrow_time": "9999-12-31T23:59:59Z",
      "compensation_paid": 0,
      "compensation_outstanding": 4465547,
      "unit_price": 250000,
      "shard_size": 52546248,
      "shard_hash": "QmRppqWpFYBwZ1t92psjvU38FvkkrBUKocYPaqoX26e59A",
      "file_hash": "QmdSKsurv7C3dCfRSu4P4TzXHCe2EizbnoNRCU9vV4wdR2",
      "last_modify_time": "2020-09-09T05:43:20.169276Z"
    },
    {
      "contract_id": "b24e163c-8813-47b4-9707-a67445f96597,425cdd33-5b0d-4780-bdcb-dbec4ee27c0d",
      "host_id": "16Uiu2HAmRqJFB4U5JQsavLXfZrLCdbpC6nrxiGguXZALjfpkAwYA",
      "renter_id": "16Uiu2HAkz5shmDGPhWibau4vSF6bwZoLh73TRiSoRLuJQxkF2oMK",
      "status": 8,
      "start_time": "2020-08-08T10:46:02.819574Z",
      "end_time": "2021-08-08T10:46:02.819574Z",
      "next_escrow_time": "9999-12-31T23:59:59Z",
      "compensation_paid": 0,
      "compensation_outstanding": 4465547,
      "unit_price": 250000,
      "shard_size": 52546248,
      "shard_hash": "QmXsKiY7xC3xny1V6XAXsqZfdJhQFtGdqj9u1im1s53fhR",
      "file_hash": "QmdTvGXhMVRYpGmgWsWWdxrjbXM1xidh34rPYuBxiZWQCW",
      "last_modify_time": "2020-09-09T05:43:20.169276Z"
    },
    {
      "contract_id": "f5589030-e05a-46df-b083-a52c5738d44d,77dac248-099e-4fd2-88a6-379f2bcfed52",
      "host_id": "16Uiu2HAmRqJFB4U5JQsavLXfZrLCdbpC6nrxiGguXZALjfpkAwYA",
      "renter_id": "16Uiu2HAkz5shmDGPhWibau4vSF6bwZoLh73TRiSoRLuJQxkF2oMK",
      "status": 8,
      "start_time": "2020-08-08T11:00:49.617277Z",
      "end_time": "2021-08-08T11:00:49.617277Z",
      "next_escrow_time": "9999-12-31T23:59:59Z",
      "compensation_paid": 0,
      "compensation_outstanding": 4465547,
      "unit_price": 250000,
      "shard_size": 52546248,
      "shard_hash": "QmRVBdwqPFsZztzjP7Scah1Vx9dRrF9uKhCEvVsDhMA3G9",
      "file_hash": "QmYKty8VtcPjJ3xaqeXaMSL8gXv4XqAK8BLQd41tCchqRp",
      "last_modify_time": "2020-09-09T05:43:20.169276Z"
    },
    {
      "contract_id": "a3570189-0827-45a6-a7f9-dc07eaddb4cd,47203325-501d-4eed-b9c7-f3fb951770a4",
      "host_id": "16Uiu2HAmRqJFB4U5JQsavLXfZrLCdbpC6nrxiGguXZALjfpkAwYA",
      "renter_id": "16Uiu2HAkz5shmDGPhWibau4vSF6bwZoLh73TRiSoRLuJQxkF2oMK",
      "status": 8,
      "start_time": "2020-08-08T11:27:09.778563Z",
      "end_time": "2021-08-08T11:27:09.778563Z",
      "next_escrow_time": "9999-12-31T23:59:59Z",
      "compensation_paid": 0,
      "compensation_outstanding": 4465547,
      "unit_price": 250000,
      "shard_size": 52546248,
      "shard_hash": "QmcYSaHc113pyZrTV4GoHHW5AYpBtuJkXFpphTFWmTjMw2",
      "file_hash": "QmUETzmwRgdVzihSF2H9kQMS6ZjutbQRt4Bz7ajScra8oH",
      "last_modify_time": "2020-09-09T05:43:20.169276Z"
    },
    {
      "contract_id": "802ff4b6-bb7e-406a-bf1a-723f18e87a30,179b5cab-7dac-402b-b534-4392c3bf6a90",
      "host_id": "16Uiu2HAmRqJFB4U5JQsavLXfZrLCdbpC6nrxiGguXZALjfpkAwYA",
      "renter_id": "16Uiu2HAkz5shmDGPhWibau4vSF6bwZoLh73TRiSoRLuJQxkF2oMK",
      "status": 8,
      "start_time": "2020-08-08T12:08:40.306959Z",
      "end_time": "2021-08-08T12:08:40.306959Z",
      "next_escrow_time": "9999-12-31T23:59:59Z",
      "compensation_paid": 0,
      "compensation_outstanding": 4465547,
      "unit_price": 250000,
      "shard_size": 52546248,
      "shard_hash": "QmQ4gZyc5NQkJ61qr48sMigJigJhcVgr9NfrafqEGFPYDQ",
      "file_hash": "QmRRy3HiFfoDeSFSMdMCgWaQ7PmEUKvYdbenyhsLNSDRj9",
      "last_modify_time": "2020-09-09T05:43:20.169276Z"
    },
    {
      "contract_id": "48300d5b-186f-4c62-ae0a-44a54c5a454a,9f6bd6c4-4ae7-48f6-b684-c8892a8aad03",
      "host_id": "16Uiu2HAmRqJFB4U5JQsavLXfZrLCdbpC6nrxiGguXZALjfpkAwYA",
      "renter_id": "16Uiu2HAkz5shmDGPhWibau4vSF6bwZoLh73TRiSoRLuJQxkF2oMK",
      "status": 8,
      "start_time": "2020-08-08T13:38:08.545637Z",
      "end_time": "2021-08-08T13:38:08.545637Z",
      "next_escrow_time": "9999-12-31T23:59:59Z",
      "compensation_paid": 0,
      "compensation_outstanding": 4465547,
      "unit_price": 250000,
      "shard_size": 52546248,
      "shard_hash": "QmWzuid6wEF2rrP8d5Wymm87w7RmbZmuZ1kfAXNsgKFqhk",
      "file_hash": "QmPkRTGgRgKYqpxf2g2W7a3DB6CwGiGXK4jW86jfNwh1Ns",
      "last_modify_time": "2020-09-09T05:43:20.169276Z"
    },
    {
      "contract_id": "3006cf6b-1cb2-4800-9903-e38ec6d3750d,a3ae26d4-2cd5-4f98-a28a-d7866bfafd44",
      "host_id": "16Uiu2HAmRqJFB4U5JQsavLXfZrLCdbpC6nrxiGguXZALjfpkAwYA",
      "renter_id": "16Uiu2HAkz5shmDGPhWibau4vSF6bwZoLh73TRiSoRLuJQxkF2oMK",
      "status": 8,
      "start_time": "2020-08-08T14:03:22.109999Z",
      "end_time": "2021-08-08T14:03:22.109999Z",
      "next_escrow_time": "9999-12-31T23:59:59Z",
      "compensation_paid": 0,
      "compensation_outstanding": 4465547,
      "unit_price": 250000,
      "shard_size": 52546248,
      "shard_hash": "QmQK1zzsVQYS3ktcX3Mw4DeW1jF7fSK5JZTkmYwuZ5q1pW",
      "file_hash": "QmYkeMeWo4Gz2b2nZ9VH121yVkDsTiXp181bAEZCeWx4oT",
      "last_modify_time": "2020-09-09T05:43:20.169276Z"
    },
    {
      "contract_id": "f05465b2-e204-4bd5-b0ec-e935c58487e7,c9d9a44d-b7d7-4a4b-8ecd-0b1dafa19319",
      "host_id": "16Uiu2HAmRqJFB4U5JQsavLXfZrLCdbpC6nrxiGguXZALjfpkAwYA",
      "renter_id": "16Uiu2HAkz5shmDGPhWibau4vSF6bwZoLh73TRiSoRLuJQxkF2oMK",
      "status": 8,
      "start_time": "2020-08-08T14:40:23.341962Z",
      "end_time": "2021-08-08T14:40:23.341962Z",
      "next_escrow_time": "9999-12-31T23:59:59Z",
      "compensation_paid": 0,
      "compensation_outstanding": 4465547,
      "unit_price": 250000,
      "shard_size": 52546248,
      "shard_hash": "QmfRbfFDctmnJL92CRxoH5cxoV8KXKseVQcLGqytXbbSQX",
      "file_hash": "QmYBadwdM57iMUDYtR1Fd53rz9SwVyA4cQwvG4hVe2vPtg",
      "last_modify_time": "2020-09-09T05:43:20.169276Z"
    },
    {
      "contract_id": "4cb252a5-0ebd-4b5b-8417-585432c444e0,5e777876-007f-4c1c-aa67-c3812882d21b",
      "host_id": "16Uiu2HAmRqJFB4U5JQsavLXfZrLCdbpC6nrxiGguXZALjfpkAwYA",
      "renter_id": "16Uiu2HAkyXPo3XG93EjqmiKQum7QxhimrxEEvRTsygsA1y4Sh743",
      "status": 8,
      "start_time": "2020-08-08T14:44:55.815956Z",
      "end_time": "2021-08-08T14:44:55.815956Z",
      "next_escrow_time": "9999-12-31T23:59:59Z",
      "compensation_paid": 0,
      "compensation_outstanding": 4456631,
      "unit_price": 250000,
      "shard_size": 52441328,
      "shard_hash": "QmYtTgsVQXdaDHoQJw3b3HV9yzBbgzntjyYCFSXfob6WCc",
      "file_hash": "QmQLUd5H3vCGYwMeLKj9KquSpfc8Nyh4FaSMvD7CuynpBr",
      "last_modify_time": "2020-09-09T05:43:20.169276Z"
    }
  ]
}

**Comment by geoffsnyder** [comment]
I have not been seeing anything coming in from that either. Nodes are all showing different dates. And airdrops from the daily 25m have seems to have stopped also, even though scoring qualifies and storage is growing. I'm about to start shutting nodes down.

**Comment by taiyangc** [comment]
Date issue will be fixed in the next release (in fact, it's already fixed on master).

**Comment by taiyangc** [comment]
Please check your wallet page to see if you already received payments, we understand the dates have bugs, but payments will be nonetheless made to your wallet.

**Comment by geoffsnyder** [comment]
I've received payments to the wallets in question before, yes.

**Comment by pavansantani** [comment]
> Please check your wallet page to see if you already received payments, we understand the dates have bugs, but payments will be nonetheless made to your wallet.

ATTACHED PIC DID NOT RECEIVE PAYMENT

![sid eby side](https://user-images.githubusercontent.com/58158473/92870101-24663e80-f421-11ea-9cf6-5b20dc0b2b1f.png)

**Comment by taiyangc** [comment]
@pavansantani ok, we are investigating, your payment will not be lost

**Comment by pavansantani** [comment]
> @pavansantani ok, we are investigating, your payment will not be lost

THANKS

NODE ID 2  16Uiu2HAkzRqkkqU6EMR24DLiU79WDnEvxLNNWMsg1hNEUbYdf1E3

BEFORE SEP 11
![2](https://user-images.githubusercontent.com/58158473/92989060-c56efb00-f4ee-11ea-8d21-2674ac7f2f11.png)



AFTER SEP 11

![issue 12](https://user-images.githubusercontent.com/58158473/92989080-e6cfe700-f4ee-11ea-9468-f0007b73230d.png)

**Comment by pavansantani** [comment]
> > @pavansantani ok, we are investigating, your payment will not be lost
> 
> THANKS
> 
> NODE ID 2 16Uiu2HAkzRqkkqU6EMR24DLiU79WDnEvxLNNWMsg1hNEUbYdf1E3
> 
> BEFORE SEP 11
> ![2](https://user-images.githubusercontent.com/58158473/92989060-c56efb00-f4ee-11ea-8d21-2674ac7f2f11.png)
> 
> AFTER SEP 11
> 
> ![issue 12](https://user-images.githubusercontent.com/58158473/92989080-e6cfe700-f4ee-11ea-9468-f0007b73230d.png)

UPdate to 2nd NODE ID  35 BTT payment has arrived but rest still pending &  NODE ID 1 still same no payment

**Comment by taiyangc** [comment]
Payments will slowly be arriving. Thanks.
