### ISSUE TITLE
Netscan of Local/Private IP Addresses

### ISSUE THREAD

**Issue by Cimplex** [TRON-US/go-btfs#693]
#### Version information:
go-btfs version: 1.3.6-b1722d1
Repo version: 9
System version: amd64/linux
Golang version: go1.14.6

#### Description:

I got told by my data center that the machine I was testing on performed a netscan (its against their ToS). I looked at the [log they provided](https://github.com/TRON-US/go-btfs/files/5193109/netscan_attempt.txt) me and it looks like they are all LAN address (192.168.*, 169.254.*, 10.0.*, etc). I am now wondering why this is happening and if I have it configured incorrectly?

[netscan_attempt.txt](https://github.com/TRON-US/go-btfs/files/5193109/netscan_attempt.txt) (same as above)

**Comment by andreas-barthel** [comment]
It's not a Bug, it's a feature ;-)
But you can disable netscan on private nets in config.
Just replace the null value of Swarm.AddrFilters with the following:
   ```
 [
    "/ip4/10.0.0.0/ipcidr/8",
    "/ip4/100.64.0.0/ipcidr/10",
    "/ip4/169.254.0.0/ipcidr/16",
    "/ip4/172.16.0.0/ipcidr/12",
    "/ip4/192.0.0.0/ipcidr/24",
    "/ip4/192.0.0.0/ipcidr/29",
    "/ip4/192.0.0.8/ipcidr/32",
    "/ip4/192.0.0.170/ipcidr/32",
    "/ip4/192.0.0.171/ipcidr/32",
    "/ip4/192.0.2.0/ipcidr/24",
    "/ip4/192.168.0.0/ipcidr/16",
    "/ip4/198.18.0.0/ipcidr/15",
    "/ip4/198.51.100.0/ipcidr/24",
    "/ip4/203.0.113.0/ipcidr/24",
    "/ip4/240.0.0.0/ipcidr/4"
]
```

You can read about it [here](https://github.com/ipfs/go-ipfs/blob/master/docs/config.md#swarmaddrfilters)

**Comment by Cimplex** [comment]
Fully expected this was the case. Thank you for the private IP tables!! Just what i needed.
