### ISSUE TITLE
btfs init command not working while installing btfs in ubuntu 

### ISSUE THREAD

**Issue by quailworthy13** [TRON-US/go-btfs#695]
while installing BTFS on Ubuntu 
the command btfs init returns  Find Metada Failed : no such file or directory
![image](https://user-images.githubusercontent.com/71061868/92689910-91180500-f35d-11ea-94df-40c3450347e6.png)

**Comment by taiyangc** [comment]
Can you remove your `~/.btfs` and try again?

**Comment by taiyangc** [comment]
Please re-open if this is still an issue.
