### ISSUE TITLE
Uptime Percentage Keeps Decreasing

### ISSUE THREAD

**Issue by wabeckman86** [TRON-US/go-btfs#697]
My uptime keeps decreasing by 1% per day.  Monday, September 7th, I was at 96%.  As of today, Saturday, September 12th, I am at 91%  I have checked my computer's network adapter logs, router logs, and modem logs.  None of them show any downtime or disruption in internet connectivity.  I was getting the HTTP 504 gateway timeout error (spin:66) from the GuardClient all week.  It stopped yesterday, and my percentage still decreased.  Also, my Host Score kept jumping back and forth from 8.2 to 7.4.  When the Spin:66 errors quit yesterday, it quit jumping and stayed at 7.2.  Is this a communication error with TRON servers messing all these stats up, or is something wrong on my end?  Is anyone else seeing any of these problems?  Thanks!

**Comment by taiyangc** [comment]
The uptime calculation period is over the last 30 days. So if you had some downtimes a while back, it will be factored into the calculation.

If you check `btfs storage stats info` it will show you which scores have been fluctuating.

**Comment by wabeckman86** [comment]
I have not had any downtime, except for when it couldn't sync stats and kept giving me the spin/hosts.go:66 errors.  I read in the other post about uptime lowering that the issue had nothing to do with it, though.  It still gradually drops.  my uptime score has even dropped more since the first post over the weekend as well as my host score.  I have no downtime or connections issues and cannot figure out what is going on.

**Comment by wabeckman86** [comment]
These two storage stats below were ran a few hours apart from each other today with absolutely no downtime or interruption in internet connection in between the two.

{"host_stats":"online":true,"uptime":0.8993,"score":6.6,"storage_used":581691431,"storage_cap":249000000000,"storage_disk_total":250041331712,"storage_disk_available":249214480384,"uptime_score":6,"age_score":5,"version_score":10,"speed_score":20,"uptime_weight":0.6,"age_weight":0.2,"version_weight":0.1,"speed_weight":0.1},"renter_stats":{"reserved":""}}

{"host_stats":"online":true,"uptime":0.8987,"score":6.6,"storage_used":581390691,"storage_cap":249000000000,"storage_disk_total":250041331712,"storage_disk_available":249214779392,"uptime_score":6,"age_score":5,"version_score":10,"speed_score":20,"uptime_weight":0.6,"age_weight":0.2,"version_weight":0.1,"speed_weight":0.1},"renter_stats":{"reserved":""}}

The uptime score has still lowered.  If it is calculated on an average span of 30 days, it should be steadily going up, right?  I do not know what is happening and desperately need help.

**Comment by wabeckman86** [comment]
Whatever you all did worked!  I got a bunch of connection refused errors and a fatal "failed to connect to database" error.  Shortly thereafter my uptime and host score went back up to where it should be.  Thank you!
