### ISSUE TITLE
uptime lower every day

### ISSUE THREAD

**Issue by boringw** [TRON-US/go-btfs#698]
2020-09-10T14:46:45.685Z        ERROR    spin    spin/hosts.go:63        Failed to sync HOST contracts: GuardClient: rpc error: code = Unavailable desc = Gateway Timeout: HTTP status code 504; transport: received the unexpected content-type "text/html"
2020-09-10T15:46:45.731Z        ERROR    spin    spin/hosts.go:63        Failed to sync HOST contracts: GuardClient: rpc error: code = Unavailable desc = Gateway Timeout: HTTP status code 504; transport: received the unexpected content-type "text/html"
2020-09-10T16:46:45.678Z        ERROR    spin    spin/hosts.go:63        Failed to sync HOST contracts: GuardClient: rpc error: code = Unavailable desc = Gateway Timeout: HTTP status code 504; transport: received the unexpected content-type "text/html"
2020-09-10T17:46:45.668Z        ERROR    spin    spin/hosts.go:63        Failed to sync HOST contracts: GuardClient: rpc error: code = Unavailable desc = Gateway Timeout: HTTP status code 504; transport: received the unexpected content-type "text/html"
2020-09-10T20:40:45.684Z        ERROR    spin    spin/hosts.go:63        Failed to sync HOST contracts: GuardClient: rpc error: code = Unknown desc = dial tcp 10.32.232.144:5432: connect: connection refused
BTFS is up-to-date.
BTFS is up-to-date.
BTFS is up-to-date.

my some nodes uptime decrease，but  dont know why,  i use aws so network is ok, and i write a monitor scipt to restart btfs when crash,   why uptime decrease.........today i cant get airdrop because uptime score just 7.....
please help me very thy

**Comment by boringw** [comment]
and my new node cant valid over 24 hours， is this some err hub server？

**Comment by boringw** [comment]
now i check my all nodes, about erery node just uptime decrease..........

**Comment by taiyangc** [comment]
The timeout errors have been addressed a few days ago. As for uptime, it takes into 30 days into account so it may not be something you recently did, but probably a while back.

**Comment by boringw** [comment]
I can be sure that my nodes have not crash， not one node， about every one decrease....don't make sense
and new nodes cant valid over 48 hours, some new node over 72 hours....

**Comment by andreas-barthel** [comment]
Same here with a few of my nodes (And a lot of another nodes in the whole community)
I think thats are some consequences of the Hub-Error.
Because the Hub was not available for a few days our nodes was "official" offline -.-
Now the Hub is reachable again and it determines that our node was "offline" and descreases our uptime and uptime_score
Maybe @taiyangc can confirm or decline this assumption?

**Comment by boringw** [comment]
> The timeout errors have been addressed a few days ago. As for uptime, it takes into 30 days into account so it may not be something you recently did, but probably a while back.

if like @andreas-barthel say,  its hard to back to before for yang nodes because "offline" time proportion is too high

**Comment by taiyangc** [comment]
@andreas-barthel No the hub issue has nothing to do with your uptime. Hub score calculation is a completely separate service that is not affected by those issues.

**Comment by taiyangc** [comment]
The number of high scores (9.5+) has not decreased, so this does not show that this is a widespread issue, but possibly an issue with a certain range of machines.

**Comment by taiyangc** [comment]
Looks like a new issue related to #701 . Both are being fixed.

**Comment by boringw** [comment]
> Looks like a new issue related to #701 . Both are being fixed.

state is ok,very thanks your help, 祝你身体健康，谢谢。

**Comment by boringw** [comment]
hello，brother. same problem happend, uptime decrease every day.....
this is some nodes id
16Uiu2HAm6rzvtBhsatmL8dGg5vd7VKBF4LWk4KpSg7EujUZucmDq
16Uiu2HAmJmEHuef3Vrmtk8XfrRpze8TzuYB8uM4yjoNWrUjE7oFn
16Uiu2HAmKV6Z4d1Tc3Qk8yrUXzFxbXS7tfGTzKWquvd3bvGAsNwX
16Uiu2HAmKfFNTWusXPiymQeurHbTcEMUzWitzxxwpbsDpGLYN7M1

yesterday points > 8.5 can get 460btt , 10869 nodes
today  can get 763 btt,  6553 nodes
may some miner has same problem

**Comment by boringw** [comment]
@taiyangc 
兄弟处理下吧，好多机器又变成只有6.6分了，和上次一毛一样，新开的机器一天多了也没有分

**Comment by taiyangc** [comment]
Yes we are aware and trying to find a fix.

**Comment by giovannicammarata** [comment]
Same issue for me. The node appears online (it is reachable) but the uptime is continuously going down every day.

**Comment by doristeo** [comment]
I have the same problem. Uptime goes down, rating goes down. Node is online all the time.

**Comment by Cimplex** [comment]
I'm having the same issue went from 67% three days ago to 57% today.

**Comment by taiyangc** [comment]
Please check again. Scores should have been refreshed now.

**Comment by gicamm** [comment]
Yes, It seems to be work now. Thank you
