### ISSUE TITLE
How long will it take the validation?

### ISSUE THREAD

**Issue by Reivaj747** [TRON-US/go-btfs#701]
I started the hosting service a few days ago. 
The message "Validating" was kept for **about 63 hours** every time I refreshed the screen. There was a power failure and I had to restart the daemon (I just executed **btfs daemon, no more commands**). It is still in validation (**24 hours**) but now the message:

2020-09-14T15:05:07.353-0400    ←[31mERROR←[0m  spin    spin/hosts.go:63        Failed to sync host stats: Failed to query stats from Hub service: HubQueryClient: Cannot query to get stats! 

appears in CMD every 30 minutes

Is this normal? (the same error message during 24 hours) 
How much longer should I wait for the validation to finish?

**I apologize if this is not the place to ask this question, if you tell me where I should ask it I will gladly take it there**

**Comment by taiyangc** [comment]
We are investigating reports of non-validation.

**Comment by taiyangc** [comment]
It should start to work now, could you let us know if you are validated?

**Comment by felixishim** [comment]
apologies same issue here Failed to sync host stats: Failed to query stats from Hub service: HubQueryClient: Cannot query to get stats!
 ←[31mERROR←[0m spin spin/hosts.go:63 Failed to sync host stats: Failed to query stats from Hub service: HubQueryClient: Cannot query to get stats!
node id: 16Uiu2HAm8Cy2oEB4w5Dq6KQYdnS9qsnJ5eYozbZLX18nktYf6QLx

**Comment by Reivaj747** [comment]
Finally the validation ended last night. Problem solved!
