### ISSUE TITLE
Add support to check TRC-10 and TRC-20 token balance

### ISSUE THREAD

**Issue by simbadMarino** [TRON-US/go-btfs#704]
- Motivation: Have the possibility to check tokens balance for "premium" users and provide special features in a future dApp 

- How the future should work: I suggest to modify current btfs wallet balance cmd to something like: "btfs wallet balance -arg='trx|trc10|trc20' -id='tokenID'

**Comment by taiyangc** [comment]
Interesting suggestion. Do you mind explaining use cases for "premium" users? We will prioritize feature requests based on urgency and also popularity.

**Comment by simbadMarino** [comment]
Hello Eric, sure, 
I’m building a mobile application similar to Dropbox or Box ( this use case is very popular among the community and decided to give it a try).
While developing I realized I will need some funding to speed up the development and take the app to the next level. So I’d like to bring to the crypto community the idea of acquiring a  VIP trc-10 token VERY LIMITED IN SUPPLY which will give them lifetime X amount of GB of storage (e.g. say 500Gb) 

So then comes the need of having a simple way to check for this token availability and somehow later on rent the space for the specific BTFS node. Of course some security measures need to be done to reduce an abuse scenario.

Maybe using tronweb could be a solution but that will complicate the code a little bit more, so, if we already have wallet support directly as btfs commands why not adding this feature hehe.

Best regards!

Sent from myMail for iOS


Friday, 18 September 2020 3:15 -0500 from notifications@github.com  <notifications@github.com>:

**Comment by inkpool** [comment]
> Hello Eric, sure,  I’m building a mobile application similar to Dropbox or Box ( this use case is very popular among the community and decided to give it a try). While developing I realized I will need some funding to speed up the development and take the app to the next level. So I’d like to bring to the crypto community the idea of acquiring a  VIP trc-10 token VERY LIMITED IN SUPPLY which will give them lifetime X amount of GB of storage (e.g. say 500Gb)  So then comes the need of having a simple way to check for this token availability and somehow later on rent the space for the specific BTFS node. Of course some security measures need to be done to reduce an abuse scenario. Maybe using tronweb could be a solution but that will complicate the code a little bit more, so, if we already have wallet support directly as btfs commands why not adding this feature hehe. Best regards! Sent from myMail for iOS Friday, 18 September 2020 3:15 -0500 from notifications@github.com <notifications@github.com>:
> […](#)
> Interesting suggestion. Do you mind explaining use cases for "premium" users? We will prioritize feature requests based on urgency and also popularity. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub , or unsubscribe .

Hi.

It is a really great idea to have a dropbox like APP based on BTFS. But I have calculated with current BTT price, it is not a deal right? BTFS is more expensive.

**Comment by simbadMarino** [comment]
Dropbox plus is $10 dollars(2TB per month) and currently you need 7680 BTT to rent 1TB on btfs which will be aprox $4 dollars per 2TB , so a 50% discount plus having your files completely encrypted and distributed across several nodes seems like a no brainer to me :). Even if it was the same price the security features of btfs are more than enough to think about using it  imo ;)



Sent from myMail for iOS


Monday, 21 September 2020 19:23 -0500 from notifications@github.com  <notifications@github.com>:

**Comment by pavansantani** [comment]
> Dropbox plus is $10 dollars(2TB per month) and currently you need 7680 BTT to rent 1TB on btfs which will be aprox $4 dollars per 2TB , so a 50% discount plus having your files completely encrypted and distributed across several nodes seems like a no brainer to me :). Even if it was the same price the security features of btfs are more than enough to think about using it  imo ;) Sent from myMail for iOS Monday, 21 September 2020 19:23 -0500 from notifications@github.com <notifications@github.com>:
> […](#)
> >Hello Eric, sure,  I’m building a mobile application similar to Dropbox or Box ( this use case is very popular among the community and decided to give it a try). While developing I realized I will need some funding to speed up the development and take the app to the next level. So I’d like to bring to the crypto community the idea of acquiring a  VIP trc-10 token VERY LIMITED IN SUPPLY which will give them lifetime X amount of GB of storage (e.g. say 500Gb)  So then comes the need of having a simple way to check for this token availability and somehow later on rent the space for the specific BTFS node. Of course some security measures need to be done to reduce an abuse scenario. Maybe using tronweb could be a solution but that will complicate the code a little bit more, so, if we already have wallet support directly as btfs commands why not adding this feature hehe. Best regards! Sent from myMail for iOS Friday, 18 September 2020 3:15 -0500 from ***@***.*** ***@***.*** : >… >Interesting suggestion. Do you mind explaining use cases for "premium" users? We will prioritize feature requests based on urgency and also popularity. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub , or unsubscribe . Hi. It is a really great idea to have a dropbox like APP based on BTFS. But I have calculated with current BTT price, it is not a deal right? BTFS is more expensive. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub , or unsubscribe .

I agree 

i also agree that it need more development and people like you can bring this type of integration to this platform will be a fabulous addition.

any sort of help u require let me know if i can do anything required.

u know where to contact


Sent from browser for WINDOWS..

**Comment by simbadMarino** [comment]
Thanks a lot Pavan, I will contact in the future for a nice logo for the app hehe, maybe you can start thinking about something and some ideas on the graphical side of the UI?



Sent from myMail for iOS


Friday, 25 September 2020 2:20 -0500 from notifications@github.com  <notifications@github.com>:

**Comment by pavansantani** [comment]
> Thanks a lot Pavan, I will contact in the future for a nice logo for the app hehe, maybe you can start thinking about something and some ideas on the graphical side of the UI? 

For sure,

But remember i will need stake in ur UNICORN STARTUP
