### ISSUE TITLE
some old nodes crashed long ago，but as long as dont restart, score will not change and can get > 8.5 airdrop

### ISSUE THREAD

**Issue by boringw** [TRON-US/go-btfs#706]
我英文不太好，意思就是很久以前分高的机器，因为某些原因崩溃了，我一直没发现，但是只要不去重启连hub server，分就不会降，每天还是可以得到大于 8.5 分的空投，前面就感觉有这个问题忘了提

**Comment by taiyangc** [comment]
Those are local scores. They are not counted as "network scores".
