### ISSUE TITLE
 Error: can not perform the operation before password is set

### ISSUE THREAD

**Issue by doristeo** [TRON-US/go-btfs#711]
Commands "btfs wallet transfer <to> <amonth>" returns "Error: can not perform the operation before password is set".

"btfs wallet init", 
"btfs wallet password XXXXX" - returns {"Message":"Password set."}
"btfs wallet validate_password" returns "Error: can not perform the operation before password is set".
"btfs wallet balance" returns correct data.

Node was not initialized from web-gui, I'm use only CLI.

**Comment by laipogo** [comment]
Could you try `btfs config UI.Wallet.Initialized --bool true`.
