### ISSUE TITLE
Builds for Raspberry Pi

### ISSUE THREAD

**Issue by ElDavoo** [TRON-US/go-btfs#713]
Why don't you provide officially binaries for ARM devices? It should be as simple as compiling normally with GOOS and GOARCH set.

**Comment by andreas-barthel** [comment]
Hi.
If i saw correctly then with next version ARM binaries are coming.
I think @taiyangc can confirm or decline that.

**Comment by taiyangc** [comment]
v1.4.0 builds will support ARM devices.

**Comment by ElDavoo** [comment]
oh ok nice
