### ISSUE TITLE
PUBLIC IP NOT VISIBLE IN WEBUI

### ISSUE THREAD

**Issue by pavansantani** [TRON-US/go-btfs#719]
PUBLIC IP NOT VISIBLE IN WEBUI

After restarting daemon stays there for few hrs..  then not staying there..

webui does not contains pub ip

**Comment by taiyangc** [comment]
We have not been actively supporting web ui, as our main focus is host ui, feel free to raise issues in https://github.com/TRON-US/btfs-webui/issues
