### ISSUE TITLE
i provider 4t ,but get 2btt  now  why?

### ISSUE THREAD

**Issue by yuzhongrong** [TRON-US/go-btfs#720]
![image](https://user-images.githubusercontent.com/7382234/94366883-7b506100-010d-11eb-91d1-e448e4004631.png)

**Comment by yuzhongrong** [comment]
It's too short of btt ？Who dares to provide storage space？

**Comment by yuzhongrong** [comment]
why next payment date is 2020.10.23?  should be next date

**Comment by yuzhongrong** [comment]
It's too short of btt  It's too short of btt  It's too short of btt  i will stop the provider store

**Comment by taiyangc** [comment]
The amount of BTT depends on who uploads to your host, if you happen to be in a region without much traffic, you will see fewer payouts.
