### ISSUE TITLE
Add French translation

### ISSUE THREAD

**Issue by Yakonche** [TRON-US/go-btfs#722]
Hi, would it be possible to add a French translation for the web interface?
I can even do it if you tell me which files need to be edited, although the easiest way would be to add the ability to translate via crowdin.com

**Comment by taiyangc** [comment]
Will sync with the team on what's needed.

**Comment by Sophia-yu-kk** [comment]
The system will automatically close the longer issues, if your problem is still not solved, you can join the discord group chat: https://discord.gg/2CwVmm5X
