### ISSUE TITLE
How to manually upgrade btfs from 1.36 to 1.4? 

### ISSUE THREAD

**Issue by boringw** [TRON-US/go-btfs#728]
i  replace btfs and confg.yaml ,but report this err :
Error: proto: wrong wireType = 5 for field StorageUsed

**Comment by taiyangc** [comment]
You can manually download the binary from https://github.com/TRON-US/go-btfs/releases/tag/btfs-v1.4.0 and replace your existing, then restart daemon.

**Comment by taiyangc** [comment]
Updated the release notes on this error: https://github.com/TRON-US/go-btfs/releases/tag/btfs-v1.4.0

**Comment by boringw** [comment]
thank you
