### ISSUE TITLE
Wallet recovery does not recover a wallet

### ISSUE THREAD

**Issue by vir2alexport** [TRON-US/go-btfs#730]
Hi.

I tried to recover my wallet with 12 words mnemonic password and it gives me a new address everytime I try to recover with 100BTT. Is there a way to recover my funds from mining competition or it is lost forever?

Thanks!

**Comment by taiyangc** [comment]
As long as you don't lose your mnemonic your funds are safe. We will check the recovery process to see if there is anything wrong.

**Comment by vir2alexport** [comment]
I took a mnemonic from my BTT wallet I had beforehand. I did recovery once when I installed a btfs node and I didn't really checked if the public address is the same. Now I try the same mnemonic and I get new address everytime. I have a log from my host, don't know if helps...
[btfs-host.log](https://github.com/TRON-US/go-btfs/files/5294788/btfs-host.log)

**Comment by vir2alexport** [comment]
I checked on the block explorer and I do see my funds, it is so strange! Сheck this out, if I enter my mnemonic pass with first capital letter for each word then I get my previous wallet TCfNzxs8hwZBAQhqbibrebJczDbz5h2eo7

My other wallet, that I got by some error, since I entered same mnemonic but without capital letters TEm6DJuFCVz9pCVDdedF6xGYbvaK4B63wq

Is there a list of valid mnemonic words or what I just described is ok?

**Comment by taiyangc** [comment]
Got it, we will perform some testing before getting back to you.

**Comment by vir2alexport** [comment]
UPDATE: I installed a TronLink browser extention to see if I can recover my wallets and suddenly I have 5 public keys for one mnemonic password only one of which TEm6DJuFCVz9pCVDdedF6xGYbvaK4B63wq is actually exists on the Tron block explorer. The other 4 are not found. Now, public address, where you can see my BTT funds is TCfNzxs8hwZBAQhqbibrebJczDbz5h2eo7 and of the same ID(contract), but **is not recoverable**, at least for now.

**Comment by taiyangc** [comment]
If you can use mnemonics (low letters) to re-import and get back `TCfNzxs8hwZBAQhqbibrebJczDbz5h2eo7` your funds are not lost. You can use `btfs wallet transfer` to move the funds out to other places.

We have found the issue and are working on a fix, FYI.

**Comment by vir2alexport** [comment]
No, I can't. Again, my mnemonic password can't recover my wallet TCfNzxs8hwZBAQhqbibrebJczDbz5h2eo7. The recovery is not working.

**Comment by taiyangc** [comment]
We will fix the issue first and reimburse how much you lost. For now, please do not import any more "new" wallets.

**Comment by vir2alexport** [comment]
Thats great but you can't recover my nerve cells. Frustration was to big for me, so I removed my node. I mean, no one ever checked if recovery is working on a testnet, are you kidding me?

**Comment by taiyangc** [comment]
This has been fixed in v1.4.1.

**Comment by vir2alexport** [comment]
Just to let you know, they never reimbursed my loss. Still no access to mined 50k BTT. Mnemonic phrase recovered all 5 wallets and only one of them has 100 BTT.
