### ISSUE TITLE
BTFS won't autoupdate

### ISSUE THREAD

**Issue by WhiteHeadbanger** [TRON-US/go-btfs#731]
Peer ID: 16Uiu2HAm8tXAVzp5BGwVBfLs3gBT2LkVd6DRfgNocnaNBrVZ3Vx7

![unknown](https://user-images.githubusercontent.com/12226415/94495847-34c03c80-01c9-11eb-896a-c0de5dd880ab.png)

**Comment by pavansantani** [comment]
same here 1.3.6 version

16Uiu2HAmRqJFB4U5JQsavLXfZrLCdbpC6nrxiGguXZALjfpkAwYA

**Comment by taiyangc** [comment]
Please check these things in order:
1. `btfs config show | grep AutoUpdate`
2. cat $(dirname `which btfs`)/config.yaml
3. cat $(dirname `which btfs`)/update.log
4. Any logs from btfs daemon that mentions auto update being disabled or failed in any step

**Comment by WhiteHeadbanger** [comment]
> Please check these things in order:
> 
> 1. `btfs config show | grep AutoUpdate`
> 2. cat `` $(dirname `which btfs`)/config.yaml ``
> 3. cat `` $(dirname `which btfs`)/update.log ``
> 4. Any logs from `btfs daemon` that mentions auto update being disabled or failed in any step

Hi, I'm on Windows, for 1 to 3 steps what are the commands that I should query?

**Comment by taiyangc** [comment]
@WhiteHeadbanger Try posting the contents of

1. `C:\Users\<username>\.btfs\config`, open the file and post the line containing `AutoUpdate`
2. `%APPDATA%/Bittorrent/btfs/config.yaml` post the contents
3. `%APPDATA%/Bittorrent/btfs/update.log` post the contents

**Comment by taiyangc** [comment]
If this still happens, please post the logs under `update.log`, thanks.
