### ISSUE TITLE
runtime error: slice bounds out of range [:30] with capacity 2

### ISSUE THREAD

**Issue by henrybug** [TRON-US/go-btfs#736]
Just to let you know..
It happened only to one of our nodes.
After daemon started again, everything works fine till now.

go-btfs version: 1.4.0-68f24b1
Repo version: 10
System version: amd64/windows
Golang version: go1.14.9

BTFS is up-to-date.
panic: runtime error: slice bounds out of range [:30] with capacity 2

goroutine 956433 [running]:
github.com/libp2p/go-libp2p-pnet.(*pskConn).Read(0xc006b06fc0, 0xc0020f9208, 0x2, 0x2, 0xc005745b30, 0x40b02c, 0x19c44a0)
        pkg/mod/github.com/libp2p/go-libp2p-pnet@v0.2.0/psk_conn.go:43 +0x249
io.ReadAtLeast(0x2ad32738, 0xc006b06fc0, 0xc0020f9208, 0x2, 0x2, 0x2, 0x2030013, 0x262f778, 0x30009)
        /usr/local/go/src/io/io.go:310 +0x8e
io.ReadFull(...)
        /usr/local/go/src/io/io.go:329
github.com/libp2p/go-libp2p-noise.(*secureSession).readNextInsecureMsgLen(0xc0020f9180, 0x2030008, 0x2030013, 0x5)
        pkg/mod/github.com/libp2p/go-libp2p-noise@v0.1.1/rw.go:134 +0x93
github.com/libp2p/go-libp2p-noise.(*secureSession).Read(0xc0020f9180, 0xc00496b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        pkg/mod/github.com/libp2p/go-libp2p-noise@v0.1.1/rw.go:53 +0x1fa
bufio.(*Reader).fill(0xc004eb7020)
        /usr/local/go/src/bufio/bufio.go:100 +0x10a
bufio.(*Reader).ReadByte(0xc004eb7020, 0xc000049768, 0xc000047000, 0xc005745d00)
        /usr/local/go/src/bufio/bufio.go:252 +0x40
encoding/binary.ReadUvarint(0x285c6e0, 0xc004eb7020, 0x457d52, 0xc0025ba508, 0xc004f2b601)
        /usr/local/go/src/encoding/binary/varint.go:110 +0x8c
github.com/libp2p/go-mplex.(*Multiplex).readNextHeader(0xc004e11780, 0xc0025ba501, 0xc0018a4680, 0x1, 0xc005745da8)
        pkg/mod/github.com/libp2p/go-mplex@v0.1.2/multiplex.go:548 +0x46
github.com/libp2p/go-mplex.(*Multiplex).handleIncoming(0xc004e11780)
        pkg/mod/github.com/libp2p/go-mplex@v0.1.2/multiplex.go:367 +0xe7
created by github.com/libp2p/go-mplex.NewMultiplex
        pkg/mod/github.com/libp2p/go-mplex@v0.1.2/multiplex.go:105 +0x204

**Comment by Crypto72** [comment]
Hello,

I got the same sort of error. My host details:

PEER ID	16Uiu2HAm37e4LJ5RCtcVDrESGMS1oLU1B73eTEV2qLLY23HxbtSh
VERSION	go-btfs v1.4.0
Advanced
GATEWAY	http://127.0.0.1:8080
API	
/ip4/127.0.0.1/tcp/5001
ADDRESSES	
/ip4/127.0.0.1/tcp/1234/p2p/16Uiu2HAm37e4LJ5RCtcVDrESGMS1oLU1B73eTEV2qLLY23HxbtSh
/ip4/192.168.0.17/tcp/1234/p2p/16Uiu2HAm37e4LJ5RCtcVDrESGMS1oLU1B73eTEV2qLLY23HxbtSh
/ip4/90.201.122.128/tcp/16262/p2p/16Uiu2HAm37e4LJ5RCtcVDrESGMS1oLU1B73eTEV2qLLY23HxbtSh
/ip6/::1/tcp/1234/p2p/16Uiu2HAm37e4LJ5RCtcVDrESGMS1oLU1B73eTEV2qLLY23HxbtSh
PUBLIC KEY	CAISIQJyPt4xusD9TGSkUKndYuauOBcuER6qx9jW5meWtnhlvg==

This is the error output:

Swarm listening on /ip4/169.254.40.171/tcp/1234
Swarm listening on /ip4/169.254.70.232/tcp/1234
Swarm listening on /ip4/192.168.0.17/tcp/1234
Swarm listening on /ip6/::1/tcp/1234
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/1234
Swarm announcing /ip4/192.168.0.17/tcp/1234
Swarm announcing /ip4/90.201.122.128/tcp/1234
Swarm announcing /ip6/::1/tcp/1234
API server listening on /ip4/127.0.0.1/tcp/5001
WebUI: http://127.0.0.1:5001/webui
HostUI: http://127.0.0.1:5001/hostui
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Remote API server listening on /ip4/127.0.0.1/tcp/5101
Daemon is ready
Storage host info will be synced at [SCORE] mode
Current host stats will be synced
Current host settings will be synced
BTFS is up-to-date.
panic: runtime error: slice bounds out of range [:583] with capacity 2

goroutine 12201831 [running]:
github.com/libp2p/go-libp2p-pnet.(*pskConn).Read(0xc00afbea80, 0xc00aaa5488, 0x2, 0x2, 0xc012a97b30, 0x40b02c, 0x19c44a0
)
        pkg/mod/github.com/libp2p/go-libp2p-pnet@v0.2.0/psk_conn.go:43 +0x249
io.ReadAtLeast(0x2c542040, 0xc00afbea80, 0xc00aaa5488, 0x2, 0x2, 0x2, 0x1000, 0x0, 0xc012a97ba8)
        /usr/local/go/src/io/io.go:310 +0x8e
io.ReadFull(...)
        /usr/local/go/src/io/io.go:329
github.com/libp2p/go-libp2p-noise.(*secureSession).readNextInsecureMsgLen(0xc00aaa5400, 0x0, 0xc012a97be8, 0x467b7e)
        pkg/mod/github.com/libp2p/go-libp2p-noise@v0.1.1/rw.go:134 +0x93
github.com/libp2p/go-libp2p-noise.(*secureSession).Read(0xc00aaa5400, 0xc007427000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        pkg/mod/github.com/libp2p/go-libp2p-noise@v0.1.1/rw.go:53 +0x1fa
bufio.(*Reader).fill(0xc00e94d4a0)
        /usr/local/go/src/bufio/bufio.go:100 +0x10a
bufio.(*Reader).ReadByte(0xc00e94d4a0, 0xc004409140, 0x0, 0x262fba8)
        /usr/local/go/src/bufio/bufio.go:252 +0x40
encoding/binary.ReadUvarint(0x285c6e0, 0xc00e94d4a0, 0x457d52, 0xc003af2738, 0x1)
        /usr/local/go/src/encoding/binary/varint.go:110 +0x8c
github.com/libp2p/go-mplex.(*Multiplex).readNextHeader(0xc001b47380, 0xc012a97d01, 0x4, 0x0, 0x0)
        pkg/mod/github.com/libp2p/go-mplex@v0.1.2/multiplex.go:548 +0x46
github.com/libp2p/go-mplex.(*Multiplex).handleIncoming(0xc001b47380)
        pkg/mod/github.com/libp2p/go-mplex@v0.1.2/multiplex.go:367 +0xe7
created by github.com/libp2p/go-mplex.NewMultiplex
        pkg/mod/github.com/libp2p/go-mplex@v0.1.2/multiplex.go:105 +0x204

When I restart the daemon, everything works fine for a few hours and then the daemon goes into that fatal error.

Hope you can fix it as soon as possible. 

Cheers,
Tony

**Comment by taiyangc** [comment]
Looks like libp2p module panics. We will try to keep them updated in a future release.

**Comment by luksssy** [comment]
The same issue with me. Now more nodes every day crashing with that error 3/4 nodes. Very annoying. Score is falling and falling. I tried also with quick restarting the node every day with batch file but did not help. I am desperatedly waiting for new release.

**Comment by zhenkas** [comment]
My node also crashing every 2-3 days on this, since version 1.4.0 and now in 1.4.1
```
panic: runtime error: slice bounds out of range [:19] with capacity 2

goroutine 232461826 [running]:
github.com/libp2p/go-libp2p-pnet.(*pskConn).Read(0xc0149498c0, 0xc011112448, 0x2, 0x2, 0xc012071b30, 0x40b03c, 0x19e3240)
        pkg/mod/github.com/libp2p/go-libp2p-pnet@v0.2.0/psk_conn.go:43 +0x249
io.ReadAtLeast(0x2d6fd2f0, 0xc0149498c0, 0xc011112448, 0x2, 0x2, 0x2, 0x3004f, 0x0, 0x8)
        /usr/local/go/src/io/io.go:310 +0x8e
io.ReadFull(...)
        /usr/local/go/src/io/io.go:329
github.com/libp2p/go-libp2p-noise.(*secureSession).readNextInsecureMsgLen(0xc0111123c0, 0x3f, 0x203004f, 0x2f328bf0)
        pkg/mod/github.com/libp2p/go-libp2p-noise@v0.1.1/rw.go:134 +0x93
github.com/libp2p/go-libp2p-noise.(*secureSession).Read(0xc0111123c0, 0xc00a337000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        pkg/mod/github.com/libp2p/go-libp2p-noise@v0.1.1/rw.go:53 +0x1fa
bufio.(*Reader).fill(0xc020ab06c0)
        /usr/local/go/src/bufio/bufio.go:100 +0x10a
bufio.(*Reader).ReadByte(0xc020ab06c0, 0xc020ab07e0, 0xc012071de0, 0xc013c90a90)
        /usr/local/go/src/bufio/bufio.go:252 +0x40
encoding/binary.ReadUvarint(0x2ab0b00, 0xc020ab06c0, 0xc013c90b18, 0xc010c39d40, 0xc013c90a90)
        /usr/local/go/src/encoding/binary/varint.go:110 +0x8c
github.com/libp2p/go-mplex.(*Multiplex).readNextHeader(0xc01c87f300, 0xc012071dc0, 0x2, 0x0, 0x0)
        pkg/mod/github.com/libp2p/go-mplex@v0.1.2/multiplex.go:548 +0x46
github.com/libp2p/go-mplex.(*Multiplex).handleIncoming(0xc01c87f300)
        pkg/mod/github.com/libp2p/go-mplex@v0.1.2/multiplex.go:367 +0xe7
created by github.com/libp2p/go-mplex.NewMultiplex
        pkg/mod/github.com/libp2p/go-mplex@v0.1.2/multiplex.go:105 +0x204
```
```
Initializing daemon...
go-btfs version: 1.4.1-488bfb8
Repo version: 10
System version: amd64/windows
Golang version: go1.14.12
```

**Comment by zhenkas** [comment]
That still happens after update to 1.4.2.
Here all the "panic"s I got in last month (note that the capacity is always 2)

```
panic: runtime error: slice bounds out of range [:30] with capacity 2
panic: runtime error: slice bounds out of range [:19] with capacity 2
panic: runtime error: slice bounds out of range [:19] with capacity 2
panic: runtime error: slice bounds out of range [:34] with capacity 2
panic: runtime error: slice bounds out of range [:19] with capacity 2
panic: runtime error: slice bounds out of range [:19] with capacity 2
panic: runtime error: slice bounds out of range [:54] with capacity 2
panic: runtime error: slice bounds out of range [:19] with capacity 2
panic: runtime error: slice bounds out of range [:35] with capacity 2
panic: runtime error: slice bounds out of range [:30] with capacity 2
panic: runtime error: slice bounds out of range [:19] with capacity 2
panic: runtime error: slice bounds out of range [:38] with capacity 2
panic: runtime error: slice bounds out of range [:629] with capacity 2
panic: runtime error: slice bounds out of range [:19] with capacity 2
```
Version info
```
go-btfs version: 1.4.2-396feb8
Repo version: 10
System version: amd64/windows
Golang version: go1.14.12
```

**Comment by taiyangc** [comment]
Can you try `master`? If not we are going to release v1.5.0 later this week which may help with this issue.

**Comment by zhenkas** [comment]
@taiyangc I prefer to wait for official version. 
If you add "Windows" section in "Build from Source" on home page, may be I will be able try that.

**Comment by taiyangc** [comment]
Please upgrade to v1.5.0 and retry. If this issue still exists, please re-open. Thank you.

**Comment by zhenkas** [comment]
Hi, @taiyangc 
Just got same crash on 1.5.0

```
panic: runtime error: slice bounds out of range [:19] with capacity 2

goroutine 6724139 [running]:
github.com/libp2p/go-libp2p-pnet.(*pskConn).Read(0xc0113202c0, 0xc00fd6b168, 0x2, 0x2, 0xc009d8bb30, 0xacc0ac, 0x2267ac0)
        pkg/mod/github.com/libp2p/go-libp2p-pnet@v0.2.0/psk_conn.go:43 +0x24c
io.ReadAtLeast(0x21a64e01f68, 0xc0113202c0, 0xc00fd6b168, 0x2, 0x2, 0x2, 0x1000, 0x0, 0xc009d8bba8)
        /usr/local/go/src/io/io.go:314 +0x8e
io.ReadFull(...)
        /usr/local/go/src/io/io.go:333
github.com/libp2p/go-libp2p-noise.(*secureSession).readNextInsecureMsgLen(0xc00fd6b0e0, 0x0, 0xc009d8bbe8, 0xb2a09e)
        pkg/mod/github.com/libp2p/go-libp2p-noise@v0.1.1/rw.go:134 +0x93
github.com/libp2p/go-libp2p-noise.(*secureSession).Read(0xc00fd6b0e0, 0xc014c9f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        pkg/mod/github.com/libp2p/go-libp2p-noise@v0.1.1/rw.go:53 +0x205
bufio.(*Reader).fill(0xc0051c2e40)
        /usr/local/go/src/bufio/bufio.go:101 +0x10a
bufio.(*Reader).ReadByte(0xc0051c2e40, 0xc01e4ce368, 0xc009d8bde0, 0x1687bd8)
        /usr/local/go/src/bufio/bufio.go:253 +0x45
encoding/binary.ReadUvarint(0x3435d40, 0xc0051c2e40, 0xc009d8bdc4, 0x2, 0x2)
        /usr/local/go/src/encoding/binary/varint.go:110 +0x8d
github.com/libp2p/go-mplex.(*Multiplex).readNextHeader(0xc019cd9080, 0xc009d8bdc0, 0x2, 0x0, 0x0)
        pkg/mod/github.com/libp2p/go-mplex@v0.1.2/multiplex.go:548 +0x46
github.com/libp2p/go-mplex.(*Multiplex).handleIncoming(0xc019cd9080)
        pkg/mod/github.com/libp2p/go-mplex@v0.1.2/multiplex.go:367 +0xef
created by github.com/libp2p/go-mplex.NewMultiplex
        pkg/mod/github.com/libp2p/go-mplex@v0.1.2/multiplex.go:105 +0x212
```

version
```
Initializing daemon...
go-btfs version: 1.5.0-86e6633
Repo version: 10
System version: amd64/windows
Golang version: go1.15.6
```

**Comment by taiyangc** [comment]
Going to link https://github.com/ipfs/go-ipfs/issues/7853 here.

**Comment by Sophia-yu-kk** [comment]
The system will automatically close the longer issues, if your problem is still not solved, you can join the discord group chat: https://discord.gg/2CwVmm5X
