### ISSUE TITLE
Too many files opened

### ISSUE THREAD

**Issue by pavansantani** [TRON-US/go-btfs#741]
![too many](https://user-images.githubusercontent.com/58158473/94987488-6566f400-0584-11eb-884d-9d867a0070e6.png)

**Comment by taiyangc** [comment]
Please increase your system file descriptor ulimit and restart btfs daemon. If it doesn't help, consider increasing IPFS_FD_MAX variable to a larger value (default 8192).

**Comment by pavansantani** [comment]
> Please increase your system file descriptor ulimit and restart btfs daemon. If it doesn't help, consider increasing IPFS_FD_MAX variable to a larger value (default 8192).

HI, thanks for reply

but not a geek here

how to do it???

**Comment by andreas-barthel** [comment]
Hi.
For all with that problem: This maybe can helps: [Link](https://www.cyberciti.biz/faq/linux-increase-the-maximum-number-of-open-files/)

**Comment by pavansantani** [comment]
> Hi.
> For all with that problem: This maybe can helps: [Link](https://www.cyberciti.biz/faq/linux-increase-the-maximum-number-of-open-files/)

THANKS BRO

BUT NAH IT DID NOT WORK

**Comment by pavansantani** [comment]
U HOO ANYTHING FOR ME :)

**Comment by pavansantani** [comment]
![ok doke](https://user-images.githubusercontent.com/58158473/95749822-cf387980-0cb9-11eb-8d8d-bf4aa5c972f2.png)


ANY HELP

i did  ulimit -n 2048 for user

and as root edited the /etc/sysctl.conf  file with addition of 1 line

fs.file-max=2048

**Comment by pavansantani** [comment]
guyz update please  error still persists

**Comment by endofthepain** [comment]
https://medium.com/@muhammadtriwibowo/set-permanently-ulimit-n-open-files-in-ubuntu-4d61064429a many articel on google why u didnt explore ur problem look error is on ulimit

**Comment by pavansantani** [comment]
> https://medium.com/@muhammadtriwibowo/set-permanently-ulimit-n-open-files-in-ubuntu-4d61064429a many articel on google why u didnt explore ur problem look error is on ulimit

Already did that's y here  read the entire post before u sggest

**Comment by endofthepain** [comment]
> > https://medium.com/@muhammadtriwibowo/set-permanently-ulimit-n-open-files-in-ubuntu-4d61064429a many articel on google why u didnt explore ur problem look error is on ulimit
> 
> Already did that's y here read the entire post before u suggest

so if still to many open file go upgrade your hardwares

**Comment by pavansantani** [comment]
> > > https://medium.com/@muhammadtriwibowo/set-permanently-ulimit-n-open-files-in-ubuntu-4d61064429a many articel on google why u didnt explore ur problem look error is on ulimit
> > 
> > 
> > Already did that's y here read the entire post before u suggest
> 
> so if still to many open file go upgrade your hardwares

I5 with 4gb ram running ubuntu  

u still think i need hardware upgrade...

**Comment by endofthepain** [comment]
> > > > https://medium.com/@muhammadtriwibowo/set-permanently-ulimit-n-open-files-in-ubuntu-4d61064429a many articel on google why u didnt explore ur problem look error is on ulimit
> > > 
> > > 
> > > Already did that's y here read the entire post before u suggest
> > 
> > 
> > so if still to many open file go upgrade your hardwares
> 
> I5 with 4gb ram running ubuntu
> 
> u still think i need hardware upgrade...

i did ulimit -n 2048 for user

and as root edited the /etc/sysctl.conf file with addition of 1 line

fs.file-max=2048 

u just upgrade to 2048 ? so if yes your ulimit number still lowest

**Comment by pavansantani** [comment]
> > > > > https://medium.com/@muhammadtriwibowo/set-permanently-ulimit-n-open-files-in-ubuntu-4d61064429a many articel on google why u didnt explore ur problem look error is on ulimit
> > > > 
> > > > 
> > > > Already did that's y here read the entire post before u suggest
> > > 
> > > 
> > > so if still to many open file go upgrade your hardwares
> > 
> > 
> > I5 with 4gb ram running ubuntu
> > u still think i need hardware upgrade...
> 
> i did ulimit -n 2048 for user
> 
> and as root edited the /etc/sysctl.conf file with addition of 1 line
> 
> fs.file-max=2048
> 
> u just upgrade to 2048 ? so if yes your ulimit number still lowest

i did it to 65535

but yet nothing happens & as soon as i lock out of OS   it just's go back to 1024

**Comment by endofthepain** [comment]
than your configuration is not permanently

**Comment by pavansantani** [comment]
> than your configuration is not permanently

yep

**Comment by endofthepain** [comment]
if you follow this link your config will be permanently

**Comment by pavansantani** [comment]
> if you follow this link your config will be permanently

no link bro  ......

**Comment by endofthepain** [comment]
> > if you follow this link your config will be permanently
> 
> no link bro ......

https://medium.com/@muhammadtriwibowo/set-permanently-ulimit-n-open-files-in-ubuntu-4d61064429a

> > if you follow this link your config will be permanently
> 
> no link bro ......
> 
> if u r talking about medium link
> 
> nah it did not worked...

are u follow this step about editing "/etc/security/limits.conf" ? if not work is problem from your configuration because i am use this setup have not a problem for my few nodes

**Comment by pavansantani** [comment]
> > > if you follow this link your config will be permanently
> > 
> > 
> > no link bro ......
> 
> https://medium.com/@muhammadtriwibowo/set-permanently-ulimit-n-open-files-in-ubuntu-4d61064429a
> 
> > > if you follow this link your config will be permanently
> > 
> > 
> > no link bro ......
> > if u r talking about medium link
> > nah it did not worked...
> 
> are u follow this step about editing "/etc/security/limits.conf" ? if not work is problem from your configuration because i am use this setup have not a problem for my few nodes

yep did it but nothing happened...

**Comment by endofthepain** [comment]
so its problem on your config actualy

**Comment by pavansantani** [comment]
> so its problem on your config actualy

how to trace where is the problem????

**Comment by andreas-barthel** [comment]
I had the same problem on all of my nodes. (Since BTFS version 1.4.0). On lesser version there was never a problem with this. I assume that someone has build in a bug in BTFS. Something like forgot to close a file descriptor or similar.
The solutions like `ulimit` and` fs.file-max=2048` in `/etc/sysctl.conf` doesn't work for me. My nodes are started as a systemd service. Appending `LimitNOFILE=2048` in the `[Service]` section solved this issue for me on all of my nodes expect the one that is hosted at contabo.de. The contabo.de node must me permanently restarted (the whole machine, not only the BTFS service) to not running in this situation.

**Comment by pavansantani** [comment]
> I had the same problem on all of my nodes. (Since BTFS version 1.4.0). On lesser version there was never a problem with this. I assume that someone has build in a bug in BTFS. Something like forgot to close a file descriptor or similar.
> The solutions like `ulimit` and` fs.file-max=2048` in `/etc/sysctl.conf` doesn't work for me. My nodes are started as a systemd service. Appending `LimitNOFILE=2048` in the `[Service]` section solved this issue for me on all of my nodes expect the one that is hosted at contabo.de. The contabo.de node must me permanently restarted (the whole machine, not only the BTFS service) to not running in this situation.

YEP I think soo too i just switched back to Debian  and no problems like that....  previously using UBUNTU

**Comment by ticpu** [comment]
I'm on Ubuntu Groovy and this problem doesn't appear to be an issue.
 ```
systemctl status btfs.service
● btfs.service - BTFS distributed filesystem
     Loaded: loaded (/etc/systemd/system/btfs.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2021-03-06 00:49:56 EST; 13h ago
   Main PID: 1996773 (btfs-linux-amd6)
         IP: 2.9G in, 3.5G out
         IO: 728.0K read, 1.7G written
      Tasks: 20 (limit: 38766)
     Memory: 1.1G (high: 2.0G max: 3.0G)
        CPU: 54min 37.117s
     CGroup: /coins.slice/btfs.service
             └─1996773 /bin/btfs-linux-amd64 daemon

$ cat /proc/1996773/limits 
Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            8388608              unlimited            bytes     
Max core file size        0                    unlimited            bytes     
Max resident set          unlimited            unlimited            bytes     
Max processes             129222               129222               processes 
Max open files            8192                 8192                 files     
Max locked memory         65536                65536                bytes     
Max address space         unlimited            unlimited            bytes     
Max file locks            unlimited            unlimited            locks     
Max pending signals       129222               129222               signals   
Max msgqueue size         819200               819200               bytes     
Max nice priority         0                    0                    
Max realtime priority     0                    0                    
Max realtime timeout      unlimited            unlimited            us        
```

I can see from the main PID, 1996773, that Max open files is set at 8192.

But as stated in the comment just before, setting LimitNOFILE=2048 (or 8192 since it seems to be the default) should fix it.  This is a system specific configuration, not a BTFS issue by itself.

Otherwise, also check your /etc/systemd/system.conf file to be sure there isn't another LimitNOFILE set for the services.

As a bonus, here is my btfs.service file with some added security.

```
[Unit]
Description=BTFS distributed filesystem
RequiresMountsFor=/mnt/btfs
After=network-online.target

[Service]
Restart=on-failure
RestartSec=60
Environment=BTFS_PATH=/data
ExecStart=/bin/btfs-linux-amd64 daemon
NoNewPrivileges=true
RestrictSUIDSGID=true
CapabilityBoundingSet=
RootDirectory=/mnt/btfs
IPAccounting=true
BindReadOnlyPaths=/etc/resolv.conf:/etc/resolv.conf
BindReadOnlyPaths=/etc/ssl/certs:/etc/ssl/certs
BindReadOnlyPaths=/usr/lib:/usr/lib
BindReadOnlyPaths=/lib:/lib
BindReadOnlyPaths=/lib64:/lib64
BindReadOnlyPaths=/proc:/proc
WorkingDirectory=/data
RestrictAddressFamilies=AF_INET AF_INET6 AF_NETLINK
RestrictNamespaces=true
SystemCallArchitectures=native
SystemCallFilter=@system-service
SystemCallFilter=~@chown @setuid setns @privileged
User=btfs-daemon
Group=btfs-daemon
PrivateDevices=true
MemoryMax=3G
MemoryHigh=2G
TemporaryFileSystem=/run:mode=1777
DevicePolicy=closed
ProtectKernelModules=true
ProtectKernelLogs=true
ProtectClock=true
ProtectHostname=true
RemoveIPC=true
RestrictRealtime=true
RestrictSUIDSGID=true
MemoryDenyWriteExecute=true
LockPersonality=true
KillMode=process
KillSignal=SIGHUP

[Install]
WantedBy=multi-user.target
```

/mnt/btfs is a directory with a /bin and /data folder owned by btfs-daemon, /bin contains btfs-linux-amd64.

**Comment by pavansantani** [comment]
> I'm on Ubuntu Groovy and this problem doesn't appear to be an issue.
> 
> ```
> systemctl status btfs.service
> ● btfs.service - BTFS distributed filesystem
>     Loaded: loaded (/etc/systemd/system/btfs.service; enabled; vendor preset: enabled)
>     Active: active (running) since Sat 2021-03-06 00:49:56 EST; 13h ago
>   Main PID: 1996773 (btfs-linux-amd6)
>         IP: 2.9G in, 3.5G out
>         IO: 728.0K read, 1.7G written
>      Tasks: 20 (limit: 38766)
>     Memory: 1.1G (high: 2.0G max: 3.0G)
>        CPU: 54min 37.117s
>     CGroup: /coins.slice/btfs.service
>             └─1996773 /bin/btfs-linux-amd64 daemon
> 
> $ egrep "Limit|open files" /proc/1996773/limits
> Limit                     Soft Limit           Hard Limit           Units     
> Max open files            8192                 8192                 files     
> ```
> 
> I can see from the main PID, 1996773, that Max open files is set at 8192.
> 
> But as stated in the comment just before, setting LimitNOFILE=2048 (or 8192 since it seems to be the default) should fix it. This is a system specific configuration, not a BTFS issue by itself.
> 
> Otherwise, also check your /etc/systemd/system.conf file to be sure there isn't another LimitNOFILE set for the services.
> 
> As a bonus, here is my btfs.service file with some added security
> 
> ```ini
> [Unit]
> Description=BTFS distributed filesystem
> RequiresMountsFor=/mnt/btfs
> After=network-online.target
> 
> [Service]
> Restart=on-failure
> RestartSec=60
> Environment=BTFS_PATH=/data
> ExecStart=/bin/btfs-linux-amd64 daemon
> NoNewPrivileges=true
> RestrictSUIDSGID=true
> CapabilityBoundingSet=
> RootDirectory=/mnt/btfs
> IPAccounting=true
> BindReadOnlyPaths=/etc/resolv.conf:/etc/resolv.conf
> BindReadOnlyPaths=/etc/ssl/certs:/etc/ssl/certs
> BindReadOnlyPaths=/usr/lib:/usr/lib
> BindReadOnlyPaths=/lib:/lib
> BindReadOnlyPaths=/lib64:/lib64
> BindReadOnlyPaths=/proc:/proc
> WorkingDirectory=/data
> RestrictAddressFamilies=AF_INET AF_INET6 AF_NETLINK
> RestrictNamespaces=true
> SystemCallArchitectures=native
> SystemCallFilter=@system-service
> SystemCallFilter=~@chown @setuid setns @privileged
> User=btfs-daemon
> Group=btfs-daemon
> PrivateDevices=true
> MemoryMax=3G
> MemoryHigh=2G
> TemporaryFileSystem=/run:mode=1777
> DevicePolicy=closed
> ProtectKernelModules=true
> ProtectKernelLogs=true
> ProtectClock=true
> ProtectHostname=true
> RemoveIPC=true
> RestrictRealtime=true
> RestrictSUIDSGID=true
> MemoryDenyWriteExecute=true
> LockPersonality=true
> KillMode=process
> KillSignal=SIGHUP
> 
> [Install]
> WantedBy=multi-user.target
> ```
> 
> /mnt/btfs is a directory with a /bin and /data folder owned by btfs-daemon, /bin contains btfs-linux-amd64.

THANKS BUDDY. WILL KEEP IN MIND IF I USE UBUNTU FOR SAME NEXT TIME.

:+1:
