### ISSUE TITLE
Storage Rental - Big size files failed to be added

### ISSUE THREAD

**Issue by simbadMarino** [TRON-US/go-btfs#742]
Preconditions:
BTFS (v1.4.0) installed and Environment PATH configured

Steps:
1. Prepare a file (size = 500GB) to be added
2. Open a terminal and Initialize BTFS daemon by "btfs daemon"
3. Open a different terminal window and use btfs add --chunker=reed-solomon <file-name>

Expected result:
3. Qm hash is returned

Actual result:
3. btfs daemon crashes and error is returned

**Comment by taiyangc** [comment]
This is a known issue. Currently bigger files cannot be added because normal machines do not have large enough memory to hold the encodings.

**Comment by simbadMarino** [comment]
In order to do so we must increase minimum requirements for nodes? Is there a workaround? 



Sent from myMail for iOS


Saturday, 3 October 2020 20:36 -0500 from notifications@github.com  <notifications@github.com>:

**Comment by taiyangc** [comment]
Currently - no. Try breaking down to multiple files may help.

**Comment by boringw** [comment]
> Currently - no. Try breaking down to multiple files may help.

thank you
I have a question，“25,000,000 BTT is distributed to 6,075 Host user nodes over 100 MiB according to the storage ratio ”
What means about “storage ratio” ,upload storage？ share data to other nodes? share to bittorrent?
please tell me ,thank you

**Comment by Kowai** [comment]
this issue is a huge drawback.

**Comment by Kowai** [comment]
I have the following error trying to upload 50Go with a HD having 100 Go free.

btfs add -r --chunker=reed-solomon /myfolderof50Go  
Error: write tcp 127.0.0.1:55144->127.0.0.1:5001: write: broken pipe 

... I guess I won't use btfs before they optimize this..

**Comment by Sophia-yu-kk** [comment]
The system will automatically close the longer issues, if your problem is still not solved, you can join the discord group chat: https://discord.gg/2CwVmm5X
