### ISSUE TITLE
BTFS AND Tron for owned blockchain

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [TRON-US/go-btfs#743]
Hi,
is it possible to use BTFS and Tron protocols to create my own multiple blockchains in a public, private or hybrid mode?
thanks

**Comment by geoffsnyder** [comment]
> Hi,
> is it possible to use BTFS and Tron protocols to create my own multiple blockchains in a public, private or hybrid mode?
> thanks

Yes. There are several tools currently available: https://github.com/tronprotocol

**Comment by taiyangc** [comment]
Yes it's possible. However, this is more of a https://github.com/tronprotocol/java-tron question.
