### ISSUE TITLE
It's too hard to dig a coin

### ISSUE THREAD

**Issue by yuzhongrong** [TRON-US/go-btfs#745]
![image](https://user-images.githubusercontent.com/7382234/95155348-874fb900-07c6-11eb-86eb-7e91ef5fd1a7.png)

I have synced for 2 months, and now I don’t have a coin.

**Comment by yuzhongrong** [comment]
How to mine coins at this speed

**Comment by yuzhongrong** [comment]
The market price of this coin is only 2 li, and it is worthless. Why is mining so slow?

**Comment by yuzhongrong** [comment]
Is it my procedure or your mechanism?

**Comment by yuzhongrong** [comment]
It’s too slow. I don’t want to provide a host. It’s meaningless

**Comment by taiyangc** [comment]
Sorry to hear. Due to network differences, you may not receive any contract, it's normal for many nodes. As we scale up more traffic and partner with more clients, the coverage will increase.

**Comment by yuzhongrong** [comment]
Is this a network problem？

**Comment by yuzhongrong** [comment]
What is the network requirement

**Comment by ROBERT-MCDOWELL** [comment]
usual decentralized issues, the guys who have the most powerful servers, the fastest network will win.
and we go back to the same game of banks.

**Comment by yuzhongrong** [comment]
What is storage mining?

**Comment by digbicks** [comment]
So on average how long does it take to get a contract? Running 2 nodes on my end for over a month now and no contracts .... but as expected I get some rewards from time to time which is again good but at the same time very discouraging. I guess what @yuzhongrong is saying has a good point. What are the minimum network requirements? I guess something has to do with upload/download speed? What is the recommendation for the network speed?

**Comment by Nanook994** [comment]
3 weeks now = 22 days (4 nodes, 4 stand alone pc)
Score 5.3 and uptime 67.  Inetnet from ISP = 1gb/s. Score and uptime looked good before I created wallet to all node. Thank you in advance. 

Node-ID - dell 390: 16Uiu2HAm1WzzWA2xJSjVTZ9hJV5E13kKW1A5AW8is9ZP8dWTBH5x
Node-ID-dell 790: 16Uiu2HAmG5p2QkkLZkVbhVmVUHwMRqYz7AZ5prMCPHsJX8s92hov
Node-ID-Fujitsu 700:  16Uiu2HAkwnc9NVEnyfrVJrzYZjCr4QFC85WdrbeGW4fVWDUN1prH
Node-ID: HP G7 MicroServr: 16Uiu2HAm3ruqUrckfdtPb1FtmNdbdoyKfzDc4YGAG48BNSFXLj9k

**Comment by digbicks** [comment]
@Nanook994 I am not sure I understand why you are sharing this information in this particular thread but may be you could elaborate on the matter?

**Comment by Nanook994** [comment]
I need help for my 4 nodes that have running for a month but score/uptime still very low. Had sent a request for help for weeks from each node to btfs support team but still the same issues.

**Comment by gicamm** [comment]
> Sorry to hear. Due to network differences, you may not receive any contract, it's normal for many nodes. As we scale up more traffic and partner with more clients, the coverage will increase.

Nodes with 10/10 should have the same probability to get contracts, but this is not happening. Some few nodes are getting lots of contracts, and some others are getting nothing.  Why does it happen?

**Comment by taiyangc** [comment]
Closing this topic. Please go to our discord https://discord.gg/PQWfzWS to discuss these mechanisms. We are taking feedback and making big reward incentive changes this month.
