### ISSUE TITLE
Storage rental - Directory upload failed to be retrevied on btfs gateway

### ISSUE THREAD

**Issue by simbadMarino** [TRON-US/go-btfs#747]
Preconditions:
BTFS (v1.4.0) installed and Environment PATH configured

Steps:

1. Prepare a directory to be upload with several files on it.
2. Open a terminal and Initialize BTFS daemon by  sending `$btfs daemon`
3. Open a different terminal window and send `$ btfs add --chunker=reed-solomon -r '<dir-name>'`
4. Send `$btfs storage upload  <QmHash>`
5. Once succesfully uploaded open the dir using btfs gateway (gateway.btfs.io/btfs/<QmHash)

Expected result:
5. The complete directory is shown in the btfs gateway and all files are accessible 

Actual result:
5. Only the first file on the directory can be retrieved, the rest of the files return the following error message: _internalWebError: /btfs/<QmHash>/<filename> not found from the directory object: context canceled_

Comments:  Please check this QmHash as reference: https://gateway.btfs.io/btfs/QmXQb6HkxE8iN7y4diS9Th9u1E6tvHW67sxH3N8bSk7rRx/testFile2.txt

**Comment by taiyangc** [comment]
How big are the files?

It is possible because currently the gateway isn't fully distributed, if the folder isn't duplicated at close geolocation to the gateway it may timeout retrieving it. Could also be a bandwidth limitation.

**Comment by simbadMarino** [comment]
I have made tests with different sizes and all get the same result, this specific issue was tested with simple txt files (no more than 50kb).

In theory if I do a “btfs get <QmHash> “ in a different btfs node I will get the whole dir right? I will try doing that to check if it’s a gateway problem...



Sent from myMail for iOS


Wednesday, 7 October 2020 12:00 -0500 from notifications@github.com  <notifications@github.com>:

**Comment by simbadMarino** [comment]
@taiyangc I noticed after a while now the available file is the second one (testfile2.txt in this example) and not the first. Not sure if this gives you a hint on what’s happening...

**Comment by taiyangc** [comment]
This is being actively looked into as we see more timeouts on gateway retrievals.

**Comment by taiyangc** [comment]
Can you retry this? We've made improvements on BTFS gateway since then.

**Comment by simbadMarino** [comment]
Will re try after work today and let you know my results, thanks!



Sent from myMail for iOS


Thursday, 25 February 2021 18:35 -0600 from notifications@github.com  <notifications@github.com>:

**Comment by simbadMarino** [comment]
Hello @taiyangc , UI seems better now however I'm still getting this issue:
![image](https://user-images.githubusercontent.com/11146636/109401711-cc12f280-7915-11eb-9c79-b5c071d31bad.png)

Please note that there is a problem with the gateway certificate as well:

![image](https://user-images.githubusercontent.com/11146636/109401742-fd8bbe00-7915-11eb-827a-b3e4a6350eb3.png)

**Comment by taiyangc** [comment]
Gateway has a self signed cert, which is normal under Chrome/Safari. Not sure why firefox is more strict.

The "no link" error will be fixed in an upcoming release.

**Comment by simbadMarino** [comment]
Great!, will wait for the release, btw I tested the `btfs get QmHash` for the directory and it worked flawlessly! :)

**Comment by taiyangc** [comment]
@simbadMarino Does v1.5.1 fix this for you?

**Comment by simbadMarino** [comment]
Hello @taiyangc , I tried twice without positive results: you can check this QmHash: https://gateway.btfs.io/btfs/QmWWN92gBSFBF5Ubg736RmQADCDEsEHMspJZs3gVm2PV99
gateway page is now blank, not sure is only happening on my end. Could you please check?
![image](https://user-images.githubusercontent.com/11146636/111414246-41681c80-86a5-11eb-9df1-0d7416f7f67d.png)

**Comment by lynk-V** [comment]
I tried to open the gateway, i got a 503 error "temporarily unavailable".

**Comment by Sophia-yu-kk** [comment]
The system will automatically close the longer issues, if your problem is still not solved, you can join the discord group chat: https://discord.gg/2CwVmm5X

**Comment by simbadMarino** [comment]
Hello btfs team, I noticed you closed this issue, I'm glad to notify I tested again and its working properly now :). Thank you for solving it!
