### ISSUE TITLE
Storage Rental - 'btfs storage contracts' shows nothing

### ISSUE THREAD

**Issue by nyanpass519** [TRON-US/go-btfs#748]
Hi,

After uploading, I could not see any contracts using btfs cli. How can I find contract information?

0. BTFS v1.4.0 Installed
1. deposit some BTT
    $ btfs wallet deposit 100000000
2. added file
    $ btfs add --chunker=reed-solomon fileOfLessThan100KB
    added Qm.... fileOfLessThan100KB
3. uploaded files
    $ btfs storage upload Qm....
    {"ID":"....-....-....-....-...."}
4. checked upload status and seemed OK
    $ btfs storage upload status ....-....-....-....-.... | jq
    {
      "Status": "complete",
      "Message": "File storage successful!",
      ....
    }
5. checked balance and some BTT reduced
    $ btfs wallet balance
    {"BtfsWalletBalance":99998290,"BttWalletBalance":....}
6. checked contracts but no contract information shown
    $ btfs storage contracts list renter
    {"contracts":[]}
    $ btfs storage contracts stat renter
    {"active_contract_num":0,"compensation_paid":0,"compensation_outstanding":0,"first_contract_start":"0001-01-01T00:00:00Z","last_contract_end":"0001-01-01T00:00:00Z","role":1}

Thank you,

**Comment by boringw** [comment]
try：btfs storage contracts sync renter

**Comment by taiyangc** [comment]
Sorry the renter contracts sync is currently unsupported. Will add it in a near future release.

**Comment by nyanpass519** [comment]
I knew that contracts sync for renter is not implemented so far, and I am guessing it is not syncing problem because almost a week has passed since I uploaded.
Is there any alternative ways to see contracts?

**Comment by taiyangc** [comment]
Should be fixed in v1.5.0. Please open a new issue if this is still a problem.
