### ISSUE TITLE
panic: qtls.ClientSessionState not compatible with tls.ClientSessionState

### ISSUE THREAD

**Issue by ec1oud** [TRON-US/go-btfs#750]
Other projects are having this same problem with Go 1.15, for example syncthing: https://github.com/syncthing/syncthing/issues/6889 and ipfs-cluster.  The issue is https://github.com/lucas-clemente/quic-go/issues/2614

I think you need to upgrade the version of https://github.com/lucas-clemente/quic-go that you depend on to 0.18.0 or greater.

I'm building btfs from source on FreeBSD.  It builds, but emits this panic at runtime.

**Comment by taiyangc** [comment]
Yes. We are planning to upgrade soon.

**Comment by taiyangc** [comment]
Fixed in v1.5.0.
