### ISSUE TITLE
180gb of 150gb 

### ISSUE THREAD

**Issue by kvasselkvasier** [TRON-US/go-btfs#760]
Btfs is now using 180gb of space but I only allocate 150gb to use. So it doesn't delete old data which doesn't have a contract (the contract bug from the old versions)

**Comment by taiyangc** [comment]
This is fixed in v1.4.1.

**Comment by taiyangc** [comment]
Sorry, closed the wrong issue.

The command to remove stale/old contracts will be released in the future.

**Comment by Sophia-yu-kk** [comment]
The system will automatically close the longer issues, if your problem is still not solved, you can join the discord group chat: https://discord.gg/2CwVmm5X
