### ISSUE TITLE
ZERO contracts with perfect scores after two weeks online.

### ISSUE THREAD

**Issue by Evgen-Viktorovich** [TRON-US/go-btfs#765]
Hi,
More than two weeks my PC is 99% time online (couple hours offline yesterday).
I have Windows 10, 600gb free space, 100mbs speed connection.
My score is jumping from 9+ to 8.4 and online also between 98% and 99% (but i was online for a week and online % was never 100%, i don`t have problems with internet.
This is my second start already and i haven`t seen any contract for all this time.
My Peer id is 	16Uiu2HAmM4gZy1FN4hTVBncUKBftvHS5i4wfF7aE2uVwscEvqfer
Can you please tell me what i`m doing wrong and if it is your side problem then when all this system will work?
Also i bought some of your BTT several month ago with hope that you will fix this problem, but if you will not then it will be better to sold them and never come back. 
I believe in this idea, please make this system possible.
![image](https://user-images.githubusercontent.com/26289449/97555440-30b25500-19e9-11eb-9846-7fdf17ef0081.png)

**Comment by endofthepain** [comment]
the issue because now we have so much host provider and btfs have low renters. another issue is your location based

**Comment by taiyangc** [comment]
Closing this topic. Please go to our discord https://discord.gg/PQWfzWS to discuss these mechanisms. We are taking feedback and making big reward incentive changes this month.
