### ISSUE TITLE
Rewards issue

### ISSUE THREAD

**Issue by turbowebmaster** [TRON-US/go-btfs#767]
Hi, 
I think I may have an issue with my rewards. My peer id is 16Uiu2HAmUPxT4quTb6xo4HjkwbYF4aEKU6EStuVS8Ko4Dt78gGB7, I am online from August 2020 and when I started my node after some days I begun to receive some rewards without contracts. But after some days my rewards stopped to come in. In order to solve the issue I read the btfs documentation and then in order to resolve the issue I decided to add my WAN external IP to the config file as this:
"Announce": [
      "/ip4/MY-WAN-EXTERNAL-IP/tcp/4001"
 ]
After this action suddenly my peer node has got 11 contracts, has stored about 0,5GB of storage and finally I got some rewards for one day. But after one single day payment I didn’t receive any reward anymore! Now the question is: do rewards be paid only randomly? Or do rewards be paid day by day? I suspect my peer node has some issues that don't permit to get the right rewards daily... My peer is installed on Windows 7 x64 with about  5TB of dedicated storage . Node score is 9.4/10 - 10/10 and uptime 97-99%. My bandwidth is 200 Mb in upstream and 1Gb in downstream.
Another note: I think that rewards issues come true when I restart Windows.

Thank you very much for help!

**Comment by Kyliux** [comment]
what makes you think you'll get rewards daily ?
If someone want to host a file for three months, he will pay only once in the beginning, not everyday.

**Comment by turbowebmaster** [comment]
I have let the default price of 7680 btt for each TB/month so I think that, if I won't receive other contracts, I can receive until about 20 GB of files ( 150/(7680/1024)=20 GB ) in my btfs storage within about next 30 days. Is it right or not?

What makes me think about daily rewards? I think about them for probably 2 good reasons:

1) other decentralized storage ecosystems  with crypto currencies pay daily (Siacoin, Storj...)

2) at the top of my hostui interface of btfs there is a message like this “Enter the BTFS -> Daily <- mining to earn 30 million BTT!”; some months ago I have obtained this rewards distribution day by day for several days but suddenly I didn’t receive anymore of those daily rewards. Can I know why? Is that distribution ended?

**Comment by Kowai** [comment]
Hi,
I am trying to understand how to make BTFS work. I am not a reference to answer your questions. Notice that I mostly asked questions.. I do not know if people are supposed to be paid daily or not !

**Comment by govenka** [comment]
like me. 1 week with 3 nodes online and zero BTT. I d'ont understand how it works

**Comment by taiyangc** [comment]
Closing this topic. Please go to our discord https://discord.gg/PQWfzWS to discuss these mechanisms. We are taking feedback and making big reward incentive changes this month.
