### ISSUE TITLE
Storage rental - Files availability problem after some time

### ISSUE THREAD

**Issue by simbadMarino** [TRON-US/go-btfs#768]
I don't have a clear set of test steps, however I noticed most of my last month uploads to btfs we vanished and I'm not able to retrieve the files by the gateway neither by a btfs node. Some QmHash examples:

- QmWAQ56Ev5ANq5yNyKLwPjUS2U9XqmrLmZpBaH9VahgnJb

- QmSNYZXfJwLj1NGWeKxvthrrBJoTZEePSUWLJpAmobKMEZ

- Qmbe2TPM41ryAh3SaydzNyGMUYHcdBeKNwzSwh8hByavtz

- QmXxevfqBZDLtmTqm5xzSjpQcPdve1adNEBwTbDx4AxmxV

I'm getting the following error: `Error: context deadline exceeded`

I used the default way of uploading files like described in the btfs guide: `btfs storage upload <file-hash>` without any time expiration date and still have around 300 BTT, more than enough to keep my files hosted for a while as far as I know...

Thanks!

**Comment by Kyliux** [comment]
Did you see anywhere written that you can upload something without specifying the length you want your files to be hosted ?

**Comment by simbadMarino** [comment]
Hello @Kyliux, not sure how I ended confused... I just added an edit suggestion in the storage rental page as this information you are giving is only available in the cli help. Closing issue
