### ISSUE TITLE
block in host validation

### ISSUE THREAD

**Issue by govenka** [TRON-US/go-btfs#774]
Hello.

I'm in validation, but it seems to be very very long: 
Validating...

Please wait up to 180 minutes while the BTFS network is validating this node. A new node needs to demonstrate its online presence long enough to qualify as a valid storage host. Please refresh every 30 minutes to check for update.

After many hours, seems to be the same.

What happens ?

Thx

**Comment by taiyangc** [comment]
Still blocked? It can be more than 3 hours due to fluctuation, but shouldn't be much longer than that.

**Comment by govenka** [comment]
Hello. No it's ok, it took 9 hours to be unblocked. 
Do you know how many time to obtains earning stats ?

![image](https://user-images.githubusercontent.com/17879561/98460746-4a048f80-21a7-11eb-99e0-f021396a3c87.png)
