### ISSUE TITLE
Can't create a wallet

### ISSUE THREAD

**Issue by govenka** [TRON-US/go-btfs#775]
When i enter my password to create a wallet, i have this error 

![image](https://user-images.githubusercontent.com/17879561/98400468-58965e00-2064-11eb-9f03-436fb0c22a62.png)

I changed 127.0.0.1 to 0.0.0.0

An idea ?

**Comment by laibingo** [comment]
u can try 127.0.0.1:5001

**Comment by govenka** [comment]
which parameter ?
i can't use 127.0.0.1 because it's a vm, then i need to access from my computer
