### ISSUE TITLE
just find a cheating miner

### ISSUE THREAD

**Issue by boringw** [TRON-US/go-btfs#777]
address : TLKkoQeD5gjtbHdn1p6MJiCoW2iixPgL18

![20201108031058](https://user-images.githubusercontent.com/46474646/98449654-2e31c700-2170-11eb-9b52-228ddea28469.png)

see this almost all airdrop just get a similar number, i don know how to say, this miner get 20000000 per day!!!!!!!!!!!!!!!!!!!

why? if somebody see every day airdrop,just can find two minner get almost all airdrop,  it is unfair to normal miner

This was the case long ago, but I can't stand it today

Don't do anything to watch this situation?

**Comment by boringw** [comment]
ridiculous

**Comment by taiyangc** [comment]
Because there is no easy way to track the destination account someone wants to send to, it was not obvious. But we will disallow this from now on.
