### ISSUE TITLE
uptime lower every day 

### ISSUE THREAD

**Issue by boringw** [TRON-US/go-btfs#781]
hey brother, same situation happend like #698

yesterday i add some new nodes to test, it can valid today and hava score，but older nodes uptime lower every day，may have same bug
please fix , thanks

**Comment by boringw** [comment]
My fault

**Comment by boringw** [comment]
yesterday，my amost all nodes uptime  is 0.96xx，6 hours ago is 0.99xx, now is 0.98xx. my node has been running for a long time，It used to be 10 points，but it changes frequently recently and most of the time can get full points, Is there any problem like previous #698 ？

**Comment by endofthepain** [comment]
its normal

**Comment by boringw** [comment]
> its normal
no，this happened several times，this is the third time I reported

**Comment by boringw** [comment]
> its normal

no，this happened several times，this is the third time I reported

**Comment by endofthepain** [comment]
> > its normal
> 
> no，this happened several times，this is the third time I reported

:v we have this issue from many month and this normal because your connection to hub, and this not serious problem actualy u will never get any respons because this question has been answered many" times u can goes to discord and find the answer, i can comment like this because i am followed this project and start own node from august

**Comment by boringw** [comment]
> > > its normal
> > 
> > 
> > no，this happened several times，this is the third time I reported
> 
> :v we have this issue from many month and this normal because your connection to hub, and this not serious problem actualy u will never get any respons because this question has been answered many" times u can goes to discord and find the answer, i can comment like this because i am followed this project and start own node from august

The final result will be less and less points，If not resolved, uptime will lower every, and it is not one node， almost all my nodes，just now i recheck every node uptime lower. this is the same case for the first two times
i guess this need official developer solve

**Comment by ng88** [comment]
Same problem here, I have a new node on a server that is constantly online (it is monitored) but my uptime score stay below 7

**Comment by jgabriel98** [comment]
my uptime stays at 0.

and it is always online

**Comment by seiftie** [comment]
This issue happened again. System was validating and stayed online for 36 hours without losing uptime, yet after it finally validated, it was 60%, now the next morning it's 53%.

Node: 16Uiu2HAkxgqpQ7kTMxCHGdR44Dbt2nhDSuCjU89ropj3A5c5tc1V
