### ISSUE TITLE
Why my potential earning is at zero ?

### ISSUE THREAD

**Issue by govenka** [TRON-US/go-btfs#784]
After  2 weeks and 2.3To of storage available: 

![image](https://user-images.githubusercontent.com/17879561/98826426-f52a7880-2435-11eb-8e00-da6e0d6ef8f7.png)

Best regards
Christophe

**Comment by geoffsnyder** [comment]
Same issue here on all nodes.

**Comment by taiyangc** [comment]
Closing this topic. Please go to our discord https://discord.gg/PQWfzWS to discuss these mechanisms. We are taking feedback and making big reward incentive changes this month.
