### ISSUE TITLE
Uploading process stuck

### ISSUE THREAD

**Issue by nyanpass519** [TRON-US/go-btfs#785]
Hi,

Renting storage several time, I found that one of the uploads was not finished with "btfs storage upload status" command saying "Searching for recommended hosts…". Of all shards in the upload, 29 shards' status was "contract", but only one shard's status was "init". Usually uploading finishes within several minutes in my environment regardless of whether result is success or not, but this upload status has not been changed at least half a day.

My questions are:
1. How can I make this upload proceed?
2. If I should upload the content again, how will the 29 succeeded shards be? (continued or closed?)

What I did is as following:
0. Using btfs 1.4.0
1. "btfs add --chunker=reed-solomon <file>" and got cid
2. "btfs storage upload <cid>" and got session ID
3. "btfs storage upload status <session ID>" and got result
result:
{
  "Status": "init",
  "Message": "Searching for recommended hosts…",
  "AdditionalInfo": "",
  "FileHash": "...(omitted)...",
  "Shards": {
    "...(omitted)...:19": {
      "ContractID": "...(omitted)...",
      "Price": 250000,
      "Host": "",
      "Status": "contract",
      "Message": "",
      "AdditionalInfo": ""
    },
    ...(omitted)...
    "...(omitted)...:0": {
      "ContractID": "...(omitted)...",
      "Price": 250000,
      "Host": "...(omitted)...",
      "Status": "init",
      "Message": "",
      "AdditionalInfo": ""
    },
    ...(omitted)...
}

Thank you,

**Comment by nyanpass519** [comment]
I tried uploading the content again, and it succeeded this time. 
I still don't know why it was stuck with "init" status (I think that should be shown as "error") and whether the 29 shards that had been contracted were closed or still alive.

**Comment by taiyangc** [comment]
Sometimes hosts do not respond correctly due to network or other unforeseen circumstances. We will try to improve the reliability of uploads in the future.

**Comment by taiyangc** [comment]
This is addressed in v1.5.0. Now the upload logic will gracefully retry until all shards are uploaded.
