### ISSUE TITLE
How to estimate cost for uploading on renter side?

### ISSUE THREAD

**Issue by nyanpass519** [TRON-US/go-btfs#790]
Hi,

When I upload file and rent storage, much more balances than I expected is subtracted.

My situation is below:
1. Original file size : 1.17GB
2. File size after reed-solomon with "btfs add --chunker=reed-solomon" commond : 3.64GB
3. Uploading file with "btfs storage upload" command, expecting it cost 910,000 μBTT/Month because "btfs storage upload status" showed price was 250,000 μBTT/GB/Month
4. Actually 25,250,220 μBTT was subtracted from my wallet, and it is about 30 times bigger than "btfs storage upload status" showed above.

I understand 250,000 μBTT/GB/Month is too small and guess some market price is used, but I am confused about that actual cost is different from specified value. I also know default price of "btfs storage upload" command is 250,000 μBTT/GB/Month, so if it costs more than specified price, this command should end with error, but seemly not.

How can I estimate cost before amount subtracted from wallet?

**Comment by taiyangc** [comment]
The storage length is at least 30 days (to prevent renters from temporarily using host storage for short length), so it is roughly 750k uBTT * 30 = (roughly) 22.5M uBTT.

I think the discrepancy came from your knowledge of `250,000 μBTT/GB/Month` but it's actually `250,000 μBTT/GB/Day`:

`-p, --price                int64  - Max price per GiB per day of storage in µBTT (=0.000001BTT).`

**Comment by nyanpass519** [comment]
Oh, I misunderstood... Thank you for pointing out my mistake.
