### ISSUE TITLE
“next_escrow_time” value error

### ISSUE THREAD

**Issue by boringw** [TRON-US/go-btfs#797]
![QQ截图20201116173330](https://user-images.githubusercontent.com/46474646/99236439-2938db80-2832-11eb-8b7d-48bcd29728ca.png)
![QQ截图20201116173431](https://user-images.githubusercontent.com/46474646/99236440-29d17200-2832-11eb-8158-1bbd2f9b275b.png)

cmmands：btfs storage contracts list -o escrow_time,asc host 
next_escrow_time value err, sort by escrow time cant take effectt

**Comment by taiyangc** [comment]
This special 0001-01-01 timestamp means that the escrow payment has not started scheduling. Is it still like this after running `btfs storage contracts sync host`?

**Comment by boringw** [comment]
> This special 0001-01-01 timestamp means that the escrow payment has not started scheduling. Is it still like this after running `btfs storage contracts sync host`?
yes，not change

**Comment by boringw** [comment]
> This special 0001-01-01 timestamp means that the escrow payment has not started scheduling. Is it still like this after running `btfs storage contracts sync host`?

yes， not change

**Comment by taiyangc** [comment]
We've made updates and can you check again if this error has been fixed?

**Comment by boringw** [comment]
checked，its fixed
