### ISSUE TITLE
up time increase score goes down

### ISSUE THREAD

**Issue by felixishim** [TRON-US/go-btfs#808]
up time finally increased from 51% to 58% but score dropped from 4 to 3/10

input btfs storage stats info shows:

`{"host_stats":{"online":true,"storage_used":19407499,"storage_cap":735000000000,"storage_disk_total":1000186036224,"storage_disk_available":723462578176,"uptime":0.5851,"score":3,"uptime_score":4,"age_score":10,"version_score":10,"speed_score":20,"upload_speed_score":10,"download_speed_score":10,"uptime_weight":0.6,"age_weight":0.2,"version_weight":0.1,"speed_weight":0.05,"upload_speed_weight":0.05,"download_speed_weight":0.05},"renter_stats":{"reserved":""}}`

nothing seems changed except increased up time, what is causing the score drop even?

**Comment by taiyangc** [comment]
That's odd. Normally the score is added up from the individual factors * weight but clearly this doesn't add up. We've seen this rarely in the past but the scoring corrects itself afterwards. What's your current stats info now?

**Comment by felixishim** [comment]
`{"host_stats":{"online":true,"storage_used":21399175,"storage_cap":722000000000,"storage_disk_total":1000186036224,"storage_disk_available":728685379584,"uptime":0.5984,"score":4,"uptime_score":4,"age_score":10,"version_score":10,"speed_score":20,"upload_speed_score":10,"download_speed_score":10,"uptime_weight":0.6,"age_weight":0.2,"version_weight":0.1,"speed_weight":0.05,"upload_speed_weight":0.05,"download_speed_weight":0.05,"last_updated":"2020-11-18T08:13:37.222796224Z"},"renter_stats":{"reserved":""}}`

**Comment by taiyangc** [comment]
The score is actually correct with the exception that `"uptime_score": 4` is weird. From our scoring breakdowns, 0.5984 should have an uptime_score of 0, and the rest does add up to a total score of 4. What version of BTFS are you on? Are you sure you are not running a modified binary?

**Comment by taiyangc** [comment]
Also, which operating system are you running?

**Comment by felixishim** [comment]
Windows 10, BTFS 1.4.1-488bfb8

**Comment by felixishim** [comment]
> can you share your node id?

      "ID": "16Uiu2HAm8Cy2oEB4w5Dq6KQYdnS9qsnJ5eYozbZLX18nktYf6QLx",

**Comment by felixishim** [comment]
> can you share your node id?

in addition, now when I put "btfs storage info stats" or "btfs storage info sync" the terminal response with Error: datastore: key not found

**Comment by khenzar** [comment]
I think the math in total score calculation is messed up.
![image](https://user-images.githubusercontent.com/2130285/99904467-4dca0300-2ccb-11eb-8d80-967b503314c4.png)
My total score should be 8.38, instead it shows 6.4.
If this is supposed to be a weighted average score, it should be calculated as individual scores multiplied by their weights and all added up together.
Also, common sense tells you that the total score can't be lower than the lower of the individual scores.

**Comment by taiyangc** [comment]
The original issue had been fixed. There was a bug related to insert 0 scores. Should work now.
