### ISSUE TITLE
Weird uptime behavior

### ISSUE THREAD

**Issue by KevinW3108** [TRON-US/go-btfs#828]
Dear btfs team,

I'm monitoring my btfs nodes and noticed some weird behavior regarding the uptime.
Every day at about 3 am, my uptime goes down until about 1 am. Then it goes up again until it reaches the original uptime at about 3 am, where the whole pattern starts again, as you can see here.
<ins>Notice:</ins> All times are given in CET (UTC+1).
![image](https://user-images.githubusercontent.com/12199663/99891658-ac13c900-2c6c-11eb-9200-6c450d716695.png)

This results in decreasing my uptime score too, which leads to a lower total score (see screenshot 1).

If it was only 1 node showing that pattern, I'd guess it may be my hoster causing the lower uptime. But it happens on all of my 10 nodes, and they are spreaded over several hosters and geo locations. (see screenshot 2).

I can see this pattern since I started monitoring my nodes (October 16th) (see screenshot 3).

Do you have any idea what could cause the decreasing uptime on all nodes, even though they're well distributed?
Maybe other people made the same observation? (Unfortunately, the newly added score history only shows one score per day, so the fluctuation over day isn't visible)

<details>
  <summary>Screenshot 1: Proportion between uptime and uptime/total score</summary>
  
![image](https://user-images.githubusercontent.com/12199663/99891678-debdc180-2c6c-11eb-9747-8a06b909a28d.png)
</details>

<details>
  <summary>Screenshot 2: Repeating pattern across all 10 nodes</summary>

![image](https://user-images.githubusercontent.com/12199663/99891705-27757a80-2c6d-11eb-85b0-c3087f4cdb0d.png)
</details>

<details>
  <summary>Screenshot 3: Repeating pattern since October 16th</summary>

![image](https://user-images.githubusercontent.com/12199663/99891744-89ce7b00-2c6d-11eb-8582-14cb916fe928.png)
</details>

Best regards,
Kevin

**Comment by andreas-barthel** [comment]
@taiyangc Any news?

**Comment by KevinW3108** [comment]
Just giving a quick update: it's still the same pattern, nothing changed so far. Even the Host UI confirms the problem.
Since the Host UI seems to show the score at about midnight (UTC+0), it matches perfectly with my statistics shown above.

![image](https://user-images.githubusercontent.com/12199663/102538273-618b3e00-40ac-11eb-8aba-c3a121724415.png)

**Comment by taiyangc** [comment]
There is definitely something going on with the uptime server. Please post at least one host id that is consistently up. We need to monitor its behavior overtime.

**Comment by KevinW3108** [comment]
Thanks for your reply! As I explained above, I have this problem on all of my 10 nodes.
Here you have a few host ids. If you need more, feel free to ask again.

- 16Uiu2HAmGdHCDGhZnY9tfjQ5Pddh2aoRLzQ973PBx1tgq6g3PVEr
- 16Uiu2HAmTXrDa1meZ9MXq4nQL2RGaRvqgu5ddZQQLt9w4ecfkfqG
- 16Uiu2HAmCGH7BWbK1zdPKBYhup7cJ2m5esWef7ZfXNFYu9eg2kMh

**Comment by rir1973** [comment]
@taiyangc, another host with the same problem:

16Uiu2HAmNEW7i1Y6AbaMcF2xDNcVrzPtjhCzSJNnfFcZP7i25ggM

Thank you for checking.

**Comment by taiyangc** [comment]
We identified the problem and will fix this very soon.

**Comment by raisro** [comment]
Thank you very much for your effort.

**Comment by taiyangc** [comment]
The fix's been applied. Please verify in the next few days to see if your uptime is stable.

**Comment by KevinW3108** [comment]
Thank you very much! 
I guess the fix has been applied to the hub/some central server, so I don't need to update my node, right? 

I'll continue monitoring my nodes and give you feedback next week.

**Comment by taiyangc** [comment]
Correct. No client update needed.

**Comment by KevinW3108** [comment]
As you can see in the following picture, since January 13th, none of my nodes' uptime has dropped! 
So I can confirm that the fix is working.

Thank you very much! I'll close the issue then.

![image](https://user-images.githubusercontent.com/12199663/104852315-97655180-58fa-11eb-846e-a2670d012458.png)

**Comment by vengi83644** [comment]
Hi Team, I am having this problem now. My uptime is increasing 1% every 6 or 7 hours. My uptime is now 54%.  
I don't see contracts yet. But I see some 12 MB storage used.

**Comment by vengi83644** [comment]
Here is my host node ID
16Uiu2HAmHrK7hAzY9PEUUihSwVpXb8AcX7bth9U7Lx9rgGevYWYP
