### ISSUE TITLE
Having contracts but no earnings to date 

### ISSUE THREAD

**Issue by AlexGGWP** [TRON-US/go-btfs#838]
I have one nod up for 2 months now with one contract for now. However I don't see any changes on the "Earnings to-date". It is always 0.  I have this contract for about 3 weeks now but I don't get any payments no rewards for being online. 

NODE ID: 16Uiu2HAm5T216MDXK7KuTyHYhLYtqAuyyrcrpfbt3Z1v1x2qTvkh

contract details: 
{"contracts":[{"contract_id":"e937258d-1b80-402f-a533-14dbee263dbc,a5832702-9256-470c-a905-b2767fdbfe82","host_id":"16Uiu2HAm5T216MDXK7KuTyHYhLYtqAuyyrcrpfbt3Z1v1x2qTvkh","renter_id":"16Uiu2HAkyXPo3XG93EjqmiKQum7QxhimrxEEvRTsygsA1y4Sh743","status":2,"start_time":"2020-11-12T10:58:40.056968Z","end_time":"2021-11-12T10:58:40.056968Z","next_escrow_time":"0001-01-01T00:00:00Z","compensation_paid":0,"compensation_outstanding":0,"unit_price":250000,"shard_size":48980222,"shard_hash":"Qmcg5U9ctrtcAB6Hf2PSNby8bT5eXhpACef5gUR3neb1VQ","file_hash":"QmfXPJ3teWzRSS3jtTfobdhgVP9z31DGSko66HeNg784X7","last_modify_time":"0001-01-01T00:00:00Z"}]}

**Comment by taiyangc** [comment]
We've made some updates recently, is it still this way after running `btfs storage contracts sync host` again?

**Comment by AlexGGWP** [comment]
Yes! Thank you now it is fixed!
