### ISSUE TITLE
update cause BTSpeed turn speed up on

### ISSUE THREAD

**Issue by felixishim** [TRON-US/go-btfs#839]
as subject, after update the BT Speed got turned on on its own spent few hundred of my BTT

**Comment by taiyangc** [comment]
Which update? Could you elaborate more? BT Speed and BTFS are separate softwares.

**Comment by Sophia-yu-kk** [comment]
The system will automatically close the longer issues, if your problem is still not solved, you can join the discord group chat: https://discord.gg/2CwVmm5X
