### ISSUE TITLE
Attempting to add single 8gb file to BTFS via browser results in out of memory message and fail

### ISSUE THREAD

**Issue by zhenkas** [TRON-US/go-btfs#842]
I tried to add 8gb file via WebUI\Files\+Add button, which ended with "out of memory" message from browser.
The node itself stayed alive, and I was able to reopen WebUI site, however file were not uploaded.

I was able to upload the file using "btfs add" command line, so the problem only in front end.

BTFS version
```
Initializing daemon...
go-btfs version: 1.4.2-396feb8
Repo version: 10
System version: amd64/windows
Golang version: go1.14.12
```

Browser: Opera 72.0.3815.400

**Comment by endofthepain** [comment]
big file = big memory is the issue when using btfs rightnow and the solution is upgrade your hardware 1 GB file need 30 GB memory just multiple it 8 x 30 GB ram

**Comment by zhenkas** [comment]
I forgot to say, that my lab has 32 gb/ram, and big file stored on disk, so
it should not take memory at all.
This is exactly how it worked with "btfs add" command. btfs process did not
reached any memory peaks.

вт, 8 дек. 2020 г. в 01:50, AoMh <notifications@github.com>:

**Comment by taiyangc** [comment]
Big files are not optimized at the moment on the UI. It is likely to fail. I am marking this as a low priority issue unless you can point out a fix for frontend.

**Comment by Kyliux** [comment]
zhenkas, it's the same bug there: #840 also unsolved.
Conclusion : BTFS isn't working, as simple as that.

**Comment by taiyangc** [comment]
@Kyliux Yours is a different bug. 

This bug is about browser OOM for large files. Likely need some help improving JS-SDK on the webui.

**Comment by Sophia-yu-kk** [comment]
The system will automatically close the longer issues, if your problem is still not solved, you can join the discord group chat: https://discord.gg/2CwVmm5X
