### ISSUE TITLE
Stuck on "Next payment date"

### ISSUE THREAD

**Issue by gicamm** [TRON-US/go-btfs#844]
Hi,
I received a few contracts in early October. I never received the payment (not the bonus). The dashboard is still showing: "Next payment date: Oct 27, 2020"
The node id is 16Uiu2HAm1DJQezjwKWtN1QHw2R6jH2Swp81PUjbBgtDCsfQH1kPR

Moreover, I'm not receiving any new contract for 2 months, despite my score being 10/10.

Thank you

@taiyangc

**Comment by taiyangc** [comment]
After running `btfs storage contracts sync host`

Please post the results of `btfs storage contracts list host` as well. Thanks.

**Comment by gicamm** [comment]
The command does not return any output.
`/ # btfs storage contracts sync host
/ # 

Thanks

**Comment by taiyangc** [comment]
We are looking into the payment date issue.

**Comment by taiyangc** [comment]
Due to the amount of payments being processed the current mechanism is slower than expected. We will work on a solution next week.

**Comment by taiyangc** [comment]
Update: payments are slowly being rolled out after resolving an issue. But expect them to be slow until we perform a major update in early-mid January.

**Comment by taiyangc** [comment]
Is this still an issue? We should have fixed the slow payout before new year's.

**Comment by gicamm** [comment]
I can see the balance in the wallet.
Thank you

**Comment by digbicks** [comment]
I am still not seeing the payments, even after running the commands: btfs storage contracts list host and  btfs storage contracts sync host.
