### ISSUE TITLE
Not recieved a payment since 17/11

### ISSUE THREAD

**Issue by bluelights2018** [TRON-US/go-btfs#850]
Hi
Host ID: 16Uiu2HAmTcMX6Wh5u2CpF87xmrhkNENptTgzoHaKDwPdKC9ZT8Lb
I have 3GB used with 65 contracts, I have had my node up and running for a few months but something is not right, no payments.
![Screenshot 2020-12-14 205059](https://user-images.githubusercontent.com/76012681/102134211-255aa200-3e4e-11eb-85e6-6c3691e95230.png)

Struggling for any help in the BTT TG channel, hoping I can get some help here.

**Comment by bluelights2018** [comment]
Also I dont see the BTSpeed option anywhere in the Utorrent app, 
![Screenshot 2020-12-14 205506](https://user-images.githubusercontent.com/76012681/102134610-b29df680-3e4e-11eb-826f-82ea94d62937.png)

**Comment by taiyangc** [comment]
Payment may be coming in slower than expected. Team is working on a solution.

**Comment by taiyangc** [comment]
Dup of #844 please track updates there.
