### ISSUE TITLE
BTFS Host Sync Error.

### ISSUE THREAD

**Issue by murthydevarakonda** [TRON-US/go-btfs#866]
Hello, 

I am new BTFS host and getting the following error.  I issued the command "btfs config profile apply storage-host" to make sure that host setting is updated in the configuration file. The UI has been stuck at verifying for long time, i.e. more than 12-hours.  I tried killing the daemon and reinitializing it, but no luck.  I am running the latest code.  Could someone help me here?

My peer ID is 	16Uiu2HAmLaTsF4mZQvREaiDMu8tFyAM8SWML9a8q42BdyhZDYgt8

2020-12-24T19:25:35.043Z        ERROR   spin    spin/helper.go:17       Failed to sync host stats: Failed to query stats from Hub service: HubQueryClient: Cannot query to get stats!

I also cannot create a BTT wallet on the host.  It takes the password and but when I click on continue, nothing happens.  

Thank you.

**Comment by taiyangc** [comment]
Should be back to normal now. Please wait a couple hours for scores to be updated.

**Comment by murthydevarakonda** [comment]
@taiyangc thanks for looking into this issue.  I still see the problem.  I did re-initiate the whole node and I got a new different peer ID now.  I am not sure what is going on.  Please do let me know if I can do something to resolve.

Initializing daemon...
go-btfs version: 1.4.2-396feb8
Repo version: 10
System version: 386/linux
Golang version: go1.14.12
Repo location: /mnt/usbdrive/.btfs
Peer identity: 16Uiu2HAm3Ps5H2hRSQkdnWaKnLC729gCGb8qpDwzVk4YNBT3Wf1R
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/192.168.1.208/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /ip6/fd0b:43eb:11c9:1:1ebf:ceff:fe93:3b81/tcp/4001
Swarm listening on /ip6/fd0b:43eb:11c9:1:cde5:c7bc:fba9:fe0d/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/108.94.140.74/tcp/64417
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/192.168.1.208/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/0.0.0.0/tcp/5001
WebUI: http://0.0.0.0:5001/webui
HostUI: http://0.0.0.0:5001/hostui
Gateway (readonly) server listening on /ip4/0.0.0.0/tcp/8080
Remote API server listening on /ip4/0.0.0.0/tcp/5101
Daemon is ready
Storage host info will be synced at [SCORE] mode
Current host stats will be synced
Current host settings will be synced
2020-12-29T04:00:38.409Z        ERROR   spin    spin/helper.go:17       Failed to sync host stats: Failed to query stats from Hub service: HubQueryClient: Cannot query to get stats!
BTFS is up-to-date.

**Comment by rooie1971** [comment]
Started a new node yesterday and same problem, it's verifying now for 16 hours, and all i get is the same error every half hour:
2020-12-29T11:51:15.419+0100    ERROR   spin    spin/helper.go:17       Failed to sync host stats: Failed to query stats from Hub service: HubQueryClient: Cannot query to get stats!
Running on Ubuntu 18.04 ip4 and multiple ip6 addresses.

**Comment by taiyangc** [comment]
Ongoing issue.
