### ISSUE TITLE
File unreachable after an indefinite amount of time

### ISSUE THREAD

**Issue by ciwines** [TRON-US/go-btfs#871]
Hello, we have created a node to try to make it work as a provider. When we upload a file to BTFS, the file is uploaded correctly and without any problems; the payment is successful and we get the CID of the file. Subsequently, when we try to use the gateway gateway.btfs.io/btfs/ the file is viewed correctly but, after an indefinite amount of time (generally two weeks), the file is no longer reachable. This happens with any type of file, regardless of size. An example is the following file, QmdWeyj3rcj8DE33DQuY7TzQ7esB4RzmYwKiBkYSmxGpoQ, which is no longer visible from the official gateway, and there is no error by making the following call /api/v1/storage/upload/status?arg=dd02daf2-025c-4cc3-a581-2f15dff8e607.
If we try to retrieve the file through the gateway of our local node instead, it doesn't give any problem. We ask for information, clarifications and how to solve the problem.
Confident of a prompt response, we congratulate to the development team.

**Comment by taiyangc** [comment]
We are working on gateway issues that should help resolve the file after extended time.

**Comment by taiyangc** [comment]
Gateway issues are fixed afaik.
