### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by sbusceti** [TRON-US/go-btfs#885]
Hi, I have btfs daemon running on a virtualbox machine configured in network bridged mode.
I changed ip addres api from 127.0.0.1 to 0.0.0.0 in config file to allow webui and hostui access from other computer in the same lan.
I also added cors header.
I can reach hostui and webui, but when I try to create or import a wallet from hostui page, nothing happens. 
From import page I have a dialog "system error" and browser inspection return a 403 forbidden requesting resource http://IP_OF_VM_RUNNING_BTFS:5001/api/v1/wallet/discovery?p=
Instead, if I do the same on btfs daemon running computer, all works fine.
Can you help me?
Version: 1.5.0-86e6633
Thanks

**Comment by andreas-barthel** [comment]
Hi.
For security reasons the `/wallet` API is completly unreachable from any remote host. That is good and fine.
If your guest os is some kind of Linux then you can use SSH port tunneling:
1. Connect via SSH to the guest OS: `ssh -L localhost:5001:localhost:5001 user@ip`
2. Open a browser on your host os and use `http://localhost:5001/hostui`
With `-L localhost:5001:localhost:5001` SSH acting as a reverse proxy, but you need the opened SSH connection every time you want to access the wallet in the HostUI. [SSH Port Forwarding Example](https://www.ssh.com/ssh/tunneling/example)

Another approach is to install a complete HTTP reverse proxy like nginx in your guest os. See [nginx.org](http://nginx.org/)

**Comment by sbusceti** [comment]
Hi, thanks for the clear explanation!
