### ISSUE TITLE
package.sh - md5 command NOT found on Unix/Linux Platform.

### ISSUE THREAD

**Issue by bommuraj2012** [TRON-US/go-btfs#90]
Can we replace "md5" command with "md5sum" because Linux/Unix platform widely supporting md5sum rather than md5.

md5=`md5sum ./cmd/btfs/btfs | awk '{print $1}'`

Thanks

**Comment by tycm4109** [comment]
@bommuraj2012 Sure, no problem I will bring it up with the team.

**Comment by bommuraj2012** [comment]
I understand the concern That "md5sum" command NOT available in Mac.
So    Mac supports "md5"
and  Unix/Linux Supports "md5sum"

To make it common and Platform independent, I would  recommend below which works everywhere.
 openssl md5 <filename> | awk '{print $2}'

PLs let  me if you anyone has questions.
Regards,
Bommuraj
