### ISSUE TITLE
Error: serveHTTPGateway: manet.Listen(/ip4/127.0.0.1/tcp/8080) failed: listen tcp4 127.0.0.1:8080: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

### ISSUE THREAD

**Issue by felixishim** [TRON-US/go-btfs#906]
Error: serveHTTPGateway: manet.Listen(/ip4/127.0.0.1/tcp/8080) failed: listen tcp4 127.0.0.1:8080: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

This has made the daemon unable to start

**Comment by endofthepain** [comment]
change ur port because port 8080 being used by another procces

**Comment by taiyangc** [comment]
Please either change port or close the process that's occupying port 8080.
