### ISSUE TITLE
Questions about post installation

### ISSUE THREAD

**Issue by raisro** [TRON-US/go-btfs#909]
Dear Support Team,

Occasionally the node starts to give errors, although I have read that some are normal I have doubt if my node is ok. For example I got this message: (Attached full log too)

"
2021-02-08T03:47:25.143+0100    ?[31mERROR?[0m  spin    Failed to sync btt-tx: Get "https://api.trongrid.io/v1/accounts/TLWym
pN8ECpYJhrJiqgkcYgvCh4D6mUJLj/transactions?limit=200&only_to=true&order_by=block_timestamp,asc&min_block_timestamp=1605896867
950": x509: certificate signed by unknown authority
"

Do I have to do something on the node to avoid these messages?, Are they errors from my node?

I have reviewed BTFS-Service Monitoring and I think it is ok, with some mistakes from the last update but overall I see it fine (attached pdf with the detail)

It has been running for 25 days with a host score of 10 and I still haven't received any earnings. How long do I have to wait to start receiving earnings?, I will wait as long as necessary.

And if you allow me another question, a node in "REPAIR MODE ON" what storage size does it have to have?, What size do you consider is optimal?. I have installed one and I think it does not need as much space as a node in REPAIR MODE OFF. But if you can also tell me this information, I will appreciate it very much.

Best Regards,
Raúl

[BTFS - Service Monitoring.pdf](https://github.com/TRON-US/go-btfs/files/5953358/BTFS.-.Service.Monitoring.pdf)
[BTFS.exe.log](https://github.com/TRON-US/go-btfs/files/5953359/BTFS.exe.log)

**Comment by taiyangc** [comment]
1) For the `x509: certificate signed by unknown authority` you may want to check your system certs or relax your SSL cert settings. Yes, these are errors related to your system.
2) Earnings are right now somewhat randomly distributed with higher earnings for more stable nodes. But this will change once staking is implemented https://medium.com/@BitTorrent/btfs-releases-new-staking-rules-87fb573dc4ee
3) We do not have any recommendations on repair storage size. As big as possible if you can. We will release some general statistics about repair functions soon.
