### ISSUE TITLE
Problem with node verification

### ISSUE THREAD

**Issue by ShadowAGT** [TRON-US/go-btfs#910]
Dear support team,

I don't know who I can ask more. I've installed and started BTFS daemon (under FreeBSD), looks like it's works. I've been able to add file in publish, and after that, It's can be accessed through https://gateway.btfs.io/btfs/QmcbVQh4aeeTuZXq7zip74Byrz7B5g15iTShBMczM96gox . API Port (4001) opened for external connections in firewall.

But problem is - my node is still in verification mode. Today is 3rd day (in the window written up to 180 minutes). May be it's because something wrong with BTFS network? As I understand, to get verification, node fetch information from https://hub.btfs.io, but if I type this in URL browser, I am getting HTTP 502 error.

Please, give me an answer what is problem and what I need to do to solve it. I'd like to run BTFS for long stable work. Thanks.

**Comment by GreenIceTea070** [comment]
Seems like a know issue. they are working on it:

https://github.com/TRON-US/go-btfs/issues/908#issuecomment-777822490

**Comment by ShadowAGT** [comment]
Aha. Didn't seen before post... Sorry for flood...

**Comment by taiyangc** [comment]
Closed as resolved.
