### ISSUE TITLE
Online miners

### ISSUE THREAD

**Issue by dellme** [TRON-US/go-btfs#912]
Hello BTFS team,

whyBTFS scan https://scan.btfs.io/#/ show that online miners droped from 540 000 to 440 000. 
From 15.12.2020 to 14.02.2021 minus 100 000 miners.

**Comment by gray21312** [comment]
Hi, I validated 2 of my nodes today and from here IDK what to do, do i leave my computers on and then my file storage is used by users? or do i have to download files and let them seed?

**Comment by taiyangc** [comment]
Thank you for your concern. It was related to node validation per #908. It has since recovered. Please check btfs scan again.
