### ISSUE TITLE
gateway.btfssoter.io "Hmm. We’re having trouble finding that site."

### ISSUE THREAD

**Issue by DmitriyPekar** [TRON-US/go-btfs#913]
I press "share." but the site doesn't exist, how can I link to my file?

https://gateway.btfssoter.io/btfs/QmQdoPhWWcQGkxY7wDQg3WjjFhfPcVyZHfjSzSmbAR9NkG not opened

**Comment by DmitriyPekar** [comment]
https://gateway.btfssoter.io/btfs/QmQdoPhWWcQGkxY7wDQg3WjjFhfPcVyZHfjSzSmbAR9NkG

**Comment by taiyangc** [comment]
This service is no longer available. Please use gateway.btfs.io instead.

By the way, where did you obtain this url in the first place?

**Comment by DmitriyPekar** [comment]
> This service is no longer available. Please use gateway.btfs.io instead.
> 
> By the way, where did you obtain this url in the first place?

I got the link from webui

**Comment by taiyangc** [comment]
Thank you, we will correct it in a future release.

**Comment by taiyangc** [comment]
Link updated on https://www.bittorrent.com/token/bittorrent-file-system/
