### ISSUE TITLE
contracts

### ISSUE THREAD

**Issue by dellme** [TRON-US/go-btfs#915]
Hello,

how i can have contracts for earn BTT because after half month work . 0 contracts.

Thanks

**Comment by gray21312** [comment]
Hi I asked the same question on discord and the answer was that you'll start getting contracts after about 1 month

**Comment by gray21312** [comment]
Hi I asked the same question on discord and the answer was that you'll start getting contracts after about 1 month

**Comment by True2dakrypto** [comment]
@gray21312 where did you find the discord group at

**Comment by gray21312** [comment]
@True2dakrypto https://discord.com/channels/491685925227724801/ this is the channel :) IDK where i found it but its quite helpful if youre lookinf for advice

**Comment by taiyangc** [comment]
This question is more suited for Discord. Thanks.
