### ISSUE TITLE
Question: Is it possible to host NFTS node locally and upload file shards externally?

### ISSUE THREAD

**Issue by xblue-light** [TRON-US/go-btfs#918]
I think this is not currently supported from my understanding you can host a BTFS node  and the storage location can only be the local machines storage. 

Is it possible to however integrate external storage resources such as an AWS S3 bucket and access it via an exposed API gateway?

I would really be interested to hear about this. Peace out!

OS: Debian GNU/Linux 10 (Buster) x86_64 architecture

**Comment by taiyangc** [comment]
Not right now. But a good suggestion. We will let you know when we start to support more storage types!

**Comment by Sophia-yu-kk** [comment]
The system will automatically close the longer issues, if your problem is still not solved, you can join the discord group chat: https://discord.gg/2CwVmm5X
