### ISSUE TITLE
btfs add <file or dir> is not evident on MFS.

### ISSUE THREAD

**Issue by Hernanm0g** [TRON-US/go-btfs#92]
Hi, I found in the documentation that `btfs add <file>` is not supposed to record that file in the MFS, so it cant be seen in the IPFS Web UI. 
But, it will be nice if you integrate it as a flag for the 'add' command, such as:
`btfs add -mfs <file or dir>`.

Every time i want to achieve this i have to type `btfs files cp /btfs/<hash> <objectName>`. What do you think?

**Comment by tycm4109** [comment]
@Hernanm0g Hello Hernan! Thank you for the suggestion. I agree that it is a good idea to integrate the flag for easier use. I will bring this back to our development team and keep you updated. Thx!
