### ISSUE TITLE
Command not found when attempting to run BTFS Host

### ISSUE THREAD

**Issue by broken613** [TRON-US/go-btfs#920]
I installed BTFS on a Raspberry Pi 4 running Raspberry Pi OS (v5.4).  The Raspberry Pi has an ARM64 chip but the OS is only 32-bit so installed BTFS using "bash install.sh -o linux -a arm # For Linux ARM".  I start the daemon and it states it is up to date. I can then open the Host UI.

When i attempt to run "btfs config profile apply storage-host" it tells me "bash: btfs: command not found" 

![Screenshot from 2021-02-23 07-33-36](https://user-images.githubusercontent.com/72591626/108870555-15c5ab00-75ad-11eb-8163-5ae2acccaa80.png)

**Comment by derkauzigekoala** [comment]
i think `export PATH=${PATH}:${HOME}/btfs/bin` in the new terminal should do it.
also add `export PATH=${PATH}:${HOME}/btfs/bin` to your `~/.bashrc` file so you don't have to do it every time you open a new terminal

**Comment by broken613** [comment]
Thanks.  Running "export PATH=${PATH}:${HOME}/btfs/bin" in the new terminal resolved the issue.
