### ISSUE TITLE
BTFS Wallet not loading

### ISSUE THREAD

**Issue by emtreix** [TRON-US/go-btfs#922]
The first error about the bfts wallet I encountered was being unable to enter any text in the password box and I created a new one. So the node is running but when I click on the Wallet, the BTFS IN-APP WALLET BALANCE and BTT CRYPTO WALLET BALANCE
only showing a loading circle under it and the balance is not updating

**Comment by endofthepain** [comment]
system going upgrade

**Comment by emtreix** [comment]
Thank you

**Comment by emtreix** [comment]
After 20h I still have this issue

**Comment by taiyangc** [comment]
Wallet was under maintenance. Is it working for you now?

**Comment by emtreix** [comment]
Yes, it's working now. Thanks alot!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
