### ISSUE TITLE
Score & Earnings not changing

### ISSUE THREAD

**Issue by blqblqblqblq** [TRON-US/go-btfs#924]
Hi, is there any known issues or reason why SCORE & EARNINGS are not being updated on the dashboard? It stays like these for day and a half now. I don't see any errors in the log. I restarted the node, then wait a couple of hours still no changes. netstat says that connections are fine.
If you need any other related data, please ask.
![dash](https://user-images.githubusercontent.com/79601818/109053771-c3d47080-76e5-11eb-87d1-548b8f67a6ea.png)

 EDIT:
I just see something in the logs, not sure if it is normal, other log data looks fine to me:

> {"error":{},"event":"IdentifyOpenFailed","peerID":"thepeerid","system":"net/identify","time":"2021-02-24T19:26:09.080211317Z"}

**Comment by taiyangc** [comment]
Hello, please be patient as we are still in the middle of payment infrastructure update. Will provide an update soon.

**Comment by taiyangc** [comment]
Score update issues are resolved. For earning updates, please track #881
