### ISSUE TITLE
A lot of Nodes with suspect average_upload_speed but with max score

### ISSUE THREAD

**Issue by andreas-barthel** [TRON-US/go-btfs#925]
Hi all.<br>
I dont know if its important, but i have a list with more than 10k BTFS-Nodes with "average_upload_speed" < 0.1<br>
Most of them have a score of 10, so max upload_speed-score.<br>
Is that normal?

Im not sure if should add the file here. @taiyangc If you think its ok to publish the list here i will attach ii

**Comment by taiyangc** [comment]
Thank you. we will investigate this new issue.

**Comment by laocheng-cheng** [comment]
hi，@andreas-barthel，could you provide some nodes for us to check it？

**Comment by andreas-barthel** [comment]
Sorry for delay.
Here are are few Nodes:

- (1) 16Uiu2HAkutsacEkpvnJrUpMW5YTAGHmKtn9i4ZJi7VXz9HoB7pwM
- (2) 16Uiu2HAmHd7nKw7qUdJggS1onYmpjYCfprDCjfjZhvf7tAwAPt4g
- (3) 16Uiu2HAkwPx2ZBGcQjskcuPonwj6oXiQ73UbP7MUkpFmjEq1HwWj
- (4) 16Uiu2HAmJMNJyvxHKovJpb8p8vbd1DoeE5zghtsKLRDss1AUnsvB
- (5) 16Uiu2HAkz4M1hwxUHWhCHBHhXW2zvDjbtz28WCGRP1krMWGbZYGf
- (6) 16Uiu2HAmSKYZZUHcZRfv3d8DQDoUVXv9YuoGHCAexsE4Ym544QjJ
- (7) 16Uiu2HAmPnkmHuwN7sf44XKqCKe7bSv2AR1pnxNZhE2FRGeWAcSJ
- (8) 16Uiu2HAmHSqvZvMqZQzy4r8MJwaSCtuSQ2XT9RNYBtyGCauavfiA
- (9) 16Uiu2HAkvW1c7hVsK5TXxDeZz8FVDQSJW3ZrXCx6AYtz2aKahLBh

**Comment by laocheng-cheng** [comment]
thanks, I will check it。 It'll be normal after a while。

**Comment by Sophia-yu-kk** [comment]
The system will automatically close the longer issues, if your problem is still not solved, you can join the discord group chat: https://discord.gg/2CwVmm5X
