### ISSUE TITLE
Node uptime fluctuates in sawtooth pattern

### ISSUE THREAD

**Issue by Hexide** [TRON-US/go-btfs#927]
Hello,
I recently started hosting few nodes, Over the past couple days, I have noticed that uptime and uptime score fluctuate.
This can be seen from some data points every 30 min:
![image](https://user-images.githubusercontent.com/7336581/109431180-da443a00-7a0d-11eb-983c-8a94bf4831e4.png)
Chart represents 27 hours.

It looks as if node uptime continuously falls until it is reset back to 1 at some point. 

Nodes:
- 16Uiu2HAm9P4owFEanRiBj55xbPMLbVSasy3DUnVzkhaEaLQSioC3
- 16Uiu2HAm9VQUXRLaSKktkRV99uRwheE8bkUPWV6uXHqdvkCuSJ4D
- 16Uiu2HAmAGbebkgVVVbcksBRT96PdCkKLT1LgrcTihqYC4n6XKXG

This issue appears to be duplicate/related to #828

**Comment by taiyangc** [comment]
Thanks will look into it again.

**Comment by Sophia-yu-kk** [comment]
The system will automatically close the longer issues, if your problem is still not solved, you can join the discord group chat: https://discord.gg/2CwVmm5X
