### ISSUE TITLE
btfs.exe not starting up

### ISSUE THREAD

**Issue by pavansantani** [TRON-US/go-btfs#944]
btfs.exe is not starting up as soon as i double click on it it pop's up a window & closes i had a node working but now all of a sudden everything has stopped working...

**Comment by jgabriel98** [comment]
run in on a CLI (cmd or powersheel, or windows terminal), not by double clicking it.

**Comment by pavansantani** [comment]
> run it on a CLI (cmd or powersheel, or windows terminal), not by double clicking it.

failed execution

little more detail how to do it. as not familiar with cli or powershell.

cli has same error as of powershell which says failed execution

**Comment by rudya** [comment]
@pavansantani Might be due to a deadlock from an old process. What is the output when you enter these lines in the [command prompt](https://www.howtogeek.com/235101/10-ways-to-open-the-command-prompt-in-windows-10/)?
`netstat -ano | findstr:8080`
`netstat -ano | findstr:5001`

**Comment by jgabriel98** [comment]
> @pavansantani Might be due to a deadlock from an old process.

Yeah,
if it isn't a socket locking from an old process, it could be a file lock or somethin like.
For that, a quick fix would be to backup the config file, redownload/reinstall btfs, and then replace the config file.

in more details:
 1. go the the .btfs folder, copy the `config` file and save it somewhere
 2. remove/uninstall BTFS (on windows probably by erasing the .btfs folder)
 3. download/install BTFS again, don't run it yet.
 4. replace the fresh `.btfs\config` file with the one you saved on step 1
