### ISSUE TITLE
Uptime started from 0% and growing super slowly. 

### ISSUE THREAD

**Issue by BicaTech** [TRON-US/go-btfs#945]
Hello all btfs team, before a month i installed btfs and just tried what is that. than stopped it. and before two weeks i turned my pc into a dedicated btt node, but the uptime was 0% since i started, and im making about 1-2% a day, now i have a 32%uptime after two weeks of 24h tuurned up node without turning off !> my question is, does the uptime starts from 0% and grows up as the node stays online ? it would be more better i think for a node to start at 100% and then fall if it goes down, this way i need almost two months just to reach the 100% so i can get any contracts, i have placed a dedicated 4TB disk just for btfs. 

This is the node ID 
16Uiu2HAmVGJYuE2uUoKAxF91FYS3jVUJt1dt3sxzKUdVebLSVUd9

please check and update me with some info :) Thank u

**Comment by taiyangc** [comment]
Can you provide some console logs? Any errors from `btfs daemon` ?

**Comment by lynk-V** [comment]
Hi I have also the same problem. 

here is my log: 
[btfs-log.txt](https://github.com/TRON-US/go-btfs/files/6177237/btfs-log.txt)

Like I have been running it now consistantly for almost 3 weeks.
