### ISSUE TITLE
No contract, No income, Nothing. Host Score 10!

### ISSUE THREAD

**Issue by sepivip** [TRON-US/go-btfs#946]
What I'm missing? its about 1 month got score 10 but nothing happens... Any ideas?
![image](https://user-images.githubusercontent.com/72915556/110836532-9a0c7380-82b9-11eb-8368-dd5390b26a52.png)

**Comment by taiyangc** [comment]
Contracts are random and they may not reach your host nodes due to network connections.

**Comment by sepivip** [comment]
Mined 0 Btt after month... is that ok?

**Comment by k4sP3rsky** [comment]
Hello, I have the same problem. How can you check whether contracts can reach me?
I discovered 582 peers at the moment.  
![btfs](https://user-images.githubusercontent.com/46832751/111513626-4a162c80-8751-11eb-8237-76e5a0ee6692.JPG)

**Comment by k4sP3rsky** [comment]
here is my config: 
![config1](https://user-images.githubusercontent.com/46832751/111514528-1daee000-8752-11eb-8bae-9780ae8da3bf.JPG)
![config2](https://user-images.githubusercontent.com/46832751/111514540-21dafd80-8752-11eb-9b1a-4e2ae6005500.JPG)
![config3](https://user-images.githubusercontent.com/46832751/111514563-26071b00-8752-11eb-8577-338e50444995.JPG)
![config4](https://user-images.githubusercontent.com/46832751/111514578-299aa200-8752-11eb-8279-1b825fa125bc.JPG)

**Comment by sepivip** [comment]
Any Help? Hello?

**Comment by thatalbertaguy** [comment]
Do you have port 4001 TCP open ?

**Comment by sepivip** [comment]
Does it matter?

**Comment by sepivip** [comment]
Will anyone help me? ID 16Uiu2HAmPYEy9u1jNUEyGB5ezpzUciyvoYHnxd8EDfMVy7Ewo6YD

**Comment by DarkBlaez** [comment]
Yes it almost becomes useless when you see the limitations of 30 shards and the number of nodes. Large percentage of the nodes will never see contracts. This is not spelled out clearly in the "lets draw everyone in glitz website". I have dedicated nodes which sit at 8 and will reach 10 over time. Plenty of RAID backed space. The cost of infrastructure outweighs the potential earnings. It's almost better to just be a shared distributed cloud instance with the bar for entry is maintaining a node. 

The nodes getting contracts seem to be the nodes that were launched early as would be expected. 

There are a number of questions being asked but no answers being provided. There are lots of Medium articles to draw attention to the effort but no responses to the comments.

Even the daemon is mislabeled in terminology and not a representation of a true daemon implementation. A number of issues which need to be resolved that should have been resolved fairly quickly.

Is there any intelligence built in to distribute shards across geographic region? Are shards distributed across across nodes with varying capabilities, storage, speed, etc. or are the top nodes being allocated most shards. If the later then this is a huge issue with potential resiliency. This all games the system to steer contracts towards certain nodes.

There needs to be full transparency in how this his handled, if none of this is taken in to consideration then it needs to be or I could see Storj taking the lead in this realm. As with all these new re-invented P2P efforts most fizzle if they do not address these items early on. Remember the bulk of the user base and supporters will be the smaller node operators, not the early supercharged users/host. No one will make a lot of money with BTFS in their BTT wallets except a few.

Ask yourself why those that post the Medium articles have not responded to comments nor addressed these comments to date? Hype drives early adoption.

-DB

**Comment by DarkBlaez** [comment]
A bit more background. I think what the hope is that in the future there is a bitorrent integration with BTT/BTFS token which would then translate in to many nodes. The100M nodes is purely bittorrent clients of which I'd hagger a guess that less than 50% are active at any given moment in time as more are leechers. The webui, the core of btfs is a for of IPFS. The UI has had minor changes under the hood to reference BTFS, but this is all IPFS. The incentives on IPFS are for those that seek to support and be apart of a decenteralized web. IPFS is not just a file storage mechanism. Do not expect to make any money off of BTFS contracts, you will be lucky to see any contracts distrubted to your node. The indications are it's "random" however, have you seen any further elaboration? Have you seen any follow ups to the comments on Medium? Have you seen many of the questions answered here? There is a reason, the project code base is not original, it is a derrivative of IPFS. The underpinnigs might have the label BTFS but its only in the letters "BTFS" it's all IPFS code base under the hood. 

If you want to tap in to an existing, mature, community supprted ecosystem, IPFS is where the acton is

-DB

**Comment by Sophia-yu-kk** [comment]
The current rule is that nodes with 8 points or more are randomly awarded to the contract. As the number of miners increases, so does the competitive pressure. Data about some contracts and miners can be viewed in the browser. https://scan.btfs.io/
