### ISSUE TITLE
Question: can i have multiple host nodes running on the same wallet

### ISSUE THREAD

**Issue by jgabriel98** [TRON-US/go-btfs#947]
I have 5 machines running btfs

 - 2 of them on EUA's separate servers,
 - 2 on Europe's separate servers.
 - 1 on Brazil (my personal computer)
 
 
 all of them are setup with the same wallet,
 
 also when checking them, i notice they all had the same peerID,
 and when i got a contract, it seems that every one of them got the same contract (but only one is storing the shards/files)
### Questions 
 1. Is this an expected behavior? having the same peerId and all nodes act like one?
 2. why only one node got the shards/files? (update: now 2 out of 5 got the shards/files, on 3 accepted contracts)
 3. since they all have the same peerID, how does it affect on their annoucement?
 4. since they all have the same peerID, how does it affect on the chances to get a crontract?

**Comment by endofthepain** [comment]
the answer is no for same wallet / same peer id, it will make another peer confused, u can running multiple node but with not same wallet / peer id

**Comment by jgabriel98** [comment]
i see,

than this issue should raise attention to a new bug report.

because e have already 3 contracts in my setup (5 nodes with same wallet), and 2 are beeing used to store _shards_ of those contracts.

**Comment by jgabriel98** [comment]
> the answer is no for same wallet / same peer id, it will make another peer confused, u can running multiple node but with not same wallet / peer id

New question:
 1. What happens if i shutdown the "extra nodes", leaving only one running?
  - The contracts keep valid or are broken?
  - What happens to the shards if they where on these "extra nodes"? they will be lost, or transfered to new remaining node (does _Repair Mode_ have a role in this?) ?
 
 2. If i run BTFS again on those "deleted nodes", but now with a wallet for each, it will be associated to the old contracts? or it will be seen as a fresh new HOST node on the network?

**Comment by taiyangc** [comment]
We do not recommendation such a setup. There is a huge distinction between running BTFS nodes and normal "cloud accounts". A cloud account can be synchronized when logged in from different locations, BTFS nodes cannot. Each node is a separate entity, even though they appear in 5 different locations. Swarm announcements will get confused.

1) If you shut down extra nodes that had shards, they will be lost. And repair mode will kick in to replace your node with someone else's.
2) If you re-create nodes again (I assume new node IDs because you deleted them), it will be an entire set of new accounts, not associated with any old contracts - contracts *do not* migrate over to new nodes.

**Comment by jgabriel98** [comment]
> We do not recommend such a setup. There is a huge distinction between running BTFS nodes and normal "cloud accounts". A cloud account can be synchronized when logged in from different locations, BTFS nodes cannot. Each node is a separate entity, even though they appear in 5 different locations. Swarm announcements will get confused.
> 
> 1. If you shut down extra nodes that had shards, they will be lost. And repair mode will kick in to replace your node with someone else's.
> 2. If you re-create nodes again (I assume new node IDs because you deleted them), it will be an entire set of new accounts, not associated with any old contracts - contracts _do not_ migrate over to new nodes.

I see,
there still one thing i don't know:

> 1. What happens if i shutdown the "extra nodes", leaving only one running?
>    - **The contracts keep valid or are broken?**


---

and a new question kinda related to this: 
**I want to delete the extras Nodes, how can i transfer the _shards_ (from those extra nodes) to the remaining last Node?**
###### assuming that the contract will be kept, since the contract is associated to the peerId

**Comment by Sophia-yu-kk** [comment]
The system will automatically close the longer issues, if your problem is still not solved, you can join the discord group chat: https://discord.gg/2CwVmm5X
