### ISSUE TITLE
[Bug] BTFS in-app includes the balance of Bittorrent Speed

### ISSUE THREAD

**Issue by btfs-squad** [TRON-US/go-btfs#948]
**Description:**
BTFS in-app also get BTT with the same quantity when you make transaction for BT Speed

**Steps to reproduce:**

1. Install Bittorrent or Utorrent client with the support of BT Speed
2. Install BTFS and launch
3. Make a transaction to BT Speed in-app
4. Check the value of BT Speed in-app
5. Go to the wallet of BTFS and check the value of BTFS in-app
6. You will find that BTFS in-app balance increased on the same amount of BTT as BT Speed in-app balance

**Notes:**

If you will add some BTT to BTFS in-app it will not work the same way for BT Speed.

**Comment by taiyangc** [comment]
Yes, because during the initialization of BTFS it asked for an import of an existing wallet. Probably something easily missed but you are using the same wallet.

As for `If you will add some BTT to BTFS in-app` could you show the steps and also the wallet address so we can check it indeed finished?

**Comment by btfs-squad** [comment]
Is BTFS in-app and BT in-app has the same PeerID?

**Comment by Sophia-yu-kk** [comment]
The system will automatically close the longer issues, if your problem is still not solved, you can join the discord group chat: https://discord.gg/2CwVmm5X
