### ISSUE TITLE
No contracts being assigned, no next payment date

### ISSUE THREAD

**Issue by cubrilomilos** [TRON-US/go-btfs#955]
Hi, I am running a node with 900+GB and when I check scan.btfs.io I see only 5kb mined. Also 0 contracts and no next payment date. Is this normal or there is some issue/bug. I am running this on Windows 10 just installed Bittorent and run btfs from it, BTFS UI show that everything is ok, I have score 8 and 100% uptime.

**Comment by steelvirus** [comment]
I think you'll start getting contracts when the host age score reaches 10/10, at least that's the case for my nodes.

**Comment by cubrilomilos** [comment]
Ok, thanks, when it reaches age I will check and if it starts I will close this. Can you tell me after how much time is that expected to happen?

**Comment by primamkata** [comment]
Hi @cubrilomilos  , have you sort this out ?  I have the same problem  everything else is 10/10  , just this one Host age (20% of score): 0/10  
Anyone knows what could couz  this ? Any settings wrong  ? 
Thanks in advance

**Comment by cubrilomilos** [comment]
I have 10/10 now on all and nothing happens, still no contracts or earnings.

**Comment by Sophia-yu-kk** [comment]
The system will automatically close the longer issues, if your problem is still not solved, you can join the discord group chat: https://discord.gg/2CwVmm5X
