### ISSUE TITLE
BTFS Scan shows Storage Mined is Kib instead of MiB and no BTT payout

### ISSUE THREAD

**Issue by UsuallyAdo** [TRON-US/go-btfs#957]
I have the situation where BTFS Scan shows:

> Storage Mined  244.94 KiB

but my actual file hosting is:

> Hosting 245 MB of files

Perhaps this is why I have not had a BTT payout on 19th March 2021 as indicated?

Peer ID:     16Uiu2HAkvDN4oTWA1oEjhwsGku3fwSAaqfrzzKFjG1UKGpyfsLRN
TRON Wallet Address:  TYhZjpjhYJVM7rcsPCz1oEpRkhTAKQU6xc

I know I have a very low storage and payout but this is me just testing the system before deciding whether to commit more resources to it.  So far it seems this is a sensible approach.

**Comment by Sophia-yu-kk** [comment]
Hello, I am glad to read your question.

Right now the data displayed on the host ui prevails, the browser data is still in beta version and not fully accurate.

**Comment by UsuallyAdo** [comment]
Sorry but I think you are missing the point.

The next payout date is still Mar 19, 2021 and "Earnings to-date" is still 0 BTT after hosting files for more than 1 month.

If this was a service I was paying money for I would conclude right now that it is a scam.  Regardless of that, right now it is a charity that is costing me money on my electric bill so can you please fix this ASAP?

**Comment by UsuallyAdo** [comment]
After running a node since 18th February 2021 I have today shut it down.

The whole thing has been a complete waste of time with only 245MB (5 contracts) out of 166GB ever allocated and ZERO BTT tokens paid out.

Hopefully it is working for some of you, but it doesn't work for me.

**Comment by Sophia-yu-kk** [comment]
Sorry for the bad experience. We will optimize the revenue-related issues you raise as soon as possible

**Comment by rgouzal** [comment]
@Sophia-yu-kk I am having this issue same, and I tried to reinstall btfs which resulted me with creating new wallet. At first time I had an error being thrown in terminal but after one day syncing it disappeared but I had a low score 6.2 which did not change for a week even device is online I though it could be the internet speedy is bad but I tested is looks alright, below is the error I am getting:

`ERROR spin Failed to sync host stats: Failed to query stats from Hub service: HubQueryClient: Cannot query to get stats, please wait for host validation `

And same thing after reinstalling I get this message it has been now 3 days and I can't see a change still validating!!
