### ISSUE TITLE
next payment date is null

### ISSUE THREAD

**Issue by flykye** [TRON-US/go-btfs#962]
![image](https://user-images.githubusercontent.com/236068/112266422-e8a11100-8cae-11eb-8726-567008855ced.png)

my host id is : 16Uiu2HAmMY5rZjwMzdmvRKCdKos1zo9gBmDm9hwabLmzp6Eq7NVT

i was change my node to other computer before

**Comment by moseszhao** [comment]
兄弟，项目方还在运营么？怎么信息发出去一周多问题和微信客服都没有回应的？btfs控制台回复的错误消息能发给你帮忙看一下么？

**Comment by flykye** [comment]
> 兄弟，项目方还在运营么？怎么信息发出去一周多问题和微信客服都没有回应的？btfs控制台回复的错误消息能发给你帮忙看一下么？

在运营啊，也不知道为啥没人管了，你直接发这里啊，我力所能及看看。

**Comment by Sophia-yu-kk** [comment]
> ![image](https://user-images.githubusercontent.com/236068/112266422-e8a11100-8cae-11eb-8726-567008855ced.png)
> 
> my host id is : 16Uiu2HAmMY5rZjwMzdmvRKCdKos1zo9gBmDm9hwabLmzp6Eq7NVT
> 
> i was change my node to other computer before

Does this current I problem still exist?
