### ISSUE TITLE
Wallet password cannot contains hashes

### ISSUE THREAD

**Issue by NourEddineX** [TRON-US/go-btfs#963]
Hello
When you generate a wallet, set a password that contains a hash ( `#` ) the password gets trimmed from the hash to the end.  
### Steps to reproduce:  
1. Run btfs daemon  
2. from web page create new wallet, set the password to something that contain a hash ( `#` ) , for example `BitTorrent#Rocks`
3. complete the setup
4. Now try to unlock the wallet, it should fail
5.  You should be able to unlock it with the password `BitTorrent`

Tested on btfs 1.5.1 linux64

**Comment by PUUR3** [comment]
Can the password be changed?

**Comment by Sophia-yu-kk** [comment]
Thank you for your feedback, this issue has been submitted to test verification.

**Comment by xGitter** [comment]
The bug doesn't seem to be limited to the `#` character. I had a quite complex password which contained all of the following characters:
`&;)'"k${}*!` plus ` itself (which can't be quoted here). 

I didn't test which character specifically led to not accepting the password on login, so I reduced the amount of special characters in the password but still created a quite strong one. 
I would suggest to fully test all regular special characters one can expect from a user (i.e. generated by KeePassX). Users will be left unable to login and have to use the seed words to restore the password until they find out the characters are the problem.

Tested with btfs 1.5.1 Ubuntu 20.04 amd64

**Comment by Sophia-yu-kk** [comment]
Thank you for your feedback.The system will automatically close the longer issues, if your problem is still not solved, you can join the discord group chat: https://discord.gg/2CwVmm5X

**Comment by xGitter** [comment]
@Sophia-yu-kk: On April 7 you wrote that the bug has been submitted to test verification.

Can you share the results? Were you able to confirm and/or fix it?

Since there is no fix linked here, I would imagine the bug still exists?

**Comment by Tafaz** [comment]
@xGitter the last commit on this project is dated 6 April ... the bug is obviously still there, seems that they're only closing issues without fixing anything
