### ISSUE TITLE
Lots of contracts / no storage used 

### ISSUE THREAD

**Issue by thatalbertaguy** [TRON-US/go-btfs#964]
Hi ,

I’m not sure what’s going on here . I jumped from 187 to 267 contracts and fell from 12 / 75 gb used to 0.01 gb / 75 gb .  I tried reinstalling BitTorrent / btfs and is all current version . 

Peer id 

16Uiu2HAmGQg7xKM6GhRqEACGJuWFfC46FsyijBc6kigUc8Y1hM9j

thanks

**Comment by thatalbertaguy** [comment]
![F9DA43D1-8C95-46C3-9717-9714347C58D1](https://user-images.githubusercontent.com/81401292/112575423-eb3a5e00-8db5-11eb-89c6-72751d2676f4.png)
![C7843A9E-030F-41E5-9472-A0E1D7DEE31F](https://user-images.githubusercontent.com/81401292/112575427-ec6b8b00-8db5-11eb-9350-337245b5f679.png)

**Comment by laipogo** [comment]
will look into it

**Comment by thatalbertaguy** [comment]
Found this website https://docs.btfs.io/docs/what-is-btfs

seems my default pricing is stuck on 7680 instead of the mentioned 3840 in the website . I changed in custom pricing to 3840 noticing an uptick in network traffic will report tomorrow if a change in storage space .

**Comment by thatalbertaguy** [comment]
Well after 10 hours I’m up to .121 gb of storage a lot better then before . I assume my storage dropped due to pricing . But still don’t know why my contracts double

**Comment by thatalbertaguy** [comment]
Is there a way to increase download speed for btfs ? Currently I am downloading shards at 10-20 kb/sec my internet is much faster then this and I have zero measures to decrease the speed so I assume it internal ? Thanks

**Comment by thatalbertaguy** [comment]
Well now 10 hours later I’m down to .118 gb storage . Btfs ram the whole time about 17 kb/sec sending and 8-18 kb/sec recieving (according to windows task manager / performance monitor filtered for btfs.exe)

**Comment by steelvirus** [comment]
Issues still persist for me, no change in storage, contracts or anything at all.

**Comment by thatalbertaguy** [comment]
Something is going on this is my new error 

![Uploading C88CE602-3BF2-4031-B061-5FA26C0EAEA2.png…]()

**Comment by thatalbertaguy** [comment]
![6A0B8138-BD45-4AFC-998A-60E5C1656441](https://user-images.githubusercontent.com/81401292/113222618-a5ade300-9244-11eb-9d7f-6ce9ad346e8a.png)

**Comment by thatalbertaguy** [comment]
Looks like they are having server issue right now https://uptime.btfs.io/

**Comment by thatalbertaguy** [comment]
Just an update still at 278 contracts but only .127gb storage

**Comment by thatalbertaguy** [comment]
Still at 278 contracts now down to .123 gb .   What I don’t understand is my computer is on 24 hours a day and btfs is constantly using bandwidth (downloaded a meter and I’m receiving more then a GB of data) but my storage isn’t going up .

**Comment by thatalbertaguy** [comment]
So I totally deleted btfs from my computer , but on this reinstall I didn’t input my wallet now I have 0 contracts and 0 storage . I don’t know if eventually they other wallet / contract situation would of worked itself out but felt like my account had glitched and I wasn’t going to make any btt that way .

**Comment by thatalbertaguy** [comment]
Never got fixed lost btt payments , started all over fresh with 0 contracts
