### ISSUE TITLE
HSTS error on gateway.btfs.io

### ISSUE THREAD

**Issue by ciwines** [TRON-US/go-btfs#965]
I can't see a file I uploaded yesterday through the official gateway. Here is the error I see on the browser (Firefox, Chrome and Safari, all with the same error).

![Error](https://user-images.githubusercontent.com/54742309/112723660-028d5e80-8f10-11eb-843c-003040be1e1f.png)

This is the link to the file: [https://gateway.btfs.io/btfs/QmV7m1QJmJDB5hLVKeGpHR58TMoveCy7fVhFnpvv5LQu7C](https://gateway.btfs.io/btfs/QmV7m1QJmJDB5hLVKeGpHR58TMoveCy7fVhFnpvv5LQu7C)

**Comment by kenken64** [comment]
I have the same issue here

**Comment by laipogo** [comment]
working on it

**Comment by Sophia-yu-kk** [comment]
The system will automatically close the longer issues, if your problem is still not solved, you can join the discord group chat: https://discord.gg/2CwVmm5X
