### ISSUE TITLE
All peers location unknown

### ISSUE THREAD

**Issue by lynk-V** [TRON-US/go-btfs#970]
Hi,

I dont know if this just me, but i noticed that all of the peers connected to my node origins are all unknown. Is this common or is it a fault?

kind regards,

**Comment by laipogo** [comment]
It's a known issue, will be fixed in next release.

**Comment by DarkBlaez** [comment]
This works in the IPFS webui from which BTFS was forked. So location is being populated as is the world map. It's broke in the BTFS version even thought BTFS underpinnings are IPFS.

-DB

**Comment by Sophia-yu-kk** [comment]
The system will automatically close the longer issues, if your problem is still not solved, you can join the discord group chat: https://discord.gg/2CwVmm5X
