### ISSUE TITLE
failed to send data to status server

### ISSUE THREAD

**Issue by wlm77** [TRON-US/go-btfs#974]
The newly installed host. fails to synchronize the nodes, and the terminal displays failed to send data to status server.Hostui has been displaying more than 1 hour of verification. 
My btfs version is 1.5.1 and my node ID is 16Uiu2HAmQqUSENzX9iRpzMJ1856K2gsPVpxeagmB1nYtgRxeDqnY
Can you give me some advice?

![截屏2021-04-01 下午2 51 18](https://user-images.githubusercontent.com/23515072/113254919-c6844000-92f9-11eb-9096-f787f139fd4d.png)

**Comment by laipogo** [comment]
There was an issue according to status and hub, should be working now. Thank you.
