### ISSUE TITLE
HostUI - Validating after hours and hours

### ISSUE THREAD

**Issue by DarkBlaez** [TRON-US/go-btfs#975]
All:

I saw a similar issue that many were having issues, as recently as 5 days ago and yet the issue was closed with a claim it's been resolved.

Well I assure you my node has been online for hours and hours and the hostUI is stuck with the amazing message...

Please wait up to 180 minutes while the BTFS network is validating this node. A new node needs to demonstrate its online presence long enough to qualify as a valid storage host. Please refresh every 30 minutes to check for update.

Refresh UI and still the same. Perhaps the popup should not be modal and more of a notification across the top as opposed to a huge splash screen message with translucency showing something under it. 

Also, I would have expected this to validate by now, Everything is setup and I am sharing just short of 1T

Identity:16Uiu2HAmKZnK24hjPj7w84DkFPrsQUTomjo89YMmDriMSguEEhux

Anyway to interrogate what is going on? Can this be manually validated? I want to get this node validated then move it to a different subnet and hardened environment for permanent hosting. But if this just sits and dingles around with a do nothing modal that gives me very little info, then I need someone to manually validate this node and/or tell me what the issue is.

Thanks
DB

**Comment by DarkBlaez** [comment]
This seems to have magically resolve itself... The next issue I ran in to is creating a wallet... I set a proper password and hit "Continue" and nothing happens, just sits there. This is in Safari Browser

-DB

**Comment by DarkBlaez** [comment]
Seems to have self resolved by hitting the terminal and running a few unrelated btfs commends, odd

**Comment by realabbas** [comment]
@DarkBlaez After how many days, the error was solved?
