### ISSUE TITLE
[Commentary] BTFS daemon - Behavior

### ISSUE THREAD

**Issue by DarkBlaez** [TRON-US/go-btfs#977]
All:

When running the btfs daemon commend, the expectations with any daemon is that it is a background task NOT a foreground task. This has been the historical context for decades. One should not have to invoke a nohup along with placing this in the background to achieve a remote host. I suggest you change the command to reflect that indeed the daemon is not invoking a true background task. This is a mislabel of the standard nomenclature and not a single project needs to redefine what a daemon is.

Also, it is a bit out of the norm to consider individuals by default will run this with http access and access via 127.0.0.1, most longterm stable nodes will run this on a separate host and access remote. Typically on their local LAN. As such, the default behavior of requiring additional steps to allow wallet access when using the actual IP of the host is by default wrong. All host have real IP addresses, this has to be taken in to consideration. Do not confuse IPs other than 127.0.0.1 for being insecure, PUBLIC and PRIVTE IP are not the same and designated by where access will take place. I suggest you allow for additional flags to accept a designation of PRIVATE IP and treat it in the same manner as 127.0.0.1 without individuals having to hunt down why they cannot access the UIs without all the config mods.

Key points in this commentary:

use the word daemon correctly, when invoked make btfs run in the background as a true daemon, output the logs only to the file. Give individuals the option to either run in foreground or background. When the word daemon is used it is assumed a background task immediately. One should be able to disconnect the terminal session and logout. Otherwise a nohup and ampersand needs to be used which is so pre-daemon usage and not contemporary (as in 30-40 years)

-DB

**Comment by kenken64** [comment]
2021-04-01T02:06:26.676Z        ERROR   spin    failed to send data to status server: context deadline exceede
d
2021-04-01T02:07:18.411Z        ERROR   spin    failed to send data to status server: context deadline exceede
d
2021-04-01T02:08:24.146Z        ERROR   spin    failed to send data to status server: context deadline exceede
d
2021-04-01T02:09:35.128Z        ERROR   spin    failed to send data to status server: context deadline exceede
d
2021-04-01T02:11:10.180Z        ERROR   spin    failed to send data to status server: context deadline exceede
d

**Comment by lukasvdberk** [comment]
Currently solved this temporally with running btfs daemon in a systemd service.
