### ISSUE TITLE
BTFS keeps validating. (Failed to sync host stats)

### ISSUE THREAD

**Issue by fair-repair** [TRON-US/go-btfs#983]
I tried to set up a BTFS Node earlier today. I keep getting this error:

←[31mERROR←[0m  spin    Failed to sync host stats: Failed to query stats from Hub service: HubQueryClient: Cannot query to get stats, please wait for host validation!

It's been doing this for half a day. I already used 'config profile apply storage-host'

What's a possible issue here and can anyone help me?

Node ID: 	16Uiu2HAm98LAQrenVXwwPEG7PFD3GtQr2F8qE7pf2YEkLSSrSk8T

**Comment by laipogo** [comment]
looks like it's validated now.

https://scan.btfs.io/#/btfsscan/search?node_id=16Uiu2HAm98LAQrenVXwwPEG7PFD3GtQr2F8qE7pf2YEkLSSrSk8T&locale=zh
