### ISSUE TITLE
LAN access to webui

### ISSUE THREAD

**Issue by zJairO** [TRON-US/go-btfs#985]
Hello, I just bought a CPU for act as a server for this project.
I have installed Ubuntu Server, but I have a problem.
I can't access to the host UI from my other computer on the same LAN, have tried openning ports without success..
Is there a config that I should do?
I always get ERR_CONNECTION_REFUSED

Thank you.

**Comment by RealLau** [comment]
yes.
1. you have the port(default: 5001, which you can change to another different one) open:

    - already done;

2. set Addresses.API: 
    - `btfs config Addresses.API "/ip4/0.0.0.0/tcp/5001"`
3. set API.HTTPHeaders.Access-Control-Allow-Origin: 
    - `btfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '["http://0.0.0.0:5001"]'`
4. set API.HTTPHeaders.Access-Control-Allow-Methods: 
    - `btfs config --json API.HTTPHeaders.Access-Control-Allow-Methods '["PUT", "GET", "POST"]'`
5. start damon:
    - `btfs daemon`
then you should acess via a LAN network address.

**Comment by JaspervdK** [comment]
I used Putty on my Windows machine to achieve a tunnel from localhost:5001 to localhost:5001 on the ubuntu server. An example: https://blog.devolutions.net/2017/4/how-to-configure-an-ssh-tunnel-on-putty#:~:text=Local%20Port%20Forwarding&text=In%20the%20Tunnels%20section%20in,well%20as%20the%20destination%20port.

**Comment by zJairO** [comment]
> I used Putty on my Windows machine to achieve a tunnel from localhost:5001 to localhost:5001 on the ubuntu server. An example: https://blog.devolutions.net/2017/4/how-to-configure-an-ssh-tunnel-on-putty#:~:text=Local%20Port%20Forwarding&text=In%20the%20Tunnels%20section%20in,well%20as%20the%20destination%20port.

I know that way, is that another way or the process can get out of the local machine ?

**Comment by DarkBlaez** [comment]
Did you make adjustments as follows:

add to your env variables
export ENABLE_WALLET_REMOTE=true
btfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '["http://Public_IP:5001", "http://0.0.0.0:5001"]'
btfs config --json API.HTTPHeaders.Access-Control-Allow-Methods '["PUT", "GET", "POST"]'

Also in the config consider setting the API to 0.0.0.0 instead of 127.0.0.1

BTFS is a fork of IPFS so if you run in to issues check out IPFS for some solutions

-DB

**Comment by klangborste** [comment]
Great that worked for me.
If somebody search the config its default is under /<user_dir>/.btfs/config

**Comment by chrisbg69** [comment]
This is not working over internet, only for LAN, i have the same issue, but i want to access UI from internet, how to achieve that? With Putty on my Windows machine to achieve a tunnel from 127.0.0.1:5001 to 127.0.0.1:5001 on the Ubuntu server is no problem, but when i quit from Putty console, BTFS daemon is break. I tried  ssh -L [LOCAL_IP:]LOCAL_PORT:DESTINATION:DESTINATION_PORT [USER@]SSH_SERVER, but then console says that IP address is in use.
