### ISSUE TITLE
Error on btfs

### ISSUE THREAD

**Issue by thatalbertaguy** [TRON-US/go-btfs#988]
Hi I keep getting this error , I’m not sure if it has to do with the update you are all doing or not . Anyways figured I would check , my host score is still going up just got to 5/10 for node age . 

![ACBD7A62-106C-4847-8527-9F48C2F63C7C](https://user-images.githubusercontent.com/81401292/114285571-79008500-9a15-11eb-8b72-def7e57fdc3d.png)

**Comment by PUUR3** [comment]
Same error over here 

![image](https://user-images.githubusercontent.com/81736944/114366257-8f285580-9b7b-11eb-8351-cfaf0a8fd1be.png)

**Comment by laipogo** [comment]
Sync btt-tx error could be ignored.

And looks like there are some network issue on your network.

**Comment by PUUR3** [comment]
@laipogo There is not any issue with my network, and as you can see, more people is having the error.

Please review further.

**Comment by laipogo** [comment]
Does the error `failed to send data to status server` happen again?

**Comment by laipogo** [comment]
> @laipogo There is not any issue with my network, and as you can see, more people is having the error.
> 
> Please review further.

I see. Syncing btt-tx error could be ignored.
