### ISSUE TITLE
Payment not received (Failed to sync btt-tx)

### ISSUE THREAD

**Issue by jgabriel98** [TRON-US/go-btfs#990]
I was supposed to receive a payment at 11/04/2021:
![image](https://user-images.githubusercontent.com/37881981/114492212-845ad880-9bee-11eb-980a-42294e7e9c64.png)

But 2 days has passed and no payment was received.

I'm getting the following errors on btfs:

![image](https://user-images.githubusercontent.com/37881981/114492282-ab190f00-9bee-11eb-8972-13bf2d3eced7.png)

<details>
<summary>The above Error Text</summary

> >
> ```
> System version: amd64/windows
> Golang version: go1.15.8
> Repo location: G:\.btfs
> Peer identity: 16Uiu2HAmDt1G3xoznkGMbr9a5pXAmYEpzJknhcE4UEWvkXHPWZss
> Swarm listening on /ip4/127.0.0.1/tcp/4001
> Swarm listening on /ip4/169.254.100.252/tcp/4001
> Swarm listening on /ip4/169.254.109.182/tcp/4001
> Swarm listening on /ip4/169.254.229.32/tcp/4001
> Swarm listening on /ip4/192.168.1.105/tcp/4001
> Swarm listening on /ip4/192.168.56.1/tcp/4001
> Swarm listening on /ip6/::1/tcp/4001
> Swarm listening on /p2p-circuit
> Swarm announcing /ip4/127.0.0.1/tcp/4001
> Swarm announcing /ip4/192.168.1.105/tcp/4001
> Swarm announcing /ip6/::1/tcp/4001
> API server listening on /ip4/127.0.0.1/tcp/5001
> WebUI: http://127.0.0.1:5001/webui
> HostUI: http://127.0.0.1:5001/hostui
> Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
> Remote API server listening on /ip4/127.0.0.1/tcp/5101
> Daemon is ready
> Storage host info will be synced at [SCORE] mode
> Current host stats will be synced
> Current host settings will be synced
> BTFS is up-to-date.
> 2021-04-12T14:56:29.729-0300    ERROR   spin    Failed to sync btt-tx: Get "https://api.trongrid.io/v1/accounts/TPoqwWTH3fx8EHL7ym9ifC1oSAakkSSmH2/transactions?limit=200&only_to=true&order_by=block_timestamp,asc&min_block_timestamp=0": net/http: TLS handshake timeout
> 2021-04-12T23:23:29.463-0300    ERROR   spin    Failed to sync btt-tx: Get "https://api.trongrid.io/v1/accounts/TPoqwWTH3fx8EHL7ym9ifC1oSAakkSSmH2/transactions?limit=200&only_to=true&order_by=block_timestamp,asc&min_block_timestamp=0": dial tcp: lookup api.trongrid.io: no such host
> ```

</details>

**Comment by cyberwalker82** [comment]
Hi,

1. This payment is overdue due to some technical issues, but  it is in the pipeline and will be paid eventually.
2. The two errors can be ignored if they didn't always happen, they were just used to sync wallet transfer transaction history
