### ISSUE TITLE
Port Forwarding

### ISSUE THREAD

**Issue by shibekin69** [TRON-US/go-btfs#991]
Hi, 

Can I know if port forwarding on my router is needed to set up BTFS? I've already followed instructions to open the inbound-connection of the firewall to a specific port used by BTFS. If I use a VPN connection, does the port forwarding settings on the router stay the same? 

Thanks!

**Comment by laipogo** [comment]
Upnp is supported, u could google it for more information.

**Comment by shibekin69** [comment]
Hi, thanks for the response! So when I look at the host page and it shows me the host score along with criterions like Download and Upload, since these two are 10/10, everything should be good in terms of connection?
