### ISSUE TITLE
 Two questions after this update

### ISSUE THREAD

**Issue by blue-cai** [TRON-US/go-btfs#993]
1.Why does the 10 point stable node have no new contract after this update, and there were several in the previous day
2.Please tell me when the airdrop award will be issued between March 27 and April 10

**Comment by zxin123662** [comment]
hello cai,I'm zxin123.

**Comment by Sophia-yu-kk** [comment]
The current rule is that nodes with 8 or more points will randomly get contracts, and as the number of miners grows, the level of competition increases accordingly. Thank you for your feedback.
