### ISSUE TITLE
Still no payments and payment date is stuck

### ISSUE THREAD

**Issue by digbicks** [TRON-US/go-btfs#996]
Hi guy, hope you are doing all good.

Following my previous issue: #881 I have some development on the matter. Now I can see only 1 payment but the payment date is now stuck on March the 5th. The price per TB is update and all but the payment date is now stuck and as usual **NO PAYMENT**. Still waiting on that fix. Hope you guys can fix it soon. 

Here is the issue with the payment date:

![Screenshot 2021-04-15 112405](https://user-images.githubusercontent.com/6688467/114838184-1d4f4680-9ddd-11eb-8c99-4f53868dc524.png)

**Comment by aladyn93** [comment]
any update?

**Comment by digbicks** [comment]
@aladyn93 nope.

**Comment by Tafaz** [comment]
Also for me payment system is stuck, my payment date is April 12, 2021 ... i received some new contracts in the past few days but still no payments. Please fix this

**Comment by broken613** [comment]
Same issue for me.  No payments and next payment stuck on April 7, 2021.  I also used the Contact Us button to send a message but never got a reply.

**Comment by rgouzal** [comment]
@Tafaz are you running linux? or windows? I am running linux and i left this for week and yet I did not get a contract my score is frozen on 6.2 for a week now, my interenet looks okay as i checked the download speed and upload speed looks okay.

**Comment by Tafaz** [comment]
I'm running nodes on various Linux versions like Ubuntu 18.10 and raspbian, in one device the score raised two days ago from 9.2 to 10 after weeks, i think also the scoring system has problems

**Comment by rgouzal** [comment]
@Tafaz Yeah same here I am running a Ubuntu 21.04 on raspberry pi  that's what I noticed too, it takes too much time to score a node. Plus there is a problem with validation for first time it shows the following message:

Please wait up to 180 minutes while BTFS network is validating this node. A new node needs .... 

But in fact it takes two or three days to validate a node. I hope it doesn't have to do with the CPU speed or performance though.

**Comment by Tafaz** [comment]
Are there any news about this issue? will the payment stuck problem be analyzed and solved? Is anyone working on this?

**Comment by Sophia-yu-kk** [comment]
When other hosts want to upload contracts to me, which ports do I need to map so that other hosts can connect to me.4001?5001?
So tell me how to configure port mapping when installing with docker.Thank you.

**Comment by Tafaz** [comment]
> When other hosts want to upload contracts to me, which ports do I need to map so that other hosts can connect to me.4001?5001?
> So tell me how to configure port mapping when installing with docker.Thank you.

What?

**Comment by Tafaz** [comment]
@Sophia-yu-kk please re-open this issue because isn't fixed and we are still affected

**Comment by AlexGGWP** [comment]
@Sophia-yu-kk why do you close the issue when it still present?

**Comment by broken613** [comment]
Issue still going on and no reply from devs. Why was this closed?

**Comment by RaspberryProgramming** [comment]
I've got the same issue. I've yet to be paid and it's stuck at June 12th.

**Comment by Tafaz** [comment]
i'm out of this project ... 3 months without a single line of new code added to this repository, payment issues never fixed, no support and they are closing all issues without giving any response.

And last but not least there are 16000 PiB of storage available and 2 PiB of storage used ... is there anything else to say?
