### ISSUE TITLE
Stuck on validating

### ISSUE THREAD

**Issue by mjovanc** [TRON-US/go-btfs#998]
Tried setting up the BTFS as a host. Still loading after 3-4 hours on validating on Linux x86_64 and macOS x86_64:

> Please wait up to 180 minutes while the BTFS network is validating this node. A new node needs to demonstrate its online presence long enough to qualify as a valid storage host. Please refresh every 30 minutes to check for update.

Is there some way around this, should I try set it up again?

**Comment by lukasvdberk** [comment]
I have the same problem. Running Linux x86

**Comment by abcdan** [comment]
Same issue here. Running Linux x64 (LXC container)

**Comment by mjovanc** [comment]
It started to work 24 hours after I posted this issue. I'm not sure why that is. Is it dependent on how many peers currently operating and their bandwidth?

**Comment by Sophia-yu-kk** [comment]
I'm sorry for everyone's feedback. The long sync time was caused by too many sync nodes, and this issue has now been fixed.

**Comment by realabbas** [comment]
@Sophia-yu-kk The issue still persists. I am running the node on Windows and it has been more than 24 hours still stuck on the validation screen. Please do look into this and suggest a solution. 

Following are the details:-

Peer identity: 16Uiu2HAm1b9AEpf5CPUbc1rkg4zFnkCSnZRiE3mzZNWYEUKVpWXS

![Screenshot 2021-06-07 at 3 13 53 PM](https://user-images.githubusercontent.com/43527087/120995391-fbea5580-c7a2-11eb-9a94-5797eee529c2.png)
![Screenshot 2021-06-07 at 3 14 44 PM](https://user-images.githubusercontent.com/43527087/120995527-19b7ba80-c7a3-11eb-90c2-1bc60c4d827c.png)
