### ISSUE TITLE
host is not running in btfs

### ISSUE THREAD

**Issue by Darkshadow253** [TRON-US/go-btfs#999]
i am having a error after running btfs 

Host profile not enabled

and i cant solve it or run any command line in cmd please help me
![Screenshot 2021-04-16 215443](https://user-images.githubusercontent.com/81405771/115054884-6519bf00-9efe-11eb-9c23-8b152262aed4.png)

**Comment by thatalbertaguy** [comment]
Not to hijack your issue but I’m having the exact issue (no host profile) and have this error in combination 
![83351DB0-6B6D-4169-87B7-CE50CE37883D](https://user-images.githubusercontent.com/81401292/115066051-383cbc00-9eac-11eb-99a2-cb1905601607.png)

**Comment by thatalbertaguy** [comment]
Mine has started working again , but the incoming / out coming traffics is erratic at best .

**Comment by Darkshadow253** [comment]
how it started can u tell me how to start it through commands clearly

**Comment by laipogo** [comment]
running the command could fix your problem.
